### ISSUE TITLE
WebServer: HTTP/2 support

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#101]
## Environment Details
* Helidon Version: 0.10.1
* Helidon SE 

----------

## Problem Description

WebServer does not currently support HTTP/2. Netty has some support for it.

**Comment by spericas** [comment]
There is now experimental support for it. See,

https://github.com/oracle/helidon/wiki/Experimental-HTTP-2-Support

**Comment by romain-grecourt** [comment]
@barchetta @spericas should we close this issue ?

**Comment by spericas** [comment]
I will close this one and open a new issue for all future HTTP/2 work.
