### ISSUE TITLE
website: "blog" button should give curated list

### ISSUE THREAD

**Issue by delabassee** [oracle/helidon#1037]
The [blog](https://medium.com/oracledevs/search?q=Helidon) button (top right) links to a Medium search which return incomplete biased results. 

For example, the 1st result is the (now 1 year old!) announcement post. Oth,  I don't see any recent relavent posts such as :

- MicroProfile 3.0 Support Comes to Helidon
- Long Running Actions for MicroProfile on Helidon… Data Integrity for Microservices
- Helidon brings MicroProfile 2.2+ support

I suggest to link to a static list page listing curated posts instead.

**Comment by barchetta** [comment]
The query does return the posts mentioned in the description -- so I'm not sure what went wrong there. But the order is haphazard and I haven't found a way to control that.

I've updated the description to reflect the desire to have the blog list curated.

**Comment by m0mus** [comment]
Fixed by https://github.com/oracle/helidon-site/pull/44
