### ISSUE TITLE
it's possible Helidon SE support swagger ui?

### ISSUE THREAD

**Issue by aranjitchi** [oracle/helidon#1041]
## Environment Details
* Helidon SE : 1.3.0
* JDK version: 12
----------
it's possible Helidon SE support swagger ui?

**Comment by romain-grecourt** [comment]
If you use [swagger-ui-dist](https://github.com/swagger-api/swagger-ui/tree/master/dist) you can serve it using the `StaticContentSupport`. See an example [here](https://github.com/oracle/helidon/tree/master/examples/webserver/static-content).

**Comment by aranjitchi** [comment]
tks,i implemented successfully
