### ISSUE TITLE
Injecting @ConfigProperty fails.

### ISSUE THREAD

**Issue by stasha** [oracle/helidon#1070]
## Environment Details
* Helidon Version: 1.0-1.3.1
* Helidon MP
* JDK version: 1.8
* OS: Linux Mint

----------

## Problem Description
Injecting @ConfigProperty fails with: 
```
Exception List with 2 exceptions:
Exception 0 :
org.jboss.weld.exceptions.DeploymentException: WELD-001409: Ambiguous dependencies for type String with qualifiers @ConfigProperty @ConfigQualifier
  at injection point InjectionPoint with type=class java.lang.String, qualifiers=[@org.eclipse.microprofile.config.inject.ConfigProperty(name="app.greeting", defaultValue="org.eclipse.microprofile.config.configproperty.unconfigureddvalue"), ConfigQLiteral{fullPath='io.helidon.examples.quickstart.mp.GreetingProvider.message', key='app.greeting', defaultValue='org.eclipse.microprofile.config.configproperty.unconfigureddvalue', rawType=class java.lang.String}], delegate=false, transient=false.
  at io.helidon.examples.quickstart.mp.GreetingProvider.message(GreetingProvider.java:0)
  Possible dependencies: 
  - ConfigPropertyProducer{qualifier=ConfigQLiteral{fullPath='io.helidon.examples.quickstart.mp.GreetingProvider.message', key='app.greeting', defaultValue='org.eclipse.microprofile.config.configproperty.unconfigureddvalue', rawType=class java.lang.String}},
  - ConfigPropertyProducer{qualifier=ConfigQLiteral{fullPath='io.helidon.examples.quickstart.mp.GreetingProvider.message', key='app.greeting', defaultValue='org.eclipse.microprofile.config.configproperty.unconfigureddvalue', rawType=class java.lang.String}}
```

## Steps to reproduce
I'm attaching helidon-quickstart-mp project with problematic code.
Take a look at GreetProvider, ExtendedGreetProvider and GreetResource classes.
[helidon-quickstart-mp.zip](https://github.com/oracle/helidon/files/3667434/helidon-quickstart-mp.zip)

**Comment by spericas** [comment]
Problem seems to be in `ConfigCdiExtension`, in the way it handles registration of producers for injection points. Whenever there is inheritance, the same field (in different classes) is discovered more than once and each discovery results in a _new_ producer being created. `ConfigCdiExtension` collects these producers in a list instead of a set, as it probably should.

**Comment by spericas** [comment]
https://github.com/oracle/helidon/pull/1074
