### ISSUE TITLE
Minor: maven-javadoc-plugin configuration needs tweaking

### ISSUE THREAD

**Issue by ljnelson** [oracle/helidon#108]
The `maven-javadoc-plugin` configuration works, but is slightly off.  In the `<additionalJOptions>` stanza:

https://github.com/oracle/helidon/blob/8fbafbd2c46afd9b76f151843300f22630882252/pom.xml#L223-L226

…the `-source` option is shoehorned in here.  This really should be [its own element](https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#source).

Additionally, to make javadoc links to [javadoc.io](https://javadoc.io/) work properly, there needs to be an explicit user agent set on the HTTP client used by the `maven-javadoc-plugin`.

I'll have a fix for this configuration as part of an upcoming PR.

**Comment by romain-grecourt** [comment]
I think this particular section of the javadoc plugin configuration was inherited from the previous iterations.

What are we linking to to javadoc.io ?

**Comment by ljnelson** [comment]
https://github.com/oracle/helidon/blob/8fbafbd2c46afd9b76f151843300f22630882252/javadocs/pom.xml#L87-L95

**Comment by romain-grecourt** [comment]
@ljnelson looking at the javadocs for 0.10.4, this seems not fixed.
see https://helidon.io/docs/0.10.4/apidocs/io/helidon/webserver/zipkin/ZipkinTracerBuilder.html

**Comment by ljnelson** [comment]
ARGH: https://bugs.openjdk.java.net/browse/JDK-8184969

**Comment by ljnelson** [comment]
See #125; an upcoming PR will fix that and this.  Closing this issue out in favor of it, as the `<links>` are not the problem.
