### ISSUE TITLE
TechEmpower Did Not Complete

### ISSUE THREAD

**Issue by guaporocco** [oracle/helidon#1081]
Hi! I noticed that the techempower benchmarks for Helidon did not complete.

I'm interested in using Helidon, but would like to compare it to other webframeworks as well!

**Comment by barchetta** [comment]
There were some issues with the "Round 18" run. Those were fixed shortly after Round 18 (so I am closing this issue). You can find Helidon SE numbers in the continuous runs. For example:

https://www.techempower.com/benchmarks/#section=test&runid=76bbd357-a161-42eb-a203-051bdd949006&hw=ph&test=json

We have not yet submitted a Helidon MP application -- it's on our todo list.
