### ISSUE TITLE
Helidon compilation problem with Firebase SDK

### ISSUE THREAD

**Issue by zarub2k** [oracle/helidon#1114]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 1.3.1
* Helidon MP
* JDK version: 1.8.0_161
* OS: WIN 10
* Docker version (if applicable):

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
I was successfully created the Helidon MP project using the archetype mentioned in the Helidon documentation. This is working fine and I was able to create my first REST API. Until this step everything is working fine and then I tried to added firebase-admin SDK dependency in my pom xml. When I compile my project i got the dependency resolvement error
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"
[ERROR] Failed to execute goal on project dailyapi: Could not resolve dependencies for project com.hustlebar:dailyapi:jar:1.3.1: Failed to collect dependencies for com.hustlebar:dailyapi:jar:1.3.1: Could not resolve version conflict among [com.google.firebase:firebase-admin:jar:6.10.0 -> com.google.cloud:google-cloud-firestore:jar:1.9.0 -> com.google.cloud:google-cloud-core-grpc:jar:1.79.0 -> io.grpc:grpc-protobuf:jar:1.22.1 -> io.grpc:grpc-api:jar:1.22.1, com.google.firebase:firebase-admin:jar:6.10.0 -> com.google.cloud:google-cloud-firestore:jar:1.9.0 -> com.google.cloud:google-cloud-core-grpc:jar:1.79.0 -> io.grpc:grpc-protobuf:jar:1.22.1 -> io.grpc:grpc-protobuf-lite:jar:1.22.1 -> io.grpc:grpc-api:jar:1.22.1, com.google.firebase:firebase-admin:jar:6.10.0 -> com.google.cloud:google-cloud-firestore:jar:1.9.0 -> io.grpc:grpc-netty-shaded:jar:1.21.0 -> io.grpc:grpc-core:jar:1.22.1 -> io.grpc:grpc-api:jar:[1.22.1,1.22.1], com.google.firebase:firebase-admin:jar:6.10.0 -> com.google.cloud:google-cloud-firestore:jar:1.9.0 -> io.grpc:grpc-stub:jar:1.22.1 -> io.grpc:grpc-api:jar:1.22.1, com.google.firebase:firebase-admin:jar:6.10.0 -> com.google.cloud:google-cloud-firestore:jar:1.9.0 ->
io.grpc:grpc-auth:jar:1.21.0 -> io.grpc:grpc-api:jar:[1.21.0,1.21.0]] -> [Help 1]

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"
Include the dependency into the created project pom
<dependency>
            <groupId>com.google.firebase</groupId>
            <artifactId>firebase-admin</artifactId>
            <version>6.10.0</version>
        </dependency>

I tried to exclude some jar which is in conflict but there is no gain to my attempt.

Any help would be much appreciated.

**Comment by romain-grecourt** [comment]
Try adding the following property to your pom: `<version.lib.grpc>1.21.0</version.lib.grpc>`.

See the helidon-dependencies pom [here](http://repo1.maven.org/maven2/io/helidon/helidon-dependencies/1.3.1/helidon-dependencies-1.3.1.pom) for a list of all the properties you can override.

**Comment by zarub2k** [comment]
Thanks, @romain-grecourt Great hint. After I changed the property the problem got resolved. I completely forgot to check the pom of helidon instead I tried to exclude the problematic version. Great hint and once again thanks.
