### ISSUE TITLE
Startup hook with Helidon MP

### ISSUE THREAD

**Issue by zarub2k** [oracle/helidon#1115]
I am developing a Microservice application with Helidon MP. So far my experience is awesome. But I end up looking for a startup / shut down hook with Helidon MP. I tried to find through search and Helidon Javadoc. But I am not able to find anything useful.

Do we have such functionality available with Helidon MP?

NOTE: I am sorry for asking the question here.

**Comment by ljnelson** [comment]
Could you kindly re-ask this question on [StackOverflow](https://www.stackoverflow.com/) under the `helidon` tag?  That is our preferred means of support.
