### ISSUE TITLE
Fault Tolerance doesn't work for Rest Client

### ISSUE THREAD

**Issue by pa314159** [oracle/helidon#1121]
# Fault Tolerance doesn't work for Rest Client

## Environment Details
* Helidon Version: 1.3.1
* Helidon MP
* JDK version: any
* OS: any

----------

## Problem Description
__Microprofile Rest Client__ specification [states](https://download.eclipse.org/microprofile/microprofile-rest-client-1.3.3/microprofile-rest-client-1.3.3.html#_microprofile_fault_tolerance):

> MP Rest Client implementations must ensure that MP Fault Tolerance annotations on client interfaces are honored. In general, these annotations are treated as CDI interceptor bindings.

Such interfaces in Helidon don't work because the fault tolerance module throws a NPE. The `CommandRetrier` attempts to update the fault tolerance metrics but the associated counters are not registered.

The reason is that `FaultToleranceExtension` which is responsible with the registration of these counters, @Observes only `ProcessManagedBean<?>` events, while the beans created by `RestClientExtension` are synthetic.

## Steps to reproduce

Run:

	git clone https://github.com/pa314159/helidon-retry-issue
	./gradlew run

... then in a new terminal run:

	curl -i http://localhost:7001

... and check the outputs of both terminals.

**Comment by pa314159** [comment]
@spericas, there is a fix for this on my fork, let me know if you want to create a PR

**Comment by spericas** [comment]
@pa314159 I have a fix as well now, but I don't like it very much. Could you describe your approach?

**Comment by pa314159** [comment]
@spericas check this https://github.com/oracle/helidon/pull/1124
