### ISSUE TITLE
Should embedded Netty threads be daemonized?

### ISSUE THREAD

**Issue by smillies** [oracle/helidon#1133]
Helidon SE embedds Netty 4.1, which produces non-daemon threads for request processing. This is a bit of a pain with regard to shutdown behavior, and also different from the default behavior of other embedded web servers, such as Tomcat. (And I think also Undertow.)

In Netty, it is possible to configure a custom thread factory. Is this possibility exposed by Helidon SE, e. g. through options in application.yaml? If not, wouldn't it be better anyway if Helidon SE produced daemon threads for request processing by default?

**Comment by romain-grecourt** [comment]
Can you provide more details on the pain points you are having around the shutdown behavior ?

**Comment by smillies** [comment]
I have some very long-running requests. I don't want such requests preventing the shutdown of the JVM, as they currently are because they are processed in non-daemons.

**Comment by romain-grecourt** [comment]
Thanks for the details.
This may be a valid enhancement for a future release.

**Comment by romain-grecourt** [comment]
There seem to be something specific to your use-case ; are you able to provide a simple reproducer for this issue.

Also, is this something that only occurs within docker ?

**Comment by spericas** [comment]
@smillies Have you tried to reproduce the SIGTERM issue outside of a Docker container? My suspicion is that this is related to how signals are routed inside a container. Simple testing using processes shows that SIGTERM and SIGINT work as expected.

**Comment by smillies** [comment]
@spericas No, I have not tried that. (I was using Helidon for an application that I want to compile to a native Linux executable, but my workstation is Windows, so I have only tried Docker). Thanks for the hint. Perhaps it's bash that isn't forwarding the signal?

**Comment by smillies** [comment]
I can confirm that in a simple test using a process started with "java -jar ..." inside a shell, the response to SIGINT is as expected. However, inside a Docker container running a native executable that is not so. 

I don't think that a shell is involved, because I have specified the native Helidon executable directly as the ENTRYPOINT. I am also not convinced it is a Docker problem, because when I run a SpringBoot app as a jar inside Docker, I can terminate it. So perhaps it is GraalVM that produces an executable which ignores SIGINT?

Anyway, I think this issue is moot, as trying to terminate a process inside a container instead of the container itself is probably kind of an unusual thing to do (I suppose). And I can detach from the container, and I can also `docker stop` it from the outside. So I have no real problem after all.

**Comment by ljnelson** [comment]
@smillies Perhaps you are experiencing what is [described here](https://engineeringblog.yelp.com/2016/01/dumb-init-an-init-for-docker.html), or something in that general area.

**Comment by smillies** [comment]
@ljnelson Thanks for that! Indeed, there's an `init` that comes with Docker itself, and passing the ` --init` flag to `docker run` entirely solves my problem. The Helidon executable no longer runs as PID 1, and SIGINT and SIGTERM get handled properly.
