### ISSUE TITLE
Add new helidon-microprofile bundles and deprecate old bundles

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#1140]
## Environment Details
* Helidon Version: 1.3.1
* Helidon MP
----------

## Problem Description
Currently (Helidon 1.3.1) we handle bundles for MicroProfile this way:

We have a bundle for each MicroProfile release, including minor and micro releases. For example: `helidon-microprofile-3.0`.  We ship all previous bundles in subsequent Helidon releases, so we don't break customer's poms when they move to a new version of Helidon. The subcomponents (Metrics, Health, etc.) in those bundles do get updated. So the MicroProfile 1.2 bundle in Helidon 1.3 actually contains Health 2.0 (not 1.0). We consider this OK as long as the newer component version is compatible with older versions.

There are some problems with this:

* We have an accumulation of MicroProfile bundles.
* We need to create a new bundle and update the codebase to use it for every minor MicroProfile release even if that bundle creates no real value. And customers need to update their poms.
* To get a "slimmer" set of MicroProfile dependencies you need to include an older MicroProfile bundle. This works (because the components are up-to-date), but it is a bit funky.

## Proposal 

For Helidon 1.4 create two new bundles that do not have a version number in the artifact ID and deprecate the old bundles (which will be removed in Helidon 2.0). The new bundles will be: `helidon-microprofile`, `helidon-microprofile-core`. 

Exact contents of `helidon-microprofile-core` are TBD, but an example would be: CDI, JAX-RS, JSON-P, JSON-B, MicroProfile Config

When Helidon ships with a new version of MicroProfile, the component versions in these two bundles are updated. If the new version of MicroProfile is incompatible with the previous version (and we can't mitigate that), then we need to wait until we ship a major version of Helidon to include the new version of MicroProfile (and this is already the case).

See PR #1143

**Comment by tjquinno** [comment]
The list of core artifacts described above matches up nicely with what the current `helidon-microprofile-server` artifact depends on.

Shall we just have the new `core` artifact depend on the existing `server`?

The full bundle can depend on `core` plus the other technologies.

**Comment by tjquinno** [comment]
This should have been closed automatically earlier once the PR was merged. Closing it manually now.
