### ISSUE TITLE
/metrics/application is NOT returning anything

### ISSUE THREAD

**Issue by zarub2k** [oracle/helidon#1141]
## Environment Details
os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 10.15
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 15
[INFO] os.detected.classifier: osx-x86_64

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
I am writing a miroservice with Helidon framework. I have enabled the metrics part. I am getting data when I access /metrics/base or /metrics/vendor

But I am not getting any data when I access /metrics/application

Am I missing any configuration?

**Comment by spericas** [comment]
Do you have any application metrics? Are you getting a 204 (No Content) response?

**Comment by zarub2k** [comment]
Yes, I have some application-level metrics code. I am expecting the count of my API access based on the metrics annotation added for each APIs. Is there any clue?

**Comment by zarub2k** [comment]
I spent some time today to investigate the problem. Finally, I came to know that the metrics annotations should be added to the implementation of the APIs. This is not working when I added the @Counted and @Timed annotation at the interface level.

Is the expectation?

**Comment by spericas** [comment]
@zarub2k The spec does not define any rules regarding annotation inheritance. At this time, you need to annotate classes and theirs methods. (Metric support has some overhead which, if inheritance was supported, could be problematic in cases where interfaces and implementations are created by different people.)

**Comment by spericas** [comment]
@zarub2k I'm closing this as _works as designed_. Reopen if necessary.
