### ISSUE TITLE
Resolve dependency added to microprofile/security pom

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#1157]
As part of retiring the numbered MP bundles and moving to the full and `core` MP bundles, we needed to add this dependency
```
        <dependency>
            <groupId>io.helidon.security.integration</groupId>
            <artifactId>helidon-security-integration-jersey-client</artifactId>
            <scope>runtime</scope>
        </dependency>
```
to `microprofile/security/pom.xml`. Currently this artifact has to be present for Helidon MP security to work correctly (thanks to Tomas for this insight during the rebundling work), and adding this dependency to the MP security pom simplifies what developers must do to use Helidon MP security.

There might be a different way to organize things that would remove the need for this dependency in mp/security. This issue is to investigate that and, if possible, implement such an alternative.

**Comment by romain-grecourt** [comment]
Fixed by https://github.com/oracle/helidon/pull/1143
