### ISSUE TITLE
Config property injection does not work in super class/base class of root resource

### ISSUE THREAD

**Issue by gmhoolageri** [oracle/helidon#1166]
## Environment Details
* Helidon Version: 1.3.1
* Helidon MP
* JDK version: 1.8
* OS: Mac OS
* Docker version (if applicable): 

Helidon MP application bootup fails with an exception if the base class of root resource has the config property injected(@Inject @ConfigProperty(name = "injected.value")). The problem is not seen if there is no config property injection in the base class. This problem is consistently seen.

```
2019.11.22 17:10:25 INFO org.jboss.weld.Event Thread[main,5,main]: WELD-000411: Observer method [BackedAnnotatedMethod] public org.glassfish.jersey.ext.cdi1x.internal.ProcessAllAnnotatedTypes.processAnnotatedType(@Observes ProcessAnnotatedType<?>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2019.11.22 17:10:25 INFO org.jboss.weld.Event Thread[main,5,main]: WELD-000411: Observer method [BackedAnnotatedMethod] private io.helidon.microprofile.openapi.IndexBuilder.processAnnotatedType(@Observes ProcessAnnotatedType<X>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
Exception in thread "main" org.jboss.weld.exceptions.DeploymentException: WELD-001414: Bean name is ambiguous. Name com.example.demo.config.BaseController.injectedValue resolves to beans: [ConfigPropertyProducer{qualifier=ConfigQLiteral{fullPath='com.example.demo.config.BaseController.injectedValue', key='injected.value', defaultValue='org.eclipse.microprofile.config.configproperty.unconfigureddvalue', rawType=class java.lang.String}}, ConfigPropertyProducer{qualifier=ConfigQLiteral{fullPath='com.example.demo.config.BaseController.injectedValue', key='injected.value', defaultValue='org.eclipse.microprofile.config.configproperty.unconfigureddvalue', rawType=class java.lang.String}}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
```

I have an application resource class

```
@ApplicationPath("/")
@ApplicationScoped
public class DemoRestApplication extends Application {
    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> classes = new HashSet<>();
        classes.add(ConfigTestController.class);
        return classes;
    }
}
```

I have a controller class -

```java
@Path("/config")
@RequestScoped
public class ConfigTestController extends BaseController {
    @Path("/injected")
    @GET
    public String getInjectedConfigValue() {
        return "Config value as Injected by CDI " + injectedValue;
    }
    @Path("/lookup")
    @GET
    public String getLookupConfigValue() {
        Config config = ConfigProvider.getConfig();
        String value = config.getValue("value", String.class);
        return "Config value from ConfigProvider " + value;
    }
}
```

I have a base controller class - 

```java
public class BaseController {
    @Inject
    @ConfigProperty(name = "injected.value")
    protected String injectedValue;
}
```

The application build works fine when I fire - `mvn clean package`. But the application fails to start when I fire - java -jar target/demo.jar

**Comment by romain-grecourt** [comment]
Can you share your pom.xml ?

**Comment by gmhoolageri** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>configdemo</artifactId>
  <version>1.0-SNAPSHOT</version>
  <properties>
    <helidonVersion>1.3.1</helidonVersion>
    <final.name>configdemo</final.name>
    <package>com.example.configdemo</package>
    <failOnMissingWebXml>false</failOnMissingWebXml>
    <mpVersion>3.0</mpVersion>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.eclipse.microprofile</groupId>
      <artifactId>microprofile</artifactId>
      <version>3.0</version>
      <type>pom</type>
      <scope>provided</scope>
    </dependency>
  </dependencies>
  <build>
    <finalName>demo</finalName>
  </build>
  <profiles>
    <profile>
      <id>helidon</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-resources-plugin</artifactId>
            <version>3.1.0</version>
            <executions>
              <execution>
                <id>copy-resources</id>
                <phase>validate</phase>
                <goals>
                  <goal>copy-resources</goal>
                </goals>
                <configuration>
                  <outputDirectory>${basedir}/src/main/resources/WEB</outputDirectory>
                  <resources>
                    <resource>
                      <directory>src/main/webapp</directory>
                    </resource>
                  </resources>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <artifactId>maven-jar-plugin</artifactId>
            <version>2.5</version>
            <configuration>
              <archive>
                <manifest>
                  <addClasspath>true</addClasspath>
                  <classpathPrefix>${libs.classpath.prefix}</classpathPrefix>
                  <mainClass>${mainClass}</mainClass>
                </manifest>
              </archive>
            </configuration>
          </plugin>
          <plugin>
            <artifactId>maven-dependency-plugin</artifactId>
            <version>2.9</version>
            <executions>
              <execution>
                <id>copy-dependencies</id>
                <phase>prepare-package</phase>
                <goals>
                  <goal>copy-dependencies</goal>
                </goals>
                <configuration>
                  <outputDirectory>${copied.libs.dir}</outputDirectory>
                  <overWriteReleases>false</overWriteReleases>
                  <overWriteSnapshots>false</overWriteSnapshots>
                  <overWriteIfNewer>true</overWriteIfNewer>
                  <overWriteIfNewer>true</overWriteIfNewer>
                  <includeScope>runtime</includeScope>
                  <excludeScope>test</excludeScope>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
      <properties>
        <libs.classpath.prefix>libs</libs.classpath.prefix>
        <mainClass>io.helidon.microprofile.server.Main</mainClass>
        <jersey.version>2.29</jersey.version>
        <copied.libs.dir>${project.build.directory}/${libs.classpath.prefix}</copied.libs.dir>
      </properties>
      <dependencyManagement>
        <dependencies>
          <dependency>
            <groupId>io.helidon</groupId>
            <artifactId>helidon-bom</artifactId>
            <version>${helidonVersion}</version>
            <type>pom</type>
            <scope>import</scope>
          </dependency>
          <dependency>
            <groupId>org.jboss</groupId>
            <artifactId>jandex</artifactId>
            <version>2.0.4.Final</version>
          </dependency>
          <dependency>
            <groupId>javax.activation</groupId>
            <artifactId>javax.activation-api</artifactId>
            <version>1.2.0</version>
          </dependency>
          <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-json-binding</artifactId>
            <version>${jersey.version}</version>
          </dependency>
        </dependencies>
      </dependencyManagement>
      <dependencies>
        <dependency>
          <groupId>io.helidon.microprofile.bundles</groupId>
          <artifactId>helidon-microprofile-${mpVersion}</artifactId>
        </dependency>
        <dependency>
          <groupId>org.glassfish.jersey.media</groupId>
          <artifactId>jersey-media-json-binding</artifactId>
        </dependency>
        <dependency>
          <groupId>org.jboss</groupId>
          <artifactId>jandex</artifactId>
          <scope>runtime</scope>
          <optional>true</optional>
        </dependency>
        <dependency>
          <groupId>javax.activation</groupId>
          <artifactId>javax.activation-api</artifactId>
          <scope>runtime</scope>
        </dependency>
      </dependencies>
    </profile>
  </profiles>
</project>
`

**Comment by spericas** [comment]
I believe this issue is likely addressed by PR #1074. We should re-test with Helidon 1.4 once it becomes available.

**Comment by spericas** [comment]
@gmhoolageri Any chance you can try out your sample using the new 1.4 release of Helidon?

**Comment by gmhoolageri** [comment]
I tried with 1.4 release of Helidon and it works as expected.
