### ISSUE TITLE
unable to setup helidon test example to-do app

### ISSUE THREAD

**Issue by prasadvsj** [oracle/helidon#1173]
trying to setup helidon to-do example app on local machine , but getting following error 

## Environment Details
* Helidon Version:
* Helidon SE or Helidon MP MP
* JDK version:1.8
* OS:Oracle Linux 7
* Docker version (if applicable):18.09.1-ol, build c3ab8a8

----------

## Problem Description

following steps to setup the to-do app https://github.com/oracle/helidon/tree/master/examples/todo-app  and gettign the following error when running the docker build for backend
## Steps to reproduce

`docker build -t helidon-examples-translator-backend backend/`

```
Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for io.helidon.examples.todos:helidon-examples-todo-backend:[unknown-version]: Could not find artifact io.helidon.applications:helidon-mp:pom:2.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 24, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.helidon.examples.todos:helidon-examples-todo-backend:[unknown-version] (/helidon/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for io.helidon.examples.todos:helidon-examples-todo-backend:[unknown-version]: Could not find artifact io.helidon.applications:helidon-mp:pom:2.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 24, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
The command '/bin/sh -c mvn package -DskipTests' returned a non-zero code: 1
```

**Comment by romain-grecourt** [comment]
You are trying to build the build from master. Please see this [https://github.com/oracle/helidon/blob/master/examples/README.md](README).

If you want to build an example from the master branch you have to build the Helidon source code first. Building the example docker images from master requires extra steps, see [https://github.com/oracle/helidon/blob/master/docs-internal/dockerbuild-local-snapshots.md](dockerbuild-local-snapshots.md).

I strongly recommend you to simply use the latest release tag (1.4.0)
