### ISSUE TITLE
Metrics type of Fault Tolerance is displayed as invalid

### ISSUE THREAD

**Issue by tkote** [oracle/helidon#1177]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 1.4.0
* Helidon MP
* JDK version: 1.8.0_191-b12
* OS: Oracle Linux 7.6
* Docker version (if applicable): n/a

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"
I have the JAX-RS resource with Fault Tolerance annotation. Then I run Helidon and GET /metrics, every metrics type related to Fault Tolerance is displayed as `invalid` like this;
```
# TYPE application_ft_io_helidon_examples_quickstart_mp_FaultToleranceResource_bulkhead_bulkhead_callsAccepted_total invalid
```
It should be `counter` , `gauge` or some other valid metrics type.

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

+ Set up Quick Start MP for 1.4.0
+ Add the following JAX-RS resource (FaultToleranceResource.java) and modify GreetApplication.java so as to register FaultToleranceResource.class
```
package io.helidon.examples.quickstart.mp;

import javax.enterprise.context.ApplicationScoped;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import org.eclipse.microprofile.faulttolerance.Bulkhead;

@ApplicationScoped
@Path("/ft")
public class FaultToleranceResource {

    @Bulkhead(3)
    @GET @Path("/bulkhead")
    @Produces(MediaType.TEXT_PLAIN)
    public String bulkhead() {
        return "OK";
    }
}
```
+ package and run
+ access to the endpoint: /metrics

**Comment by spericas** [comment]
Fixed by PR #1179.
