### ISSUE TITLE
Example of how to access configuration in a JUnit test case

### ISSUE THREAD

**Issue by mattjlewis** [oracle/helidon#1192]
Is it possible to access server configuration properties for use in a JUnit test case?
Something like:
```
server = Server.create().start();
String property = server.getConfig().get("app.myProperty");
```
I know that I can define my own Config instance prior to creating the server, however, if possible I would like to rely on the properties that the server loads by default.

**Comment by tomas-langer** [comment]
Helidon components do not internally use a `Config` instance - they extract the values from config and store them in fields (most of Helidon components are immutable).
There are a few properties you can get through methods, such as the port the server is running on (`Server.port()`).
I think it may be a good enhancement to provided the "defaults" of each component.

In your example, you are looking for `app.myProperty` - that would never be available on `Server`, as server only cares about properties in its configuration tree. Also server would never create a `Config` instance, unless one is provided through API.

**Comment by mattjlewis** [comment]
Thanks Tomas. I got around the issue by doing this:
```
		Config config = Config.builder().build();
		server = Server.builder().config(config).build().start();
```
I was just wondering if there was an alternative solution that avoided building my own config instance - I was concerned that this may be built differently to the one created internally when simply calling Server.create().start();.
Happy for this to be closed.

**Comment by mattjlewis** [comment]
For the record, I believe this is the "correct" option:
```
		server = Server.create().start();
		Config config = ConfigProvider.getConfig();
```
A guide on unit testing would be very much appreciated, in particular for dependency injection. I'd be happy to contribute. Example:
```
class JpaTest {
	@PersistenceContext
	private EntityManager entityManager;

	@BeforeAll
	public static void setup() {
		cdiContainer = SeContainerInitializer.newInstance().addBeanClasses(JpaTest.class).initialize();
		assertNotNull(cdiContainer);

		server = Server.create().start();
		Config config = ConfigProvider.getConfig();
	}

	EntityManager getEntityManager() {
		return entityManager;
	}

	@Test
	public void aTestCase() {
		final EstimationToolJpaTest self = cdiContainer.select(JpaTest.class).get();
		assertNotNull(self);
		EntityManager em = self.getEntityManager();
		assertNotNull(em);
	}
}
```

**Comment by tomas-langer** [comment]
1. You can use `Config.create()` as a shortcut for builder
2. Server does create its own `Config`, though you can also pass your own instance using the builder
3. You can control how config is created through meta configuration (see the docs)
4. In MP you have a choice for configuration
   1. You can either leave it to us to create a configuration instance (that uses either meta configuration, or expected configuration files on classpath)
   2. You can create configuration using Helidon SE Config and pass it to the Server builder
   3. You can create configuration using MicroProfile Config (`ConfigProviderResolver.instance().getBuilder()`) to use the MP specific APIs

**Comment by tomas-langer** [comment]
I realized I did not answer one question - yes, `Config config = ConfigProvider.getConfig();` is the correct way to obtain config instance anywhere in Helidon MP. You must be careful about timing, if you want to use a custom build config. If you rely on the default instance, you are fine calling this method anytime (though I would recommend not calling it in a static initializer, as that would not work nice with GraalVM native image in the future).

**Comment by tomas-langer** [comment]
For the unit testing of CDI, I would kindly ask @ljnelson to get into the conversation

**Comment by ljnelson** [comment]
For unit testing I like to keep things simple.  Here's a short little recipe I use (I'm typing this mostly from memory so excuse syntax errors; I'm sure you'll get the idea:
```
@ApplicationScoped // make the test itself a bean
class MyTest {

  private SeContainer cdiContainer;

  @Inject // inject whatever you want
  private Frob whatever;

  @Inject // here we've injected a MicroProfile Config implementation
  private Config microprofileConfig;

  @PersistenceContext // ...if you use Helidon JPA stuff
  private EntityManager em;

  @Inject // self-injection so you can test interceptors etc.
  private MyTest self;

  @BeforeEach
  public void setUp() {
    if (this.cdiContainer != null) {
      this.cdiContainer.close();
    }
    final SeContainerInitializer initializer = SeContainerInitializer.newInstance();
    initializer.addBeanClasses(this.getClass());
    this.cdiContainer = initializer.initialize();
    // If you need Helidon and not just CDI; obviously store it somewhere
    final Server server = Server.builder().cdiContainer(this.cdiContainer).start();
  }

  @AfterEach
  public void tearDown() {
    if (this.cdiContainer != null) {
      this.cdiContainer.close();
  }

  @Test 
  public void testSomething() {
    // you can't just use, e.g. this.em, because @Test methods are not invoked by CDI.
    // so you'll need to use a method on the test-as-bean, like so:
    final EntityManager entityManager = self.getEntityManager();
    final Frob whatever = self.getWhatever();
  }

  public Config getConfig() {
    return this.config;
  }

  public EntityManager getEntityManager() {
    return this.em;
  }

  public Frob getWhatever() {
    return this.whatever;
  }
}
```

**Comment by ljnelson** [comment]
@mattjlewis Does this get you what you need?

**Comment by mattjlewis** [comment]
Yes, thank you.
