### ISSUE TITLE
Quickstart MP guide for metrics not working as expected

### ISSUE THREAD

**Issue by ottuzzi** [oracle/helidon#1196]
## Environment Details
* Helidon Version: 1.4
* Helidon MP
* JDK version: Amazon Corretto 11
* OS: Amazon Linux 2
* Docker version (if applicable): Docker Desktop CE 2.1

----------

## Problem Description
Following the quickstart MP guide I'm running the example in Docker container and testing all reported URL using curl. When trying "Metrics in JSON Format" curl will respond after many seconds reporting metrics in prometheus format and not json as requested.

## Steps to reproduce
Follow the quickstart guide, change Dockerfile to use `FROM maven:3-amazoncorretto as build` and `FROM amazoncorretto:11` as 2nd stage and run the command `curl -H 'Accept: application/json' -X GET http://localhost:8080/metrics`

**Comment by spericas** [comment]
A quick test shows it works just fine without changing the FROM image. Will investigate further.

**Comment by spericas** [comment]
Even with the suggested changes, it seems to work just fine. Please provide more information.

```
>> curl -H 'Accept: application/json' http://localhost:8080/metrics
{"base":{"classloader.loadedClasses.count":7546,"classloader.loadedClasses.total":7555,"classloader.unloadedClasses.total":0,"cpu.availableProcessors":2,"cpu.systemLoadAverage":0.21,"gc.time;name=G1 Old Generation":0,"gc.time;name=G1 Young Generation":111,"gc.total;name=G1 Old Generation":0,"gc.total;name=G1 Young Generation":12,"jvm.uptime":10775,"memory.committedHeap":55574528,"memory.maxHeap":524288000,"memory.usedHeap":26299008,"thread.count":16,"thread.daemon.count":13,"thread.max.count":16},"vendor":{"grpc.requests.count":0,"grpc.requests.meter":{"count":0,"meanRate":0.0,"oneMinRate":0.0,"fiveMinRate":0.0,"fifteenMinRate":0.0},"requests.count":1,"requests.meter":{"count":1,"meanRate":0.13272131641177248,"oneMinRate":0.0,"fiveMinRate":0.0,"fifteenMinRate":0.0}}}```

**Comment by ottuzzi** [comment]
Hi,

  thank you for testing!
After you feedback I tried again and I found the issue: in Windows 10 command line you have to use double quotes to add request headers.
So in windows the right command is 
`curl.exe -H "Accept: application/json" http://localhost:8080/metrics`

Thanks for your help!
