### ISSUE TITLE
Oracle UCP autoCommit property - clarification

### ISSUE THREAD

**Issue by mattjlewis** [oracle/helidon#1202]
I am using Helidon 1.4.0 and am having issues with transaction rollbacks when updating multiple entities in one transaction (and have made note of the issue 1146 - I am yet to test with 2.0-SNAPSHOT).
While investigating this, I noticed that the JDBC connection property autoCommit is set to true. Should this be false? I cannot see a way to change this property via configuration properties as I think it can only be configured via setConnectionProperties(Properties).

**Comment by ljnelson** [comment]
@mattjlewis and I have been in extensive conversations around this.  Suffice it to say I think there is a real issue involved, but not at the JPA level.  That is, Helidon's (2.0-SNAPSHOT) JPA support is OK, but the enlistment of even single-database resources into a JTA transaction is problematic.  #1146 definitely addresses the JPA issues related to this, but not the underlying how-do-I-get-a-`javax.sql.DataSource`-as-used-by-Hibernate-or-EclipseLink-to-participate-properly-in-a-JTA-transaction bits.

**Comment by ljnelson** [comment]
See #1316.

**Comment by ljnelson** [comment]
Fixed with #1376.
