### ISSUE TITLE
Add support for Helidon Features

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1215]
We should print out features enabled for the current instance.
This should differ for Helidon SE and MP, only printing out features of the current flavor.

Features are (sample list):
- Server
- JAX-RS
- Config
- Tracing
- Metrics
- Security

Consider support for nesting, example:
- Tracing
  - Jaeger
- Security
  - OIDC
  - ABAC

**Comment by m0mus** [comment]
I know that it’s not directly related to this task. There must me an easy way to enable and disable features using CLI. I want to make sure that property names in CLI and here are the same to avoid inconsistency and user confusion.
