### ISSUE TITLE
Outdated version of protobuf-java

### ISSUE THREAD

**Issue by hadrienk** [oracle/helidon#1221]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 1.4.0
* Helidon SE
* JDK version: openjdk version "11.0.5" 2019-10-15
* OS: Archlinux
* Docker version (if applicable): N/A

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"

I have a maven module inside a multi-module project that contains only my protobuf files. When using the module system what I needed for the autogenerated java classes to compile was as follow: 

```
    requires com.google.common;
    requires com.google.protobuf;
    requires io.grpc;
    requires grpc.stub;
    requires grpc.protobuf;
    requires java.annotation;
```

I ran into the problem when I then used this module in my helidon service implementation. The problem is that since the version `3.9.1` of `protobuf-java` the module name has been changed to `com.google.protobuf`, whereas part of the helidon grpc stack brings in the version `3.5.1` that uses the module name `protobuf.java`. 

https://github.com/protocolbuffers/protobuf/issues/3903

Downgrading to version `3.5.1` and using module name `protobuf.java` fixed my problem but I suppose it would be better to bump the protobuf-java version.

[//]: # "Include stack traces or command outputs"

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"

Try to use a protobuf-java version >= `3.9.1` and import it as `com.google.protobuf` and see that the `requires transitive protobuf.java;` from grpc-core causes problems.

[//]: # "Provide sample code/application if relevant"

https://github.com/oracle/helidon/blob/d34ad1e36e08bbe1fa36974b1b18d8c66118d785/grpc/core/src/main/java/module-info.java#L20-L44

**Comment by tomas-langer** [comment]
We depend (transitively) on version 3.11.0.
Could you please try with latest 1.x version (1.4.7), as this should be resolved.
