### ISSUE TITLE
Investigate websocket support

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon#123]
Netty has support for websocket.
Investigate how the webserver API could be used to handle websockets.

See some netty + websocket blog post: https://medium.com/@irunika/how-to-write-a-http-websocket-server-using-netty-f3c136adcba9

**Comment by romain-grecourt** [comment]
See also #143

**Comment by dansiviter** [comment]
Could this be via WebSocket 1.1 Spec (JSR356) APIs? I know you're not trying to write the next JEE container here but I'll make porting code to Helidon easier.

**Comment by spericas** [comment]
Just as we did for REST in MP using JAX-RS, we should consider JSR356 for WS. I agree that it would help migration to Helidon MP.

**Comment by AshwinPrabhuB** [comment]
WebSockets would definitely help in use cases that require a server push. With the current Helidon infra, I guess the max one can achieve is a SSE with a long running Handler. But a WebSocket protocol support within Helidon would definitely help us avoid a parallel stack like Node just for the push capability.

**Comment by dansiviter** [comment]
Any update on this?

I've had a look into this and it looks like both a 'native' API as well as a JSR356 implementation would be needed especially if reusing the Netty implementation of websockets as it's somewhat buried under `Server[Request|Response]` and `Bare[Request|Response]`.

I'm tempted to have a bash at it so any guidance on style?

**Comment by eduvim** [comment]
I would like to point to help to implement this, I mean it's an important feature to be added and critical if we think on jax rs. In order to be logical I am thinking just on apply the medium blog's idea, then we can add it to helidon and for the last we should think on something like a SocketSeevices

**Comment by spericas** [comment]
@eduvim Please see #927. There's already a simple prototype that integrates with Helidon SE. We are targeting this work for Helidon 2.0. I'm going to close this issue so that we can continue discussion over there.
