### ISSUE TITLE
Refactor media type selector in WebServer.

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon#1236]
`io.helidon.webserver.ContentTypeSelector` maps file extensions to `MediaType` and can be useful for application developers.

We should consider making it public for 2.0, and perhaps move it to `common/http`.

**Comment by romain-grecourt** [comment]
Merge the content of https://github.com/oracle/helidon/blob/master/webserver/webserver/src/main/java/io/helidon/webserver/ContentTypeSelector.java to https://github.com/oracle/helidon/blob/master/common/media-type/src/main/resources/io/helidon/common/media/type/default-media-types.properties

**Comment by romain-grecourt** [comment]
Then replace usage with `io.helidon.common.media.type.MediaTypes`

**Comment by tomas-langer** [comment]
I am looking at #1869 - I will fix this issue as part of that effort, as it is solely used from static content handling
