### ISSUE TITLE
Allow SocketConfiguration to specify SSLParameters as well as SSLContext

### ISSUE THREAD

**Issue by justy152** [oracle/helidon#1266]
## Environment Details
* Helidon Version: 1.4.0
* Helidon SE
* JDK version: 11
* OS: MacOS

----------

## Problem Description
I would like to be able to set up a WebServer socket that needs client auth but there doesn't seem to be a way of setting SSLParameters so that I can do that.

The SocketConfiguration.Builder class has an ssl method that allows an SSLContext to be specified, but can we also add an sslParams method that takes SSLParameters (and a corresponding sslParams() method on the SocketConfiguration class that returns what was set)?

**Comment by tomas-langer** [comment]
Mutual TLS is now fully supported by Helidon. Could you please check with latest Helidon version?
If there is still a problem with configuration of TLS, please re-open this issue and let us know what is missing.
Thanks!
