### ISSUE TITLE
Support for HTTP/2 Server Push

### ISSUE THREAD

**Issue by spericas** [oracle/helidon#1286]
HTTP/2 has support for server push of resources. It isn't clear how popular this feature is these days. For some background information, see https://jakearchibald.com/2017/h2-push-tougher-than-i-thought/.

Support for HTTP/2 server push would require the introduction of some new API in Helidon. I'm marking it as low priority since it hasn't been requested by our users yet.

**Comment by tomas-langer** [comment]
This may no longer be needed, as browsers seem to go away from it, see for example https://www.ctrl.blog/entry/http2-push-chromium-deprecation.html

**Comment by tomas-langer** [comment]
Closing this issue as server push is not requested
