### ISSUE TITLE
OpenAPI incomplete with multiple JAX-RS applications

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1288]
When I have two JAX-RS applications in my MP project, the OpenAPI is generated only for one of them (a random one is picked).

I will link a reproducer.

**Comment by tomas-langer** [comment]
Reproducer: https://github.com/tomas-langer/helidon-repro-1288

**Comment by tjquinno** [comment]
Tomas also mentioned that this test illustrates the problem:

tests/integration/native-image/mp-1

**Comment by tjquinno** [comment]
The MP OpenAPI 1.x spec states this about multiple applications:

> The 1.0 version of the MicroProfile OpenAPI specification does not define how the /openapi endpoint may be partitioned in the event that the MicroProfile runtime supports deployment of multiple applications. If an implementation wishes to support multiple applications within a MicroProfile runtime, the semantics of the /openapi endpoint are expected to be the logical union of all the applications in the runtime, which would imply merging multiple OpenAPI documents into a single valid document (handling conflicting IDs and unique names).

There is a 2.0-MR1 spec, but it says exactly the same thing.

We will start by adopting the "merge" approach while carefully monitoring the spec as it evolves in case it changes direction on this topic.

**Comment by tjquinno** [comment]
PR #1493 contains the changes to address this issue. Those changes include a simple two-app test, and the reproducer https://github.com/tomas-langer/helidon-repro-1288 Tomas linked to (with some updates to work with 2.0) now returns the endpoints from both apps.
