### ISSUE TITLE
Exception thrown from SseEventSink instead of the ComplectionStage

### ISSUE THREAD

**Issue by martin-sladecek** [oracle/helidon#1290]
The fix for https://github.com/oracle/helidon/issues/806 makes the issue to be thrown directly out of the send() method instead of being wrapped in the returned CompletionStage.
----------

## Problem Description
Stack trace: 
java.lang.IllegalStateException: This event source has already been closed.
	at org.glassfish.jersey.media.sse.internal.JerseyEventSink.checkClosed(JerseyEventSink.java:129) ~[jersey-media-sse-2.29.1.jar:?]
	at org.glassfish.jersey.media.sse.internal.JerseyEventSink.send(JerseyEventSink.java:99) ~[jersey-media-sse-2.29.1.jar:?]
## Steps to reproduce
See original issue

**Comment by danielkec** [comment]
Sorry it took so long, I have just confirmed with Jersey team, this is expected behavior. There is even TCK test for that. While javadoc of the `send` method is not somehow clear about it, javadoc of the `close` method is quite explicit:
```
    /**
     * Close the {@link SseEventSink} instance and release all associated resources.
     * <p>
     * Subsequent calls have no effect and are ignored. Once the {@link SseEventSink} is closed,
     * invoking any method other than this one and {@link #isClosed()} would result in
     * an {@link IllegalStateException} being thrown.
     */
    @Override
    void close();
```
Accompanied by javadoc of `isClosed` the picture is complete:
```
    /**
     * Check if the stream has been closed already.
     * <p>
     * Please note that the client connection represented by this {@code SseServerSink} can be closed by the
     * client side when a client decides to close connection and disconnect from the server.
     *
     * @return {@code true} when closed, {@code false} otherwise.
     */
    boolean isClosed();
```

**Comment by danielkec** [comment]
When the time comes for upgrading to Helidon 2.0, consider our new reactive Kafka connector should be as simple as this:
```java
@Incoming("from-kafka")
public void broadcast(String msg) {
    this.sseBroadcaster.broadcast(new OutboundEvent.Builder().data(msg).build());
}
```
Here is some background:
https://medium.com/helidon/reactive-messaging-with-helidon-2-0-f5de1ca5dc63
And example of usage of messaging with SSE:
https://github.com/oracle/helidon/tree/master/examples/microprofile/messaging-sse
