### ISSUE TITLE
Helidon SE: use jlink to create minimal Java 11 runtime

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#130]
## Environment Details
* Helidon Version: 0.10.4
* Helidon SE 
* JDK version: 11

## Problem Description

We should determine the minimum set of modules needed to run a Helidon SE application and document it. Also, we should consider updating our quickstart Dockerfile to generate the JRE as part of a two stage docker build.

I did a quick experimentation and this seems to work, but I did not exercise very many code paths:

```
$JAVA_HOME/bin/jlink --compress=2 --output jre --add-modules java.base,java.logging,java.sql,java.desktop,java.management
```

**Comment by barchetta** [comment]
Here as some examples of dependencies on modules of interest:

java.desktop:  java/beans/IntrospectionException (org.yaml.snakeyaml)
java.sql: java/sql/Date (org.yaml.snakeyaml)

**Comment by barchetta** [comment]
Example Dockerfile to generate image with custom JRE:
```
# Multistage docker build.
# Stage 1: Build custom Java 11 JRE and put it in /linked
FROM openjdk:11-slim AS build
RUN ["jlink", "--compress=2", \
     "--add-modules", "java.base,java.logging,java.sql,java.desktop", \
     "--output", "/linked"]

# Stage 2: Build application image using JRE from Stage 1
FROM debian:sid-slim
COPY --from=build /linked /opt/jdk/
ENV PATH=$PATH:/opt/jdk/bin

RUN mkdir /app
COPY libs /app/libs
COPY ${project.artifactId}.jar /app

CMD ["java", "-jar", "/app/${project.artifactId}.jar"]
```

**Comment by ljnelson** [comment]
Yep; more stuff than you think pulls in `java.desktop` for the Java beans features.

Haven’t thought deeply about this but if we put together some kind of configuration in the sample app that does not use YAML etc. we might be able to use `requires static` or something similar to sever a branch off the dependency tree.

**Comment by barchetta** [comment]
Ack! Because of bug https://github.com/docker-library/openjdk/issues/217 the above approach results in a docker image size >500MB. Need to look for a work-around.

**Comment by barchetta** [comment]
The work-around for the bloated `libjvm.so` is to strip it. Ick:
```
RUN [ "apt", "update"]
RUN [ "apt-get", "install", "-y", "binutils"]
RUN ["strip", "-p", "--strip-unneeded", "/var/tmp/myjre/lib/server/libjvm.so"]

```

**Comment by barchetta** [comment]
This is being documented in PR #182
