### ISSUE TITLE
Missing javadoc for grpc MP

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1377]
Our build job does not generate javadoc for grpc MP

**Comment by romain-grecourt** [comment]
I don't see any `io.helidon.microprofile.grpc` under javadocs/pom.xml

**Comment by barchetta** [comment]
It looks like this was fixed as part of the 2.0 javadoc re-work (for example: https://helidon.io/docs/v2/apidocs/io.helidon.microprofile.grpc.server/module-summary.html).
