### ISSUE TITLE
Update helidon-quickstart-mp to show proper JAX-RS application discovery

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#1380]
## Environment Details
* Helidon Version: 2.0.0-M1
* Helidon MP
* JDK version: 11
----------

## Problem Description
helidon-quickstart-mp still uses `javax.ws.rs.core.Application.getClasses()` for discovery. In light of the new JAX-RS scanning improvements, should we change this (remove it)?

**Comment by spericas** [comment]
I think so, it's easier to integrate with other libraries if scanning is enabled and not overridden.

**Comment by tomas-langer** [comment]
Why do we have the application class at all? I am not confident this change is good.

**Comment by spericas** [comment]
> Why do we have the application class at all? I am not confident this change is good.

Why aren't you confident?
