### ISSUE TITLE
No documentation coverage for Fault tolerance

### ISSUE THREAD

**Issue by zarub2k** [oracle/helidon#1382]
I am not able to find any document reference for Fault tolerance in Helidon documentation. Am I missing something? Or is it hidden on my view?

**Comment by tomas-langer** [comment]
Helidon MP fault tolerance:
https://helidon.io/docs/v2/#/mp/faulttolerance/01_overview

As this implements a specification and we do not add Helidon specific features, this docs is quite short.

There is no Helidon SE fault tolerance (yet) - we do have a new module in `master` - it was not yet released and it is now in experimental and "incubation" mode. We will add docs for it once we are confident it is ready for use.

**Comment by ljamen** [comment]
Issue closed with 2399
