### ISSUE TITLE
Native image docker image is missing a library

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1383]
When you try a native image build in a docker image, it fails as the following library is missing:
`libstdc++`

This library needs to be installed.

**Comment by barchetta** [comment]
I just tried the `Dockerfile.native` that comes as part of the 2.0.0-M1 Helidon SE archetype and it  worked. It uses `helidon/jdk11-graalvm-maven:19.3.1`  which has `libstdc++`:
```
$ ls /usr/lib/libstdc++*
/usr/lib/libstdc++.so.6  /usr/lib/libstdc++.so.6.0.19
```

**Comment by tomas-langer** [comment]
From customer:
So far it’s a main method that launches a fabric8 Kubernetes client and installs a watch

Version is 1.4.1
