### ISSUE TITLE
[Inquiry] Plans for MicroProfile GraphQL Adoption 

### ISSUE THREAD

**Issue by emecas** [oracle/helidon#1401]
Since there is a release candidate for MicroProfile GraphQL 1.0.0

https://github.com/eclipse/microprofile-graphql/releases/tag/1.0.0-RC1

I'm wonder if there is any plan for adopting it soon, I have been looking around the existent issues here and available documentation , but did not find anything related to the subject

In general terms, how the process  for supporting new Microprofile specifications works?

Thanks

**Comment by m0mus** [comment]
Thanks for the info! We have no concrete plans for adoption of GraphQL spec yet. We'll think about it after Helidon 2.0 release.

**Comment by anthonyvdotbe** [comment]
I suppose this can be closed, since there's now #799
