### ISSUE TITLE
Config Profiles

### ISSUE THREAD

**Issue by spericas** [oracle/helidon#1416]
EDITED by @tomas-langer 
As agreed, the following config profile approach will be added to Helidon SE:

- [x] support inline config in meta config
- [x] support config.profile as a fallback system property to define the file (name config-profile-${profile}.xxx
- [x] support env var to define a different "profile" `HELIDON_CONFIG_PROFILE`
- [x] basically rename "meta configuration" to "config profile"
- [x] add a guide/example with a best practise
sources:
  - type: "file"
    properties:
      path: "config/application-dev.yaml"
  - type: "inlined"
    properties:
      key: "value"
      "server.port": 40877

Original text:
The idea behind config profiles is to be able to repeat configuration (properties) in such a way that they can be selected depending on the target environment in which the application will run. Selection of a profile can be done _externally_ via a system property or environment variable such as HELIDON_CONFIG_PROFILE.

~~As an example, different HTTP ports may be necessary in production and development:~~

```
%dev.http.port=8080
%prod.http.port=7001
```

~~where dev and prod are environment names. A property without a profile prefix would be active in all environments.~~

~~The notion of config profiles has been requested a few times, and it is supported by many other microservice frameworks.~~

**Comment by barchetta** [comment]
For reference: Profile support in MicroProfile Config 2.0: https://github.com/eclipse/microprofile-config/issues/418

**Comment by tomas-langer** [comment]
We have agreed on the following steps:

- support `inline` config in meta config
- support `config.profile` as a fallback system property to define the file (name `config-profile-${profile}.yaml`
- support env var to define a different "profile"
- basically rename "meta configuration" to "config profile"
- example `System.setProperty("io.helidon.config.meta-config", "config/config-profile-" + System.getProperty("config.profile") + ".yaml");`
- add a guide/example with a best practise

```yaml
sources:
  - type: "file"
    properties:
      path: "config/application-dev.yaml"
  - type: "inlined"
    properties:
      key: "value"
      "server.port": 40877
```

Possible structure:
```
config/config-profile-dev.yaml (with inlined config)
config/config-profile-stage.yaml (with a file based config)
etc.
```
