### ISSUE TITLE
Update SE config documentation for 2.0

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1420]
Update documentation after PR #1417 

- [x] Javadoc
- [x] User Documentation SE
- [x] User Documentation MP
- [x] Changelog

**Comment by tomas-langer** [comment]
Changelog - differentiate between MP and SE.

**Comment by ljamen** [comment]
1420 Covers both MP and SE doc for Config. 
For MP Config include the following:

    About MP Config specification
    Concepts
    How it's related to Helidon SE Config (partially covered in JAX-RS)
    Use cases

For SE Config include: 
Reflect Helidon 2.0 changes

**Comment by romain-grecourt** [comment]
@tomas-langer Can you update the task list  to reflect the current status, thanks.
