### ISSUE TITLE
Support server push in the webserver API

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon#143]
The webserver API needs to be updated in order to support server side push.
Could be supported by HTTP2 or websocket (which we don't have at the moment)

**Comment by dansiviter** [comment]
This would be needed for MP 2.0 support as SSE is part of the JAX-RS 2.1 spec.

**Comment by spericas** [comment]
We should already have SSE support via Jersey. We do have support for JAX-RS 2.1. The notion of _server push_ is broad. E.g., in HTTP/2 it refers to the ability of send related resources ahead of time, before they are requested.

**Comment by AshwinPrabhuB** [comment]
WebSocket would be a nice addition for server pushed notifications that isn't the same as HTTP/2 which is more of a network optimization for responses at the protocol layer.

**Comment by lutzhorn** [comment]
Is there any Maven dependency to be added to be able to use SSE with MP/JAX-RS 2.1?

**Comment by spericas** [comment]
SSE support would likely require adding a new dependency to your project. For more information, see Jersey's documentation here https://jersey.github.io/documentation/latest/sse.html

**Comment by spericas** [comment]
I'm closing this issue because the discussion has diverged into multiple topics that are not all related. For information about WebSockets in Helidon, see #1231. SSE should already be supported via Jersey. Finally, I will create another issue that is specific to HTTP/2 server push of resources.
