### ISSUE TITLE
Add support for CDI discovery and registration of JAX-RS providers

### ISSUE THREAD

**Issue by aseovic** [oracle/helidon#1432]
## Environment Details
* Helidon Version: 1.4.1 and 2.0
* Helidon MP
* JDK version: any
* OS: any
* Docker version (if applicable):

----------

## Problem Description

At the moment JAX-RS providers, such as request/response filters and message body readers/writers are not discovered and registered automatically by the CDI, unlike JAX-RS resources.

This is problematic, as it requires one of several approaches:

1. Creating `Application` class and explicitly specifying all resources and providers via `getClasses` method
2. Implementing `MpService`, which is going away in Helidon 2.0 and seems like an overkill anyway
3. Implementing `AutoDiscoverable`, which is internal and fairly low level.

Neither of these approaches seems reasonable for such a common use case. If the provider is implemented as a proper CDI managed bean, we should be able to discover it and register it automatically.
 
## Example

The following filter should be automatically discovered and registered with JAX-RS application, just like the resources currently are:

```java
/**
 * Simple CORS filter.
 */
@ApplicationScoped
@Provider
@ConstrainedTo(RuntimeType.SERVER)
public class CorsResponseFilter
        implements ContainerResponseFilter {
    @Override
    public void filter(ContainerRequestContext requestContext, ContainerResponseContext responseContext) {
        MultivaluedMap<String, Object> headers = responseContext.getHeaders();

        headers.add("Access-Control-Allow-Origin", "*");
        headers.add("Access-Control-Allow-Methods", "GET, POST, DELETE, PUT, PATCH, OPTIONS, HEAD");
        headers.add("Access-Control-Allow-Headers", "Content-Type, *");
    }
}
```

**Comment by ljnelson** [comment]
…but it would seem to be critical IMHO to respect https://eclipse-ee4j.github.io/jersey.github.io/apidocs/latest/jersey/org/glassfish/jersey/server/ServerProperties.html#FEATURE_AUTO_DISCOVERY_DISABLE if it is present in the application's configuration in any way, shape or form, yes?
