### ISSUE TITLE
Add CORS support to Helidon

### ISSUE THREAD

**Issue by aseovic** [oracle/helidon#1436]
## Environment Details
* Helidon Version: 1.x and 2.x
* Helidon SE or Helidon MP: both
* JDK version: any
* OS: any
* Docker version (if applicable):

----------

## Problem Description
CORS support is a very generic and useful piece of functionality that users shouldn't have to implement by themselves. For example, it may be necessary to allow access to the API endpoints from the OpenAPI/Swagger UI (my use case), or for many other use cases (modern single page apps typically need it to access API endpoints).

We should provide an OOB implementation that allows users to enable CORS via custom `ContainerResponseFilter` and `@CORS` annotation at the application/resource/method level, and allow them to configure various `Access-Control-*` headers via annotation properties.

**Comment by tomas-langer** [comment]
Duplicate of #931 I think

**Comment by aseovic** [comment]
Yup, you are correct. Closing it, sorry.
