### ISSUE TITLE
Java 8 DateTime in DbMapper

### ISSUE THREAD

**Issue by hantsy** [oracle/helidon#1454]
* Helidon Version:2.0.m1
* Helidon SE 
* JDK version: AdaptOpenJDK 11
* OS: Windows 10 
* Docker version (if applicable):

I used PostgreSQL for tests, [the PostgreSQL Jdbc driver supports Java 8 DateTime well](https://jdbc.postgresql.org/documentation/head/java8-date-time.html).

But when I tried to fetch a `TIMESTAMP` field to `LocalDateTime` property, it failed.

```sql
created_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP ,
```
The `DbMapper`, it always a `java.sql.TimeStamp`, I can not convert it as `LocalDateTime` direclty.

```java
 post.setCreatedAt(createdAt.as(Timestamp.class).toLocalDateTime());
```

My [sample codes](https://github.com/hantsy/helidon-sandbox/tree/master/se-dbclient).

**Comment by Tomas-Kraus** [comment]
OK, this seems to be Helidon DB Client issue. I'll let you know when I know more.
thanks for the report.

**Comment by Tomas-Kraus** [comment]
I'm trying to run your sample code.
```
docker run -it --rm --name pgsql -p 5432:5432 -e POSTGRES_DB=test -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password postgres
```
Starts PgSQL to be used by jUnit tests, but there is no DB schema and tests are failing with erorrs like 
```
relation "comments" does not exist
```
Does your sample code have some DB initialization part, or at least SQL script to tun?

**Comment by hantsy** [comment]
Use [docker-compose.yaml](https://github.com/hantsy/helidon-sandbox/blob/master/docker-compose.yml) file to serve PostgreSQL service, it includes a init.sql script file

**Comment by Tomas-Kraus** [comment]
Thanks, it works now.
What HTTP request shall I use to trigger the issue?

**Comment by hantsy** [comment]
If you replace [this line](https://github.com/hantsy/helidon-sandbox/blob/master/se-dbclient/src/main/java/demo/PostMapper.java#L25).

with:

```java
post.setCreatedAt(createdAt.as(LocalDateTime.class));
```

Will get an exception, but according to [PostgreSQL JDBC doc](https://jdbc.postgresql.org/documentation/head/java8-date-time.html). it should work if DbMapper using ResultSet or RowSet.

**Comment by Tomas-Kraus** [comment]
I got it:
```
Caused by: io.helidon.common.mapper.MapperException: Failed to map class java.sql.Timestamp to class java.time.LocalDateTime: Failed to find mapper.
	at io.helidon.common.mapper.MapperManagerImpl.lambda$notFoundMapper$6(MapperManagerImpl.java:128)
	at io.helidon.common.mapper.MapperManagerImpl.map(MapperManagerImpl.java:55)
	at io.helidon.dbclient.jdbc.JdbcStatementQuery$RowPublisher$2.map(JdbcStatementQuery.java:453)
	at io.helidon.dbclient.jdbc.JdbcStatementQuery$RowPublisher$2.as(JdbcStatementQuery.java:447)
	at demo.PostMapper.read(PostMapper.java:29)
```
when running 
```
curl -X GET http://localhost:8080/posts
```
on code with few modifications:
```
    public Post read(DbRow dbRow) {
        var id = dbRow.column("id");
        var title = dbRow.column("title");
        var content = dbRow.column("content");
        DbColumn createdAt = dbRow.column("created_at");
        Post post = new Post();
        post.setId(id.as(UUID.class));
        post.setTitle(title.as(String.class));
        post.setContent(content.as(String.class));
        LocalDateTime createdAtLocDT = createdAt.as(LocalDateTime.class);
        post.setCreatedAt(createdAtLocDT);

        return post;
    }
```

**Comment by Tomas-Kraus** [comment]
The question is, whether this is a bug or a feature. :)
JDBC driver returns this as java.sql.Timestamp and will always do that.
Helidon does not have default mapper for `java.sql.Timestamp to java.time.LocalDateTime`
I'll implement set of mappers to map java.sql.Timestamp to Calendar/LocalDateTime/ZonedDateTime types.

**Comment by Tomas-Kraus** [comment]
Fixed in PR https://github.com/oracle/helidon/pull/1485

**Comment by Tomas-Kraus** [comment]
PR is merged, closing this issue.
