### ISSUE TITLE
Helidon MPConfig does not return config values based on MP priority 

### ISSUE THREAD

**Issue by LateshDulani** [oracle/helidon#1468]
## Environment Details
* Helidon Version: 1.4.1
* Helidon MP
* JDK version: 1.8
* OS: Any
* Docker version (if applicable):

----------

I have created a custom ConfigSource with priority > microprofile-config.properties < system properties. So that property values in microprofile-config.properties can be overridden from another properties file.

When requesting config value from org.eclipse.microprofile.config.Config, correct and overridden value returns but if I use io.helidon.microprofile.config.MpConfig to get config value it still returns value from microprofile-config.properties.

This is happening because when creating helidon config code is considering MP priority and only loading property in set order.

## Steps to reproduce
1. Create a custom CustomPropertyConfigSource to load and read config dynamically with priority > 100 < 300.
2. Try to get overridden property using MPConfig.

Attached is the same code with test case.
[quickstart-mp-bug-mp-priority.tar.gz](https://github.com/oracle/helidon/files/4288649/quickstart-mp-bug-mp-priority.tar.gz)

**Comment by tomas-langer** [comment]
Workaround:
Use Priority instead of ordinal. Until this issue is resolved - if you change the `PRIORITY` to 50, the test will pass.

**Comment by tomas-langer** [comment]
OK, I see the problem now
1. MP Config works as expected, including injection - this follows the MP ordinals as it should
2. Problem is when the key is retrieved from Helidon config

I will see how we can align the Helidon config priority with MP ordinals

**Comment by LateshDulani** [comment]
Yes correct. and reason being Helidon Config reads microprofile-config.properties as highest priority.

**Comment by tomas-langer** [comment]
I have found a fix, will create a PR in a few minutes.
Also validated that in `master` branch, this is fixed, so the problem does not exist in 2.0.*

**Comment by tomas-langer** [comment]
The fix is now merged into 1.x branch.
