### ISSUE TITLE
Table field naming convention issues

### ISSUE THREAD

**Issue by hantsy** [oracle/helidon#1474]
* Helidon Version:2.0.m1
* Helidon SE 
* JDK version: AdaptOpenJDK 11
* OS: Windows 10 
* Docker version (if applicable):

I used PostgreSQL in Docker for tests.

When I defined the **createdAt** as TIMESTAMP like this.

```sql
createdAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP ,
```

Then I tried to fetch this field via `DbRow`, I found the field name is **createdat**, not **createdAt**. I am not sure this is the design purpose or an issue.

(I have changed my codes to use `created_at` as the field name finally to avoid this issue)

**Comment by Tomas-Kraus** [comment]
This can be affected by too many things, not just Helidon. I don't have access to your DB so please verify few things first.
- check whether database columns are really case-sensitive. See https://blog.xojo.com/2016/09/28/about-postgresql-case-sensitivity/
What does describe on the table show?
- Helidon DB client shall work exactly the same way as your JDBC driver. Please try some minimal test with JDBC prepare statement and check ResultSet:
```
ResultSet rs = statement.executeQuery();
ResultSetMetaData metaData = rs.getMetaData();
String name = metaData.getColumnLabel(i); // where i is index of your column
```
If metaData.getColumnLabel(i) returns case-sensitive names and Helidon does not, it's bug in Helidon.

**Comment by hantsy** [comment]
This problem should be caused by PostgreSQL itself. I know camel-case naming maybe not a good option for RDBMS.

**Comment by m0mus** [comment]
@hantsy It's worth investigating it. @Tomas-Kraus can you simulate it based on the sample code here https://blog.xojo.com/2016/09/28/about-postgresql-case-sensitivity/ and make sure that DB Client doesn't have problems with case sensitivity.

**Comment by hantsy** [comment]
I confirmed this is a PostgreSQL issue(maybe convention in PostgreSQL).

I defined a table like this.

```sql
CREATE TABLE IF NOT EXISTS Person(
ID UUID DEFAULT uuid_generate_v4() ,
FullName VARCHAR(255) NOT NULL,
Email VARCHAR(255) NOT NULL,
createdAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP ,
PRIMARY KEY (ID)
);
```
And create a jdbc sample to connect the database and println the metadata of table *Persone*.

```java
public class JdbcMetadataSample {
    private final String url = "jdbc:postgresql://localhost/test";
    private final String user = "user";
    private final String password = "password";

    public void printPersonTableMetadata() {
        Connection conn = null;
        try {
            conn = DriverManager.getConnection(url, user, password);
            System.out.println("Connected to the PostgreSQL server successfully.");

            var statement = conn.prepareStatement("select FullName, email, createdAt from PERSON");
            ResultSet rs = statement.executeQuery();
            ResultSetMetaData metaData = rs.getMetaData();

            for (int i = 1; i <= metaData.getColumnCount(); i++) {
                String label = metaData.getColumnLabel(i);
                String name = metaData.getColumnName(i);
                System.out.println("label:" + label);
                System.out.println("name:" + name);
            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    public static void main(String[] args) {
        JdbcMetadataSample app = new JdbcMetadataSample();
        app.printPersonTableMetadata();
    }
}
```

It prints the following results.

```bash
Connected to the PostgreSQL server successfully.
label:fullname
name:fullname
label:email
name:email
label:createdat
name:createdat
```

The column name and table in the SQL are insensitive, and in the JDBC metadata, it becomes lowercase.

**Comment by ljnelson** [comment]
That's right; [`DatabaseMetaData` can help you here](https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/DatabaseMetaData.html#storesLowerCaseIdentifiers()).

**Comment by Tomas-Kraus** [comment]
> @hantsy It's worth investigating it. @Tomas-Kraus can you simulate it based on the sample code here https://blog.xojo.com/2016/09/28/about-postgresql-case-sensitivity/ and make sure that DB Client doesn't have problems with case sensitivity.

Integration tests are running with MySQL. But maybe it's time to add few more databases.

**Comment by Tomas-Kraus** [comment]
Closing this. Created https://github.com/oracle/helidon/issues/1518 to setup PgSQL integration tests.
