### ISSUE TITLE
JSON-B for Jersey missing from microprfile bundle.

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1522]
We get a transitive dependency from Jersey that is older (1.0.3) than we use in Helidon (1.0.6).
We should add this explicitly to our bundle pom (exclude yasson from Jersey, add our own explicit version).

**Comment by ljnelson** [comment]
One way to approach this is to use dependency management (rather than exclusions) which imposes a version on an entire tree.

**Comment by tomas-langer** [comment]
This works for us, but not if a user references Helidon bom. The dependency management is lost if they have a different parent.

**Comment by tomas-langer** [comment]
This issue's root cause is that our microprofile bundle is missing dependency on JSON-B for Jersey.

**Comment by olotenko** [comment]
I wonder whether JSON-B should be excluded after all. If I use Jackson for client-to-Helidon, I shouldn't get JSON-B for Helidon-to-service.

**Comment by romain-grecourt** [comment]
@tomas-langer Need to remember this for our convergence story and the use of helidon-dependency to import 3rd party dependency manually if not inheriting from the application parent poms.
