### ISSUE TITLE
WebSocket: Annotated Endpoints always have contextRoot /websocket

### ISSUE THREAD

**Issue by dansiviter** [oracle/helidon#1565]
## Environment Details
* Helidon Version: MP 2.0.0-M2
* JDK version: 11
* OS: Windows
* Docker version (if applicable): N/A

----------

## Problem Description
Using Microprofile WebSocket integration only apps initialised with `ServerApplicationConfig` can have their `contextRoot` set. If using pure annotated endpoints, then this always defaults to `/websocket`. I feel there are two issues here:

* Default path should not be `/websocket` as we may want to interleave the routing with Jersey or other routes,
* Annotated endpoint should be inspected for `@RoutingPath` and that be honoured, but if it doesn't exist, use purely the value in `@ServerEndpoint#value`.

Issue is here: [WebSocketCdiExtension](https://github.com/oracle/helidon/blob/2.0.0-M2/microprofile/websocket/src/main/java/io/helidon/microprofile/tyrus/WebSocketCdiExtension.java#L182)

## Steps to reproduce
Create any annotated WebSocket endpoint. You'll see the message: 
> `INFO: Registering websocket application at /websocket`

**Comment by spericas** [comment]
This is currently by design and somewhat similar to how Grpc is supported. What you suggest is different (and has other issues), but I'm not sure is better, and is certainly less consistent with the SE support.

**Comment by dansiviter** [comment]
TBH my expectation is that the `@ServerEndpoint#value` is the only specifier of path, similar to how `@ApplicationPath#value` is. This would be the same regardless of server runtime. However, I will concede that the specification does state that:
>  If the WebSocket server includes the Jakarta Servlet API, the WebSocket root must be the same as the Servlet context root of the web application [WSC-6.4-1].
https://github.com/eclipse-ee4j/websocket-api/blob/master/spec/src/main/asciidoc/WebSocket.adoc#65-websocket-server-paths

...and as Servlet is not implemented in Helidon, it doesn't have to match. Therefore, can we at least be able to customise it? Otherwise, I'll have to put in horrible URL mappings to make the paths look consistent.

**Comment by dansiviter** [comment]
So for an MP example:
* JAX-RS `@ApplicationPath("my-app")` & `@Path("v1/foo")` = `<scheme>://<host>:<port>/my-app/v1/foo`
* WS `@ServerEndpoint("/my-app/v1/ws")` = `<scheme>://<host>:<port>/websocket/my-app/v1/foo`

I therefore cannot set a consistent context root, nor configure away from `/websocket`.

**Comment by spericas** [comment]
> So for an MP example:
> 
> * JAX-RS `@ApplicationPath("my-app")` & `@Path("v1/foo")`:
>   `<scheme>://<host>:<port>/my-app/v1/foo`
> * WS `@ServerEndpoint("/my-app/v1/ws")`:
>   `<scheme>://<host>:<port>/websocket/my-app/v1/foo`
> 

`@ServerEndpoint` is analogous to `@Path` not `@ApplicationPath`, that is, it applies to an individual endpoint. The default value for an application path in JAX-RS is `/`, in Web sockets is `/websocket` to avoid conflicts. 

To override the default for Web sockets you need to create a subclass of `ServerApplicationConfig` and use `@RoutingPath` on it; just like you need to define a subclass of `Application` and use `@ApplicationPath` in JAX-RS.

**Comment by dansiviter** [comment]
@spericas I just tried the `ServerApplicationConfig` approach and although I don't think `/websocket` should be the default, similar to other implementations of Jakarta WebSocket it should share the same context root at JAX-RS, Servlet, etc.,, it appears I can force it to share the same namespace which means I can simplify my Istio config.

I'll do some more testing first before I close this issue.

QQ: were there specific conflict issues with gRPC or WebSocket handlers that were observed by sharing the same content root? From my quick test it seems I can interleave JAX-RS and WebSocket endpoints.

**Comment by spericas** [comment]
@dansiviter It seemed like the separation of context roots would lead to fewer user surprises, but it sounds like it had the opposite effect in your app. Perhaps we should reconsider this decision before 2.0 goes final ...

**Comment by spericas** [comment]
Default context root has been set to "/" for WebSocket endpoints as well (PR #1622, PR #1631). This change should be available in the next milestone release (M3).
