### ISSUE TITLE
Metrics InterceptorBase uses SortedMap

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1591]
It seems the `InterceptorBase` uses `SortedMap` from API to get hold of a specific metric.
This should be refactored to use the registry method to get appropriate metric type,
such as `MetricRegistry.counter(...)` instead of `MetricRegistry.getCounters()`, as the first is implemented without a need for sorting all metrics every time a metric is needed.

This is a performance overhead.

**Comment by tjquinno** [comment]
The changes for issue #1595 addressed a couple of metrics interceptor performance issues, of which this was one. Marking this as closed.
