### ISSUE TITLE
#TYPE is redundant in prometheus format metrics

### ISSUE THREAD

**Issue by harishamurthy** [oracle/helidon#1606]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 14.1
* Helidon SE or Helidon MP: MP
* JDK version: JDK 8
* OS:N/A
* Docker version (if applicable):

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
/metrics response has the redundant TYPE value, 
for eg:
# TYPE base_gc_total counter
base_gc_total{name="PS MarkSweep"} 3
# TYPE base_gc_total counter
base_gc_total{name="PS Scavenge"} 5

Expected:
# TYPE base_gc_total counter
base_gc_total{name="PS MarkSweep"} 3
base_gc_total{name="PS Scavenge"} 5

[//]: # "State if the problem is easily reproducible or happens intermittently"
happens always.

[//]: # "Include stack traces or command outputs"
N/A
## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
/metrics
[//]: # "Provide sample code/application if relevant"
N/A

**Comment by spericas** [comment]
Possibly related to #1427. @harishamurthy Any chance you can try Helidon 1.4.4?

**Comment by spericas** [comment]
Please reopen if not fixed in latest 1.x release.
