### ISSUE TITLE
Ability to define WebSocket Extensions

### ISSUE THREAD

**Issue by dansiviter** [oracle/helidon#1607]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 2.0.0-M2
* Helidon SE or Helidon MP: MP
* JDK version: N/A
* OS: N/A
* Docker version (if applicable):

----------

## Problem Description
WebSocket implementation does not permit defining of installed extensions. This is predicated on another change being performed in Tyrus before this can work: (eclipse-ee4j/tyrus#694).

I think the change would be overriding the `#getInstalledExtensions` method in [here](/oracle/helidon/blob/2.0.0-M2/webserver/tyrus/src/main/java/io/helidon/webserver/tyrus/TyrusSupport.java#L165) but not sure of how the actual Extension classes should be passed/loaded into it.

## Steps to reproduce
N/A

**Comment by spericas** [comment]
@dansiviter Interesting, what extension are you looking to use?

**Comment by dansiviter** [comment]
@spericas `permessage-deflate` is the key one. It massively shrinks the websocket frames which is very useful for larger messages when clients are not geographically close.

It looks like Tyrus needs to do some work before Helidon can leverage it though. [Undertow uses](/undertow-io/undertow/blob/master/websockets-jsr/src/main/java/io/undertow/websockets/jsr/ServerWebSocketContainer.java) `#installedExtensions` as a basis for all endpoints, but Tyrus doesn't for some reason. 🤷‍♂

**Comment by dansiviter** [comment]
I've submitted a PR to Tyrus to link this to {{WebsocketContainer#getInstalledExtensions}} (eclipse-ee4j/tyrus#695). With this it may just be a case of overriding {{TyrusServerContainer#getInstalledExtensions}} in {{TyrusSupport}}.

**Comment by dansiviter** [comment]
Looks like [2.0.0-M1](https://github.com/eclipse-ee4j/tyrus/compare/1.16...2.0.0-M1-BRANCH) of Tyrus has this in. I'll create a PR when it's made it to release version.

**Comment by barchetta** [comment]
Implemented by PR #1934. Thanks @dansiviter
