### ISSUE TITLE
 Helidon GraalVM native image for webserver, static-content.

### ISSUE THREAD

**Issue by pmatejewski** [oracle/helidon#1623]
## Environment Details
* Helidon Version: 1.4.4
* Helidon SE
* JDK version: OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
* OS: Ubuntu 18.04.4 LTS
* Docker version: 19.03.8, build afacb8b7f0

----------

## Problem Description

GralVM native image do not render properly static-content example.

According to this [page](
https://github.com/oracle/helidon/wiki/Native-image) Helidon supports ahead of time compilation using GraalVM native image for webserver.
For me in case of static-conten example is not working properly.

#### Install GralVM

```
cd /tmp
wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.1/graalvm-ce-java11-linux-amd64-19.3.1.tar.gz
tar xvf graalvm-ce-java11-linux-amd64-19.3.1.tar.gz
export GRAALVM_HOME=/tmp/graalvm-ce-java11-19.3.1
$GRAALVM_HOME/bin/gu install native-image
```

#### ENV
$GRAALVM_HOME/bin/java -version
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)
OpenJDK 64-Bit Server VM GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07, mixed mode, sharing)
```

$GRAALVM_HOME/bin/native-image --version
```
GraalVM Version 19.3.1 CE
```

mvn -v
```
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 1.8.0_242, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.3.0-45-generic", arch: "amd64", family: "unix"
```

#### Helidon
```
git clone https://github.com/oracle/helidon.git
cd helidon/
git checkout tags/1.4.4
cd examples/webserver/static-content/
```

#### GraalVM Native Image 

```
For compilation native-image depends on the local toolchain, so please make sure: glibc-devel, zlib-devel (header files for the C library and zlib) and gcc are available on your system.
sudo apt-get install build-essential zlib1g-dev
```

```
mvn package -Pnative-image
./target/helidon-examples-webserver-static-content
http://localhost:8080/ui/index.html
```
* Note that http is running but the content is corrupted in my case starts with
```
pan></p>
    </div>
</div>

<div class="container">
    <!-- Example row of columns -->
```

If I run it normally without native-image page is rendered properly

```
mvn package
mvn exec:java
http://localhost:8080/ui/index.html
```

**Comment by tomas-langer** [comment]
Reproduced on Graalvm 20 as well
