### ISSUE TITLE
[WIP]  Doc 2.0: Introduction for Helidon SE

### ISSUE THREAD

**Issue by ljamen** [oracle/helidon#1626]
#774  Environment Details
* Helidon Version: 2.0
* Helidon SE 

----------

## Problem Description
 Introduction to Helidon SE [overview]

  

- [x]   Nice image with components (from slides) or cards

 

- [x]    Update components list, add links

- [x]     What it is, why you should use it, some basic examples.

**Comment by m0mus** [comment]
It also should contain some basic information about GraalVM native-image support.
