### ISSUE TITLE
 Doc 2.0: Introduction to Helidon MP

### ISSUE THREAD

**Issue by ljamen** [oracle/helidon#1628]
## Environment Details
* Helidon Version: 2.0
* Helidon MP

----------

## Problem Description
The Introduction to Helidon MP should introduce users to the offering. Provide an overview along with links to additional information. A What's New in 2.0 section should be added to list the changes existing users can expect. 

    Nice image with components (from slides) or cards
    Update components list, add links

**Comment by m0mus** [comment]
+ basic information about GraalVM native image support

**Comment by ljamen** [comment]
merged with PR 1653
