### ISSUE TITLE
Doc 2.0: Documentation for CORS SE Support 

### ISSUE THREAD

**Issue by ljamen** [oracle/helidon#1632]
* Helidon Version: 2.0
* Helidon SE

<also applicable for HDon 1.x but this is tracking the 2.0 doc>
----------
Documentation to support 1573, 1562

**Comment by tjquinno** [comment]
Here are some thoughts I've jotted down about the CORS SE support that might be a good head-start for the doc: https://gist.github.com/tjquinno/d7336ad17268116fc6b7ed2c238f0cc5

It is rough and evolving and not intended as-is for public consumption.
