### ISSUE TITLE
Setup a one-pager directory and template

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon#166]
Setup a directory in the workspace that will include all our design docs (one-pagers, dev-guidelines, other design docs, diagrams etc.)

This directory would contain a README.md that describes what the types of documents in the directory and give a few pointers. Tomas's development guidelines would fit in that directory as well, the readme can have a link to it.

- Get a consensus for the right location
- Setup a one-pager template in markdown format

Make a list of the existing design that need to be documented (e.g. config, webserver), this could be started off the initial one-pagers that we had internally.

**Comment by romain-grecourt** [comment]
@barchetta I've assign this to you, hopefully you won't mind ^^

**Comment by barchetta** [comment]
See PR #177
