### ISSUE TITLE
guide se-restful-webservice incorrect readme

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon#169]
The following readme is incorrect: https://github.com/oracle/helidon/blob/master/examples/guides/se-restful-webservice/README.md ; It seems to be the README.md generated from the archetype.

We should customize this readme to the guide. Also, since the guide doc is authored in adoc we could use a README.adoc and include the content from src/main/docs/index.adoc (or reference it with a link).

OR, we could simply make the guide docs the README.adoc file in the guide directory.
I kind of like this idea, what do you think ?

**Comment by m0mus** [comment]
This guide is gone.
