### ISSUE TITLE
MP Data source: cannot override using environment variables

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1693]
## Environment Details
* Helidon Version: 1.4.1
* Helidon MP
----------

## Problem Description
When using CDI integration for data sources, we cannot override some settings using environment variables.

This is most likely caused by approach (such as in `AbstractDataSourceExtension` line 312) where we iterate through config sources instead of getting the value from config.

This approach may miss environment variable rules.

**Comment by ljnelson** [comment]
I'll take a look.  Related: https://github.com/eclipse/microprofile-config/issues/431#issuecomment-519858099

**Comment by ljnelson** [comment]
@tomas-langer Looping back to this: is it your opinion that environment variable substitution rules should be housed outside of individual `ConfigSource`s?

**Comment by tomas-langer** [comment]
@ljnelson - yes, this is done by the environment variable config source (and if you disable it, it should not happen). This also depends on order of config sources (so if your file source is before environment variables source, these rules will not trigger.

The method to get config sources is not intended for obtaining properties. You should always use methods on `Config` to follow the spec (otherwise you may get values from the wrong place)

**Comment by ljnelson** [comment]
Do you know offhand if, in our implementation, [the requirement that the set of property names returned by `Config#getPropertyNames()` be equal to the union of the sets of property names returned by each installed `ConfigSource`](https://github.com/eclipse/microprofile-config/issues/431#issuecomment-519858099) is honored?  It would seem if environment variables are aliased based on, among other things, the order of installed `ConfigSource`s this would not be the case.

**Comment by ljnelson** [comment]
Whoops; never closed this; fixed back in September with #2322
