### ISSUE TITLE
Health example app uses deprecated methods

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#1702]
## Environment Details
* Helidon Version: 2.x
* Helidon SE
* JDK version: n/a
* OS: n/a
* Docker version (if applicable): n/a

----------

## Problem Description
The health example app(`Main:lines 42-43`) has two invocations of the now-deprecated `add` method on `HealthSupport.Builder`. Our sample should not do that.

**Comment by barchetta** [comment]
See PR #1715
