### ISSUE TITLE
JaxRS produces(MediaType.APPLICATION_XML) always returns NO_CONTENT

### ISSUE THREAD

**Issue by btcdevops-apps** [oracle/helidon#1718]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 1.4.4, 1.4.0
* Helidon MP
* JDK version: openjdk version "1.8.0_252"
* OS: ubuntu 16.0x
* Docker version (if applicable):

----------

## Problem Description
Rest path annotated with produces/consumes (MediaType.APPLICATION_XML) always returns NO_CONTENT status.

[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
endpoint signature

`@POST
    @Path(ServiceConstants.PATH_PAYMT_SETTLE)
    @Consumes({MediaType.APPLICATION_JSON,MediaType.APPLICATION_XML})
    @Produces({MediaType.APPLICATION_XML,MediaType.APPLICATION_JSON})
    @Transactional(Transactional.TxType.REQUIRED)
    public Response postSettlement(@RequestBody GwRequest payload){
       //do stuff
      CustomerInfo dto = findCustomerInfo(payload)
      response = Response.status(Response.Status.OK).entity(dto).build();
      return response;
    }`

[//]: # "State if the problem is easily reproducible or happens intermittently"
when invoked, the method executes and returns status.OK, **however the client receives a "NO_CONTENT" status**
[//]: # "Include stack traces or command outputs"
MessageBodyWriter not found for media type = application/xml for class
## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
create rest endpoint that accepts and returns application_xml.
Pojo e.g. CustomerInfo is annotated with @XmlRootElement
CustomerInfo has attribute Address object which is also annotated @XmlRootElement
[//]: # "Provide sample code/application if relevant"

**Comment by spericas** [comment]
Could you please provide more details about the dependencies in your pom?

**Comment by btcdevops-apps** [comment]
Hello,
below is a copy of my pom.xml

`
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.helidon.applications</groupId>
        <artifactId>helidon-mp</artifactId>
        <version>1.4.4</version>
        <relativePath/>
    </parent>
    <groupId>co.uk.btcserv.cloud.saas.mp.btc.metro</groupId>
    <artifactId>metro-assetmgt-service</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>metro-assetmgt-service</name>

    <properties>
        <mainClass>metro.assetmgt.service.MetroAssetMgmtMsMain</mainClass>
        <ojdbc.version>18.3.0.0</ojdbc.version>
        <ojdbc.group>com.oracle.jdbc</ojdbc.group>
        <ojdbc.artifcat>ojdbc8</ojdbc.artifcat>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.helidon.microprofile.bundles</groupId>
            <artifactId>helidon-microprofile</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jboss</groupId>
            <artifactId>jandex</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>javax.activation</groupId>
            <artifactId>javax.activation-api</artifactId>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>io.helidon.integrations.cdi</groupId>
            <artifactId>helidon-integrations-cdi-jta-weld</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.helidon.integrations.cdi</groupId>
            <artifactId>helidon-integrations-cdi-jpa</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.helidon.integrations.cdi</groupId>
            <artifactId>helidon-integrations-cdi-eclipselink</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.persistence</groupId>
            <artifactId>jakarta.persistence-api</artifactId>
            <version>2.2.2</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.transaction</groupId>
            <artifactId>javax.transaction-api</artifactId>
            <version>1.2</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>${ojdbc.group}</groupId>
            <artifactId>${ojdbc.artifcat}</artifactId>
            <version>${ojdbc.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.0</version>
        </dependency>
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-core</artifactId>
            <version>1.2.5</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>1.2.5</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>1.2.5</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>co.uk.btcserv.cloud.saas.tdd.common</groupId>
            <artifactId>btc-common-tddutil</artifactId>
            <version>1.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.javafaker</groupId>
            <artifactId>javafaker</artifactId>
            <version>1.0.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.btc.xnm.ui.bdd</groupId>
            <artifactId>btc-xnm-common-bdd-settings</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>co.uk.btcserv.cloud.saas.mp.btc.metro</groupId>
            <artifactId>metro-common-service</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.practicalddd.cargotracker</groupId>
            <artifactId>rabbitadaptor-core</artifactId>
            <version>1.0</version>
        </dependency>
        
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>RELEASE</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>RELEASE</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.3.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>commons-collections</groupId>
            <artifactId>commons-collections</artifactId>
            <version>3.2.2</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.10.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-json-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-jaxb</artifactId>
        </dependency>
    </dependencies>


    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-libs</id>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.jboss.jandex</groupId>
                <artifactId>jandex-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>make-index</id>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

`

**Comment by btcdevops-apps** [comment]
Note: if this is a bug. also make not of restclients
I've tested accessing the XML annotated endpoint as a restclient from another project.
The call was unsuccessful too, immediately returning NO_CONTENT without executing the actual service mapped to the endpoint.

**Comment by barchetta** [comment]
I took the Helidon MP Quickstart and added an endpoint that returns XML using jaxb. It seems to work (I built/ran with Java 11):

https://github.com/barchetta/helidon-quickstart-mp-xml

**Comment by spericas** [comment]
@btcdevops-apps Seems like there may be some problem with dependencies, but it's hard to see why the writer is not found --it is also quite strange because your resource _returns_ JSON, so no XML writer should be necessary, only an XML reader. 

In order to make progress, we are going to need to create a reproducer: a simple project that shows the problem with a minimal set of dependencies. Any chance you can provide us with that?

**Comment by btcdevops-apps** [comment]
@spericas I've used the additional dependencies in @barchetta 's example and the xml response was returned successfully (added the annotations XmlRootElement and XmlElement(true) too.

_Note: without the pojo annotations, no messagewriter was found at runtime for xml response._

_I would have thought the helidon libraries should contain the required jaxb dependencies._

These three were the only one's i didn't have
<dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-core</artifactId>
        </dependency>


@spericas @barchetta  thanks for looking into this. 
This can be closed
