### ISSUE TITLE
In local build links from AsciiDoc to JavaDoc class go to top-level JavaDoc page

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#1730]
## Environment Details
* Helidon Version:2.x
* Helidon SE or Helidon MP both
* JDK version:n/a
* OS:n/a
* Docker version (if applicable):n/a

----------
Links from an AsciiDoc document to a specific class in the JavaDoc lands at the top-level JavaDoc page, not at the expected target.

## Steps to reproduce
1. Build the site locally and start the server. https://github.com/oracle/helidon/blob/master/etc/scripts/BUILDDOCS.md
2. Browse to Config -> The Configuration Component and scroll down to the Your First Config Application section. Click on the `Config` link in the first sentence which should go directly to the `Config` interface JavaDoc. 
3. The browser opens a new tab, but it lands at the top-level JavaDoc page, not the `Config` page.

**Comment by barchetta** [comment]
See PR #1754
