### ISSUE TITLE
DbClient - metric wrong format hangs application

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1775]
## Environment Details
* Helidon Version: 2.0.0-M3
* Helidon SE
----------

The following code:
```java
DbClient.builder()
                .config(config.get("db"))
                .addInterceptor(DbCounter.builder()
                                        // %1$s - statement name, %2$s - statement type
                                        .nameFormat("db.counter.%1$s.%2$s.%3$s")
                                        .build())
                .build();
```
will pass, and when a statement is called, it just hangs indefinitely

**Comment by paulparkinson** [comment]
This actually didn't occur in my test. I got 
 java.util.concurrent.CompletionException: java.util.MissingFormatArgumentException: Format specifier '%3$s'
on the server and returned to the client with no hang.
I used the jdbc example and curl http://localhost:8079/db

**Comment by paulparkinson** [comment]
unable to recreate issue and so closing...
