### ISSUE TITLE
DbClient change DbRows to Multi if possible

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1791]
`DbRows` seems to have a set of methods already available on `Multi`. Maybe we could just use it and remove `DbRows` from Helidon.

**Comment by tomas-langer** [comment]
We have a requirement in `DbExecute` to return a `CompletionStage`.
In case of DbRows (which is a "promise" of rows), this was returning a "promise of a promise"
 - when the stage completes, you get db rows, that can serve rows.
While this allowed us to distinguish between execution of a statement and processing of result set, it may be too complex.
The signature `CompletionStage<Multi<DbRow>>` is functionally identical to existing code, yet it looks ridiculous that we may get a future of a future.
I think the `DbExecute` API should be changed, so we do not enforce the completion stage in this case.

**Comment by danielkec** [comment]
I would prefer unwrapped `Multi`, only real information we get from this outer callback is a moment when stream is constructed and stream construction just can't block. That would be like blocking in constructor of `new CompletableFuture()`

**Comment by tomas-langer** [comment]
Depends on #1790
