### ISSUE TITLE
Create a JSON-B stream writer

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1794]
Add support for a `Publisher<Pojo>` when writing a WebServer response using 
`Response.send(publisher, Pojo.class)` (also usable in client when sending request).

**Comment by tomas-langer** [comment]
Have a look at https://github.com/oracle/helidon/pull/1796 - JsonpBodyWriter.java

**Comment by michael-simons** [comment]
Here's one approach https://github.com/michael-simons/neo4j-examples-and-tips/blob/master/examples/neo4j-and-helidon-se-reactive/src/main/java/io/helidon/examples/quickstart/se/api/MovieBodyStreamWriter.java

Should be generified but I guess you get the idea.

For reference http://ndjson.org

That would also be more appropriate for the Jsonp writer… With it, one can actually stream the content.

**Comment by michael-simons** [comment]
A different approach leading to the same Sse Events that Quarkus and Spring produce:

```java
public final class SseJsonObjectBodyStreamWriter implements MessageBodyStreamWriter<Object> {

	private static final MediaType APPLICATION_X_NDJSON = MediaType
		.parse("text/event-stream;element-type=\"application/json\"");
	private static final Jsonb JSON_FACTORY = JsonbBuilder.create();
	private static final byte[] DATA = "data: ".getBytes(StandardCharsets.UTF_8);
	private static final byte[] NL = "\n\n".getBytes(StandardCharsets.UTF_8);

	@Override
	public PredicateResult accept(GenericType<?> type, MessageBodyWriterContext context) {
		return PredicateResult.supports(Object.class, type);
	}

	@Override
	public Flow.Publisher<DataChunk> write(Flow.Publisher<? extends Object> publisher,
		GenericType<? extends Object> type, MessageBodyWriterContext context) {

		context.contentType(APPLICATION_X_NDJSON);
		return Multi.defer(() -> publisher)
			.flatMap(m -> Multi.just(
				DataChunk.create(DATA),
				DataChunk.create(JSON_FACTORY.toJson(m).getBytes(StandardCharsets.UTF_8)),
				DataChunk.create(NL))
			);
	}
}
```
