### ISSUE TITLE
Build fails with 2.0.0-M3 - CollectionsHelper

### ISSUE THREAD

**Issue by ksurendra** [oracle/helidon#1822]
## Environment Details
* Helidon Version: 2.0.0-M3
* Helidon MP
* JDK version: OpenJDK 11
* OS: Centos 8
* Docker version (if applicable):

----------

## Problem Description
Updated the version from `1.4.4` to `2.0.0-M3` and when `mvn clean package`, seeing these compilation errors:
```
ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project cord: Compilation failure: Com
pilation failure: 
[ERROR] /home/suren/cord-java/cord/src/main/java/com/engg/java/cord/CordApplication.java:[10,25] cannot find symbol
[ERROR]   symbol:   class CollectionsHelper
[ERROR]   location: package io.helidon.common
[ERROR] /home/suren/cord-java/cord/src/main/java/com/engg/java/cord/CordApplication.java:[18,16] cannot find symbol
[ERROR]   symbol:   variable CollectionsHelper
[ERROR]   location: class com.engg.java.cord.CordApplication
```
- Open JDK 11
- Centos 8

## Steps to reproduce
1. Using a working project built with `1.4.4`, open `pom.xml`, change the version from `1.4.4` to `2.0.0-M3`
```
 <parent>
        <groupId>io.helidon.applications</groupId>
        <artifactId>helidon-mp</artifactId>
        <version>2.0.0-M3</version>
        <relativePath/>
```
also comment out `javax.activation` dependency. 
```
<!--
        <dependency>
            <groupId>javax.activation</groupId>
            <artifactId>javax.activation-api</artifactId>
            <scope>runtime</scope>
        </dependency>
        -->
```

2. Run `mvn clean package`

**Comment by romain-grecourt** [comment]
CollectionsHelper was provide equivalents of `Map.of` and `List.of` compatible with Java8.
Since 2.0 requires Java11, CollectionsHelper was removed ; you can now use `Map.of` `List.of` instead.
