### ISSUE TITLE
ExceptionMapper not working with @Provider annotaion

### ISSUE THREAD

**Issue by felipe-alves-moraes** [oracle/helidon#1857]
## Environment Details
* Helidon Version: 2.0.0-M3
* Helidon MP
* JDK version: 11
* OS: macOS Catalina

----------

## Problem Description
I created the following ExceptionMapper using the `@Provider` annotation:

```
@Provider
public class ConstraintViolationExceptionMapper implements ExceptionMapper<ConstraintViolationException> {

    @Override
    public Response toResponse(ConstraintViolationException e) {
        
        return Response.status(Response.Status.BAD_REQUEST).build();
    }
    
}
```

But for some reason it's not recognized by the application. I could make it work when I manually registered it in my Application class. Is this the intended behavior?

**Comment by spericas** [comment]
@felipe-alves-moraes Are you including an application-subclass in your project? Could you please try the final 2.0.0 bits to see if the issue persists?

**Comment by spericas** [comment]
I have tried with the final version of 2.0.0 and the issue _not_ reproducible. I can see the provider being found and called when the exception is thrown.

**Comment by spericas** [comment]
[myproject.zip](https://github.com/oracle/helidon/files/4846192/myproject.zip)

**Comment by spericas** [comment]
Closing as `cannot reproduce`. Please re-open if necessary.

**Comment by antonio-petricca** [comment]
Same issue for me with 2.3.4 and 2.4.1 too. :(

**Comment by spericas** [comment]
@antonio-petricca Please re-open with a reproducer.
