### ISSUE TITLE
Use Helidon WebClient connector

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1875]
Upgrade to latest Jersey and switch to WebClient connector when using Jersey Client in all Helidon modules.

**Comment by spericas** [comment]
We have now moved to Jersey 2.31. Will re-target the `WebClient` work for the final release.

**Comment by spericas** [comment]
The Jersey connector has now been moved to the Helidon workspace. It needs some cleanup in the pom and with checkstyle. This will be done as part of this task as well.

**Comment by spericas** [comment]
Connector is available by simply adding a dependency, but _it is not set as default_ until further stress/performance testing is done. See #2008.
