### ISSUE TITLE
Config: refactor based on development guidelines

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#190]
Refactor the config module to follow the development guidelines in PR #135. 

The following tasks are part of this issue ("Validate" means check and if not compliant, fix):

- [x] Change builders that accept other builders to accept a supplier instead
- [x] Change scope to "provided" where reasonable to have a cleaner dependency graph
- [x] Validate bundle dependencies to not bring in too many third party libraries
- [x] Move SE bundles to a /bundles root module and change group ids accordingly??
- [x] Validate module names and package names to ensure they adhere to dev guidelines)
- [x] Validate naming convention of configuration keys used by components
- [x] Fix inconsistencies in getter and setter names
- [x] Validate we do not create instances using "new" and use factory methods
- [x] Refactor factory method names (use create)
- [x] Refactor config methods in builders (use config)
- [x] Validate java module files are in each module

And for tests:

- [x] Refactor unit tests to use Hamcrest assertions

**Comment by tomas-langer** [comment]
Needed follow up tasks:

- [ ] fix UML diagrams in config/config/src/docs
- [ ] drop usage of old security configuration (search for BMCS or `com.oracle.prime`) - used in a lot of places, not valid anymore
- [ ] meta configuration should be probably refactored - the factory methods for config and config builder do not sound right (the naming) - `loadSourceFrom` and `builderLoadSourcesFrom`
