### ISSUE TITLE
Test Se1Main.java uses io.helidon.media.jsonp.common

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#1907]
After the MediaType flattening (PR #1899) the following test breaks:

$ grep -r --include "*.java" io.helidon.media.jsonp.common .
./tests/integration/native-image/se-1/src/main/java/io/helidon/tests/integration/nativeimage/se1/Se1Main.java:import io.helidon.media.jsonp.common.JsonpSupport;

Looks like this test is protected by the `native-image` profile and is not run by default  in the pipeline (so that's why the PR passed the pipeline).

**Comment by Verdent** [comment]
fixed
