### ISSUE TITLE
WebServer: refactor based on development guidelines

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#192]
Refactor the webserver module to follow the development guidelines in PR #135. 

The following tasks are part of this issue ("Validate" means check and if not compliant, fix):

- [x] Change builders that accept other builders to accept a supplier instead
- [x] Change scope to "provided" where reasonable to have a cleaner dependency graph
- [x] Validate bundle dependencies to not bring in too many third party libraries
- [x] Move SE bundles to a /bundles root module and change group ids accordingly??
- [x] Validate module names and package names to ensure they adhere to dev guidelines)
- [x] Validate naming convention of configuration keys used by components
- [x] Fix inconsistencies in getter and setter names
- [x] Validate we do not create instances using "new" and use factory methods
- [x] Refactor factory method names (use create)
- [x] Refactor config methods in builders (use config)
- [x] Validate java module files are in each module

And for tests:

- [x] Refactor unit tests to use Hamcrest assertions

**Comment by webfolderio** [comment]
> Validate we do not create instances using "new" and use factory methods

What is the point of using static factory methods instead of new operator?

**Comment by romain-grecourt** [comment]
static factory methods are provided as convenient shorthands on top the builders. I believe the only reason to enforce this over "new" is for consistency.

@tomas-langer feel free to comment.

**Comment by tomas-langer** [comment]
A constructor is more restrictive - you lose the flexibility to use whatever implementation you need and are stuck with the implementation when designing the API.
We have encountered this already - we needed to change a class into an interface. As we were using static factory methods and a builder, there was no impact on the API.

Some other advantages:
- Factory methods have names
- Factory methods may return the same instance or a new instance as needed
- Factory methods may return a subtype of the expected type (see example above with interface)

In general, this is about an opinion - either approach is usable. We have decided for the factory methods and must be consistent across all our modules.
