### ISSUE TITLE
archetypeArtifact helidon-quickstart-se in IDEA InteliJ

### ISSUE THREAD

**Issue by rfelcman** [oracle/helidon#1963]
## Environment Details
* Helidon Version: 2.0.0-RC1
* Helidon SE
* JDK version: 11.0.7
* OS: Linux (Debian 10)
* Docker version (if applicable): N/A
* IDEA InteliJ 2020.1.2

----------

## Problem Description
It seems, that IDEA InteliJ has problem with some Helidon dependencies in this case, or there is something wrong in Helidon parent POMs.

## Steps to reproduce
1. Create new project by
``mvn archetype:generate -DinteractiveMode=false -DarchetypeGroupId=io.helidon.archetypes 
	-DarchetypeArtifactId=helidon-quickstart-se -DarchetypeVersion=2.0.0-RC1 
	-DgroupId=io.helidon.examples -DartifactId=Test01_InitialProject    -Dpackage=io.helidon.examples.quickstart.se``
2. Import project into IDEA InteliJ (My version is 2020.1.2).
3. Open pom.xml file by IDEA "Project manager"
4. Move mouse cursor over "<project ...." element.
			Idea prints in the bubble:
				Unable to provision, see the following errors: 1) Error in custom provider, java.lang.TypeNotPresentException: 
				Type io.helidon.build.dev.maven.MavenProjectConfigCollector not present at ClassRealm[extension>io.helidon.build-tools:helidon-maven-plugin:2.0.0-RC1, 
				parent: sun.misc.Launcher$AppClassLoader@14ae5a5] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule) 
				while locating org.apache.maven.AbstractMavenLifecycleParticipant 1 error
5. "External Libraries" in InteliJ Project Manager are empty -> dependencies from pom are not loaded/detected by InteliJ. As a result IDEA code assistant doesn't work correctly too. IDEA thinks, that classes "io.helidon.\*" are not in the classpath.
		Note: Helidon 1.4.4 or 2.0.0-M* works well.

It doesn't any negative impact to command line build. Command line build works well.

**Comment by rfelcman** [comment]
I tried to delete InteliJ caches and restart IDE, but issue still remains there.

**Comment by romain-grecourt** [comment]
I cannot reproduce the error, but I believe the fix is from #2023 is right.
