### ISSUE TITLE
Documentation references old archetype artifact id

### ISSUE THREAD

**Issue by rfelcman** [oracle/helidon#1964]
## Environment Details
* Helidon Version: 2.0.0-RC1
* Helidon MP
* JDK version: 11.0.7
* OS: Linux (Debian 10)
* Maven: 3.6.3

----------

## Problem Description
Unable create project based on archetypeArtifactId=helidon-mp .

## Steps to reproduce
Command:
``mvn archetype:generate \
-DinteractiveMode=false \
-DarchetypeGroupId=io.helidon.archetypes \
-DarchetypeArtifactId=helidon-mp \
-DarchetypeVersion=2.0.0-RC1 \
-DgroupId=io.helidon.example \
-DartifactId=helidon-jpa \
-Dpackage=io.helidon.example.jpa \
-DrestResourceName=ExampleResource \
-DapplicationName=ExampleApplication``
throws
``[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate (default-cli) on project standalone-pom:
The desired archetype does not exist (io.helidon.archetypes:helidon-mp:2.0.0-RC1) -``
It seems, that not all archetype(s) are available at Maven Central for 2.0.0-RC1 like 1.4.4 or 2.0.0-M* version.
See https://repo.maven.apache.org/maven2/io/helidon/archetypes/

**Comment by spericas** [comment]
#2021
