### ISSUE TITLE
Missing access to EncryptionUtil#decryptAes

### ISSUE THREAD

**Issue by TroubiCZ** [oracle/helidon#1975]
## Environment Details
* Helidon Version:
1.4, but the same problem can be seen on the master branch in git
* Helidon SE or Helidon MP
both
* JDK version:
N/A
* OS:
N/A
* Docker version (if applicable):
N/A
----------

## Problem Description
Class io.helidon.config.encryption.EncryptionUtil provides utility methods for encryption and decryption using RSA/AES ciphers. Most of the methods are public, but decryptAes and decryptAesLegacy are declared with default access, which makes them next to impossible to use correctly.
I think it's just an overlook in the API design.

**Comment by Verdent** [comment]
Hi @TroubiCZ , thank you for this report. I have made fix for this issue to both branches.
