### ISSUE TITLE
Documentation "QuickStart" link is not working properly

### ISSUE THREAD

**Issue by tvallin** [oracle/helidon#1976]
## Environment Details
* Helidon Version: 2.0.0-RC1
* Helidon Documentation
* JDK version: 11
* OS: 
* Docker version (if applicable):

----------

## Problem Description

On Prerequisites page, the final link "Quickstart Examples" is not working.
I recommend two links "Quickstart SE" and "Quickstart MP"

**Comment by barchetta** [comment]
See  PR #1996
