### ISSUE TITLE
HTTPs should be reported at startup

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#2017]
When we start MP `Server`, SE `WebServer` they print out the listen host, port and protocol.
The protocol section (for sure in MP) does not reflect whether the port is secured with TLS, so the address always starts with `http://`

We should honor TLS configuration of the WebServer, and print `https://` in case it is enabled.

Also example may be changed to show `https://` in case the configuration is changed to tls (check feasibility, possible API addition, such as `WebServer.protocol()`).

**Comment by tweenietomatoes** [comment]
Also it's prints listening on 0.0.0.0.0.0.0.0 
not 0.0.0.0

**Comment by tweenietomatoes** [comment]
Channel '@default' started: [id: 0xf6841beb, L:/0:0:0:0:0:0:0:0:8080]
