### ISSUE TITLE
Add an annotation to add a class for reflection in native image

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#2030]
Currently POJOs used with reflection (such as when using JSON-B) need to be manually configured in `reflect-config.json` for native image.
By introducing a dedicated annotation, we could simplify this for the user.
This is valid both for Helidon SE and MP.

Example:
```
@Reflected
public class Pokemon {
  private String name;
}
```

We can add all such classes for reflection in our extension, thus removing the need to add config files.

**Comment by romain-grecourt** [comment]
Fixed in https://github.com/oracle/helidon/pull/2070
