### ISSUE TITLE
ForwardingHandler does not complete RequestContext Publisher if the LoadBalancer cuts the started Expect: 100-continue process

### ISSUE THREAD

**Issue by ao2-io** [oracle/helidon#2061]
We are providing Helidon MP Rest-Services behind an Apache httpd Load balancer. The following constellation leads to a stuck of the JerseySupport Service executor queue.

A Client sends a POST request to our rest service with a json payload and an Expect 100-continue Header. The Apache load balancer sends the request do the backend. The backend takes the request and starts a JerseySupport runnable which waits for incomming data, then the backend sends a response to the LB to start the stream (Response Status 100). If the client request exceeds the load balancer connection timeout at this point the load Balancer cuts the connection to the calling client with a proxy error but the backend service does not get informed and waits forever.

The problem is that the io.helidon.webserver.ForwardingHandler only completes the http content publisher if a LastHttpContent Message is send and this never happens. If the publisher never completes, the subscriber inside the waiting JerseySupport service instance blocks a server executor instance forever. If this happens several times the whole rest service is blocked.

I did not found a possibility to configure a corresponding timeout inside helidon to interrupt the JerseySupport service nor a possibility to get the apache load balancer to end the connection to the backend appropriately.

Thanks in advance

### Environment Details
* Helidon Version: 1.4.4
* Helidon MP
* JDK version: Java 12
* OS: openjdk:12 (Docker Image)
* Docker version: 19.03.8

----------

**Comment by danielkec** [comment]
Hi @ao2-io, 
we will take a deeper look in to this. 
In the mean time there is a possible workaround by using your custom ExecutorService:
```java
        Server server = Server.builder()
                .defaultExecutorServiceSupplier(myExecutorServiceWithGlobalTimeout)
                .addApplication(HelloWorldApplication.class)
       ....
```
Or only for jax-rs app:
```java
        Server server = Server.builder()
                .addApplication(JaxRsApplication.builder()
                        .contextRoot("/app2")
                        .application(new HelloWorldApplication())
                        .executorService(myExecutorServiceWithGlobalTimeout)
                        .build())
```

**Comment by ao2-io** [comment]
Hi @danielkec 
Thanks for your reply and workaround.

**Comment by danielkec** [comment]
Reproduced successfully with Helidon 1.4.4 and Apache 2.4.48 by artificially prolonging 100 response
```diff
diff --git a/webserver/webserver/src/main/java/io/helidon/webserver/ForwardingHandler.java b/webserver/webserver/src/main/java/io/helidon/webserver/ForwardingHandler.java
--- a/webserver/webserver/src/main/java/io/helidon/webserver/ForwardingHandler.java	(revision 52591c9f13a1daf34df43bf299885a909ed62e1c)
+++ b/webserver/webserver/src/main/java/io/helidon/webserver/ForwardingHandler.java	(date 1630566809672)
@@ -189,6 +189,12 @@
     }
 
     private static void send100Continue(ChannelHandlerContext ctx) {
+        System.out.print("Waiting before sending 100 ");
+        for(int i = 0; i < 8; i++){
+            System.out.print(".");
+            try {Thread.sleep(500);} catch (InterruptedException e) {}
+        }
+        System.out.println(" DONE");
         FullHttpResponse response = new DefaultFullHttpResponse(HTTP_1_1, CONTINUE);
         ctx.write(response);
     }
``` 

Each call time-outing before 100 response leaves indefinitely blocked thread:
```
helidon-9" #67 daemon prio=5 os_prio=0 cpu=8,28ms elapsed=1044,35s tid=0x00007f0fd12bb000 nid=0x7121 waiting on condition  [0x00007f0e6bffd000]
   java.lang.Thread.State: WAITING (parking)
        ...
	at java.util.concurrent.CompletableFuture.get(java.base@11.0.10/CompletableFuture.java:1998)
	at io.helidon.media.common.PublisherInputStream.read(PublisherInputStream.java:72)
```
At PublisherInputStream.java:72 https://github.com/oracle/helidon/blob/52591c9f13a1daf34df43bf299885a909ed62e1c/media/common/src/main/java/io/helidon/media/common/PublisherInputStream.java#L72
Simple Apache LB:
```dockerfile
FROM httpd:2.4

ENV LB_TIMEOUT=1
ENV LB_MEMBER=http://127.0.0.1:7001/greet
ENV VIRTUAL_HOST=*:80

ENV MODULES=\
"LoadModule proxy_module modules/mod_proxy.so\\n"\
"LoadModule proxy_http_module modules/mod_proxy_http.so\\n"\
"LoadModule proxy_balancer_module modules/mod_proxy_balancer.so\\n"\
"LoadModule slotmem_shm_module modules/mod_slotmem_shm.so\\n"\
"LoadModule lbmethod_byrequests_module modules/mod_lbmethod_byrequests.so\\n"
ENV LB_CONFIG=\
"<VirtualHost $VIRTUAL_HOST>\\n"\
"<Proxy balancer://cluster>\\n"\
"BalancerMember $LB_MEMBER timeout=$LB_TIMEOUT\\n"\
"</Proxy>\\n"\
"ProxyPreserveHost On\\n"\
"ProxyPass / balancer://cluster/\\n"\
"ProxyPassReverse / balancer://cluster/\\n"\
"</VirtualHost>"
ENV HTTPD_CONF_FILE=/usr/local/apache2/conf/httpd.conf

RUN echo "Setting up load-balancer" && \
sed -i "1s@^@$MODULES@" "$HTTPD_CONF_FILE" && \
echo "$LB_CONFIG" >> "$HTTPD_CONF_FILE"
```
Client call:
```bash
curl -v -d '{"foo":"bar"}'          \
-H "Content-Type: application/json" \
-H "Expect: 100-continue"           \
-X POST                             \
localhost
```
