### ISSUE TITLE
Allow customization of graceful shutdown timeout and quiet period

### ISSUE THREAD

**Issue by Sobuno** [oracle/helidon#2087]
## Environment Details
* Helidon Version: 1.4.5 and 2.0.0
* Helidon SE or Helidon MP: Both
----------

## Problem Description
It is currently not possible to customize the timeout and quiet period for gracefully shutting down the Netty webserver. These are hardcoded to 10 and 0 respectively.

Regarding the fixed 10 second shutdown timeout, I have some endpoints that can be slower than 10 seconds which means these will fail if not done before the period has elapsed. Ideally, I would be able to control this to match (or almost match) my container's `terminationGracePeriodSeconds` . At the moment, I am just using a prestop hook in Kubernetes to delay the SIGTERM enough to give all requests a chance to finish. This is not nice however, since I am then delaying a fixed amount of time rather than exactly until no requests are being served.

As far as I can tell, the quiet period set to 0 means that no further tasks are being taken in. I believe this poses two issues for me:
1. New requests coming from our service in Kubernetes are not being handled
2. Queued requests that have been accepted are not being handled.

Per https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods, when a pod is shutting down, the pod will receive a SIGTERM signal simultaneously with the removal of the pod from the service loadbalancer. However, due to Kubernetes distributed nature, this is not necessarily 100% simultaneous which means we can be open for traffic from Kubernetes POV while also being in the process of shutting down. I believe being able to customize the graceful shutdown timeout and quiet period could help solve this issue.

**Comment by ljnelson** [comment]
For reference:

https://github.com/oracle/helidon/blob/929c4c687492c5fceb576c98f7ee47b39dad0c8c/webserver/webserver/src/main/java/io/helidon/webserver/NettyWebServer.java#L342-L344
