### ISSUE TITLE
db archetype should log a supported path

### ISSUE THREAD

**Issue by batsatt** [oracle/helidon#2089]
The app created from the db archetype logs 
```
WEB server is up! http://localhost:8080/
```
but should include some "main" path as the other apps do to avoid any confusion on first use, e.g.
```
WEB server is up! http://localhost:8080/pokemon
```
It would be nice if all of the apps could serve the README at `/`, e.g. using a generated `README.html` file.

**Comment by spericas** [comment]
Fixed as part of #2100
