### ISSUE TITLE
Failure to parse media type

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#211]
Caused by: java.lang.IllegalArgumentException: Could not parse '*; q=.2'
	at io.helidon.common.http.MediaType.parse(MediaType.java:253)

Request from another service using Jersey client with default Accept header.

**Comment by romain-grecourt** [comment]
@tomas-langer I've created a reproducer based on what you said: 2 apps, one using mp and one using se, with the mp app calling the se app with a jaxrs client.

I've pushed it to a repository at https://github.com/romain-grecourt/helidon-issue-211

However it does not reproduce the issue. Can you take a look and tell me if that reproduces the issue on your side ? If I'm missing changes to reproduce please submit a PR.

**Comment by barchetta** [comment]
This gets the error:
```
curl -H 'Accept: *;q=.2' -X GET http://localhost:8080/greet/
```

This works
```
curl -H 'Accept: */*;q=.2' -X GET http://localhost:8080/greet/
```

Is the first one generated by the Jersey client? Is that valid?

**Comment by romain-grecourt** [comment]
I was setting the requested media type in the jaxrs client, removing it reproduces the error.

**Comment by romain-grecourt** [comment]
The client sends an Accept headers like this `text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2`

**Comment by romain-grecourt** [comment]
This header is not added by the jersey code, it's coming from HTTPURLConnection.

This reproduces:
```java
 URL url = URI.create("http://localhost:9090").toURL();
 HttpURLConnection uc = (HttpURLConnection) url.openConnection();
 uc.setDoInput(true);
 uc.connect();
```

**Comment by romain-grecourt** [comment]
Found this JDK bug: https://bugs.openjdk.java.net/browse/JDK-8163921
