### ISSUE TITLE
Mutual Auth for Helidon 1.4.* version

### ISSUE THREAD

**Issue by venkat79** [oracle/helidon#2114]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version:
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"

We would like to have same mutual auth supported that was done for Helidon 2.* as per the issue:
https://github.com/oracle/helidon/issues/658

I did have a conversation with Tomas Langer. Can you evaluate the feasibility and let us know?

**Comment by Verdent** [comment]
Fixed by #2166
