### ISSUE TITLE
Missing app.yaml file in the generated source

### ISSUE THREAD

**Issue by nelvadas** [oracle/helidon#2134]
docs/mp/guides/02_quickstart.adoc

## Environment Details
* Helidon Version: 2.0.1 
*  Helidon MP
* JDK version: java version "11.0.7" 2020-04-14 LTS
* OS: Mac OS Catalina 10.15.5 (19F101)
* Docker version (if applicable):

----------

## Problem Description
While following the tutorial docs/mp/guides/02_quickstart.adoc , Cannot find the required app.yaml to run the application on kubernetes, is this file to be genreated by the artifact or is it referencing an existing file?

## Steps to reproduce
[//]: #  follow docs/mp/guides/02_quickstart.adoc
[//]: # deploy application to k8s section.

**Comment by barchetta** [comment]
Looks like this was dropped this when we switched to our new archetype implementation. As a work-around you can try the file here: https://github.com/oracle/helidon/blob/release-2.0.1/examples/quickstarts/helidon-quickstart-mp/app.yaml

**Comment by barchetta** [comment]
Fixed. See PR #2141
