### ISSUE TITLE
"WARNING: Span has already been finished" with tracing and jaeger in k8s env

### ISSUE THREAD

**Issue by paulparkinson** [oracle/helidon#2153]
When running an MP app with @Traced and jaeger in k8s env, "WARNING: Span has already been finished" is repeated logged.
This does not occur when run outside k8s.

## Environment Details
* Helidon Version: 2.0.0
* Helidon SE or Helidon MP: MP
* JDK version: <baseImage>openjdk:11</baseImage>
* OS: 
* Docker version (if applicable):

----------

## Problem Description

Full log message that is repeated...

```
Jul 11, 2020 12:25:22 AM io.jaegertracing.internal.reporters.LoggingReporter report
INFO: Span reported: 4ab83ed96d9daec7:5e3948f5eeb571fe:4ab83ed96d9daec7:1 - content-write
Jul 11, 2020 12:25:22 AM io.jaegertracing.internal.JaegerSpan finishWithDuration
WARNING: Span has already been finished; will not be reported again.
```

## Steps to reproduce

Annotate MP microservice with @Traced annotation...
 ```
@Path("/placeOrder")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Traced(operationName = "OrderResource.placeOrder")
public Response placeOrder(@QueryParam("orderid") String orderid, @QueryParam("itemid") String itemid,
                               @QueryParam("deliverylocation") String deliverylocation)
```

And microprofile-config.properties files...

```
# Microprofile Tracing Properties
# tracing.service=mp
tracing.service=order.msdataworkshop
tracing.protocol=http
tracing.host=jaeger-collector.msdataworkshop
tracing.port=14268
tracing.path=/api/traces
tracing.propagation=b3
tracing.log-spans=true
#tracing.sampler-type=const
tracing.sampler-param=1
```

Deploy to k8s env where jaeger is installed (jaeger must match tracing.host and tracing.port properties), eg. `kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-kubernetes/master/all-in-one/jaeger-all-in-one-template.yml -n msdataworkshop`

Notice log messages.

**Comment by tomas-langer** [comment]
I have narrowed down the problem - can be reproduced using `Mp1Main` in our repository.
The `Response.MessageBodyEventListener.onEvent` is called twice with `AFTER_ONCOMPLETE`, resulting in multiple calls to `finish` method, that attempts to finish the `span` instance again.
This seems like a problem with reactive class reporting the event more than once.

**Comment by tomas-langer** [comment]
Increasing priority as this is a bug.
