### ISSUE TITLE
Tutorial issue

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon#2155]
## Environment Details

* Helidon Version: 2.x
* Helidon MP

## Problem Description

There seems to be a doc issue with https://helidon.io/docs/v2/#/mp/guides/10_mp-tutorial. 
"You can set the mainClass to `io.helidon.microprofile.Main` and it will find the application annotated with ApplicationScoped."  
The class must be `io.helidon.microprofile.cdi.Main`.

**Comment by barchetta** [comment]
Fixed by PR #2152
