### ISSUE TITLE
Upgrade Weld to 3.1.4

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#2176]
Upgrade weld to latest 3.x version.

**Comment by tomas-langer** [comment]
Upgrade in 1.x may introduce backward incompatibilities (or may be hard to do) as the new Weld version probably depends on `jakarta` groupIds and the build fails if the version is simply changed.

@barchetta do we need to upgrade for 1.x branch as well?

**Comment by barchetta** [comment]
No, I don't think we need to upgrade in 1.x branch.
