### ISSUE TITLE
WebServer should return content-length 0 when no entity

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#2208]
When I use `response.send()` in my code, the server responds with `Transfer-Encoding: Chunked`
and no `Content-Length` header

## Environment Details
* Helidon Version: 2.0.0
* Helidon SE 
* JDK version: 11.0.7
* OS: Mac OS

----------

## Expected output
The `Content-Length` should be set to `0` when there is no entity (esp. when we call `ServerResponse.send()` without parameters).
Also the `Transfer-Encoding` does not need to be `chunked` in such a case

**Comment by ninadingole** [comment]
I have done the following changes:
```
boolean lengthSet = HttpUtil.isContentLengthSet(response);
if (!lengthSet) {
    long contentLength = HttpUtil.getContentLength(response);
    HttpUtil.setContentLength(response, contentLength > 0 ? contentLength : 0);
    lengthOptimization = status.code() == Http.Status.OK_200.code()
            && !HttpUtil.isTransferEncodingChunked(response);
    HttpUtil.setTransferEncodingChunked(response, true);
}
```
But I want to know why TransferEncoding was set to `chunked` and should I remove that for this issue?
