### ISSUE TITLE
Basic load test

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#222]
Implement and document a basic load test. Some requirements:

* Basic Helidon SE server with at least GET and POST consuming and producing JSON payloads
* Run client and server on difference machines
* Configurable number of concurrent requesting threads
* Report requests per second
* Report JVM heap usage 
* This can require manual steps -- does not need to be fully automated
* Can use Apache JMeter, gatling.io, etc

**Comment by barchetta** [comment]
For reference:

https://github.com/oracle/helidon/wiki/Performance-Testing-Using-JMeter

**Comment by spericas** [comment]
For more information see wiki page.
