### ISSUE TITLE
Helidon maven plugin: native-image, Windows,  "Unable to find native-image command path"

### ISSUE THREAD

**Issue by Karm** [oracle/helidon#2230]
## Environment Details
* Helidon Version: 2.0.1
* Helidon SE
* JDK version: GraalVM CE Java11 20.1.0
* OS: Windows 2019 Server
* Helidon maven plugin: io.helidon.build-tools:helidon-maven-plugin:2.0.2:native-image (native-image)

## Unable to find native-image command path

Hello, when I try to build a simple Helidon hello world app as a native-image, it works just fine on Linux, but it fails on Windows:

```
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.helidon.build-tools:helidon-maven-plugin:2.0.2:native-image (native-image) 
on project helidon-quickstart-se: 
Unable to find native-image command path, C:\Program_Files\graalvm-ce-java11-20.1.0\bin\native-image is not a valid file
```

Note the underscore in ```Program_Files```, I tried that symlink instead of "Program Files" as I suspected the white space could have been the problem. Unfortunately that was not the case. The problem persists.
Yes, the file exists and it works (Quarkus and others build with it on the same machine).

```
λ C:\Program_Files\graalvm-ce-java11-20.1.0\bin\native-image --version
GraalVM Version 20.1.0 (Java Version 11.0.7)
```

## Steps to reproduce
Build an arbitrary Helidon quickstart on Windows.

Thanks for pointers

K.

**Comment by romain-grecourt** [comment]
Thanks for filing this issue.
The `native-image` does not support windows the way it should, I have a PR going and will release a version with a fix shortly.

**Comment by Karm** [comment]
Hello, @romain-grecourt 

```
[INFO] Building native image :C:\projects\mandrel-integration-tests\apps\helidon-quickstart-se\target\helidon-quickstart-se
[WARNING] 'logging.properties' is not recognized as an internal or external command,
[WARNING] operable program or batch file.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.281 s
[INFO] Finished at: 2020-10-27T03:37:43-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.helidon.build-tools:helidon-maven-plugin:2.1.2:native-image (native-image) on project helidon-quickstart-se: Image generation failed, exit code: 255 -> [Help 1]
[ERROR] 
```
Which version has the patch?

**Comment by romain-grecourt** [comment]
2.1.2 should have the fix. You might be running into another issue. Can you run with -X and share the command line.
