### ISSUE TITLE
Unable to generate Enterprise PGO Optimized native image for Helidon MP Helloword app

### ISSUE THREAD

**Issue by nelvadas** [oracle/helidon#2249]
Not able to use PGO feature from GraalVM EE to generate an optimized native image for helidon MP helloworld microservice 

## Environment Details
* Helidon Version: 2.0.1 
* Helidon MP
* JDK version:11-20.1.0
* OS: Mac OS 10.15.6 (19G73)
* Docker version (if applicable):

----------

## Problem Description

0- Set GRAALVM_EE_HOME and JAVA_HOME
$env | grep HOME
`GRAALVM_HOME= ~/Java/graalvm-ce-java11-20.1.0/Contents/Home`
`GRAALVM_EE_HOME=~/Java/graalvm-ee-java11-20.1.1/Contents/Home`
`JAVA_HOME=~/Java/graalvm-ee-java11-20.1.1/Contents/Home`

PGO is an enterprise feature so we will be  using **GRAALVM_EE_HOME**

1. Generate the helidon Microservice using [https://helidon.io/docs/latest/#/mp/guides/02_quickstart](https://helidon.io/docs/latest/#/mp/guides/02_quickstart)

2.  Build the JAR, and Run it with PGOInstrument option 
```$GRAALVM_EE_HOME/bin/java -Dgraal.PGOInstrument=hello.iprof -jar target/helidon-hello.jar```
 The profile is generated properly.

3.  Use the generated iprof file to build an optimized a native image.  
```$GRAALVM_EE_HOME/bin/native-image --pgo=hello.iprof -jar target/helidon-hello.jar```
Here the process stops with ` **Duplicate key on some classes , JBoss, glassfish , jersey etccc**`
.... Error 
safe access!
[helidon-helloworld:86188]     (clinit):   1,169.95 ms,  3.45 GB
[helidon-helloworld:86188]     analysis:  89,275.73 ms,  3.45 GB
Fatal error:java.lang.IllegalStateException: java.lang.IllegalStateException: Duplicate key [org.glassfish.jersey.internal.inject.Providers$$Lambda$2920dae572260e2b5caab4b3632779bc6caaa7d4.apply:0] (attempted merging values [J@581b579 and [J@da09471)

the native image generation process without PGO option is working

**Comment by tomas-langer** [comment]
Hello,
 you cannot run `native-image` on the jar file itself - you are missing mandatory libraries that are used when running using our maven plugin.
There are two ways to resolve this:
1. Use Helidon maven plugin, and add a `native-image.properties` file to your `resources/META-INF/native-image/group-id/artifact-id/native-image.properties` with `Args=--pgo=hello.iprof`, then run `mvn clean package -Pnative-image` and a native image is built as expected (tried this)
2. Add the following dependency to your project (this will add two jars to your `libs` directory that are mandatory if you want to build a Helidon MP application using native image):
```
                <dependency>
                    <groupId>io.helidon.integrations.graal</groupId>
                    <artifactId>helidon-mp-graal-native-image-extension</artifactId>
                </dependency>
```

**Comment by tomas-langer** [comment]
As there was no reaction from original submitter, I am closing this issue.
The feature works, it just requires adding correct dependencies when building native image.

**Comment by nelvadas** [comment]
I @tomas-langer , sorry will check this and revert to you, was busy with some others stuffs. But for native image without pgo i can create it from jar for this example with no issue.
