### ISSUE TITLE
TransactionManager timeout

### ISSUE THREAD

**Issue by ottuzzi** [oracle/helidon#2251]
## Environment Details
* Helidon Version: 1.4.5
* Helidon MP
* JDK version: 11
* OS: Win10
* Docker version (if applicable): N/A

----------

## Problem Description
If request debugging (for example debugging using eclipse debugger) takes longer than a certain amount of time and the method has been marked with Transactional annotation I get the error `"faultDescription": "javax.transaction.RollbackException: ARJUNA016102: The transaction is not active! Uid is 0:ffffa9fefc27:f8e4:5f2d4f35:2"` 
Is there a way to specify the transaction timeout?

## Steps to reproduce
* create a method annotated as Transactional and debug it; set a breakpoint and wait some time (not sure... I think 60s is enough)

**Comment by ljnelson** [comment]
Hello; have a look at a [blog article I wrote on the subject](https://lairdnelson.wordpress.com/2020/03/11/configuring-narayana/).

**Comment by ljnelson** [comment]
Closing due to no further questions.
