### ISSUE TITLE
Make it possible to build on windows

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#227]
Fix the build to work on windows.

**Comment by romain-grecourt** [comment]
See this PR https://github.com/oracle/helidon-build-tools/pull/12 that address fixes for windows needed in the sitegen tool

**Comment by romain-grecourt** [comment]
@kumar-dhanagopal FYI

**Comment by kumar-dhanagopal** [comment]
Thanks, @romain-grecourt
