### ISSUE TITLE
Documentation for Security providers

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#2273]
## Environment Details
* Helidon Version: 2
* Helidon both SE and MP (security providers related)
----------

## Problem Description
Missing documentation:

1. Detailed expected interactions when a JWT token is received (OIDC provider and JWT provider) - what happens behind the scenes, interactions with identity provider
2. Detailed expected interactions when outbound service is called (what tokens would be attached and when)
3. How to configure per target outbound security

**Comment by ljamen** [comment]
Reviewed doc in PR 2357.
