### ISSUE TITLE
Native-image runtime error with QueryParam of type Long

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#2291]
## Environment Details
* Helidon Version: 2.0.1
* Helidon MP
* JDK version: 11

## Problem Description

Our native image support seems to have issues with QueryParams that are not of type String (QueryParams of type String work fine). For example if I have a JAX-RS application with an endpoint like this:

```
public JsonObject sleep(@DefaultValue("100") @QueryParam("millis") Long millis) {
```

It works fine with the JVM. Native image compiles, but when I run the native image I get an error:

```
2020.08.25 17:33:42 INFO org.jboss.weld.Bootstrap Thread[main,5,main]: WELD-ENV-002001: Weld SE container a4d253ed-1d6e-4e39-ba9e-81162929849d shut down
Exception in thread "main" org.glassfish.jersey.server.model.ModelValidationException: Validation of the application resource model has failed during application initialization.
[[FATAL] No injection source found for a parameter of type public javax.json.JsonObject io.helidon.examples.quickstart.mp.SleepService.sleep(java.lang.Long) at index 0.; source='ResourceMethod{httpMethod=GET, consumedTypes=[], producedTypes=[application/json], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class io.helidon.examples.quickstart.mp.SleepService, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@111880638]}, definitionMethod=public javax.json.JsonObject io.helidon.examples.quickstart.mp.SleepService.sleep(java.lang.Long), parameters=[Parameter [type=class java.lang.Long, source=millis, defaultValue=100]], responseType=interface javax.json.JsonObject}, nameBindings=[]}']
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:371)
	at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:293)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:292)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:246)
	at io.helidon.webserver.jersey.JerseySupport.<init>(JerseySupport.java:135)
```

If I change the query param to type `String` then it works.

## Steps to reproduce

1.  Run the helidon-quickstart-mp archetype to create the project
2. Add the following to `GreetResource.java`

```
    @GET
    @Path("sleep")
    @Produces(MediaType.APPLICATION_JSON)
    public JsonObject sleep(@DefaultValue("100") @QueryParam("millis") Long millis) {
        try {
            Thread.sleep(millis);
        } catch (InterruptedException e) { }

        return JSON.createObjectBuilder()
                .add("millis", millis)
                .build();
    }
```
3. `mvn package -Pnative-image`
4. `target/helidon-quickstart-mp`, the server will fail with the above error. If you change the Long to a String it will work

**Comment by barchetta** [comment]
Just in case this Jersey bug is relevant: https://github.com/eclipse-ee4j/jersey/issues/4555 (thanks to @ljnelson for pointing this out)

**Comment by tomas-langer** [comment]
Narrowed down the problem to `MultivaluedParameterExtensionFactory` method `process(ParamConverterFactory, String, Class, Type, Annotation[], String)`, where the converter obtained from `paramConverterFactory` is null in native image, while non-null in hotspot.

**Comment by tomas-langer** [comment]
Hotspot debug (added println, as there is no logging available):
```
Processing long (class java.lang.Long): null
Converter: org.glassfish.jersey.internal.inject.ParamConverters$TypeValueOf$1@5e905f2c
```

Native image:
```
Processing long (class java.lang.Long): null
Converter: null
```

Jersey code:
```
        System.out.println("Processing " + parameterName + " (" + rawType + "): " + defaultValue);
        // Try to find a converter that support rawType and type at first.
        // E.g. if someone writes a converter that support List<Integer> this approach should precede the next one.
        ParamConverter<?> converter = paramConverterFactory.getConverter(rawType, type, annotations);
        System.out.println("Converter: " + converter);
```

**Comment by tomas-langer** [comment]
Identified the problem.
Jersey uses reflection to find static methods that create an instance of a parameter from `String`. For `Long`, this is `valueOf(String)`. 
As we do not add `Long` for reflection, this method is not found and as a result the "coercion" into Long does not work.

Hence a simple workaround/solution is to add this method for reflection for any type parameters should be converted.
Add file `reflect-config.json` to `META-INF/group-id/artifact-id` with the following content (for `Long`):
```json
[
    {
        "name": "java.lang.Long",
        "methods": [
            {
                "name": "valueOf",
                "parameterTypes": [
                    "java.lang.String"
                ]
            }
        ]
    }
]

```

**Comment by tomas-langer** [comment]
The PR adds an automated support for injected fields and parameters for headers, path parameters and query parameters that have types with static methods `valueOf` or `fromString`
