### ISSUE TITLE
No immediately apparent way to emulate JAX-RS' UriInfo#getBaseUri()

### ISSUE THREAD

**Issue by ljnelson** [oracle/helidon#231]
I don't see an easy (existing) way to emulate [JAX-RS' `UriInfo#getBaseUri()` method](https://jax-rs.github.io/apidocs/2.1/javax/ws/rs/core/UriInfo.html#getBaseUri--).  There probably should be one on [`ServerRequest`](https://helidon.io/docs/latest/apidocs/io/helidon/webserver/ServerRequest.html).  Feel free to close this issue if I've overlooked something.

This would be useful&mdash;perhaps necessary&mdash;for `Location` headers.

**Comment by romain-grecourt** [comment]
Maybe this could be done with a new method in HttpRequest.Path, perhaps something like this:

```java
request.path().base()
```

**Comment by ljnelson** [comment]
But then you have the distinctly bizarre situation where a "path" is actually a URI.

What I'm personally confused by is why `request.uri().equals(request.path().absolute())`.  That seems counterintuitive.

**Comment by romain-grecourt** [comment]
How about `request.baseUri()` ?

**Comment by ljnelson** [comment]
Yeah; not crazy about it but it's fine.

More important to me is how to implement it (I'm no deep expert on the HTTP protocol; the answer may very well be very simple).  Consider a Helidon `WebServer` listening on `0.0.0.0`.  Since the `Host` HTTP header is mandatory, it will be present, of course, but is it reliable?  What about port, given that (I think) a `WebServer` may be configured to share a `Routing` across the multiple sockets described by its associated `SocketConfiguration`?  Or maybe this is a non-sensical use case?  How can we tell whether the request itself is HTTP vs HTTPS?

Jersey appears to punt on most of this in many of its container implementations.  For example, here's what their Netty container does: https://github.com/eclipse-ee4j/jersey/blob/eafb9bdcb82dfa3fd76dd957d307b99d4a22c87f/containers/netty-http/src/main/java/org/glassfish/jersey/netty/httpserver/JerseyServerInitializer.java#L61-L74

Note that you pass in the base URI at construction time.

On the other hand, here's what they do using the crummy little HTTP server in the JDK: https://github.com/eclipse-ee4j/jersey/blob/eafb9bdcb82dfa3fd76dd957d307b99d4a22c87f/containers/jdk-http/src/main/java/org/glassfish/jersey/jdkhttp/JdkHttpHandlerContainer.java#L115-L158

**Comment by romain-grecourt** [comment]
@ljnelson @barchetta @tomas-langer Does this seem like a good candidate for 1.0 ?

**Comment by ljnelson** [comment]
For posterity: see https://github.com/oracle/helidon/blob/936844212257a0886ee827303ad15b8da62013f5/webserver/jersey/src/main/java/io/helidon/webserver/jersey/JerseySupport.java#L124-L170 which also has to deal with this; perhaps we could, in some way, make this `public`….
