### ISSUE TITLE
Minor issues in the getting-started guides

### ISSUE THREAD

**Issue by kumar-dhanagopal** [oracle/helidon#233]
Team,

While trying out the quickstart examples, I ran into a few minor issues, listed below. New users like me might see these issues as well.

Please review. I can fix them after you take a look.

https://helidon.io/docs/latest/#/getting-started/02_base-example#Prerequisites
1. For the `archetype:generate` command to work, users might need to set the proxy in {maven.home}/conf/settings.xml
2. `java --version` → Should be: `java -version`
3. (@tjquinno and I discussed this one for the MP web service guide) To enable users running Maven on Windows to copy/paste the archetype:generate commands at the CMD prompt, show the entire command in one line in the doc, i.e., without the \ line separators.

https://helidon.io/docs/latest/#/getting-started/02_base-example
4. Before running the application, ask users to first `cd` to the `quickstart-se` or `quickstart-mp` directory, as required.
5. For users who try out both examples, to help them see which app (se or mp) is serving requests, customize the response body for the GET calls to include an indicator or some sort (e.g., "This request is served by `<app name>`"
6. Before building the docker container, ask users to first `cd` to the `quickstart-se` or `quickstart-mp` directory, as required.
7. If docker was installed by the superuser, then to let a logged-in non-SU user access the docker engine, the user must be added to the docker group: sudo usermod -a -G docker $USER

**Comment by kumar-dhanagopal** [comment]
Thanks, @romain-grecourt !

I didn't see a response to the `java --version` issue. I presume you're ok with updating that to `java -version`.

> The Maven proxy configuration is common knowledge. We have to draw a line on what we document, here the assumption is that it is very easy to find information on how to configure proxy Maven.
> Similar to my comment about configuring the proxy with Maven, the docker setup is something that belongs in the Docker docs.
Ok. In that case, we should mention "Basic working knowledge of Maven and Docker setup" as a prereq.
 
> Also note that you should not update the default settings.xml in the Maven installation.
> You basically have two options, either you create your own settings at `~/.m2/settings.xml` or you export `MAVEN_OPTS` and set `-Dhttp.proxyHost -Dhttp.proxyPort` system properties
If we add Maven/Docker knowledge as a prereq, we're covered on this front.

> As discussed on the PR (I think), not breaking the line leads to having an horizontal scrolling behavior which makes it harder to see the full command (even on wide screens).
If we want users to simply copy & paste, then being able to copy is more important IMO.

> The getting-start page you reference does have a `cd` instruction, not sure what you are referring to.
My mistake. I missed that part.

>Adding the app name in the greeting message may be a good enhancement to make, @barchetta what do you think ?
Your thoughts, @barchetta ?

**Comment by romain-grecourt** [comment]
> I didn't see a response to the `java --version` issue. I presume you're ok with updating that to `java -version`.

Yes, that's a mistake / typo that needs to be fixed.

> Ok. In that case, we should mention "Basic working knowledge of Maven and Docker setup" as a prereq.

That seems fair, we can add a something to mention that.

> If we want users to simply copy & paste, then being able to copy is more important IMO.

Breaking the line does not remove the ability to copy and paste.
There is a copy to clipboard button that works regardless of the line breaking.
However most people won't use this button, so if the command is on a single line the users have to select the line by scrolling horizontally in order to copy it to their clipboard, this can be tricky. Breaking the line also makes that easier.

**Comment by tjquinno** [comment]
Just to be a pain in the neck:

Partial output from `java -h`:
```
    -version      print product version to the error stream and exit
    --version     print product version to the output stream and exit
```
The difference is the stream used. 

🙂

**Comment by kumar-dhanagopal** [comment]
Here's the error I get with `java --version` ...
```
$ java --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Unrecognized option: --version
```
`-version` works fine:

```
$ java -version
java version "1.8.0_202-ea"
Java(TM) SE Runtime Environment (build 1.8.0_202-ea-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b03, mixed mode)
```

**Comment by kumar-dhanagopal** [comment]
Btw, assuming Maven looked for the `JAVA_HOME` variable, wouldn't it be better to ask users to verify that the variable is set. In other words, they might have JDK 8+, but without setting JAVA_HOME, they can't proceed, right?

**Comment by kumar-dhanagopal** [comment]
> 
> 
> Btw, assuming Maven looked for the `JAVA_HOME` variable, wouldn't it be better to ask users to verify that the variable is set. In other words, they might have JDK 8+, but without setting JAVA_HOME, they can't proceed, right?

Scratch that... I just noticed that the Prerequisites doc does call this out.

**Comment by tjquinno** [comment]
Oops. `java --version` seems to have been added in 9. My bad.

**Comment by kumar-dhanagopal** [comment]
> Breaking the line does not remove the ability to copy and paste.
> There is a copy to clipboard button that works regardless of the line breaking.

Perhaps a poor choice of words on my part....

Yes, users can still copy, regardless of the line breaks. But on Windows, the copied command won't work when pasted.

> However most people won't use this button

 I thought otherwise.  Do we have some data to support this?

**Comment by kumar-dhanagopal** [comment]
> 
> 
> Oops. `java --version` seems to have been added in 9. My bad.

No problem.

**Comment by romain-grecourt** [comment]
> > However most people won't use this button
> 
> I thought otherwise. Do we have some data to support this?

Just my own experience: people tend to not use the copy to clipboard button. When it's text and there is a need to copy they select it and press ctrl+c / cmd+c.
