### ISSUE TITLE
Unable to build native image in windows for helidon example

### ISSUE THREAD

**Issue by nagasitaramthigulla** [oracle/helidon#2331]
## Environment Details
* Helidon Version: 20.2
* Helidon SE or Helidon MP
* JDK version: OpenJDK 11
* OS: Windows
* Docker version (if applicable):

----------
I have downloaded GraalVM and native image in windows and followed set from https://helidon.io/docs/latest/#/mp/guides/36_graalnative
when I tried running
` mvn package -Pnative-image`

[WARNING] Fatal error:java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 47
[WARNING] logging.properties|META-INF\beans.xml|META-INF\microprofile-config.properties|META-INF\native-image\reflect-config.json
[WARNING]                                                ^
[WARNING]       at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
[WARNING]       at java.base/java.util.regex.Pattern.escape(Pattern.java:2616)
[WARNING]       at java.base/java.util.regex.Pattern.atom(Pattern.java:2285)
[WARNING]       at java.base/java.util.regex.Pattern.sequence(Pattern.java:2209)
[WARNING]       at java.base/java.util.regex.Pattern.expr(Pattern.java:2068)
[WARNING]       at java.base/java.util.regex.Pattern.compile(Pattern.java:1782)
[WARNING]       at java.base/java.util.regex.Pattern.<init>(Pattern.java:1428)
[WARNING]       at java.base/java.util.regex.Pattern.compile(Pattern.java:1068)
[WARNING]       at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[WARNING]       at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[WARNING]       at java.base/java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3566)
[WARNING]       at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[WARNING]       at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[WARNING]       at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[WARNING]       at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[WARNING]       at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
[WARNING]       at com.oracle.svm.hosted.ResourcesFeature.duringAnalysis(ResourcesFeature.java:123)
[WARNING]       at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:732)
[WARNING]       at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
[WARNING]       at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:732)
[WARNING]       at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:555)
[WARNING]       at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
[WARNING]       at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[WARNING]       at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[WARNING]       at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[WARNING]       at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[WARNING]       at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[WARNING]       at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[WARNING] Error: Image build request failed with exit status 1

**Comment by Verdent** [comment]
Hi, this looks like a bug. Possible workaround could be adding the following plugin to the build section of the pom.xml, that might help you to solve this issue for now.
```xml
<plugin>
    <groupId>io.helidon.build-tools</groupId>
    <artifactId>helidon-maven-plugin</artifactId>
    <configuration>
        <addProjectResources>false</addProjectResources>
    </configuration>
</plugin>
```
