### ISSUE TITLE
security.enabled flag is not working from application.yaml

### ISSUE THREAD

**Issue by PasiPraveen** [oracle/helidon#2333]
Environment Details
Helidon Version: 1.4.7
Helidon MP
JDK version: 1.8
OS: Windows 10

## Problem Description

This is followup to fix proived for https://github.com/oracle/helidon/issues/2132 in 1.4.7.

The flag to enable security [security.enabled] is working only when sent as run time parameter[ex:-Dsecurity.enabled=true]

As per the description of the fix provided for https://github.com/oracle/helidon/issues/2132 we can  configure security.enabled=true or in application.yaml:

security:
  enabled: true
  
When the below is set in application.yaml  security is not getting enabled & the server displays the message[2020.09.07 21:37:09 INFO io.helidon.microprofile.security.SecurityMpService Thread[main,5,main]: Security is disabled.] while starting the server.

## Steps to reproduce

Add the below to application.yaml[src\main\resources]

security:
  enabled: true
  
## Log Trace
2020.09.07 21:37:06 INFO io.helidon.microprofile.server.Main Thread[main,5,main]: Logging configured using classpath: /logging.properties
2020.09.07 21:37:07 INFO org.jboss.weld.Version Thread[main,5,main]: WELD-000900: 3.1.1 (Final)
2020.09.07 21:37:07 INFO org.jboss.weld.Bootstrap Thread[main,5,main]: WELD-ENV-000020: Using jandex for bean discovery
2020.09.07 21:37:08 INFO org.jboss.weld.Bootstrap Thread[main,5,main]: WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
2020.09.07 21:37:08 INFO org.jboss.weld.Event Thread[main,5,main]: WELD-000411: Observer method [BackedAnnotatedMethod] public org.glassfish.jersey.ext.cdi1x.internal.ProcessAllAnnotatedTypes.processAnnotatedType(@Observes ProcessAnnotatedType<?>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2020.09.07 21:37:09 INFO org.jboss.weld.Bootstrap Thread[main,5,main]: WELD-ENV-002003: Weld SE container ceb9f633-3f97-4c53-8cda-f62b94298bc6 initialized
2020.09.07 21:37:09 INFO io.helidon.microprofile.security.SecurityMpService Thread[main,5,main]: Security is disabled.
2020.09.07 21:37:09 FINEST AUDIT Thread[main,5,main]: INFO security.configure cf6188d2-d7fd-46a9-899d-c7bb3ab827ae  io.helidon.microprofile.security.SecurityMpService configure SecurityMpService.java 68 :: "Security initialized. Providers: audit: "[io.helidon.security.DefaultAuditProvider]"; authn: "[default: io.helidon.security.Security$Builder$$Lambda$464/1809129176]"; authz: "[default: io.helidon.security.Security$Builder$$Lambda$465/1554877309]"; identity propagation: "[]";"
2020.09.07 21:37:10 INFO io.helidon.webserver.NettyWebServer Thread[main,5,main]: Version: 1.4.7
2020.09.07 21:37:10 INFO io.helidon.webserver.NettyWebServer Thread[nioEventLoopGroup-2-1,10,main]: Channel '@default' started: [id: 0x999abd39, L:/0:0:0:0:0:0:0:0:8080]
2020.09.07 21:37:10 INFO io.helidon.microprofile.server.ServerImpl Thread[nioEventLoopGroup-2-1,10,main]: Server initialized on http://localhost:8080 (and all other host addresses) in 4520 milliseconds.

**Comment by tomas-langer** [comment]
Hello, the `security.enabled` can be configured either in `META-INF/microprofile-config.properties` or in `application.yaml`.
The default is `true`, so you probably have it configured to `false` somewhere in your application already.

The order of providers in Helidon MP is defined by a `config_ordinal` value. 
One of the following is probably causing your problem:
1. you configure the `security.enabled=true` in a source that has lower priority than the one it is already configured in
2. your yaml formatting is bad and not recognized
3. you configure config sources by hand 

To fix these:
1. add `config_ordinal` property with value higher than `100` (the default) and lower than `300` (environment variables property source)
2. make sure the `enabled` is under the `security` node (indentation is significant in yaml):
```
security:
  enabled: true
```
3. check your config source setup and change this value in a config source that is more significant than the one already containing the `security.enabled=false` value

**Comment by PasiPraveen** [comment]
[helidon-quickstart-mp.zip](https://github.com/oracle/helidon/files/5230808/helidon-quickstart-mp.zip)
Hi,
I have tried to replicate the issue in the helidon-quickstart-mp for 1.4.7 version.Please find the attached helidon-quickstart-mp.zip file & have verified the below 2 items.
1.No security.enabled entry in src\main\resources\META-INF\microprofile-config.properties
2.correct indentation in application.yaml

security:
  config.require-encryption: false
  enabled: true
  jersey:    
    use-abort-with: false

Regards,
Praveen

**Comment by tomas-langer** [comment]
I will have a look

**Comment by tomas-langer** [comment]
I have built and run your application and security is enabled.

There are only two ways I can see that could disable security for this application:
1. You may have an environment variable (such as `SECURITY_ENABLED=false`, or `security.enabled=false`) 
2. You set up a system property `security.enabled=false`

I do not see how it could get disabled otherwise, as the default is that security is enabled.

I have also tried setting the `security.enabled` to `false` using `application.yaml` and it works (e.g. it disabled security in the application). When I remove that property (or set it back to `true`), security works as expected.

If you cannot work this out, please contact me over our slack channel, and we can set up a zoom call to figure it out.

**Comment by PasiPraveen** [comment]
I have verified the environment variables & do have SECURITY_ENABLED variable set to false.

![image](https://user-images.githubusercontent.com/54166303/93466109-60117480-f909-11ea-8984-cf440b4db509.png)

**Comment by tomas-langer** [comment]
So that is the root cause of this problem.
Environment variables config source has higher priority than any file on file system or classpath. As a result, this configuration is always overridden.
You can verify this by running the application from command line.
If I remember correctly for windows:
```
unset SECURITY_ENABLED
mvn package
java -jar target/helidon-quickstart-mp.jar
```

Should do the trick

**Comment by PasiPraveen** [comment]
Thanks Tom.I will be closing this as this is more system[environment] related.

Regards,
Praveen
