### ISSUE TITLE
Tutorials landing page in the docs site

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#239]
## Problem Description
Create a landing page for our guides that lists the guides, maybe as a matrix of cards. 

This will be referenced directly from the helidon.io home page.

**Comment by kumar-dhanagopal** [comment]
Examples discussed on #j4c-dev...

https://openliberty.io/guides/
https://istio.io/docs/examples/

**Comment by kumar-dhanagopal** [comment]
A few more site examples:

http://fnproject.io/tutorials/
https://kubernetes.io/docs/tutorials/
https://docs.docker.com/samples/

**Comment by kumar-dhanagopal** [comment]
The intent of this ticket is to provide a landing page for the step-by-step "tutorials" that are currently called "guides" on the docs site. The term "guides" has a broader meaning in the doc world; it could include all documentation - procedural guides, references guides, concept guides, etc.

**Comment by kumar-dhanagopal** [comment]
@romain-grecourt - Pls take a look at the mockup at https://kumar-dhanagopal.github.io/repo1/index.html, and let me know what you think.  How can we implement something like this on our site?

**Comment by tjquinno** [comment]
Generally I very much like the idea of a tutorials landing page. 

Specific notes:
1. The About->Intro page also uses cards (I think), with quite a different look and feel from what is on the mock-up page for the tutorials. It would be good if the two uses of cards look the same. Is the L&F on the mock-up page the proposal for how all cards would display?
2. Would the eventual plan be to have separate landing pages for the different types of doc, or a single page segmented by type? Currently we have only three tutorials. What about if their cards shared space on a more general page with cards for other types of doc, such as the quick-starts? When we have more tutorials or quick-starts we could spin off a separate page or pages if we wanted.

**Comment by romain-grecourt** [comment]
Like Tim said, the intro page has cards that are generated from asciidoc. see about/01_introduction.adoc

I'm not a fan of collapsible content inside the main area, IMO it should just be scrollable.
How about having sections of cards that can span on multiple lines ? Exactly like openliberty guides https://openliberty.io/guides/

**Comment by tjquinno** [comment]
Where do we think the tutorials landing page would be and how would the user get there?

Currently expanding a category in the left-hand nav panel does not also change what's shown in the main panel. Conceivably one option would be that clicking on the Guides (or, perhaps changed to Tutorials) item in the nav panel would not only expand the list but also reload the main panel with the cards for the tutorials. I do not know how easy or hard it would be to change the behavior that way.

**Comment by kumar-dhanagopal** [comment]
> one option would be that clicking on the Guides (or, perhaps changed to Tutorials) item in the nav panel would not only expand the list but also reload the main panel with the cards for the tutorials.
+1

**Comment by kumar-dhanagopal** [comment]
See PR https://github.com/oracle/helidon/pull/368 for a draft of the new tutorials landing page based on the `CARDS` markup that we have in `about/01_introduction.adoc`.

**Comment by romain-grecourt** [comment]
> Where do we think the tutorials landing page would be and how would the user get there?
> 
> Currently expanding a category in the left-hand nav panel does not also change what's shown in the main panel. Conceivably one option would be that clicking on the Guides (or, perhaps changed to Tutorials) item in the nav panel would not only expand the list but also reload the main panel with the cards for the tutorials. I do not know how easy or hard it would be to change the behavior that way.

I'd say we should remove the individual guide links from the menu and make it a single link for guides.

**Comment by tjquinno** [comment]
Not to expand the scope of _this_ item, but some thoughts that might match up with what we're discussing here...

I think of two general types of items in that left-hand nav panel. Some are categories that contain multiple separate items, such as tutorials and extensions which when expanded list those separate items. Some are single, longer documents which when expanded list the "chapters" (for lack of a better term) of each larger single document.

If it's easy to do, I like the idea of the items in that first category (such as tutorials) both expanding on the left _and_ filling the main pane with cards for the individual items in that category. I think what we are discussing for tutorials applies equally well to extensions and maybe others.

In contrast, web server and config expand into "chapters". The card metaphor for chapters of a larger document is less useful, I think, so I would not suggest using cards for chapters of those types of item although I could be convinced otherwise if it's hard to implement.

----
I just read Romain's comment that he posted while I was editing this one. That works for me too.

**Comment by romain-grecourt** [comment]
> Besides that, we could also add a Tutorials link adjacent to the Documentation link on the main site: https://helidon.io/#/.

I'd rather not add another link at the top. However we could add more links a the bottom in the getting started section. Instead of "try it now", we could have a links for the quickstarts and guides.

**Comment by romain-grecourt** [comment]
> Fixed that. Where do you recommend we add the link - directly to the title of each card? Or, is there a way to make the entire card clickable?

Your last update to #368 is not valid asciidoc. Also I can't think of an easy to make the cards clickable currently, we will have to make changes to the sitegen to support that.

**Comment by kumar-dhanagopal** [comment]
Ok, can you pls help me identify the issue in the markup, Romain?

**Comment by romain-grecourt** [comment]
the card block is delimited by `--`

```
[CARD]
--
card content
--
```

In your PR you've removed one of the `--`

**Comment by kumar-dhanagopal** [comment]
Thanks, Romain!  

Given the following `CARD` ...

```
[CARD]
--
.Create a RESTful Web Service Using Helidon SE
Use Helidon SE to create a RESTful web service that accepts HTTP requests.
--
```
How do I make the card title "Create a RESTful Web Service Using Helidon SE" a link pointing to guides/01_SE_REST_web-service.adoc ?

**Comment by romain-grecourt** [comment]
Links in card title are not supported currently, I'm actually working on adding this feature.

**Comment by romain-grecourt** [comment]
Sitegen features can be added anytime, it's not a part of the helidon "product". I'm working on this right now we may be able to use this for 1.0.

**Comment by kumar-dhanagopal** [comment]
> Sitegen features can be added anytime, it's not a part of the helidon "product". 

Yes, I get that. My question was whether the work you're doing to support links in the card title will be done in the 1.0 timeframe. And you answered that. Thank you!

**Comment by kumar-dhanagopal** [comment]
Do let me know when the feature is ready.   Is there a tracking issue that I can watch ?

**Comment by romain-grecourt** [comment]
I created this issue https://github.com/oracle/helidon-build-tools/issues/28

**Comment by spericas** [comment]
I really like the idea of the cards and a landing page for tutorials! On a separate note, the copyright year at the bottom of the page (http://helidon.io) only shows 2018. Do we need to update that?

**Comment by kumar-dhanagopal** [comment]
>... the copyright year at the bottom of the page (http://helidon.io) only shows 2018. Do we need to update that?

Yes!

@romain-grecourt - Could you please update the copyright notice?

For reference, the Oracle Legal-approved convention is:

"Copyright © <yearOfFirstPublication>, <yearOfMostRecentUpdate>, Oracle and/or its affiliates."

**Comment by romain-grecourt** [comment]
The landing page has not been updated this year yet. @barchetta Can you update the copyright year with your next update in https://github.com/oracle/helidon-site/pull/22 ?

@kumar-dhanagopal the copyright notice of the website was given to us by the proper people. Also for the website I think only having the latest year of update is better.

**Comment by romain-grecourt** [comment]
Let me clarify since this wasn't clear. The copyright text was given to us by **lawyers**.
Also please stop mentioning internal URLs and corporate legal matters on GitHub.

**Comment by kumar-dhanagopal** [comment]
ok.

**Comment by romain-grecourt** [comment]
@kumar-dhanagopal See PR https://github.com/oracle/helidon-build-tools/pull/29 for the card link support.

**Comment by kumar-dhanagopal** [comment]
Thanks!  

So would markup like in the following example make the entire card (including the card title) clickable ?

```
[CARD]
.Create a RESTful Web Service Using Helidon SE
--
[link=01_SE_REST_web-service.adoc]
Use Helidon SE to create a RESTful web service that accepts HTTP requests.
--
```

**Comment by kumar-dhanagopal** [comment]
I've added the link attrib to the cards on the landing page.

**Comment by kumar-dhanagopal** [comment]
@romain-grecourt , @barchetta - From @romain-grecourt 's comment in the PR that he closed, it appears that further review is required.  Let me know what else needs to be done to complete this task before 1.0. If we need to talk, my calendar is up to date.

**Comment by kumar-dhanagopal** [comment]
@romain-grecourt  and @barchetta published this page: https://helidon.io/docs/latest/#/guides/01_overview on 2/8
