### ISSUE TITLE
mismatch versions of ojdbc artifacts

### ISSUE THREAD

**Issue by paulparkinson** [oracle/helidon#2415]
There are mismatch versions of ojdbc artifacts. See dependencies pom.xml...
       <version.lib.oracle.ojdbc10>19.3.0.0</version.lib.oracle.ojdbc10>
          [...]
        <version.lib.ojdbc8>19.6.0.0</version.lib.ojdbc8>

## Environment Details
* Helidon Version: 2.0.1
* Helidon SE and MP
* JDK version: any
* OS: any
* Docker version (if applicable):

----------

## Problem Description
All references to ojdbc (and ucp) should be com.oracle.database.jdbc ojdbc8 v 19.7 which is not currently the case, however, we may as well wait until November to make this change as v20 of these artifacts will be out then with support for native image in UCP and wallet which is the only major issue this mismatch causes.  We can pick up ojdbc11 and v20 at that time. 
We should also consider making production rather than "regular" the default artifacts as it has become the more common requirement/use case due to ATP database.

## Steps to reproduce
Attempt to build native image using ojdbc, ucp, and jpa

**Comment by paulparkinson** [comment]
correction, will be v21 not v20

**Comment by arjav-desai** [comment]
With above PR, we have removed ojdbc10 and ucp and now keeping only ojdc8 (v 19.8.0.0 and picking up all production version).

Keeping this issue open since we want to pick v21 which has native image support and will be available early december.

**Comment by arjav-desai** [comment]
We have uptake 21.3 ojdbc jars and verified that native image works with UCP for accessing ATP.
