### ISSUE TITLE
Helidon attempts to load vetoed JAX-RS application

### ISSUE THREAD

**Issue by mhorejsi** [oracle/helidon#2418]
# Environment Details
* Helidon Version: 2.0.2
* Helidon MP
* JDK version: 11.0.8
* OS: OS X El Capitan

----------

## Problem Description
If I write a custom CDI extension that `@Observes ProcessAnnotatedType<T>` with [lower priority](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#observer_ordering) than Helidon's `JaxRsCdiExtension` and `veto()` my JAX-RS application in the observer method, Helidon ignores the veto and attempts to load it. This attempt fails because my JAX-RS application injects other vetoed CDI beans.

This bug wasn't present in Helidon 1.4.x

**Comment by spericas** [comment]
Would make sense as there were changes in that area in 2.x. Will investigate.

**Comment by spericas** [comment]
See PR #2429
