### ISSUE TITLE
Usage of raw type in public Service method

### ISSUE THREAD

**Issue by ljnelson** [oracle/helidon#242]
Before we bake the API completely, I'd like to see this method use `Routing.Rules<?>` instead of just `Routing.Rules` so we can avoid raw type warnings:

https://github.com/oracle/helidon/blob/a52d082939216e85cd6bebe8417a926e86d1f9db/webserver/webserver/src/main/java/io/helidon/webserver/Service.java#L33

I haven't checked to see if anything will break as a result.

**Comment by spericas** [comment]
We should definitely fix this. Lots of implementations too.

**Comment by tomas-langer** [comment]
The type seems useless from user's point of view. As far as I understand it, we only use Rules<Rules> in the API.
Maybe the interface we provide should not have a type parameter at all? As when using a Rules<?>, I would always wonder (as a developer of a new application), how can I get Rules<somethingElse>...

**Comment by ljnelson** [comment]
`Routing.Rules` has a type parameter whose purpose is to permit fluent chaining.  It's useful in that regard, I guess.

I like Romain's suggestion that the type of parameter supplied to `Service#update()` should be `Routing.Rules<? extends Routing.Rules>`.

**Comment by ljnelson** [comment]
Hmm, that might _still_ trigger raw warnings, come to think of it.

**Comment by spericas** [comment]
I agree with Romain's suggestion. I don't follow why that would generate warnings, though.

**Comment by ljnelson** [comment]
Because `Rules` is a parameterized type, so in `Rules<? extends Rules>` (Romain's suggestion) the last occurrence of "`Rules`" is raw.

**Comment by ljnelson** [comment]
Yes, with Romain's suggestion you get:
```
[WARNING] [snip] [unchecked] unchecked conversion
  required: Rules<? extends Rules>
  found:    Rules
```

**Comment by romain-grecourt** [comment]
Yikes, how do we solve this then ?

**Comment by ljnelson** [comment]
Working on it.  I think it's going to be something like this (don't quote me):
```
interface Rules<T extends Rules<T>>...
```
…and:
```
public <T extends Rules<T>> void update(Rules<T> rules);
```
Applying the first change is fine.  There are all sorts of various unchecked warnings etc. but this doesn't seem to add to them, nor would I expect it to.  In a vacuum, this seems proper.

Applying the second change is more problematic.  There are some test failures that have to do with `Service`'s `register` method:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:testCompile (default-testCompile) on project helidon-webserver: Compilation failure: Compilation failure: 
[ERROR] /Users/LANELSON/Projects/github/ljnelson/forks/oracle/helidon/webserver/webserver/src/test/java/io/helidon/webserver/RouteListRoutingRulesTest.java:[153,25] error: method register in class RouteListRoutingRules cannot be applied to given types;
[ERROR]   required: Service[]
[ERROR]   found: (c)->c.get[...]DLER)
[ERROR]   reason: varargs mismatch; invalid functional descriptor for lambda expression
[ERROR]       method <T>(Rules<T>)void in interface Service is generic
[ERROR]   where T is a type-variable:
[ERROR]     T extends Rules<T> declared in method <T>update(Rules<T>)
[ERROR] /Users/LANELSON/Projects/github/ljnelson/forks/oracle/helidon/webserver/webserver/src/test/java/io/helidon/webserver/RouteListRoutingRulesTest.java:[181,25] error: method register in class RouteListRoutingRules cannot be applied to given types;
[ERROR]   required: String,Service[]
[ERROR]   found: String,(c)->{ }
[ERROR]   reason: varargs mismatch; invalid functional descriptor for lambda expression
[ERROR]       method <T>(Rules<T>)void in interface Service is generic
[ERROR]   where T is a type-variable:
[ERROR]     T extends Rules<T> declared in method <T>update(Rules<T>)
```

**Comment by ljnelson** [comment]
I am guessing that the original author wanted `Service` to be a functional interface (I mean it _is_ one) and ran into the fact that when you make a functional interface method take type parameters, then [using lambdas is impossible](https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.27.3).  If you remove the type parameter and replace it with a wildcard (or raw type) of course you can use lambdas again, but now you get raw type warnings (in this case).

Muse muse muse.

**Comment by ljnelson** [comment]
OK, assuming that the usage of lambdas-instead-of-explicit-`Service` instances is more important here than anything else, I think we're best off:
1. Making the first change (`interface Rules<T extends Rules<T>>`), because that's proper and correct.
1. Changing `Service#update(Rules)` to be: `public void update(Rules<? extends Rules<?>>);`.  It's not strictly speaking correct but it is as correct as we can get without running afoul of the JLS and preserving the ability to use `Service` as a functional interface.

I'll test this out and see what the next set of hurdles is.  I'm anticipating that there might actually be problems with chaining such a type, but they can't be any worse than they are now (with a raw type).

**Comment by ljnelson** [comment]
See PR #247.

Just to close the loop on something I said above: this fix is indeed backwards compatible.

**Comment by ljnelson** [comment]
@barchetta commented that #247 made the API clunky.  So I made #248.  **These PRs are alternatives and only one of the two (if any) should be merged.**
