### ISSUE TITLE
Ensure epoll support is used when available

### ISSUE THREAD

**Issue by ljnelson** [oracle/helidon#2444]
Netty offers the ability to [use epoll when it is available](https://netty.io/wiki/native-transports.html#using-the-linux-native-transport).  We should have this, silently, in our server layer.

**Comment by dansiviter** [comment]
This will also help with Unix Domain Socket connections to K8s sidecars for a mild performance improvement.

**Comment by ljnelson** [comment]
Closing this issue because #2732 introduces an experimental epoll `Transport` implementation as a first step. Selecting it as default when available is not necessarily what we want to do, but for now at least it is available.
