### ISSUE TITLE
Examples: reorganize and cleanup

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#245]
## Environment Details
* Helidon Version: 0.10.5
* Helidon SE and Helidon MP

----------

## Problem Description
Our examples are a bit messy. They're buried under each component which makes them difficult to navigate. Plus we're missing some basic stuff. Like do we have an example that shows how to handle posted json? 

Also, the examples are not buildable in master unless you do a priming build of the workspace (due to dependency on SNAPSHOT versions). We might be stuck with that, although at least one user has complained (see #235).

The ask is to:
- [x] Consider reorganizing the examples to the top level "examples" directory. Examples are currently spread out:
    * config/examples
    * microprofile/examples
    * security/examples
    * webserver/examples
    * examples/integrations
    * examples/guides
    * examples/\*quickstarts\*
    * examples/integrations
- [x] Consider pom organization. Some of our examples intentionally have a self-contained pom (quickstarts, todo) others have a parent pom.
- [x] Makes sure all have READMEs 
- [x] Think about reconciliation with guides

**Comment by romain-grecourt** [comment]
@tomas-langer this should have been fixed already. see the "integrations" profile. Are there other examples that are broken ?

**Comment by barchetta** [comment]
The first pass of this has been merged (which includes moving all examples under the top level `examples` directory). Need to do more work on the READMEs.

**Comment by barchetta** [comment]
Also PRs #373 and #374.

This completes the first pass of examples cleanup.
