### ISSUE TITLE
Docs: MP gRPC Client states 'class' when should be 'interface'

### ISSUE THREAD

**Issue by dansiviter** [oracle/helidon#2451]
Source: https://helidon.io/docs/latest/#/mp/grpc/02_mp_clients (via [/docs/mp/grpc/02_mp_clients.adoc](https://github.com/oracle/helidon/blob/master/docs/mp/grpc/02_mp_clients.adoc))

Example:
```java
@ApplicationScoped
@io.helidon.microprofile.grpc.core.Grpc
public class StringService {  // <-- that should be interface

    @io.helidon.microprofile.grpc.core.Unary
    public void upper(String s, StreamObserver<String> response);  // <-- public not needed
}
```

There's 3 examples in the ASCIIDoc that need altering.

Also, I question that it's under the section `gRPC servers` which I think is due to [sitegen.yaml#L115](https://github.com/oracle/helidon/blob/master/docs/sitegen.yaml#L115) and [sitegen.yaml#L272](https://github.com/oracle/helidon/blob/master/docs/sitegen.yaml#L272).

**Comment by barchetta** [comment]
Fixed by PR #2457
