### ISSUE TITLE
i.h.m.t:helidon-microprofile-tests-junit5:jar:2.1.0 not in Maven Central

### ISSUE THREAD

**Issue by dansiviter** [oracle/helidon#2468]
The dependency `io.helidon.microprofile.tests:helidon-microprofile-tests-junit5:jar:2.1.0` stated in  [/docs/mp/testing/01_testing.adoc](https://github.com/oracle/helidon/blob/master/docs/mp/testing/01_testing.adoc) is not in Maven Central.

## Environment Details
* Helidon Version: 2.1.0
* Helidon SE or Helidon MP: MP
* JDK version: n/a
* OS: n/a
* Docker version (if applicable):

----------

## Problem Description
Unable to use `@HelidonTest` annotation as the dependency is not in Maven Central.

## Steps to reproduce
Use the following as a dependency:

```xml
<dependency>
    <groupId>io.helidon.microprofile.tests</groupId>
    <artifactId>helidon-microprofile-tests-junit5</artifactId>
    <version>2.1.0</version>
    <scope>test</scope>
</dependency>
```

**Comment by spericas** [comment]
@barchetta An issue with the release process?

**Comment by barchetta** [comment]
The `microprofile/tests` module is not deployed:

```
        <maven.deploy.skip>true</maven.deploy.skip>
```

We need to decide what under here should be deployed.

**Comment by romain-grecourt** [comment]
Fixed in https://github.com/oracle/helidon/pull/2476
