### ISSUE TITLE
Upgrade GraalVM

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#2477]
## Problem Description
Upgrade GraalVM to 20.1.1 or newer.

**Comment by tomas-langer** [comment]
Check if 20.2.0 is backward compatible with 20.1.x release. If so, use 20.2, otherwise use 20.1.x latest.

**Comment by spericas** [comment]
Found some issues with 20.2.0 and our quickstart-mp on Mac. Someone else should double check this.
