### ISSUE TITLE
KeyManagerFactory should not hardcode JKS keystore type

### ISSUE THREAD

**Issue by scottoaks17** [oracle/helidon#2481]
## Environment Details
* Helidon Version: 2.1.0
* Helidon SE or Helidon MP: MP
* JDK version: 11.0.7
* OS: Linux
* Docker version (if applicable): N/A

----------

## Problem Description
I am trying to run Helidon in SSL mode with a third-party security provider. (Running with the standard JSSE provider is fine.) The security provide requires that the keystore used to initialize the SSL context is of a format provided by that security provider.

Current implementation of KeyManagerFactory doesn't support that; it hardcodes the keystore type that it creates from the private key file:
private static KeyManagerFactory buildKmf(KeyConfig privateKeyConfig) throws IOException, GeneralSecurityException {
            ....
            KeyStore ks = KeyStore.getInstance("JKS");
            ....
}

This should be configurable like all the other SSL configuration properties. Replacing this with the desired keystore type allows the third-party provider to work properly. (And technically, there's no assurance that the JKS provider is installed in a particular JVM anyway.)

**Comment by tomas-langer** [comment]
`WebServerTls` in WebServer, and `SslContextBuilder` in gRPC

**Comment by tomas-langer** [comment]
@scottoaks17 - Is it sufficient to use the default keystore type of the current environment for your security provider?

Such as:
```java
KeyStore ks = KeyStore.getInstance(KeyStore.getDefaultType());
```

The keystore is only used to initialize the key manager factory - not really something I would like to expose through configuration. So if the above code is sufficient, I would modify it.

**Comment by tomas-langer** [comment]
Please see the referenced PR

**Comment by tomas-langer** [comment]
I have merged the change. Please feel free to come back to us if this fix is not sufficient. The default keystore is configurable through Java security.
