### ISSUE TITLE
Create a proposal for grpc / protobuf support

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon#251]
Create a proposal to support protobuf in helidon-webserver.

Protobuf can be very valuable when implementing low-latency services that aren't exposed on their own as a REST API.

This can be useful for services that are consumed by serverless functions. Considering the short-lived and stateless paradigm of a function, any callout to an external service should be low latency and there is certainly no need to talk JSON.

Netty has support for protobuf already, thus we should be able to support receiving and sending protobuf messages with the helidon webserver. This will likely involve enabling the experimental HTTP2 support. We will also want to separate the netty-protobuf support for packaging purpose (i.e make it optional).

We can also look at supporting rpc services annotated with http options (see https://github.com/googleapis/googleapis/blob/master/google/api/http.proto). This would be done by generating java code for the services with a protoc plugin. We may also want to investigate a mechanism to expose these services as JSON easily.

The grpc support seems rather "nice to have", we could chose to do it in a separate phase.

**Comment by tomas-langer** [comment]
This is already done as part of Helidon gRPC
