### ISSUE TITLE
No parser configured for application.yaml

### ISSUE THREAD

**Issue by joaofouyer** [oracle/helidon#2561]
## Environment Details
* Helidon Version: 2.1.0
* Helidon SE
* JDK version: 11
* OS: Linux
----------

## Problem Description
The settings are loaded correctly when using `application.properties`. But when I try to use `application.yaml` (which is preferable for me), the settings are not loaded and the following warning is shown: `WARNING io.helidon.config.MetaConfigFinder Thread[main,5,main]: Configuration file application.yaml is on classpath, yet there is no parser configured for it`.

It's not clear to me if I need to inject a depency to parse yaml, like [Snake YAML](https://mvnrepository.com/artifact/org.yaml/snakeyaml) or if it's related to a known issue #1596

## Steps to reproduce
 In both cases (application.properties, wich works nice! and application.yaml ), are under ` /src/main/resources` and loaded in the Main Class `Config config = Config.create();`.

**Comment by spericas** [comment]
Do you have this dependency?

```
        <dependency>
            <groupId>io.helidon.config</groupId>
            <artifactId>helidon-config-yaml</artifactId>
        </dependency>
```

**Comment by joaofouyer** [comment]
I do, altough I'm using Gradle. But now that you reminded me, I checkend and it was as testCompile, since I just pasted from Maven Repository. I fix'd now (changed to compile).
