### ISSUE TITLE
Documentation for CDI extensions

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon#260]

**Comment by barchetta** [comment]
Probably want a new section for "CDI Extensions": https://helidon.io/docs/latest/

**Comment by kumar-dhanagopal** [comment]
@ljnelson - Hi Laird, while looking through the tech resources to plan the doc for CDI extensions, I noticed that the package names don't follow a consistent pattern w.r.t the placement of "cdi":

io.helidon.integrations.datasource.hikaricp.cdi
io.helidon.integrations.cdi.oci.objectstorage
io.helidon.integrations.jedis.cdi

The name used for the OCI object-storage package appears to be more logical to me.

Your thoughts?

**Comment by ljnelson** [comment]
That's an excellent point; let me think about ramifications, but yes, these should be unified one way or the other IMHO.

**Comment by kumar-dhanagopal** [comment]
@ljnelson - Could you pls review the outline I've proposed here: https://github.com/oracle/helidon/wiki/Helidon-CDI-extensions---doc-outline ?

**Comment by romain-grecourt** [comment]
@kumar-dhanagopal for temporary docs, prefer https://gist.github.com/ over wiki pages.

**Comment by ljnelson** [comment]
Hi, @kumar-dhanagopal; I think this looks fine.  You may find that the headings "How the extension works" end up repeating each other a fair amount, and hence might be able to be consolidated up front.  What I mean is, in general each extension works by driving the mutable aspects of a given client's behavior down into configuration—for each such extension, therefore, you supply the right extension-specific configuration and it is applied to the client that you ultimately inject, i.e. all extensions work the same way in this regard.

**Comment by kumar-dhanagopal** [comment]
> 
> 
> @kumar-dhanagopal for temporary docs, prefer https://gist.github.com/ over wiki pages.

Sure @romain-grecourt . I'll keep that in mind for the future.

**Comment by kumar-dhanagopal** [comment]
> ... You may find that the headings "How the extension works" end up repeating each other a fair amount, and hence might be able to be consolidated up front. What I mean is, in general each extension works by driving the mutable aspects of a given client's behavior down into configuration—for each such extension, therefore, you supply the right extension-specific configuration and it is applied to the client that you ultimately inject, i.e. all extensions work the same way in this regard.

Thanks @ljnelson ! I agree. As I write the content, I'll adjust the structure to avoid repeating content.

**Comment by ljnelson** [comment]
Ah!  Strictly speaking, yes, but I see that it can be unclear (i.e. it looks like these two examples should belong together).  I'll make the change.

**Comment by kumar-dhanagopal** [comment]
@romain-grecourt, @ljnelson  - Hi Romain, Laird,  now that https://github.com/oracle/helidon/blob/master/docs/src/main/docs/cdi-extensions.adoc is ready, how do we surface it on the helidon.io/docs site ?

**Comment by barchetta** [comment]
Yes. A top level menu entry sounds good to me.

**Comment by kumar-dhanagopal** [comment]
Here's what I think needs to be done. **Please confirm.**

1. Move cdi-exensions.adoc from ...docs/src/main/docs/ to helidon/docs/src/main/docs/extensions/

2. In ...docs/src/main/docs/sitegen.yaml, add the following after the "Microprofile" node:

```
- title: "Exensions"
  pathprefix: "/extensions"
  glyph:
    type: "icon"
    value: "widgets"
  items:
    -  includes:
         - "extensions/*.adoc"
```

Btw, **would the title "Integrations" be more appropriate than "Extensions" ?**

**Comment by romain-grecourt** [comment]
These steps are correct.

We need to decide of an icon and the order in the menu. I'd vote for putting it between security and microprofile.

You can pick any icon from https://material.io/tools/icons - E.g. https://material.io/tools/icons/?icon=extension&style=baseline

**Comment by kumar-dhanagopal** [comment]
If CDI extensions are specific to MP, then could we simply move this doc under the existing **Microprofile** node, with the title "Using CDI Extensions"?  

A separate **Extensions** node at the top level would make this content more visible. But the left nav-pane would become just a little longer, and I'm guessing we'll add more in the future.

**Comment by barchetta** [comment]
For whatever reason I too slightly prefer "Extensions".

I'm OK with it top level or under MicroProfile.

FYI #304 will add three more top level items (Metrics, Tracing, Health Checks).

**Comment by kumar-dhanagopal** [comment]
> FYI #304 will add three more top level items (Metrics, Tracing, Health Checks).

I suggest we keep Extensions under MicroProfile then.

**Comment by romain-grecourt** [comment]
CDI is not limited exclusively to Helidon-MP. Also, we may have extensions that are not CDI based.
Microprofile being a set of specifications, having extensions nested there feels odd.

**Comment by ljnelson** [comment]
I am mostly neutral on the issue.  I guess I'd slightly prefer a top-level Extensions section.

**Comment by kumar-dhanagopal** [comment]
@ljnelson - I'll put this doc under an Extensions node then. Thank you!

**Comment by kumar-dhanagopal** [comment]
See https://github.com/oracle/helidon/pull/355/files
