### ISSUE TITLE
Documentation Helidon MP : Main class does not exist anymore into quickstart example 

### ISSUE THREAD

**Issue by tvallin** [oracle/helidon#2600]
While following Helidon MP Config Guide: 

Into Default Configuration section. there is View Main.startServer. But there is no Main class.

REPRODUCER:
```
mvn -U archetype:generate -DinteractiveMode=false \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-quickstart-mp \
    -DarchetypeVersion=2.1.1-SNAPSHOT \
    -DgroupId=io.helidon.examples \
    -DartifactId=helidon-quickstart-mp \
    -Dpackage=io.helidon.examples.quickstart.mp
```

It contains GreetResource and GreetingProvider class only. 

NOTE:
The mp-tutorial guide which explain how to build a Helidon MicroProfile application very similar than the quickstart has a Main class and the configuration guide is appropriate.

**Comment by TomYipOracle** [comment]
Technically, your own main class is not needed unless you want to control the startup sequence. You can set the mainClass property to io.helidon.microprofile.cdi.Main and it will use Helidon’s default main class.

Source: https://helidon.io/docs/latest/#/mp/guides/10_mp-tutorial
