### ISSUE TITLE
HTTP Client

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#261]
Investigate the HTTP Client in JDK 11 and ways we could integrate it with Helidon. Some items to investigate:

- Compile vs runtime dependencies: how can we continue to support Java 8 (with no Java 11 HTTP client) and Java 11 (with Java 11 HTTP client)?
- Integrate with Helidon WebServer: are there things we can do (like helper classes?) to make it more convenient to use the Java 11 HTTP client with Helidon? Can we simplify context/header/tracing propogation?

**Comment by tomas-langer** [comment]
See other clients (such as Unirest) to evaluate

**Comment by tomas-langer** [comment]
Investigating Netty client.
API under design.
Full support for automated propagation of security and tracing when running within Helidon servers (web server, gRPC server and future messaging)
Support for metrics through configuration and registration

**Comment by m0mus** [comment]
Investigation is finished. It makes sense crating our own Web Client in Helidon SE.
