### ISSUE TITLE
Documentation Helidon SE/MP: Multi-stage Docker build fails

### ISSUE THREAD

**Issue by tvallin** [oracle/helidon#2613]
The command `docker build -t helidon-quickstart-se-jri -f Dockerfile.jlink .` from Custom Runtime Images with jlink guide fails.

REPRODUCER:
```
mvn -U archetype:generate -DinteractiveMode=false \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-quickstart-se \
    -DarchetypeVersion=2.1.1-SNAPSHOT \
    -DgroupId=io.helidon.examples \
    -DartifactId=helidon-quickstart-se \
    -Dpackage=io.helidon.examples.quickstart.se

mvn package -Pjlink-image

docker build -t helidon-quickstart-se-jri -f Dockerfile.jlink .
```

Exception:
`COPY failed: stat helidon/target/helidon-quickstart-se: file does not exist`

Note:
It tries to copy helidon-quickstart-se which does not exist as it created helidon-quickstart-se-jri.
To fix this I replaced this line into Dockerfile.jlink file:
`COPY --from=build /helidon/target/helidon-quickstart-se ./`
by 
`COPY --from=build /helidon/target/helidon-quickstart-se-jri ./`

**Comment by batsatt** [comment]
I'm pretty sure this has been fixed: the `Dockerfile.jlink` files were updated by #2469.

**Comment by batsatt** [comment]
Oh, sorry, I see: you are correct that the _documentation_ is wrong: both oft he Dockerfile.jlink.**mustache** files need to be updated:

```
find archetypes -name "Dockerfile.jlink*" | grep -v target | xargs grep COPY

archetypes/quickstart-mp/src/main/resources/Dockerfile.jlink.mustache:COPY --from=build /helidon/target/{{artifactId}} ./
archetypes/quickstart-se/src/main/resources/Dockerfile.jlink.mustache:COPY --from=build /helidon/target/{{artifactId}} ./
```
