### ISSUE TITLE
JPA: drop-and-create schema generation action failed

### ISSUE THREAD

**Issue by hantsy** [oracle/helidon#2630]
I tried to update my sample application to the latest Helidon 2.2 from 1.3. But failed. The application failed to start.

[Sample codes](https://github.com/hantsy/helidon-sample/tree/master/mp-jpa)

## Environment Details
* Helidon Version: 2.2
* Helidon MP
* JDK version: 11
* OS: Windows
* Docker version (if applicable): 3.0

## Description

When setting the **javax.persistence.schema-generation.database.action** to **drop-and-create**, it did not work as expected. 

The table generation failed and the application failed to start. 

I attached a copy of the log from the console.

[app.log](https://github.com/oracle/helidon/files/5739475/app.log)

And in the Postgres database Docker console, there are some errors.

```bash
postgres_1  | 2020-12-24 11:42:27.444 UTC [73] STATEMENT:  CREATE TABLE comments (ID VARCHAR(255) NOT NULL, CONTENT VARCHAR(255), created_at VARCHAR(255), post_id VARCHAR(255), PRIMARY KEY (ID))
postgres_1  | 2020-12-24 11:42:27.456 UTC [73] ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgres_1  | 2020-12-24 11:42:27.456 UTC [73] STATEMENT:  SELECT 1
postgres_1  | 2020-12-24 11:42:27.523 UTC [73] ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgres_1  | 2020-12-24 11:42:27.523 UTC [73] STATEMENT:  INSERT INTO posts (ID, CONTENT, created_at, STATUS, TITLE) VALUES ($1, $2, $3, $4, $5)
postgres_1  | 2020-12-24 11:42:27.525 UTC [73] ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgres_1  | 2020-12-24 11:42:27.525 UTC [73] STATEMENT:  SELECT 1
postgres_1  | 2020-12-24 11:46:10.519 UTC [89] ERROR:  table "posts" does not exist
postgres_1  | 2020-12-24 11:46:10.519 UTC [89] STATEMENT:  DROP TABLE posts CASCADE
postgres_1  | 2020-12-24 11:46:10.534 UTC [89] ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgres_1  | 2020-12-24 11:46:10.534 UTC [89] STATEMENT:  SELECT 1
postgres_1  | 2020-12-24 11:46:10.553 UTC [89] ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgres_1  | 2020-12-24 11:46:10.553 UTC [89] STATEMENT:  DROP TABLE comments CASCADE
postgres_1  | 2020-12-24 11:46:10.565 UTC [89] ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgres_1  | 2020-12-24 11:46:10.565 UTC [89] STATEMENT:  SELECT 1
postgres_1  | 2020-12-24 11:46:10.573 UTC [89] ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgres_1  | 2020-12-24 11:46:10.573 UTC [89] STATEMENT:  DROP TABLE posts CASCADE
postgres_1  | 2020-12-24 11:46:10.576 UTC [89] ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgres_1  | 2020-12-24 11:46:10.576 UTC [89] STATEMENT:  SELECT 1
```

There is a `CREATE TABLE comments (ID VARCHAR(255) NOT NULL, CONTENT VARCHAR(255), created_at VARCHAR(255), post_id VARCHAR(255), PRIMARY KEY (ID))` in the log, 

The `LocalDateTime` is converted to `varchar`, which is also not my expectation.

**Comment by ljnelson** [comment]
I see from your sample project that you _do_ have that property set.  It seems like perhaps it is not being seen or read, because I think deployment should be happening considerably earlier than this if it were.  I'll look more at this, though this is under the control of Eclipselink, not Helidon.

**Comment by hantsy** [comment]
@ljnelson You have to know this sample is upgraded from an earlier **working** version.

**Comment by ljnelson** [comment]
Returning to the issue at hand, there was a lot of work in the transactions/JTA area that solved other problems.  I'm guessing that in fixing those problems, lazy initialization of the `EntityManagerFactory` ended up being problematic.

If you have a feature request, do kindly file an issue about it; we're happy to help.

**Comment by ljnelson** [comment]
I've confirmed that eagerly "inflating" the `EntityManagerFactory` client proxies at startup fixes the transaction problem.  Now when I run your sample code against an appropriately configured Postgres database, I get this:
```
org.glassfish.jersey.server.model.ModelValidationException: 
Validation of the application resource model has failed during application initialization.
[[FATAL] No injection source found for a parameter of type public javax.ws.rs.core.Response com.example.PostResource.savePost(com.example.Post,javax.ws.rs.core.UriInfo) at index 0.; source='ResourceMethod{httpMethod=POST, consumedTypes=[application/json], producedTypes=[], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class com.example.PostResource, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@44c2e8a8]}, definitionMethod=public javax.ws.rs.core.Response com.example.PostResource.savePost(com.example.Post,javax.ws.rs.core.UriInfo), parameters=[Parameter [type=class com.example.Post, source=null, defaultValue=null], Parameter [type=interface javax.ws.rs.core.UriInfo, source=null, defaultValue=null]], responseType=class javax.ws.rs.core.Response}, nameBindings=[]}']
```
That seems to be a different problem entirely.

I will submit a pull request soon to fix the `EntityManagerFactory` initialization problem.

**Comment by ljnelson** [comment]
Good news; with https://github.com/hantsy/helidon-sandbox/pull/1 and a resolution for #3009 your `mp-jpa` project works.

I'll submit a PR for #3009 soon.

I will also submit a PR against your sample code to work around this problem in the meantime (it should be an easy fix).

**Comment by ljnelson** [comment]
I've also posted https://github.com/hantsy/helidon-sandbox/pull/2.  If you apply https://github.com/hantsy/helidon-sandbox/pull/2 and https://github.com/hantsy/helidon-sandbox/pull/1, your project works (tested with (Helidon-supported) JDK 11).

**Comment by hantsy** [comment]
Thanks @ljnelson , finally got it working on Java 16.
