### ISSUE TITLE
Improve support for serving SPAs with Client-Side Routing

### ISSUE THREAD

**Issue by zimmi** [oracle/helidon#2631]
## Environment Details
* Helidon Version: 2.2.0
* Helidon SE
* JDK version: openjdk 15.0.1 2020-10-20
* OS: debian

----------

## Problem Description

Single Page Applications (SPAs) often implement routing (e.g. clicks on links) by manipulating the URL path client side through browser APIs without sending requests to the server. The first request (or page refreshes) will go through to the server however, so a request to `/todos/12` should return the entry point into the application. See for example the [React docs](https://create-react-app.dev/docs/deployment/#serving-apps-with-client-side-routing) for this.

`StaticContentSupport` makes this a little awkward: The entry point for a React SPA is `index.html`. The Helidon app has to return `index.html` for every requested path, but those are not known in advance (e.g. invalid paths will be handled by the SPA), so duplicating `index.html` doesn't work. `StaticContentSupport` will next the request, leaving the developer to do the file handling, not benefitting from the caching and other optimizations in  `StaticContentSupport` / `ClassPathContentHandler`.

One straightforward solution would be to allow setting a fallback file, that gets sent when there was no matching file for the requested path:

```java
var staticContent = StaticContentSupport.builder("META-INF/frontend", ClassLoader.getSystemClassLoader())
    .welcomeFileName("index.html")
    // If the requested file wasn't found, use this one instead of nexting the request
    .fallbackFile("/index.html")
    .build();
```

Another solution would be to allow server side redirects like [`RequestDispatcher::forward`](https://javadoc.io/doc/jakarta.servlet/jakarta.servlet-api/latest/jakarta/servlet/RequestDispatcher.html#forward-jakarta.servlet.ServletRequest-jakarta.servlet.ServletResponse-), but that's overkill here, IMO.

**Comment by tomas-langer** [comment]
Hello,
 could you solve this problem with a sequence of content supports? 

Example:
```java
var staticContentFrontend = StaticContentSupport.builder("META-INF/frontend", ClassLoader.getSystemClassLoader())
    .welcomeFileName("index.html")
    // If the requested file wasn't found, use this one instead of nexting the request
    .fallbackFile("/index.html")
    .build();
var staticContentFallback = StaticContentSupport.builder("/").welcomeFileName("index.html").build();

Routing.builder()
 .register("/static", staticContentFrontend)
 .register("/static", staticContentFallback)
...
```

As the static content is not returning a 404, rather calls `.next()`, this should work fine. Also it would not require support for "fallback of fallback"  - you can use as many as you want.

**Comment by zimmi** [comment]
Thanks for taking the time @tomas-langer !

I'm afraid I don't quite understand your example: `fallbackFile` was my proposed addition, right now only the `welcomeFileName` is configurable. Leaving that out, the following remains (serving static files at `/`):

```java
var staticContentFrontend = StaticContentSupport.builder("META-INF/frontend", ClassLoader.getSystemClassLoader())
    .welcomeFileName("index.html")
    .build();
// The path passed to builder() is the resource root in the classpath, which is META-INF/frontent in this example
var staticContentFallback = StaticContentSupport.builder("META-INF/frontend", ClassLoader.getSystemClassLoader())
    .welcomeFileName("index.html")
    .build();

Routing.builder()
 .register("/", staticContentFrontend)
 .register("/", staticContentFallback)
```
If a request for `/foo/1` comes in, `staticContentFrontend` would neither find `META-INF/frontend/foo/1` nor `META-INF/frontend/foo/1/index.html`. Then `staticContentFallback` tries the same thing (request path hasn't changed) and fails again.

To clarify what I want:

Given following files:
- META-INF/frontend
  - index.html
  - other.txt
  - foo
    - index.html

Request | Served File
--- | ---
/ | META-INF/frontend/index.html
/other.txt | META-INF/frontend/other.txt
/foo | META-INF/frontend/foo/index.html (not strictly required to have this for SPAs)
/foo/1 | META-INF/frontend/index.html
/unknown | META-INF/frontend/index.html

It'd be equally fine if there was a way to configure `StaticContentSupport` to serve the same file for every request path, but I couldn't find a way to do it. If that was possible, that could be the `staticContentFallback` in the example above.

My PR switched `fallbackFile` to `fallbackPath` because it allows the user to only specify the welcome file name once: If the requested file is not found, it's as if `/` was requested instead. I'm happy with every solution that solves the problem, it doesn't have to be that one. :)

**Comment by romain-grecourt** [comment]
@tomas-langer This could be done with WebServer routing by adding a later route that matches any path and always serves the index.html. There is no clean way to do this with Helidon currently.

This is a Single Page Application specific scenario (SPA), where routing is actually done with Javascript and the backend should serve the static content regardless of the actual request. In other words if the path maps to a file serve the file, if not serve index.html.

This can be done with nginx with a configuration like this:
```
server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri /index.html;
    }

    # redirect server error pages to the static page /50x.html
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
```

**Comment by zimmi** [comment]
Turns out this is possible:

```java
var staticContent = StaticContentSupport.builder("META-INF/frontend", ClassLoader.getSystemClassLoader())
    .welcomeFileName("index.html")
    .build();

Routing.builder()
    .register(staticContent)
    // "eat" the whole request path so staticContent only sees /
    .register("/{+all}", staticContent)
```

I'll close the PR if you don't mind, this is much cleaner IMO. Good talk. :)

@romain-grecourt The nginx config is probably the best solution for more "serious" deployments (better performance, allows separate deployment etc.). I'm fine with the "fat runtime image with everything in it" approach for now. Good to have it documented here though!

Now the only thing that's bothering me is the trailing slashes (`/foo/1/ `). I'll open another issue if it becomes an issue with client side routing. Thanks again!

**Comment by romain-grecourt** [comment]
@tomas-langer can you add a snippet here to describe how to solve this with the changes you've made?, thanks.

**Comment by tomas-langer** [comment]
```java
// static content reading from classpath location "web"
        StaticContentSupport staticContent = StaticContentSupport.builder("web")
                .welcomeFileName("index.html")
                .build();
        // fallback always returns "web/index.html" for any request
        StaticContentSupport fallback = StaticContentSupport.builder("web")
                .pathMapper(path -> "index.html")
                .build();
        
        Routing.builder()
                .register(staticContent)
                .register(myBusinessService)
                .register(fallback);
```
