### ISSUE TITLE
Fault Tolerance 3.0

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon#2641]
- [ ] Fault Tolerance 3.0 support
- [ ] Documentation
- [ ] Samples
- [ ] Guides

MicroProfile 4.0 support epic: #2636

**Comment by spericas** [comment]
Changes in FT 3.0:

- [ ] Lifecycle of circuit breakers
- [ ] Changes related to Jakarta EE dependencies
- [ ] `@Asynchronous` test related to security/naming context
- [ ] Changes to metrics and scopes

**Comment by spericas** [comment]
PR #2680
