### ISSUE TITLE
application.yaml config source in MP has 100 ordinal by default

### ISSUE THREAD

**Issue by ljnelson** [oracle/helidon#2652]
When the Helidon MP server is started, `application.yaml` is picked up as one of the default MicroProfile Config configuration sources (by virtue of the fact that [`YamlMpConfigSourceProvider`](https://github.com/oracle/helidon/blob/master/config/yaml/src/main/java/io/helidon/config/yaml/YamlMpConfigSourceProvider.java) is included on the classpath, together with its [service provider file](https://github.com/oracle/helidon/blob/master/config/yaml/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSourceProvider), [by default](https://github.com/oracle/helidon/blob/9362b7d0033a5af698ef2658965bc3024877ad00/examples/microprofile/hello-world-implicit/pom.xml#L39-L42)).  This is a Helidon "value-add" and so far so good.

The `org.eclipse.microprofile.config.ConfigSource` that is added automatically to represent this classpath resource does not define an ordinal, so it gets the default ordinal, [which is `100`](https://javadoc.io/static/org.eclipse.microprofile.config/microprofile-config-api/1.4/org/eclipse/microprofile/config/spi/ConfigSource.html#DEFAULT_ORDINAL).

This means that by default it is undefined which of the two `META-INF/microprofile-config.properties` or `application.yaml` classpath resources will "win".  A value found in `application.yaml` might override a value found in `META-INF/microprofile-config.properties`, or vice versa.

Probably the `YamlMpConfigSource` should have a default ordinal of `101` or `200` or something like that to (a) come "under" system properties and environment variables but "above" `META-INF/microprofile-config.properties`, which of course is expected to be the source of last-ditch fallback values.

**Comment by ljnelson** [comment]
I seem to recall that the return value of `org.eclipse.microprofile.config.spi.ConfigSource#getName()` is used as a "tiebreaker" for sorting purposes, but the specification does not mandate any rules for what this method must or must not return, so we may be getting lucky here, i.e. I'm guessing that `YamlMpConfigSource` probably returns something like "`application.yaml`" from its `getName()` method, and probably the `org.eclipse.microprofile.config.spi.ConfigSource` that represents `META-INF/microprofile-config.properties` probably returns something starting with "`M`" or "`m`", and so by luck `application.yaml` resources will "come first".  We should make this more explicit IMHO.

**Comment by ljnelson** [comment]
Following up with a few more details and/or summary:
* Running our `hello-world-implicit` example results in four MP `ConfigSource`s: environment variables, system properties, `application.yaml` and `META-INF/microprofile-config.properties`.
* The last two sources both have an effective ordinal of `100`.  Nevertheless there is total ordering because `getName()` returns something different in both cases.
* Only jar files are likely to have `META-INF/microprofile-config.properties` inside them.  `application.yaml` is often found outside a jar file.
* Users can of course put `config_ordinal` in any MP `ConfigSource` they choose to make ordering explicit.

**Comment by tomas-langer** [comment]
The config ordinal is intentionally the same, as we treat both `application.yaml` and `META-INF/microprofile-config.properties` as default config sources in Helidon applications.

You can override `config_ordinal` in a configuration file to increase/decrease its weight.
The config source only reads `application.yaml` from classpath by default.
If you want to read a file, you would need to call one of the factory methods on `YamlMpConfigSource`. 

I think we may want to add a builder to `YamlMpConfigSource` that would allow customization of ordinal of the config source. I do not see a reason to modify the automated discovery of `application.yaml` from classpath.
If we agree on this, we can create another issue to "Allow custom ordinal for YAML MP Config Source".

We may also add automated discovery of `application.yaml` from a file system, though that would require a lot more work and may result in unexpected behavior. In this case I would agree that a different ordinal should be used with a higher priority than the default config source.

**Comment by tomas-langer** [comment]
To make this absolutely clear - you should not define the same properties in `application.yaml` and in `META-INF/microprofile-config.properties`. This is a Helidon specific way, which allows you to choose between these two files, or to merge their content (especially useful for Security configuration, which is a tree structure and is really hard to define in a properties file).

**Comment by tomas-langer** [comment]
I am closing this issue, as the current behavior is explained.
