### ISSUE TITLE
meta-config.yaml with Helidon MP causes environment variable overriding rules to not work

### ISSUE THREAD

**Issue by ljnelson** [oracle/helidon#2653]
A user reported this behavior and I can confirm it.  I don't know if it's a bug or not, nor do I know offhand what should be done.  I am capturing it here.

When `meta-config.yaml` is on the classpath of a Helidon MP application, it is taken to be the one true source of configuration sources.  Underneath the covers, its presence causes a Helidon SE `Config` to be used as a single MicroProfile Config `ConfigSource`.  When this happens, MicroProfile Config-defined environment variable overriding rules appear not to always apply.

For example, assuming `meta-config.yaml` arranges for `application.yaml` to be included as a configuration source, a property of `camelCase : no` cannot be overridden to have a value of `yes` by setting an environment variable named `CAMELCASE` to `yes`.

Obviously since `meta-config.yaml` is a Helidon "value-add" when it is used you can make an argument that MicroProfile Config-specification-defined rules need not be followed.  On the other hand, users might reasonably be expected to have MicroProfile Config expectations around these rules.

**Comment by tomas-langer** [comment]
`meta-config.yaml` is not a MicroProfile (MP) Config feature - there is no such support in MP specification.
If such a file exists, we expect the user to want Helidon Config behavior. As the meta configuration is using only Helidon SE config sources, it cannot be applied to MP config.

If you use `meta-config.yaml` you would get Helidon SE Config behavior for environment variables, system properties and all other config sources (including support for retries, polling, file watching etc.).

If you use MP Config only, you would get support for `microprofile-config.properties`, `application.yaml` and for your own configuration sources implementation.


Until MP Config adopts something like meta configuration, we cannot really merge these two styles, as they are not compatible. We could come up with our own "MP Meta Config", but then we put ourselves in danger if a similar feature becomes part of MP Config.

**Comment by tomas-langer** [comment]
Nevertheless we may want to add documentation to make this clear to our docs.

**Comment by tomas-langer** [comment]
Related to #1737 - if we decide to do meta config for MP, this issue would be resolved

**Comment by ljnelson** [comment]
Closing due to presence of "works as designed" label
