### ISSUE TITLE
combine webserver and webserver-netty

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon#268]
Merge webserver and webserver-netty and remove the webserver SPI.

Before doing so, investigate netty5 and wether we would benefit from having the webserver SPI around in order to support both netty4 and netty5.

**Comment by romain-grecourt** [comment]
@tomas-langer @barchetta I've targeted this to 1.0, let me know if you are okay with it.

**Comment by barchetta** [comment]
I don't see this as a must-have for 1.0 since it won't change any public APIs.

**Comment by romain-grecourt** [comment]
It's going to remove a dependency and impact the pom files.

**Comment by stekylsha** [comment]
I realize this is really late, by six months, but I was wondering why the change to a hard dependency on netty? This seems rather antithetical to the rest of the framework (apologies for using that word) which lets you choose only the pieces you want/need. Was this a performance issue or just simplifying? 

It seems there are a number of other reactive servers available. I didn't see an issue open for supporting others, but is that a long term goal?
