### ISSUE TITLE
Datasource not created with custom yaml file - works with META-INF/microprofile-config.properties  

### ISSUE THREAD

**Issue by rossano-lunardi** [oracle/helidon#2682]
## Environment Details
* Helidon Version: 2.2.0
* Helidon MP
* JDK version: jdk11.0.6_10
* OS: Windows 10
* Docker version (if applicable):

It seems the same issue of 
https://github.com/oracle/helidon/issues/2115

If we use a custom yaml config we get this error

org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type DataSource with qualifiers @'Named' 

while if we copy the same properties in 
META-INF/microprofile-config.properties 
the datasource is created and injected

**Comment by ljnelson** [comment]
I'd like to learn more.  What do you mean by "custom yaml config"?  Do you mean `application.yaml` on the classpath (which is supported by Helidon and so is not custom) or do you mean that a `ConfigSource` that you have written is not doing something you want?

**Comment by rossano-lunardi** [comment]
Hi @ljnelson 

thank you for your prompt reply

We mean the second you said but let's show some code to make it clearer

This is how we create the ConfigSources poiting to our custom yaml config
 
		this.config = Config.builder().sources(
				ConfigSources.classpath(appEnv.name().toLowerCase() + "_" + "config.yaml"))
				.build();

and then we use it to create a Server

			final Server server = Server.builder().config(config).addApplication(restApplicationClass).build().start();

src/main/resources/local_config.yaml is the yaml file where we define the datasource properties 

javax.sql.DataSource.ox.dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
javax.sql.DataSource.ox.dataSource.url: jdbc:postgresql://factorynew....
javax.sql.DataSource.ox.dataSource.user: user
javax.sql.DataSource.ox.dataSource.password: password

when we start we get this error 

org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type DataSource with qualifiers @Named
  at injection point [BackedAnnotatedField] @Inject @Named private it.vegans.common.resource.jdbc.JDBCResource.dataSource

******************

If we move those properties to src/main/resources/META-INF/microprofile-config.properties

javax.sql.DataSource.ox.dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
javax.sql.DataSource.ox.dataSource.url=jdbc:postgresql://factorynew...
javax.sql.DataSource.ox.dataSource.user=user
javax.sql.DataSource.ox.dataSource.password=password


		this.config = Config.builder().sources(
				ConfigSources.classpath("META-INF/microprofile-config.properties"), 
				ConfigSources.classpath(appEnv.name().toLowerCase() + "_" + "config.yaml"))
				.build();

the Server starts fine

We are migrating from Helidon 1.4.7, we've read the migration and configuration guide and it seems our code is still supported
but maybe we are missing something...

**Comment by ljnelson** [comment]
That's interesting.  You're using [Helidon's configuration system](https://helidon.io/docs/v2/#/se/config/01_introduction), not [MicroProfile's](https://helidon.io/docs/v2/#/mp/config/01_introduction), but you're using Helidon MP.  That is slightly odd, but it should work, I would think.  I know, for example, that the [data source extension that provides `DataSource` injection](https://github.com/oracle/helidon/tree/master/integrations/cdi/datasource-hikaricp) is written to assume nothing other than a MicroProfile environment.  There is a fair amount of code in the Helidon implementation of MicroProfile Config that tries to make the Helidon configuration system "show up" quietly in the MicroProfile Config configuration system.  Perhaps there is something in there that is not working properly.  I'll take a look.

A better approach in general when using Helidon MP is not to declare your configuration sources up front at all.  The whole point of MicroProfile Config is that if a MicroProfile `ConfigSource` is on the classpath, it just shows up.  You can read more about this area of the MicroProfile Config specification here: https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configsources.asciidoc

You also appear to be trying to provide Spring-like configuration profiles.  Just so you know, profiles are available in MicroProfile Config 2.0, which will be supported by a major release of Helidon in the future.

My recommendation overall here would be:
* Start the server following one of our examples.  I would recommend the [hello world implicit one](https://github.com/oracle/helidon/tree/master/examples/microprofile/hello-world-implicit).
* Write a [`ConfigSource` implementation](https://javadoc.io/doc/org.eclipse.microprofile.config/microprofile-config-api/1.4/org/eclipse/microprofile/config/spi/ConfigSource.html).  Or, in your case, maybe write a [`ConfigSourceProvider`](https://javadoc.io/doc/org.eclipse.microprofile.config/microprofile-config-api/1.4/org/eclipse/microprofile/config/spi/ConfigSourceProvider.html) implementation that handles all the profile stuff for you.  Put it on the classpath.
* In the actual YAML files (or properties files, or whatever), you can [set `config_ordinal` values to explicitly control ordering](https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configsources.asciidoc#manually-defining-the-ordinal-of-a-built-in-configsource).

You'll note, too, that if you follow the "hello world implicit" example there's no need, either, to explicitly register your JAX-RS application.  In general, Helidon MP works by your simply placing things on the classpath and running the main class.

**Comment by rossano-lunardi** [comment]
Hi @ljnelson,

here we are again, just to notify that we could migrate to Helidon 2.2.0
Indeed we were trying something that should be supported in Helidon MP too, see "Custom configuration sources" in this guide
https://helidon.io/docs/v2/#/mp/guides/03_config

Anyway we decided to follow your recommendation and walk on the "main MP path":

- we implemented a ConfigSourceProvider for our custom yaml file
- then we wrapped the "MP main call" in our main class, doing our additional configurations after the application start

Now the datasource is correctly created and injected
Thanks again for your advice  :-)

**Comment by ljnelson** [comment]
I'm glad to hear this.  I'm also going to guess that you don't need a main class! 😄   As a hint, in Helidon MP, JAX-RS applications are automatically registered if they're found on the classpath.

**Comment by rossano-lunardi** [comment]
We do use the Helidon MP main class to start the server, avoiding to register JAX-RS applications on the classpath.
But we have to wrap it in our main class because after the start we need some other settings, not strictly Helidon related

	public void startServer() {
		try {
			long startTime = System.currentTimeMillis();
			// we start the server using the new Helidon MP Main 
			io.helidon.microprofile.cdi.Main.main(new String[0]);
                        ....
                       here we place other settings
       }

**Comment by ljnelson** [comment]
(And that's fine.)

Another thing you could do instead is write a CDI startup listener (e.g. `private final void onStartup(@Observes @Initialized(ApplicationScoped.class) final Object event) { /*...*/ }`) which would be notified when the CDI container starts.  Then you don't need a `main` method.  But I'm getting off topic for this issue.  

I'm going to leave this issue open because whether it is the "right" way to go or not, you should be able to follow our guides, so if there's a problem there I want to fix it.

**Comment by tomas-langer** [comment]
There is a bug in `Server` bootstrapping. The server configures MP config too late, so default MP config is used to create data source.
This is also a bug in the abstract data source, as the config should be refreshed when an instance of a data source gets created (as the current approach would not work correctly when running in native image, as the extension is instantiated at buildtime.

**Comment by tomas-langer** [comment]
In `Server.Builder.build()` - we call `HelidonContainer.instance()` before setting the configuration.
It is then set later in `doBuild()` which is too late

**Comment by ljnelson** [comment]
@rossano-lunardi May I close this bug?

**Comment by rossano-lunardi** [comment]
Hi @ljnelson 
I've been on holiday, first day back to office...
Yes, of course, you can close that
thank you
