### ISSUE TITLE
Add musl to Graal build images

### ISSUE THREAD

**Issue by dansiviter** [oracle/helidon#2683]
Graal static native images cannot do some things, [such as DNS](oracle/graal#571) lookup [unless they have a `libc` set](https://www.graalvm.org/reference-manual/native-image/StaticImages/). Unfortunately, due to the build images removing all the pkg, apt, etc., directories, ([Dockerfile.jdk11-graalvm#L56](https://github.com/oracle/helidon/blob/2.2.0/etc/dockerfiles/Dockerfile.jdk11-graalvm#L56)) it makes a complicated task even more difficult. Therefore, would it be possible to have this embedded into the image so this can be pulled in as and when needed? Then usage would be a case of adding `--libc=musl`, potentially with another flag added to the `helidon-maven-plugin` for convenience.

I have been able to get this working using [this](https://cloud.google.com/blog/topics/developers-practitioners/comparing-containerization-methods-buildpacks-jib-and-dockerfile) as a template into `Dockerfile.jdk11-graalvm` file. If you're ok with this approach I'm happy to code this up.

**Comment by romain-grecourt** [comment]
To clarify, the part of the link you are refferring to is the following right ?
```
# BEGIN PRE-REQUISITES FOR STATIC NATIVE IMAGES FOR GRAAL 20.2.0
# SEE: https://github.com/oracle/graal/blob/master/substratevm/StaticImages.md
ARG RESULT_LIB="/staticlibs"

RUN mkdir ${RESULT_LIB} && \
    curl -L -o musl.tar.gz https://musl.libc.org/releases/musl-1.2.1.tar.gz && \
    mkdir musl && tar -xvzf musl.tar.gz -C musl --strip-components 1 && cd musl && \
    ./configure --disable-shared --prefix=${RESULT_LIB} && \
    make && make install && \
    cd / && rm -rf /muscl && rm -f /musl.tar.gz && \
    cp /usr/lib/gcc/x86_64-redhat-linux/4.8.2/libstdc++.a ${RESULT_LIB}/lib/

ENV PATH="$PATH:${RESULT_LIB}/bin"
ENV CC="musl-gcc"

RUN curl -L -o zlib.tar.gz https://zlib.net/zlib-1.2.11.tar.gz && \
   mkdir zlib && tar -xvzf zlib.tar.gz -C zlib --strip-components 1 && cd zlib && \
   ./configure --static --prefix=${RESULT_LIB} && \
    make && make install && \
    cd / && rm -rf /zlib && rm -f /zlib.tar.gz
#END PRE-REQUISITES FOR STATIC NATIVE IMAGES FOR GRAAL 20.2.0
```

**Comment by dansiviter** [comment]
Yes, without it and `--libc=musl` you get `java.net.UnknownHostException` if you try and lookup a host.

**Comment by dansiviter** [comment]
I've just build the images to compare and contrast. Note, I've also upgraded to Graal 21.0.0.

| Image | Size | Notes |
| --- | --- | --- |
| `helidon/jdk11-graalvm:20.2.0` | 580MB | |
| `helidon/jdk11-graalvm-maven:20.2.0` | 591MB | |
| `helidon/jdk11-graalvm:21.0.0` | 2.09GB | |
| `helidon/jdk11-graalvm-maven:21.0.0` | 2.1GB | |
| `helidon/jdk11-graalvm:21.0.0-musl` | 2.1GB | |
| `helidon/jdk11-graalvm-maven:21.0.0-musl` | 2.11GB | |
| `helidon-quickstart-mp:20.2.0-native` | 93.7MB | |
| `helidon-quickstart-mp:21.0.0-native` | 95.1MB | |
| `helidon-quickstart-mp:21.0.0-native-nomusl` | 95.1MB | With musl but __without__ `--libc=musl` |
| `helidon-quickstart-mp:21.0.0-native-musl` | 93.5MB | With musl but __with__ `--libc=musl` |

It appears upgrading to 21.0.0 has added 1.4MB onto the final binary, but a massive ~1.5GB onto the intermediate build image. Without `--libc=musl` it hasn't added anything AFAIKS, but turning it on actually dropped the image size by 1.6MB.

I'll try and figure out why the build images have jumped up and if there are any start-up performance hits.

**Comment by tomas-langer** [comment]
Hello, we will add this to our 2.3.0. We plan to migrate to 21.0.0 in that version. We do plan one version in between, so we will merge your PR once that release is done.

Thanks for your contribution!
