### ISSUE TITLE
Expose a metric / healthcheck to monitor the number of inflight requests with run time exceeding KPI

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#2688]
(via @olotenko) In order to monitor the status of the microservice efficiently, need the ability to determine the presence of stuck requests / too slow requests.

Usually we want to know the number of requests exceeding some KPI (eg tens of seconds), to be able to restart, if too many are observed - typically stuck requests indicate some form of overload, or (distributed) deadlock.

May be a good idea to expose the duration of the longest running request.

**Comment by tjquinno** [comment]
@olotenko I'd like to hear your thoughts on some points related to this.

The need you've described is very real, the ability to assess the health of the service based on how long requests are taking to process.

The enhancement request really involves two aspects, as your title states: a metric and at least one health check. 

That leads to (at least) two questions:

1. What metric is best suited to use?
2. How would a health check interpret that metric?

## What metric?
There are two natural options.

### Concurrent gauge
A concurrent gauge is designed to track parallel actions. If we used one for this enhancement, it would report the current number of concurrent requests and also the min and max over the preceding minute: if the current clock reads h:m:s then the min and max are essentially computed for h:(m-1):00 to h:(m-1):59.99. 

A concurrent gauge would give a health check a small window into the recent past (preceding minute), allowing it to detect whether the value seems to be increasing, stable, or decreasing--at least with respect to that preceding minute.

### Timer
A timer combines:
* a _meter_ - a monotonically increasing counter and one-minute, five-minute, and 15-minute rates based on that counter, and
* a _histogram_ - an exponentially-decaying reservoir of the meter's counter values exposing current count, min, max, mean, std dev, and the 50, 75, 90, 95, 99, and 99.9 percentiles.
 
Using a timer to track all requests--or all requests that took longer than a configured threshold--would give a health check  any or all of those exposed values to assess the liveness and readiness of the service. Of course, it costs a bit more to maintain the data required for those stats than for a concurrent gauge.

## What health check(s)?

There are at least three distinct cases which might merit different responses.

1. If the number of inflight requests exceeds that threshold but only for "brief" periods of time, then that might be OK and the service could be considered alive and ready and worthy of receiving additional requests.
2. If the number stays above the threshold for "significant" periods of time but does not grow significantly, then the service might be considered alive (worthy of being allowed to continue running) but _not_ ready (not capable of handling additional incoming requests) until the count drops below the threshold, then subsequently rises above it only briefly if at all. 
3. If the number is above the threshold and rises "consistently" then we might have the deadlock situation you mentioned. 

## Is Helidon or is the app better suited to measure these values and make these decisions?
A key question is whether Helidon should provide a _built-in_ metric and/or a _built-in_ health check (perhaps configurable), or whether an application itself should provide them.
I'm concerned that it will be difficult for Helidon to expose a metric and health check(s) and their configuration in a way that usefully covers the use cases for a broad cross-section of apps.

The health checks could require appreciable logic to interpret the metric which measures requests' processing times in order to assess the service's liveness and readiness. To be sure, some of this logic could be configurable in Helidon-provided metric and health checks: what is "brief," or "significant," or "consistently?" 

That said, it is straightforward for a Helidon SE application to add a metric of its choice to measure all requests or for a Helidon MP app to add a filter to measure all JAX-RS requests. And it's straightforward for an app to add its own health checks that would embed whatever logic is needed to define "brief," "significant," or "consistently" for _that_ application.

Helidon could provide some examples of how to do this.

Might that be the better approach?

**Comment by olotenko** [comment]
I agree there are application-specific cases. But I also see the need to provide something simple that covers a lot of the cases, where boilerplate code to compute metrics efficiently is replaced by a configuration option to expose such generic metrics.

What I've seen to work well:

* count requests that last longer than N seconds

Nothing fancy, just keep track of when the requests started. Once every N seconds (we know we are interested only in those that last longer than N, and we are after a crude estimate that something is wrong) check the list of ongoing requests, and count how many are ongoing more than N seconds after the start.

Apps may be able to implement it on their own end, but wouldn't this cause repetition of similar code across all apps?

* compute load average

When the request starts or ends, add or subtract 1 from a global counter. Every M seconds add the total thus computed to an exponentially decaying counter.

* compute hit rate

When a request is received, add 1 to an exponentially decaying counter. Apps have no visibility into when requests arrive - they may see only the requests that have been dispatched.

App should be able to stop arrival of requests (eg through 429). Looking at the number of requests being processed is not the same, as the request queue build-up is one of the problems.

* compute queue length

How many requests are ready to be dispatched, but not dispatched yet. This is something apps cannot detect through their own metrics. Something like a difference between the requests received (and, say, placed in Jersey queue) and started (picked up from the Jersey queue).

**Comment by tjquinno** [comment]
Hi, @olotenko. I need to switch gears to work on some other things for a short while, but when I get back to this here is the current thinking (after discussions with some others on the team)...

We would add some new built-in `vendor` metrics. As noted below, some would apply only to MP and not SE simply because of differences in how the two flavors of Helidon accept and work on requests from Netty. 

The new metrics would give some insight into the performance of the service.

We _do not_ plan to add additional built-in health checks based on these new metrics. The metric names and the fact that they will be registered in the `vendor` registry will be public and part of the exposed Helidon interface, so users can add their own health checks which look up these metrics, check any of those metrics' statistics, and draw their own conclusions as to the liveness or readiness of the service given their knowledge of the service's implementation and purpose.

Here are the proposed new metrics (including the requests in-flight proposed in the companion issue #2689). First, some notes about two specific metric types we propose to use:

* `ConcurrentGauge`- measures an integer quantity; can rise and fall; exposes a precise current value as well as min and max over the preceding whole minute (hh:mm:00 to hh:mm:59.99).
* `Meter` - measures events over time using an exponentially-weighted moving average; exposes total count, mean over entire lifetime, and rates (using the EWMA) over the previous 1-, 5-, and 15-mimute windows.

1. in-flight requests: Add a `ConcurrentGauge`, incremented as each request is received and decremented as each request is completed. This gives a precise, instantaneous reading as well as the min and max over the preceding minute (hh:mm:00 to hh:mm:59.99).
2. long-running requests: Add a `Meter`, with a configurable threshold for what constitutes a "long-running" request. Invoke `mark()` upon completion of each long-running request.
3. load (MP only): Add a `Meter`, invoking `mark()` as work is started on each request. This differs from the hit rate which measures arrivals of new requests, some of which might be queued; this `Meter` is updated only as a request begins processing.
4. hit rate: The existing `requests.meter` `Meter` satisfies this requirement.
5. queue length (MP only): 
    
    There are no queues within Jersey. Helidon MP basically accepts incoming requests from Netty as fast as they arrive and then hands them off to an `ExecutorService` which in turn will invoke Jersey to work on the request. MP does not know ahead of time exactly what type of `ExecutorService` will be in use. MP could, though, check for the most likely known types which have queueing behavior and expose getters for the queue itself or current queue size or current thread usage. Some or all of these values would allow us to infer whether a new request would or would not be queued before being worked on. If the application does not specify which type of `ExecutorService` to use, the default MP uses is one that does expose relevant queueing data we can use.
    
    With that in mind, add a `Meter`, invoking `mark()` if we infer that this request will be queued within the `ExecutorService`. This is not guaranteed to be accurate because circumstances could change between when we query the service's getters and when the request is actually handed off to the executor service. But it would be very close.

Using the existing types of metrics (`ConcurrentGauge`, `Meter`) rather than fashioning our own (e.g., a `Gauge`) simplifies the engineering work as well as the doc task and ease of user understanding because these have well-known behavior.

I think these additions would handle the statistics you were describing, assuming I've understood them clearly.

**Comment by olotenko** [comment]
Sounds good.

I think `queue length` can be inferred from the difference between `in-flight` (received) and `load` (started executing), there may be no need for knowing the executor type or asking the actual queue.

**Comment by tjquinno** [comment]
If the queue length can be inferred from _load_ - _in-flight_, does it make sense for the _observer_ to draw the inference and avoid the overhead of Helidon maintaining the additional queue-length metric that provides no additional information?

**Comment by olotenko** [comment]
I don't see the overhead of returning a difference of two values, rounded up to 0. But I imagine some healthchecks may lack the capability to perform computations based on multiple keys; checking a value against a threshold is often the minimal functionality you can get from dashboards / alerts.
