### ISSUE TITLE
gRPC metrics code replicates logic in metrics component and is possibly out-of-date

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#2694]
## Environment Details
* Helidon Version: 2.x
* Helidon SE or Helidon MP SE
* JDK version: n/a
* OS: n/a
* Docker version (if applicable): n/a

----------
In gRPC, the `MetricsConfigurer` class contains an `accept` method that specifically acts on metrics annotations `@Counted`, `@Timed`, and `@Metered`. That method then delegates to `addMetric` which checks for those (and other, but not all possible) metrics annotations and then runs some logic that replicates code in the metrics component to create metrics.

I'm checking with the gRPC folks whether the code should pay attention to all metrics which SE metrics supports or only some, and in that case which ones.

Further, we should avoid the duplicated code in `MetricsConfigurer` and have it instead delegate to the metrics SE code. If needed we can expose a new method from SE metrics which gRPC can invoke.

**Comment by tjquinno** [comment]
@aseovic @thegridman 

If one of you could confirm which metrics the gRPC code should pay attention to — either a list of specific ones (such as timed, counted, metered) or “all that exist now and might be added in the future” — I will work on refactoring the gRPC and metrics code so gRPC does not duplicate code in metrics and therefore won’t have to be updated going forward.

**Comment by tjquinno** [comment]
@aseovic @thegridman Any feedback on which metrics make sense for gRPC?

Here's the list of MicroProfile metrics annotations and brief summaries in case that helps:

* `ConcurrentGauge` - reflects current number of parallel invocations of marked methods or constructors; includes min and max over previous complete minute (all `long`)
* `Counted` - monotonically increasing `long` value
* `Gauge` - instantaneous value (`long`); can vary up or down; no history
* `Metered` - count (`long`) and throughput mean and one-, five-, and 15-minute exponentially-weighted moving averages (`double`)
* `SimplyTimed` - count of invocations ('long') and min, max, and cumulative elapsed time `Duration`s
* `Timed` - total `Duration` plus `Metered` behavior
* `Metric` - injection or registration of a metric for the annotated field or parameter

**Comment by thegridman** [comment]
Apart from the last one, `metric` as I don't quite know what it is, the rest can probably be implemented. In gRPC metrics are implemented using gRPC interceptors and not using the normal microprofile/cdi way of wrapping the annotated method in a CDI interceptor. This is because gRPC is all async and in order to correctly implement things like timings you need to start and stop the timing at the correct point, not just around the service method.

**Comment by tjquinno** [comment]
OK, thanks for the response. I'll see about abstracting out the common behavior so the gRPC code does not have to change if new metrics are added or if we fix bugs in the original code.
