### ISSUE TITLE
Different output in Db client

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#2696]
Version: 2.2.0

When I use `helidon init` and create a database SE application and run it as is, I get inconsistent output.

`curl -i http://localhost:8080/pokemon` returns:
```
[{"id":1,"idType":12,"name":"Bulbasaur"},{"id":2,"idType":10,"name":"Charmander"},{"id":3,"idType":11,"name":"Squirtle"},{"id":4,"idType":7,"name":"Caterpie"},{"id":5,"idType":7,"name":"Weedle"},{"id":6,"idType":3,"name":"Pidgey"},{"id":100,"idType":1,"name":"Test"}]
```

but `curl -i http://localhost:8080/pokemon/1` returns:
```
{"ID":1,"ID_TYPE":12,"NAME":"Bulbasaur"}
```

For some reason the names of columns are capitalized, where they are lower cased in select all - in `application.yaml` both are lower case in selects. 
Select by ID and by NAME both use parameters, where the select all does not - may be related to the inconsistency

**Comment by tomas-langer** [comment]
Maybe caused by usage of JSON-B versus JSON-P usage (List all uses JSON-B, by name uses JSON-P).
I think we should have consistent output - so either use JSON-B or JSON-P for all calls

**Comment by Tomas-Kraus** [comment]
Yes, I was able to reproduce this as well.

**Comment by Tomas-Kraus** [comment]
I have chosen 1st option. 2nd one depends on database setup: it will work only with case sensitive column names.
```
mvn -U archetype:generate -DinteractiveMode=false -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-database-se -DarchetypeVersion=2.2.1-SNAPSHOT \
    -DgroupId=io.helidon.examples -DartifactId=helidon-database-se -Dpackage=io.helidon.examples.db.se
cd helidon-database-se && mvn package
java -jar target/helidon-database-se.jar
```
Test:
```
curl -i http://localhost:8080/pokemon/1
{"id":1,"idType":12,"name":"Bulbasaur"}
curl -i http://localhost:8080/pokemon/name/Bulbasaur
{"id":1,"idType":12,"name":"Bulbasaur"}
```
