### ISSUE TITLE
JerseySupport error response masking hard coded

### ISSUE THREAD

**Issue by dansiviter** [oracle/helidon#2730]
## Environment Details
* Helidon Version: 2.2.1-SNAPSHOT
* Helidon SE or Helidon MP
* JDK version: N/A
* OS: N/A
* Docker version (if applicable):

----------

## Problem Description
Hiding/masking of error responses is hard coded in [`JerseySupport.java#119`](https://github.com/oracle/helidon/blob/master/webserver/jersey/src/main/java/io/helidon/webserver/jersey/JerseySupport.java#L119). With applications that already sanitise the error responses there is often a desire to be able to consume the payload.

This has two problems:
* Moving away from default behaviour of Jersey Client which will cause confusion,
* Not possible to disable.

IMO this is opt-in behaviour and should be neither the default or hard-coded.

## Steps to reproduce
N/A

**Comment by spericas** [comment]
@dansiviter We absolutely need to change the default as this behavior presents a security risk. The app can override this by re-setting the property, but I agree this can be tricky as it depends on the loading of `JerseySupport`. One possible minor improvement would be for the code to make sure the property is unset (null) before setting it. The way an app could override this externally. Would that help in your case?

Application developers can also define their own exception mappers.

**Comment by dansiviter** [comment]
Depends on your interpretation of a security risk. I expect if I use Jersey, ReSTEasy `URLConnection` or any other client library that I would be able to read the payload without configuration regardless of status code. That in itself is not a risk. The risk comes when the downstream system bleeds information when a error occurs. Therefore, I understand why there is an option to opt-in to hiding the payload, but it shouldn't be the default and it must be configurable.

It also concerns me that the only way to supply this is via system properties. It should come from the normal configuration mechanism so the value can be set globally in `application.yaml` or equivalent.

**Comment by dansiviter** [comment]
Thinking about it, if we can just have this come from the normal configuration mechanism this would suffice. Happy for it to default to `true` if we can globally set this (not via System properties).

**Comment by spericas** [comment]
PR #2737
