### ISSUE TITLE
Security providers should support optional flag

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#2772]
Currently some providers (such as HTTP Basic auth and OIDC) do not have a configuration option to mark them optional.
When a provider cannot be optional, it always returns a failure when it cannot validate authentication based on request data.

When configured as optional, it should return `ABSTAIN` rather than `FAILURE`, allowing composite security policy to follow up with the next provider when flag is set to `SUFFICIENT`. Currently we need to set flag to `MAY_FAIL`, so all providers are called, even if the first one authenticates the request.

This also requires an integration test that validates a sequence of authentication providers used.

**Comment by tomas-langer** [comment]
The optional flag should always cause return of `ABSTAIN` - we may want to use the same provider (such as JWT).
Right now if two JWT providers are used using the same header both in `SUFFICIENT` flag, if the first one fails to validate the request, it fails overall, even if the second provider would validate it.

**Comment by arjav-desai** [comment]
Raised https://github.com/oracle/helidon/pull/3039 to add support for optional.

Still need to add integration test for this.

**Comment by arjav-desai** [comment]
Added integration tests and updated docs with #3191
