### ISSUE TITLE
JTA not working with CDI + JDBC (without JPA)

### ISSUE THREAD

**Issue by rossano-lunardi** [oracle/helidon#2777]
## Environment Details
* Helidon Version: 2.2.0
* Helidon MP
* JDK version:  jdk11.0.6_10
* OS: Windows 10
* PostgreSQL: 42.2.18 

Hi,

as we come from the "JEE world" we'd like to have in Helidon the same nice feature, the Container Managed Transactions:
in other words we'd like to annotate CDI beans with `@Transactional`, like EJBs and `@TransactionAttribute`, and let the framework managing commits and rollbacks.

We've followed this guide
https://helidon.io/docs/v2/#/mp/guides/08_jta

Please note that:
- we use HikariCP connection pool
- datasource class is `org.postgresql.ds.PGSimpleDataSource`, so not XA support (HikariCP does not like `org.postgresql.xa.PGXADataSource`)
- we are NOT using JPA but a "low level" class that injects the datasource and implements JDBC calls

We noticed this sentence in the guide above:
> Annotating a method with @Transactional demarcates a JTA transaction, but it is up to individual JTA-aware frameworks and libraries to actually do something when the transaction is implicitly started. JPA is an example of a framework that is JTA aware.

and we got worried because we are not using JPA.

But then digging quite a lot we've found these too:
* https://github.com/oracle/helidon/pull/1316
* http://jbossts.blogspot.com/2019/04/jta-and-cdi-integration.html
* https://developer.jboss.org/thread/280909

where it seems it is possible 

The weird behaviour we are experiencing is:

with autocommit=true (default) the inserted row is committed even if the service exits with a runtime exception
(here it seems that when the transaction manager tries to rollback the transaction has already been committed)

with autocommit=false the row is not inserted at all, even if the service goes ok
(here it seems that when the transaction manager tries to commit the transaction has been already rolled back, due to a dirty state)
```
[Thu Feb 18 15:41:22 CET 2021] FINE: com.zaxxer.hikari.pool.ProxyConnection close - HikariPool-1 - Executed rollback on connection org.postgresql.jdbc.PgConnection@58c79829 due to dirty commit state on close(). 
```
we applied the annotation to a REST resource 

	@POST
	@Path("v1/email/verification")
	@Produces(MediaType.APPLICATION_JSON)
	@Consumes(MediaType.APPLICATION_JSON)
	@Authenticated
	@Authorized
	@RolesAllowed({ Role.GUEST })
	@Operation(summary = "Send an email verification code", description = "Send an email verification code")
	@APIResponse(responseCode = "200", description = "The validation code for an email", 
			content = @Content(mediaType = MediaType.APPLICATION_JSON, 
							   schema = @Schema(implementation = VerifyMailSendResponse.class)))
	@Transactional
	public Response verifyMailSend(...

and pom dependencies seems ok

But it's not working as expected and we are stuck and confused

**Comment by ljnelson** [comment]
I haven't dived into this yet but I think what you're running into is:
1. Fundamentally HikariCP does not support XA transactions which, strictly speaking, are necessary for distributed transaction management.
2. The articles you reference were all written by me or about my efforts to try to make non-XA database drivers and non-XA connection pools work, sort of, with JTA.
3. There is a layer somewhere in Helidon (can't remember exactly where) that fakes some of this.  It's possible it's in the JPA layer.  I'll have a look.
4. Our JPA unit tests take advantage of this fake support and exercise a use case similar to yours.

**Comment by ljnelson** [comment]
Oh, I missed something you said:
> we are NOT using JPA but a "low level" class that injects the datasource and implements JDBC calls
So _you_ will have to write or manage your own pseudo/fake XA layer for non-XA datasources.  I'll keep this open because there might be a way to make the Helidon "fake XA" layer work more generally.

**Comment by ljnelson** [comment]
The heart of the matter can be found here:

https://github.com/oracle/helidon/blob/c589951e78bcd915eac6d891a3c2d4405c5456ca/integrations/cdi/jpa-cdi/src/main/java/io/helidon/integrations/cdi/jpa/JtaDataSourceProvider.java#L314-L318

This is what "Annotating a method with @transactional demarcates a JTA transaction, but it is up to individual JTA-aware frameworks and libraries to actually do something when the transaction is implicitly started" means: you are going to have to get your JDBC-managing "framework" to become JTA "aware" in a similar fashion.  Or, again, there might be a way to expose this more generically.

**Comment by rossano-lunardi** [comment]
Hi @ljnelson 

ok, now we have JtaDataSource compiling in our project, here you can see the classes taken from Helidon JPA layer

![image](https://user-images.githubusercontent.com/77846559/108725657-e5d3c480-7526-11eb-8f04-a6249afb1515.png)

We replaced javax.sql.DataSource with the new JtaDataSource in our JDBC class, thinking that it would be enough to do the trick, but we get this error

org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type JtaDataSource with qualifiers @Named
  at injection point [BackedAnnotatedField] @Inject @Named private it.vegans.common.resource.jdbc.JDBCResource.dataSource

even if JtaDataSource implements javax.sql.DataSource 

Are we still missing something?

**Comment by ljnelson** [comment]
(Disclaimer: since you're hacking 😄  none of this can be supported.)

I can't comment on the unsatisfied dependencies, but certainly you're still missing the part where all these pieces get notified of when the transaction starts and ends.  In Helidon, we accomplish this by looking at CDI events fired by the transaction scope when it is initialized and destroyed.

This is what the statement you cited means:
> Annotating a method with @transactional demarcates a JTA transaction, but it is up to individual JTA-aware frameworks and libraries to actually do something when the transaction is implicitly started.

**Comment by ljnelson** [comment]
Closing; see #3024 and #3089
