### ISSUE TITLE
Bean Validation does not work in REST Controllers

### ISSUE THREAD

**Issue by progaddict** [oracle/helidon#2779]
## Environment Details
* Helidon Version: 2.2.1
* Helidon MP
* JDK version: OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1) (AdoptOpenJDK 11.0.9.hs-adpt in `SDKMAN!`)
* OS: Linux x86_64

----------

## Problem Description
Bean Validation does not work in REST Controllers. Even with [hibernate-validator-cdi](https://stackoverflow.com/a/61995634).

According to the [spec](https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html#validation) it should work (sorry, there is no content in the `2.1` [version](https://jakarta.ee/specifications/restful-ws/2.1/) therefore I've taken the last version).

## Steps to reproduce
* `mkdir tmp && cd tmp`
* `git clone -b bug/bean-validation-does-not-work https://github.com/progaddict/helidon.git`
* `cd helidon/examples/microprofile/hello-world-implicit`
* `mvn clean package`
* `java -jar target/helidon-examples-microprofile-hello-world-implicit.jar`
* `curl --request POST --url http://127.0.0.1:7001/helloworld --header 'content-type: application/json' --data '{"description": "this should fail"}'`
* observe `NewToDoItem{name='null', description='this should fail'}` response instead of HTTP 5xx error
* `curl http://127.0.0.1:7001/helloworld/test2?description=foobarbaz`
* observe `null foobarbaz` response instead of HTTP 5xx error
* see the last 3 commits in the `bug/bean-validation-does-not-work` branch for more details: https://github.com/progaddict/helidon/commits/bug/bean-validation-does-not-work

**Comment by spericas** [comment]
@progaddict You seem to be mixing and matching the wrong dependencies (EE 9 ones). Try this set of dependencies in your project:

```
    <dependencies>
        <dependency>
            <groupId>io.helidon.microprofile.bundles</groupId>
            <artifactId>helidon-microprofile</artifactId>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.ext</groupId>
            <artifactId>jersey-bean-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jboss</groupId>
            <artifactId>jandex</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>jakarta.activation</groupId>
            <artifactId>jakarta.activation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
```

The key addition being `jersey-bean-validation`.

**Comment by progaddict** [comment]
Hello @spericas

Thanks a lot for your quick response!
Yes, indeed, the jersey implementation of the bean validation spec works.
After the change introduced by the commit https://github.com/progaddict/helidon/commit/5cb0471115faf235466056dbbe85a21dd75501bc I'm getting `HTTP 400 Bad Request` which is a correct expected behavior.

It would be great, if this nuance would be described in the documentation somewhere https://helidon.io/docs/latest/#/mp/guides/01_overview (I'll make a PR for documentation if I have time) because bean validation is quite popular way to ensure your system/app receives correct inputs. Currently it's not at all obvious that you need to include a specific dependency to make it work. E.g. I am used to the Hibernate Validator which is very mature and widespread implementation of the bean validation spec and there is this CDI integration for it (described here https://stackoverflow.com/a/61995634) which a developer expects to just work but unfortunately it doesn't.

Once again, muchas gracias and have a nice day! :slightly_smiling_face:

**Comment by ljnelson** [comment]
For completeness: Jersey's bean validation is just the machinery that lets Hibernate Validator work in a JAX-RS application (https://github.com/eclipse-ee4j/jersey/blob/84b7eba4b62ff7ed8f1cbc39cade7a8469ad688c/ext/bean-validation/pom.xml#L86-L99).  Hibernate Validator's CDI integration is just the machinery that lets Hibernate Validator work in a CDI application.  If you want to validate CDI beans, you'll need the latter; if you want to validate JAX-RS-specific constructs like query parameters and so forth, you'll need the former.

**Comment by spericas** [comment]
Created issue #2786.
