### ISSUE TITLE
Expose HikariCP metrics

### ISSUE THREAD

**Issue by trym-moeller** [oracle/helidon#2781]
I would like to be able to enable the HikariCP metrics in Helidon using the microprofile-config.properties file

## Environment Details
* Helidon Version: 2.2.0
* Helidon MP
* JDK version: any
* OS: any
* Docker version (if applicable): any

----------

## Problem Description
I cannot find a property key, that allows me to enable the HikariCP metrics in Helidon

## Steps to reproduce
Start the Helidon server, call the /metrics endpoint, validate that no HikariCP metrics are available

See https://github.com/brettwooldridge/HikariCP/wiki/Dropwizard-Metrics for existing metrics to expose

**Comment by ljnelson** [comment]
Notes for myself:

https://github.com/brettwooldridge/HikariCP/blob/04919ad540cc108a3f67ac801a47a69927f05089/src/main/java/com/zaxxer/hikari/HikariConfig.java#L669-L672

Note that it supports [Micrometer `MeterRegistry` instances](https://micrometer.io/docs/concepts#_registry).
