### ISSUE TITLE
Support exemplars in Prometheus metrics output

### ISSUE THREAD

**Issue by slto** [oracle/helidon#2797]
## Environment Details
* Helidon Version: 2.1.0
* Helidon SE or Helidon MP: SE
* JDK version: 11.0.8
* OS: Linux 
* Docker version (if applicable):

----------

## Problem Description
Provide support for exemplars in Helidon metrics output in Prometheus format for Timers/Histograms
https://github.com/OpenObservability/OpenMetrics/blob/master/specification/OpenMetrics.md

Exemplars allows drilldown from metrics to traces in Grafana.
https://grafana.com/blog/2021/02/04/grafana-7.4-released-next-generation-graph-panel-with-30-fps-live-streaming-prometheus-exemplar-support-trace-to-logs-and-more/

As Helidon already uses WeightedSnapshot to store sample values for Histograms, is it possible to capture trace id active at the time when the metric is updated and store the trace id value along with the metric sample value.  When computing the histogram quantiles, pick one of the trace ids from the samples in that quantile and include in the metrics output

**Comment by tjquinno** [comment]
Some early thoughts about this.

1. OpenMetrics permits exemplars to appear on the following metric types:
    1. counter total
    2. bucket values in a histogram
