### ISSUE TITLE
Helidon MP + Gradle:  No handler found for path

### ISSUE THREAD

**Issue by joaofouyer** [oracle/helidon#2846]
## Environment Details
* Helidon Version: 2.2.1
* Helidon MP
* JDK version: 11
* OS: Linux (Ubuntu 20.04)
----------

## Problem Description
I am not able to create a Helidon MP project with Gradle ([using recommended quickstart settings](https://github.com/oracle/helidon/blob/2.2.1/examples/quickstarts/helidon-quickstart-mp/build.gradle)) and "expose" JAX-RS resources. Even when I try the quickstart example, when I make a GET request I only receive "No handler found for path: /greet". I've tried many examples or official tutorials but it isn't clear how to add / map resources. 

## Steps to reproduce
1. I've cloned and tried the [quickstart example](https://github.com/oracle/helidon/tree/2.2.1/examples/quickstarts/helidon-quickstart-mp), using Gradle.
2. I had to change the version since I couldn't find for some dependencies and the jersey-media-json-binding version 3.* or higher changes from javax to jakarta: 

```groovy
dependencies {
    implementation group: 'io.helidon.microprofile.bundles', name: 'helidon-microprofile', version: '2.2.1'
    implementation group: 'org.glassfish.jersey.media', name: 'jersey-media-json-binding', version: '2.33'

    runtimeOnly group: 'org.jboss', name: 'jandex', version: '2.2.3.Final'
    runtimeOnly group: 'javax.activation', name: 'javax.activation-api', version: '1.2.0'
    //...
}
```
3. Just to be sure, I've also changed the beans.xml bean-discovery-mode to **all**: 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://xmlns.jcp.org/xml/ns/javaee"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee
                           http://xmlns.jcp.org/xml/ns/javaee/beans_2_0.xsd"
       version="2.0"
       bean-discovery-mode="all">
</beans>
```

4. And I manually created the Main class: 

```java
import io.helidon.microprofile.server.Server;

public class Main {
	private Main() { }
	
	public static void main(String[] args) {
		Server server = Server.builder()
				.host("localhost")
				.port(0)
				.build();

		server.start();

		String endpoint = "http://" + server.host() + ":" + server.port();
		System.out.println("Started application on     " + endpoint + "/greet");
	}
}

```

What am I doing wrong or what else must I do to be able to send a GET request to [GreetResource](https://github.com/oracle/helidon/blob/2.2.1/examples/quickstarts/helidon-quickstart-mp/src/main/java/io/helidon/examples/quickstart/mp/GreetResource.java)?

**Comment by romain-grecourt** [comment]
All dependencies should be resolvable from Maven Central. 

All versions for the required dependencies are managed by the `helidon-dependencies` BOM, it's imported here https://github.com/oracle/helidon/blob/78fe1c2bb17dd7c165a76fb588f4cc53075f85a1/examples/quickstarts/helidon-quickstart-mp/build.gradle#L45

`2.2.1` uses Jersey `2.33`, and all Jersey artifacts have their version managed ; you shouldn't have to declare the version.
Helidon uses the new `jakarta` artifacts, you should not use the older `javax` variants.

If you just clone the `2.2.1` tag and try to build the `quickstart-mp` as-is, does it work ?

**Comment by barchetta** [comment]
As @romain-grecourt suggested, I have verified that the following works:

```
# In Heldon clone
git checkout tags/2.2.1
cd examples/quickstarts/helidon-quickstart-mp
gradle build
java -jar build/libs/helidon-quickstart-mp.jar
curl -X GET http://localhost:8080/greet/hello
```
 
So you your project differs from that example.

**Comment by joaofouyer** [comment]
> All dependencies should be resolvable from Maven Central.
> 
> All versions for the required dependencies are managed by the `helidon-dependencies` BOM, it's imported here
> 
> https://github.com/oracle/helidon/blob/78fe1c2bb17dd7c165a76fb588f4cc53075f85a1/examples/quickstarts/helidon-quickstart-mp/build.gradle#L45

I'm importing, I didn't change that. I just omitted for brevity in my question.

> Helidon uses the new `jakarta` artifacts, you should not use the older `javax` variants.

Not in 2.2.1, it does still use javax. For example: https://github.com/oracle/helidon/blob/2.2.1/examples/quickstarts/helidon-quickstart-mp/src/main/java/io/helidon/examples/quickstart/mp/GreetResource.java. 

> If you just clone the `2.2.1` tag and try to build the `quickstart-mp` as-is, does it work ?

Yes it does work, but one change I made and isn't clear why it isn't working is when I create a Main class and try to run. So what should I do if I want to make that example work with a Main class just as pointed in the description?

Thank you in advance.

**Comment by joaofouyer** [comment]
> So you might want to see how your project differs from that example.

It differs in the main class I just posted in the description.

**Comment by romain-grecourt** [comment]
`jakarta.activation:jakarta.activation-api:1.2.2` provides the `javax.activation` package, see the [javadoc](https://javadoc.io/doc/jakarta.activation/jakarta.activation-api/1.2.2/jakarta.activation/javax/activation/package-summary.html).

We maintain exclusions for `javax` artifacts to ensure a proper Maven dependency tree ; using the `javax` artifacts may have non-desired have side effects.

I tried dropping in your main class as-is and it worked (had to update `build.gradle` to change the `Main-Class` manifest attribute).

Looks like CDI does not discover the resource class.

- How are you starting your application ? 
- Is the packaging correct ? I.e do you have the `beans.xml` file in the same JAR file or class-path entry as the application classes ?

**Comment by barchetta** [comment]
We've been unable to reproduce. @joaofouyer if you have more information feel free to re-open.
