### ISSUE TITLE
Helidon config documentation needs updates

### ISSUE THREAD

**Issue by arjav-desai** [oracle/helidon#2850]
## Environment Details
* Helidon Version: 2.2.1
* Helidon SE and Helidon MP

----------

## Problem Description
* https://helidon.io/docs/latest/#/mp/guides/03_config
Our MP Config Guide seems to be based on SE one and talks about creating custom sources using SE ConfigSources.

* https://helidon.io/docs/latest/#/se/config/05_mutability-support in section "Setting up Config Source Change Detection" mentioned `.pollingStrategy(PollingStrategies::watch)` and `.pollingStrategy(PollingStrategies::noop)` which is wrong. We have changeWatcher instead.

* In general, our config documentation for both SE and MP needs a thorough re-read and clean-up as well as reorganization to be more user friendly e.g.
** There is a lot of information in Guide docs which could go in Main config section.
** Information about config sources and format, as well their order is spread/duplicated multiple times and sometimes each specify a little different information e.g. https://helidon.io/docs/latest/#/mp/config/02_MP_config_sources (application.yaml is missing from mention) but then https://helidon.io/docs/latest/#/mp/config/01_introduction has it listed as default helidon config.
** Server config is defined with WebServer section and not with config section.

**Comment by bfedoronchuk** [comment]
Guys, check also "Exceeding three sources" section on this [page](https://helidon.io/docs/v2/#/mp/guides/03_config).  This section describes outdated API:
```
import io.helidon.config.ConfigSources;
...

  private static Config buildConfig() {
      return Config.builder()
          .sources(ConfigSources.create(   
              directory("conf"),
              file("config-file.properties"),
              classpath("config.properties").optional(),
              classpath("META-INF/microprofile-config.properties")))
          .build();
  }
```

Such sources() method was removed in this [commit](https://github.com/oracle/helidon/commit/c38554957d19faad9fca04aaf15021c0ae7411e8). Check ConfigSources diff: 

Now, this API looks like this:
```
return Config.builder()
            .addSource(directory("conf"))
            .addSource(file("config-file.properties"))
            .addSource(classpath("config.properties").optional())
            .addSource(classpath("META-INF/microprofile-config.properties"))
            .build();
```

**Comment by bfedoronchuk** [comment]
Check "Meta-configuration" section on this [page](https://helidon.io/docs/v2/#/mp/guides/03_config). This section describes outdated API:
```
  private static Config buildConfig() {
      return Config.loadSourcesFrom( file("meta-config.yaml")); 
  }
```
Method `loadSourcesFrom()` was removed since Helidon MP 2.0.0. Moreover, it's absolutely unnecessary because Helidon Config automatically checks files with `meta-config.` prefix and loads meta configuration from there.

**Comment by bfedoronchuk** [comment]
"Injecting the Config object" section in MP Config [guide](https://helidon.io/docs/v2/#/mp/guides/03_config) describes an unnecessary workaround:
```
public void onStartUp(@Observes @Initialized(ApplicationScoped.class) Object init) {
        message.set(config.get("app.greeting").asString().get()); 
}
```
with such explanation:

> You can inject the Config object into the class and access it directly as shown below. This object is not initialized when the GreetingProvider constructor is called, so you need to provide a method (onStartup) that observes `@Initialized`. This method will be called when GreetingProvider is ready for use.

Config bean could be simply injected via the constructor:
```
@Inject
public GreetingProvider(Config config) {
        String message = config.get("app.greeting").asString().get();
        this.message.set(message);
}
```
Config bean is created lazily, with callback defined in `ConfigCdiExtension` class in `registerConfigProducer()` method:
```
private void registerConfigProducer(@Observes AfterBeanDiscovery abd) {
        // we also must support injection of Config itself
       ....
        abd.addBean()
                .addTransitiveTypeClosure(io.helidon.config.Config.class)
                .beanClass(io.helidon.config.Config.class)
                .scope(ApplicationScoped.class)
                .createWith(creationalContext -> {
                    Config config = ConfigProvider.getConfig();
                    if (config instanceof io.helidon.config.Config) {
                        return config;
                    } else {
                        return MpConfig.toHelidonConfig(config);
                    }
                });
       ...
}
```
