### ISSUE TITLE
Need support for hot SSL certificate reload

### ISSUE THREAD

**Issue by srpavan** [oracle/helidon#2863]
We need to be able to reload SSL keys while the server is running. 

## Environment Details
* Helidon Version: 1.4.8
* Helidon SE 
* JDK version: 1.8
* OS: Linux OEL7
* Docker version (if applicable):

----------

## Problem Description
Currently, if we modify the certificate the application will have to be restarted. We have a requirement where there will be multiple clients connecting to the application and each will have their own certificate. In this situation, restarting the application is not feasible as that will require coordination between multiple clients. Would it be possible for Helidon to allow SSL certificates to be reloaded at runtime.

## Steps to reproduce
Nothing to reproduce. This is an enhancement request.

**Comment by tomas-langer** [comment]
This is about mutual TLS - e.g. the requirement is to modify trust store of the server, not the private key.

**Comment by Verdent** [comment]
I will just add a clarification note here, this creates completely new SSLContext and that means, it reloads basically everything.  When WebServerTls is created, the new SSLContext instance  is created based on the provided values and that includes private key, trust store etc.
