### ISSUE TITLE
config-yaml optional dependencies with jdk modules

### ISSUE THREAD

**Issue by wojtask9** [oracle/helidon#2865]
## Environment Details
* Helidon Version: 2.2.1
* Helidon SE
* JDK version: OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
* OS: linux
* Docker version (if applicable):

----------

## Problem Description

There is something wrong with `config-yaml` optional dependency (`microprofile.config.api`).
Everything works fine when executing with classpath
But when we use `config-yaml` with jdk modules then we gets

```
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Module io.helidon.config.yaml does not read a module that exports org.eclipse.microprofile.config.spi
```

If we add `microprofile.config.api.jar` to module-path then everything is OK.

Probably problem occurs because in https://github.com/oracle/helidon/blob/master/config/yaml/src/main/java/module-info.java#L31 there is entry `require static...` and later 
https://github.com/oracle/helidon/blob/master/config/yaml/src/main/java/module-info.java#L36 module provides service that SPI cannot be found 
 

## Steps to reproduce

The simplest way:

1) create file `module-info.java`
```
module test.app {
    requires java.logging;
    requires io.helidon.config;
}
```
in `examples/config/sources/src/main/java`

2) execute `mvn clean package`
3) copy jar to libs ` cp helidon-examples-config-sources.jar libs/`
4) execute ` java -p target/libs/ -m test.app`

**Comment by tomas-langer** [comment]
This is temporarily fixed already - the microprofile config API is now a hard dependency of `yaml` module.
