### ISSUE TITLE
microprofile graphql has incosistent module name

### ISSUE THREAD

**Issue by wojtask9** [oracle/helidon#2866]
## Environment Details
* Helidon Version: 2.2.1
* Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

See https://github.com/oracle/helidon/blob/master/microprofile/graphql/server/src/main/java/module-info.java#L22

Current module name `helidon.microprofile.graphql.server` but should be `io.helidon.microprofile.graphql.server`

**Comment by tmiddlet2666** [comment]
Fixed in https://github.com/oracle/helidon/commit/2c64c129a186f6d97f058c4dac3287d80a712ea0
