### ISSUE TITLE
HTTP/2 in Chrome reports ERR_CONNECTION_CLOSED 

### ISSUE THREAD

**Issue by karan-1992** [oracle/helidon#2876]
## Environment Details
* Helidon Version: 2.2.0
* Helidon MP
* JDK version: 11
* OS: Windows
* Docker version (if applicable):NA
* Web browser: Google chrome Version 89.0.4389.90 

----------
Related to issue : #2587 
Used the same testing.zip from the linked issue with the Helidon MP version changed to 2.2.0 and 2.2.1

**Comment by spericas** [comment]
I've downloaded the zip file from Issue #2587 and made the following changes:

- Updated the pom to use Helidon 2.2.1
- Made some changes to the tests that were not passing
- Installed the client certs in Safari and Chrome (Mac OS)
- Loaded the HTML page with the client script in both browsers

I am not able to reproduce the connection closed problem. Will attach zip file with my version of the app as well as some screenshots for you to verify.

**Comment by spericas** [comment]
<img width="1269" alt="Screen Shot 2021-03-25 at 11 08 53 AM" src="https://user-images.githubusercontent.com/5586231/112496314-062bb480-8d5b-11eb-879e-ff32fb699162.png">
<img width="1430" alt="Screen Shot 2021-03-25 at 11 08 42 AM" src="https://user-images.githubusercontent.com/5586231/112496329-088e0e80-8d5b-11eb-8118-3bd3e688f567.png">

**Comment by spericas** [comment]
[issue-2587.zip](https://github.com/oracle/helidon/files/6205769/issue-2587.zip)

**Comment by wojtask9** [comment]
Test on my machine

![image](https://user-images.githubusercontent.com/6099236/112600179-24ec8280-8e11-11eb-9e37-cf260d0cccd7.png)

**Comment by wojtask9** [comment]
@spericas 
You should be able to reproduce this issue if you "slow down" your computer for example if you trigger maven repo reindex in IDE or other IO tasks in another terminal

**Comment by spericas** [comment]
@wojtask9 Thanks for the additional info. Questions:

1. Could you describe what kind of machine you are running this on?
2. Any chance you can try another browser on same machine?
3. Could you please attach the complete server log?

Further analysis on my Mac, if I do multiple reloads with 10 concurrent requests on Chrome, I do see some connections that fail but not in the same way as you describe (mine simply hang) and without any exceptions in the server log. Interestingly, I cannot reproduce the same problems running the script on Safari, which leads me to believe there is a client factor here as well.

**Comment by wojtask9** [comment]
1. Just normal laptop ThinkPad T450

On this laptop with Gentoo Linux I cannot reproduce this issue.
Only on my secondary system (win10) this issue occurs but only when I run server using `git-bash`. 
With normal `cmd.exe` I also cannot reproduce this issue.

`git-bash` has slow STDOUT. Also after redirecting STDOUT to file it is harder to reproduce issue.

Both systems are using JDK 11

2. Firefox 87.0
![image](https://user-images.githubusercontent.com/6099236/112716791-ceeb0e00-8ee8-11eb-90a2-511be5479003.png)

Firefox reports different errors but in server.log I see the same exceptions when using Chrome

3. server.log using Chrome browser after probably 5 page refreshes (I don't remember correctly)
[log.txt.tar.gz](https://github.com/oracle/helidon/files/6215451/log.txt.tar.gz)



@spericas 
If you need some more debug info I can apply patches and build `helidon`

**Comment by spericas** [comment]
After further analysis and testing, I was able to reproduce the `stream id` exception. It is sometimes logged even when no client errors are reported. Now looking for the cause and a resolution.

**Comment by spericas** [comment]
PR #2920
