### ISSUE TITLE
Allow access to the java.sql.Connection from DbExecute

### ISSUE THREAD

**Issue by zimmi** [oracle/helidon#2914]
## Environment Details
* Helidon Version: 2.3.0-SNAPSHOT
* Helidon SE
* JDK version: 16
* OS: debian

----------

## Problem Description
I'm trying to use the [CopyManager](https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/copy/CopyManager.java) from the PostgreSQL JDBC Driver to insert some CSV-Data into my database. That requires access to the underlying `java.sql.Connection`, which seems impossible to obtain from the `io.helidon.dbclient.DbExecute` / `io.helidon.dbclient.DbTransaction` passed to `DbClient::execute` / `DbClient::inTransaction`. The Connection obtained should be part of the current transaction, if possible. Thank you for the work on Helidon, it's a joy to use. :)

Edit: I'm imagining something like this:
```java
dbClient.execute(exec -> {
    Optional<org.postgresql.core.BaseConnection> connection = exec.unwrap(org.postgresql.core.BaseConnection.class);
    // use connection ...
});
```
Ideally, the `JdbcDbClient` variant would handle further unwrapping of the connection (I actually need the `org.postgresql.core.BaseConnection`), but just getting the `java.sql.Connection` would be fine as well.

**Comment by Tomas-Kraus** [comment]
JDBC DbClient instance contains JDBC connection pool so I can add some unwrap to return Single<java.sql.Connection> from this pool when available.
JDBC DbExecute contains CompletionStage<java.sql.Connection> which can be also unwrapped as Single<java.sql.Connection>.

Just keep in mind that you are working with reactive API and anything that you do with pure JDBC is blocking so you have to handle it yourself.

**Comment by zimmi** [comment]
I see, thank you for taking the time @Tomas-Kraus. I don't have any pressing performance needs, so I'm blocking left and right anyway in anticipation of https://github.com/oracle/helidon/issues/2341. But I know that's not encouraged, and I don't want the API to contain any footguns because of it.

This issue in particular is no longer relevant to me, since I have worked around the issue by writing insert statements for the CSV manually. It would be a better fit for https://github.com/oracle/helidon/pull/2796, so feel free to close this one if it can't be done in a safe way with the reactive API and if nobody else has a similar use case.

**Comment by Tomas-Kraus** [comment]
I already have the code so here it is. Maybe someone will find it useful.

**Comment by Tomas-Kraus** [comment]
@zimmi I don't know whether we'll do blocking API extension or not. It does not make sense in Helidon which is reactive.

**Comment by zimmi** [comment]
Thanks a lot for the code, I'm sure it will come in handy. Listening to talks about [Project Loom](https://wiki.openjdk.java.net/display/loom/Main) I got the impression that it will reduce the need for reactive streams by allowing blocking code to scale in a similar fashion. So I assumed that this is the long term goal of Helidon, especially because it's an Oracle effort as well. But I'm happy to be told otherwise.

**Comment by Tomas-Kraus** [comment]
Yes, Project Loom will change a lot. With features like fibres, we can probably start simplifying some reactive APIs which won't be required anymore. But until that, we can't do much in this area.
