### ISSUE TITLE
Provide  integration for for exposing Jaeger client's internal metrics through /metrics endpoint

### ISSUE THREAD

**Issue by vasanth-bhat** [oracle/helidon#2947]
The Jaeger  client's   have a number of  internal metrics  for   key data points on sampler and reporter statistics.   These include data points such as counts of spans reported,  spans  dropped ,  current queue length of the reporter,  sampling strategy changes in case of remote sampling etc. 

 Details of such metrics  are available at  - https://github.com/jaegertracing/jaeger-client-java/blob/7544006e1aaf42c35d1e9dbc086608f6f6964e56/jaeger-core/src/main/java/io/jaegertracing/internal/metrics/Metrics.java#L138

Some of these metrics are very useful  for  diagnosis  of issues  where we see that traces are loosing spans,  or sampling not working as expected. 

Jaeger client provides  SPI  "io.jaegertracing.spi.MetricsFactory"  that is loaded via the Java Service loader  mechanism.   An implementation has to provide  the mechanism to create  the  metrics such as Counter, Timer & Gauge that is specific to the  platform.   

An example  of such  a implementation already exists for Micrometer and is  available at  
https://github.com/jaegertracing/jaeger-client-java/tree/master/jaeger-micrometer

We need to have an implementation for Helidon that will work for both SE as well as MP.    

## Environment Details
* Helidon Version:
* Helidon SE or Helidon MP  - Both 
* JDK version:   11
* OS:
* Docker version (if applicable):

**Comment by vasanth-bhat** [comment]
Tried a quick  prototype. 
There is no code change required in Helidon
Just had to implement the  Jaeger's service provider interface   "io.jaegertracing.spi.MetricsFactory"  , and  make it available to the sample service via adding dependency in pom.xml,  as below 

 <dependency>
            <groupId>io.helidon.tracing.jaeger</groupId>
            <artifactId>helidon-tracing-jaeger-metrics</artifactId>
            <version>1.0</version>
    </dependency>

Now  when I invoke  /metrics   on my sample MP  based service it's also listing the Jaeger's internal metrics

curl -X GET http://localhost:7070/metrics  | grep -i jaeger
# TYPE application_jaeger_tracer_baggage_restrictions_updates_total counter
# HELP application_jaeger_tracer_baggage_restrictions_updates_total
application_jaeger_tracer_baggage_restrictions_updates_total{result="err"} 0
application_jaeger_tracer_baggage_restrictions_updates_total{result="ok"} 0
# TYPE application_jaeger_tracer_baggage_truncations_total counter
# HELP application_jaeger_tracer_baggage_truncations_total
application_jaeger_tracer_baggage_truncations_total 0
# TYPE application_jaeger_tracer_baggage_updates_total counter
# HELP application_jaeger_tracer_baggage_updates_total
application_jaeger_tracer_baggage_updates_total{result="err"} 0
application_jaeger_tracer_baggage_updates_total{result="ok"} 0
# TYPE application_jaeger_tracer_finished_spans_total counter
# HELP application_jaeger_tracer_finished_spans_total
application_jaeger_tracer_finished_spans_total 911
# TYPE application_jaeger_tracer_reporter_queue_length gauge
# HELP application_jaeger_tracer_reporter_queue_length
application_jaeger_tracer_reporter_queue_length 0
# TYPE application_jaeger_tracer_reporter_spans_total counter
# HELP application_jaeger_tracer_reporter_spans_total
application_jaeger_tracer_reporter_spans_total{result="dropped"} 0
application_jaeger_tracer_reporter_spans_total{result="err"} 0
application_jaeger_tracer_reporter_spans_total{result="ok"} 911
# TYPE application_jaeger_tracer_sampler_queries_total counter
# HELP application_jaeger_tracer_sampler_queries_total
application_jaeger_tracer_sampler_queries_total{result="err"} 0
application_jaeger_tracer_sampler_queries_total{result="ok"} 0
# TYPE application_jaeger_tracer_sampler_updates_total counter
# HELP application_jaeger_tracer_sampler_updates_total
application_jaeger_tracer_sampler_updates_total{result="err"} 0
application_jaeger_tracer_sampler_updates_total{result="ok"} 0
# TYPE application_jaeger_tracer_span_context_decoding_errors_total counter
# HELP application_jaeger_tracer_span_context_decoding_errors_total
application_jaeger_tracer_span_context_decoding_errors_total 0
# TYPE application_jaeger_tracer_started_spans_total counter
# HELP application_jaeger_tracer_started_spans_total
application_jaeger_tracer_started_spans_total{sampled="n"} 0
application_jaeger_tracer_started_spans_total{sampled="y"} 912
# TYPE application_jaeger_tracer_traces_total counter
# HELP application_jaeger_tracer_traces_total
application_jaeger_tracer_traces_total{sampled="n",state="joined"} 0
application_jaeger_tracer_traces_total{sampled="n",state="started"} 0
application_jaeger_tracer_traces_total{sampled="y",state="joined"} 2
application_jaeger_tracer_traces_total{sampled="y",state="started"} 5

**Comment by vasanth-bhat** [comment]
Attaching the prototype code 
[helidon-tracing-jaeger-metrics.tar.gz](https://github.com/oracle/helidon/files/6345271/helidon-tracing-jaeger-metrics.tar.gz)

**Comment by vasanth-bhat** [comment]
Can this get integrated into helidon?  if so any inputs as to what time frame?

**Comment by tjquinno** [comment]
Hi, @vasanth-bhat  I have taken a look at the code you attached and thanks very much for the effort to write it. It looks very clear and straightforward.

I plan to begin integrating the prototype into Helidon this week. 

I will need to add some tests, write some documentation, etc. I will also probably register the Jaeger metrics in the `vendor` repository rather than the `application` one, but that's a minor change.

Because of other work in progress it might be a couple weeks or so until I finish this up. I'll keep you posted.
