### ISSUE TITLE
Strikethrough is not rendered in docs

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#295]
https://helidon.io/docs/latest/#/security/02_providers#_http_basic_authentication_provider
"Authorization Provider" and "Audit Provider" should be striked-through in the section that states "This provider is:"

In sources, it was defined as:
* [line-through]#Audit Provider#

This is also not rendered by Github - so maybe we should find a different way for this?

**Comment by romain-grecourt** [comment]
re-opening as fixing this in helidon requires integration of a new version of sitegen.

**Comment by romain-grecourt** [comment]
sitegen 1.0.5 has been integrated in pr #331
