### ISSUE TITLE
Tracing of OCI calls

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#2952]
Validate we can easily add tracing to OCI integration and write a short guide.
This will most likely involve changes in API to enable tracing in MP.

Feature PR #2894

**Comment by m0mus** [comment]
The project name is APM. They've tested their tracer with Helidon and it works. @spericas is involved. We need a better story.

**Comment by tomas-langer** [comment]
This issue was for our custom implementation of OCI client. Closing as this is no longer relevant.
