### ISSUE TITLE
The CLI page should be updated

### ISSUE THREAD

**Issue by fco-code-org** [oracle/helidon#2957]
Hello,

Looking at [https://helidon.io/docs/latest/#/about/05_cli](url), it should be good to highlight that Maven and Java are the pre-requisites to use Helidon cli.

When the Helidon cli on Windows will be available ?

Best Regards.

**Comment by romain-grecourt** [comment]
Thanks for reporting this, I'm moved the issue to the main Helidon repository since this is where the documentation is maintained.

The windows CLI is actually available, we need to update the CLI for the windows support. You can download it here: https://helidon.io/cli/latest/windows/helidon.exe.
