### ISSUE TITLE
Config.Builer resets MetaConfig if we use .addSource method

### ISSUE THREAD

**Issue by wojtask9** [oracle/helidon#2977]
## Environment Details
* Helidon Version:
* Helidon SE 
* JDK version: jdk-11
* OS:
* Docker version (if applicable):

Hello!

I found that Config.Builder.addSource can lead to unexpectedly behaviour.
Here are my concerns about Config.Builder :) 

1. (probably bug)

`meta-config.yaml`

```
sources:
  - type: "environment-variables"
  - type: "system-properties"
```
test
```
@Test
public void test1() {
	System.setProperty("test.sys.prop", "sys_prop");

	Config metaConfig = Config.builder().metaConfig().build();
	Config.Builder builder = Config.builder();
	builder.addSource(ConfigSources.create(Map.of("test.value", "somevalue"))); //(1)coment this
	Config config = builder.config(metaConfig).build();

	assertThat(config.get("test.sys.prop").exists()).isEquals(true);
}
```

Here we want to create Config form MetaConfig. If you comment (1) then this test passes. Otherwise it fails.
This is because 
https://github.com/oracle/helidon/blob/master/config/config/src/main/java/io/helidon/config/BuilderImpl.java#L415
should merge instead of replace configSources.
I would expect from Builder that `.addSource` is additional source and don't replace `meta-config` configuration.

Important part of this issue:
It's not about meta-config but about method `.addSource` from Builder that use other `Config` object as MetaConfig (method `Builder.config(...)`).
If we use `.addSource` then we ignore provided `MetaConfig`

2. Config.Builder.sources (this is orthogonal to previous one)

currently method `.sources()` clears 'sources' added by `.addSource()` (see https://github.com/oracle/helidon/blob/master/config/config/src/main/java/io/helidon/config/BuilderImpl.java#L117)
This causes that builder.sources(...).addSource(...) behaves different from builder.addSource(...).sources(...)

**Comment by tomas-langer** [comment]
I thing there is a misunderstanding here.
Meta configuration is expected to have the content you see in `meta-config.yaml`.
So the line:
```
Config metaConfig = Config.builder().metaConfig().build();
```
does NOT create a meta configuration. It creates a configuration based on the meta-configuration in `meta-config.yaml`.
So line `builder.metaConfig(metaConfig)` breaks everything, as this clears all config sources, as `metaConfig` instance is in fact NOT a meta configuration.

If you want to combine meta configuration and explicit config source, do the following:
```
Config config = Config.builder()
           .metaConfig()
           .addSource(ConfigSources.create(Map.of("test.value", "somevalue")))
           .build();
```
Or (if your meta configuration is in a different file):
```
        Config config = Config.builder()
                .config(Config.create(ConfigSources.classpath("my-meta-config.yaml")))
                .addSource(ConfigSources.create(Map.of("test.value", "somevalue")))
                .build();
```

**Comment by tomas-langer** [comment]
The behavior of methods `sources` and `addSource` is by design and documented in their respective javadocs - as you can see in my answer above, order of invocation of those methods matters.
