### ISSUE TITLE
Static content - classpath should support any classpath resource

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#298]
The classpath content hadler supports only files and jar files (e.g. classpath constructed from directories and/or jars).
We may be running in other types of classpaths (e.g. nested jars) and our static content handler would not work in such a setup.

We should add a generic support for any URL (and use URL.openConnection() to get the content).

Related to #256

**Comment by romain-grecourt** [comment]
Nested JAR isn't supported out of the box in Java. What would the resource path look like if a user wanted to serve static content out of a nested jar resource ?

Also in such case the user could possibly create the classloader for the nested jar and provide the classpath resource for the nested jar resource, right ?

I do agree about generic URL support though, maybe we should rename the title accordingly ?

**Comment by tomas-langer** [comment]
Nested JAR approach is just an example of a classpath constructed from elements that are not jar files nor directories.
The current implementation is not capable of processing any other resource on the classpath (than plain files and files nested in a jar), even though the tools exist in java to do that.

**Comment by romain-grecourt** [comment]
I don't understand the use-cases involving nested jars, what else than plain files should this support ?
Can you illustrate a pseudo example?

**Comment by spericas** [comment]
@tomas-langer I think I understand the general use case that you're referring to. However, I struggle to imagine a developer going the class loader route to read static resources from a DB. I wouldn't consider this type of use case a high priority.

**Comment by tomas-langer** [comment]
I understand the database example is a bit artificial (though I have seen that at customers in Java EE world). Nevertheless nested jars is sometimes used.

**Comment by tomas-langer** [comment]
Also this is labeled as an enhancement ;)

**Comment by romain-grecourt** [comment]
I fail to understand how we would support nested jars.

How does one create a class-path resource for a nested jar without a custom class-loader ? What does the resource path look like ?

**Comment by tomas-langer** [comment]
BTW this is very much valid for Graal native-image, where we would fail to load the static content. 
If this is fixed the way I proposed, we would work just fine also in native-image.
