### ISSUE TITLE
Uptake helidon-build-tools 2.2.0

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#2983]
Integrate helidon-build-tools 2.2.0 after it has been released.

**Comment by tomas-langer** [comment]
- add services maven plugin (and use it to delete all META-INF/services records, or do it by hand), then configure it to generate them (can be done in parent pom, plugin skips pom projects automatically), requires excludes for examples and tests
- add enforcer maven plugin and fix all discovered problems in whole Helidon
- remove existing copyright plugin (obsoleted by Helidon enforcer)

**Comment by barchetta** [comment]
Resolved by PRs #2991 and #2993
