### ISSUE TITLE
MP: Introduce application lifecycle events

### ISSUE THREAD

**Issue by hantsy** [oracle/helidon#3011]
Due to the errors of #2630, I hope Helidon can introduce application lifecycle events to make sure developers do init work at the moment all resoruces are ready for use, or do some clean work before all resources are destroyed.

Like what is done in Spring Boot, such as `ApplicationReadyEvent`

or Quarkus @Startup, @Shutdown event.

**Comment by ljnelson** [comment]
This is already handled via the standard CDI mechanism of observing the initialization of a scope.  For example:
```
private void onStartup(@Observes @Initialized(ApplicationScoped.class) Object event) {
  // this will be called when the application starts
}
private void rightBeforeShutdown(@Observes @BeforeDestroyed(ApplicationScoped.class) Object event) {
  // this will be called right before the application stops
}
```

**Comment by hantsy** [comment]
Obviously, it is not a good approach for a specific framework.
