### ISSUE TITLE
MP: Improve the CDI injection

### ISSUE THREAD

**Issue by hantsy** [oracle/helidon#3012]
## Environment Details
* Helidon Version: 2.2.2
* Helidon MP
* JDK version: 11 and 16
* OS: Windows 
* Docker version (if applicable): 3.3.3 Docker for Windows

1.  Inject dependent beans automatically if there is a single constructor. 

    ```java 
    public class Foo{
        public Foo(Bar bar){
        }
    }
    ```

2.  Inject dependent beans into methods

    ```java 
    public class Foo{
       // auto inject UriInfo here.
        public Response save(Bar bar, UriInfo uri){
        }
    }
     ```
3. Make `@Context` in jaxrs can be replaced by `@Inject`

**Comment by spericas** [comment]
Helidon is based on Jakarta REST. Many of these things are planned, see here https://projects.eclipse.org/projects/ee4j.jaxrs/releases/4.0.0. Closing issue.
