### ISSUE TITLE
Update docs, list basic prerequisites in quickstarts

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#3022]
Currently our quickstart documentation references prerequisites as another page.
It would be good to list the core prerequisites (especially Java version) within the page.

Example: https://helidon.io/docs/latest/#/se/guides/02_quickstart

We should at least note that Java 11 is required, as a lot of people still run on Java 8 and they will get a cryptic exception:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.0:generate (default-cli) on project standalone-pom: Execution default-cli of goal org.apache.maven.plugins:maven-archetype-plugin:3.2.0:generate failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-archetype-plugin:3.2.0:generate: java.lang.UnsupportedClassVersionError: io/helidon/build/archetype/maven/postgenerate/Aether has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
It may be also good to have a check in our library, that would print a more informative exception, such as "You are running on Java 1.8, Helidon minimal required version is Java 11"

**Comment by romain-grecourt** [comment]
There was a check in place that performed by the groovy script. That logic has been moved to a compiled class, which obviously can't work unless the code is compiled for earlier versions of Java ; thus there is a bug in our maven archetype compatibility tooling. I'll create a bug in build-tools to track that.

**Comment by ljamen** [comment]
I can take the doc piece of this (adding the prereqs to the guide vs linking off to a separate topic).

**Comment by ljamen** [comment]
Closing this issue as PR #3168 addresses the doc portion of this issue. Romain was going to create a separate issue to track the build tools enhancement.
