### ISSUE TITLE
Create a convenience method to send a Clear Cookie directive on ServerResponse

### ISSUE THREAD

**Issue by CbxDunderklumpen** [oracle/helidon#3030]
It would be useful to have a easy way to set a HTTP Header which would send a directive to clear an existing cookie.

This can be done by setting a Set-Cookie header where:
* the name and path match the cookie that needs to be cleared.
* the expires and max age attributes are in the past.
* the value should be empty

A convenience method (for example ServerResponse.headers().cookies().clear(....); ) would make this much easier.

## Environment Details
* Helidon Version: 2.2.0
* Helidon SE
* JDK version: 11.0
* OS: (all)
* Docker version (if applicable): n/a

----------

## Problem Description

This is not a problem, but a request for a qualirty of life improvement to the Heldion API

## Steps to reproduce

No repro (see above)

**Comment by spericas** [comment]
PR #3037
