### ISSUE TITLE
HttpBasicAuthProvider.java Fails To Parse Password Containing a Colon (:)

### ISSUE THREAD

**Issue by RichardExley** [oracle/helidon#3041]
## Environment Details
* Helidon Version: 2.2.0
* Helidon MP
* JDK version: 11
* OS: Linux

----------

## Problem Description
Authentication fails if the password contains a colon because the regular expression pattern is incorrect:

`    private static final Pattern CREDENTIAL_PATTERN = Pattern.compile("(.*):(.*)");`

Should be:

`    private static final Pattern CREDENTIAL_PATTERN = Pattern.compile("(.*?):(.*)");`

**Comment by spericas** [comment]
PR #3045
