### ISSUE TITLE
Native image stuck on image testing

### ISSUE THREAD

**Issue by antonio-petricca** [oracle/helidon#3049]
## Environment Details
* Helidon Version: 2.3.0
* Helidon MP
* JDK version: 11
* OS: Ubuntu 18.0.4
* Docker version (if applicable): latest

----------

## Problem Description

I am trying to generated a GraalVM native image as documentated by the demo projects, but during the image generation it stucks for a very long time on image testing stage because my application (a classic REST web service).

With JLINK image generation I found by `mvn helidon:help -Ddetail=true -Dgoal=jlink-image` the `<testImage>false</testImage>` setting which is not available for GraalVM too.

The questions are:

1. Did I miss something?
2. Does `helidon-maven-plugin` send test image termination signal which I could respond to?
3. Is there a way to skip the test image phase?

**Comment by romain-grecourt** [comment]
The `testImage` configuration is only applicable to the `jlink-image` goal, see this [README](https://github.com/oracle/helidon-build-tools/blob/master/maven-plugins/helidon-maven-plugin/README.md) for more information.

**Comment by romain-grecourt** [comment]
Can you share the build output? Can you share a reproducer we can use to reproduce this behavior ?

Also what do you mean by image testing ? If the build is stuck as part of the native-image goal execution then this is not "image testing" but actually the native-image build itself.

**Comment by antonio-petricca** [comment]
I just understood why native image building requires the execution which I have not propertly called test image.

Thank you!
