### ISSUE TITLE
@ConfigProperty fails after upgrade from Helidon 1.4.4 to Helidon 2.3.0

### ISSUE THREAD

**Issue by bogedal** [oracle/helidon#3058]
I have a service which uses constructor injection - like this
`    @Inject
    public OperationsService(@ConfigProperty(name = "operations") Config config) {`

However this fails after I upgraded to Helidon 2.3.0 (See the error in attached image) 
![console-shows-error](https://user-images.githubusercontent.com/42640385/120274373-080c7980-c2b0-11eb-9525-68d71e7da87b.png)

If I debug the config I can see the property in the Config as you can see here
![debug-is-in-config](https://user-images.githubusercontent.com/42640385/120274470-2d00ec80-c2b0-11eb-8a05-80a491dfb9ca.png)

Also note that the unit-test work fine :)

Here is the reproducer project also (Look in run.sh and edit the export line to the path for the sample.yaml file)
[reproducer-cdi-configproperty.zip](https://github.com/oracle/helidon/files/6573764/reproducer-cdi-configproperty.zip)

## Environment Details
* Helidon Version: 2.3.0
* Helidon MP
* JDK version: 11
* OS: Windows

Can you help me understand why this has started to fail after the upgrade?

Kind regards
Bogedal

**Comment by spericas** [comment]
@bogedal Unfortunately, you cannot inject an interior node of the config tree in the latest MP according to its spec. You can either inject a single property using `@ConfigProperty` or map a set of properties with the same prefix using `@ConfigProperties`. What you can do is inject the complete config tree and extract "operations" out of it, which is what you're doing in your unit test. 

Something like:

```
diff -r orig/reproducer-cdi-configproperty/src/main/java/my/reproducer/domain/OperationsService.java reproducer-cdi-configproperty/src/main/java/my/reproducer/domain/OperationsService.java
3,6c3,4
< import my.reproducer.model.OperationOutput;
< import my.reproducer.model.OperationsResponse;
< import io.helidon.config.Config;
< import io.helidon.config.ConfigValue;
---
> import javax.enterprise.context.ApplicationScoped;
> import javax.inject.Inject;
10a9
> import java.util.Optional;
13,15c12,16
< import javax.enterprise.context.ApplicationScoped;
< import javax.inject.Inject;
< import org.eclipse.microprofile.config.inject.ConfigProperty;
---
> 
> import io.helidon.config.Config;
> import io.helidon.config.ConfigValue;
> import my.reproducer.model.OperationOutput;
> import my.reproducer.model.OperationsResponse;
29c30
<     public OperationsService(@ConfigProperty(name = "operations") Config config) {
---
>     public OperationsService(Config config) {
75a77,84
>         Optional<Config> operations = config.asNodeList()
>                 .get()
>                 .stream()
>                 .filter(c -> c.name().equalsIgnoreCase("operations"))
>                 .findFirst();
> 
>         assert operations.isPresent();
> 
77c86
<         ConfigValue<List<Config>> listConfigValue = config.asNodeList();
---
>         ConfigValue<List<Config>> listConfigValue = operations.get().asNodeList();

```

**Comment by bogedal** [comment]
@spericas Thanks for investigation and I change my code accordingly.
Must have missed that in the spec.
Do you have a link to that section ?

**Comment by bogedal** [comment]
@spericas Also a side note 
This code 
`@Inject
    public OperationsService(Config config) {}`

results in an unsatisfied dependency: no bean matches the injection point

**Comment by spericas** [comment]
@bogedal This worked in 1.4 sort of by accident, it was likely related to how it was implemented together with the Helidon SE support. If you look at the Config spec or the Javadocs for the annotations (such as `@ConfigProperty`) you will find that injection of _interior nodes_ (variable of type `Config`) as you were doing in your constructor is not supported. 

 See https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#_simple_dependency_injection_example

You may want to check `@ConfigProperties` and how you can use that to bind properties to a bean.
