### ISSUE TITLE
Enhancement request - ability to reload Helidon server ( private-key ) certificate without restart

### ISSUE THREAD

**Issue by abvaidya** [oracle/helidon#3059]
## Environment Details
* Helidon Version: 2.3.0
* Helidon MP
* JDK version: 11.0.10
* OS: All
* Docker version (if applicable): N/A

----------

## Problem Description
We use short lived certificates on the server and provide file system path config to TLS cert and key ( private-key ). This enhancement request is for server sslcontext to reload if the TLS cert and key has changed, without a need to restart the server.

## Steps to reproduce
N/A ( This is an enhancement request )

**Comment by janotav** [comment]
@abvaidya Did you find a workaround until this is implemented?

**Comment by abvaidya** [comment]
Yes, for now we have been doing restarts / redeployments. The certs are valid for 90 days so it's not a big issue.

**Comment by romain-grecourt** [comment]
See https://github.com/oracle/helidon/issues/2863 and https://github.com/oracle/helidon/blob/master/webserver/webserver/src/main/java/io/helidon/webserver/WebServer.java#L172

**Comment by Verdent** [comment]
May I ask you to test your usecase with the method Romain mentioned? It should do exactly what you expect.

**Comment by Verdent** [comment]
Closing now. If this is still valid issue, please reopen.

**Comment by janotav** [comment]
I can confirm that update functionality appears to be working correctly

**Comment by Verdent** [comment]
Thank you @janotav
