### ISSUE TITLE
Neo4j examples fail when built using JDK 17

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#3064]
## Environment Details
* Helidon Version: 2.3.0
* Helidon SE and Helidon MP
* JDK version: 17-ea+24-2164
* OS: MacOS

----------

## Problem Description

Building the Neo4J examples (`integrations/neo4j/neo4j-se` and `integrations/neo4j/neo4j-mp`) fail when using JDK 17. The failure is in the test:

```
[INFO] Running io.helidon.examples.quickstart.se.MainTest
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.679 s <<< FAILURE! - in io.helidon.examples.quickstart.se.MainTest
[ERROR] io.helidon.examples.quickstart.se.MainTest  Time elapsed: 8.679 s  <<< ERROR!
java.lang.RuntimeException: Error starting Neo4j database server at /var/folders/xs/54nvktvd6f9dn9xrvtt1bpw80000gn/T/9264187dc44b6a86381a5aece383b3d6/data/databases
	at io.helidon.examples.quickstart.se.MainTest.startTheServer(MainTest.java:53)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.dbms.database.DefaultSystemGraphInitializer@7161457' was successfully initialized, but failed to start. Please see the attached cause exception "Could not initialize class org.neo4j.internal.helpers.Exceptions".
	at io.helidon.examples.quickstart.se.MainTest.startTheServer(MainTest.java:53)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.neo4j.internal.helpers.Exceptions
	at io.helidon.examples.quickstart.se.MainTest.startTheServer(MainTest.java:53)

```

## Steps to reproduce

1. Install JDK 17 and verify you are using it: `java --version`
2. Checkout 2.3.0 tag: `git checkout tags/2.3.0`
3. `cd examples/integrations/neo4j/neo4j-se`
4. `mvn clean package`

**Comment by dalexandrov** [comment]
After some investigations and consultations with Neo4j guys, there are the following options:

1. Add the following args to the maven build:
`<argLine>
     --add-opens java.base/java.lang=ALL-UNNAMED --add-exports java.base/sun.nio.ch=ALL-UNNAMED
</argLine>`

2. Stop using Neo4j test harness, and migrate to TestContainers (The preferred option)

**Comment by dalexandrov** [comment]
@romain-grecourt, what do you think about adding these arguments to the build script?

**Comment by romain-grecourt** [comment]
Not sure what you mean exactly. I don't like much the idea of  setting these JVM options globally from the build scripts.
Can we just configure surefire in the neo4j examples?

**Comment by tomas-langer** [comment]
Resolved using surefire configuration (not needed for runtime). As I was fixing the same problem in other modules, I fixed it here as well.

**Comment by dalexandrov** [comment]
Great!
