### ISSUE TITLE
OCI Integration with ATP DB

### ISSUE THREAD

**Issue by arjav-desai** [oracle/helidon#3072]
This task is to document how to integrate helidon apps with ATP DB running in OCI e.g. how wallet file generated can be stored in vault and used with helidon applications etc.

**Comment by aalmiray** [comment]
FWIW Micronaut uses the OCI REST API to request the wallet on the fly and load it in memory thus avoiding the need to store the wallet in a secure location as an intermediate step. You might want to support this use case as an additional option.

**Comment by arjav-desai** [comment]
Thanks @aalmiray for the feedback. We will look into similar feature/API support in Helidon.
