### ISSUE TITLE
Health check introduced runtime dependency on junit-jupiter-params

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#308]
`health/health-checks/pom.xml` and `health/health/pom.xml` has:

```
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <scope>compile</scope>
        </dependency>
```

This results in junit (and other) stuff being pulled in as runtime dependencies.

This should be `test` scope, right?

**Comment by spericas** [comment]
It should, and it works with `test`.

**Comment by romain-grecourt** [comment]
@tomas-langer did you fix this in #310 ?

**Comment by tomas-langer** [comment]
yes

**Comment by tomas-langer** [comment]
yes
