### ISSUE TITLE
A question related to @Timed metric units

### ISSUE THREAD

**Issue by javierdiegof** [oracle/helidon#3088]
Hello, hope you're doing fine :)

I have a question regarding the way the `@Timed` works, when units are specified. 
In the [Helidon MP Metrics Guide](https://helidon.io/docs/v2/#/mp/guides/05_metrics), a code snippet is provided where an endpoint is `@Timed` and the metric named `cardTimer`. 
``` java
package io.helidon.examples.quickstart.mp;

import java.util.Collections;
import javax.enterprise.context.RequestScoped;
import javax.json.Json;
import javax.json.JsonBuilderFactory;
import javax.json.JsonObject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import org.eclipse.microprofile.metrics.MetricUnits;
import org.eclipse.microprofile.metrics.annotation.Counted;
import org.eclipse.microprofile.metrics.annotation.Metered;
import org.eclipse.microprofile.metrics.annotation.Timed;

@Path("/cards")
@RequestScoped
public class GreetingCards {

  private static final JsonBuilderFactory JSON = Json.createBuilderFactory(Collections.emptyMap());

  @GET
  @Produces(MediaType.APPLICATION_JSON)
  @Counted(name = "cardCount", absolute = true) 
  @Metered(name = "cardMeter", absolute = true, unit = MetricUnits.MILLISECONDS) 
  @Timed(name = "cardTimer", absolute = true, unit = MetricUnits.MILLISECONDS) 
  public JsonObject anyCard() throws InterruptedException {
    return createResponse("Here are some random cards ...");
  }

  private JsonObject createResponse(String msg) {
    return JSON.createObjectBuilder().add("message", msg).build();
  }
}
```
As you can see, the units provided are milliseconds using the `unit = MetricUnits.MILLISECONDS` argument. Afterwards, the tutorial shows the output given when querying the `metrics` endpoint:
``` json
{
  "cardCount": 2,
  "cardMeter": {  
    "count": 2,
    "meanRate": 0.3664337145491488,
    "oneMinRate": 0.4,
    "fiveMinRate": 0.4,
    "fifteenMinRate": 0.4
  },
  "cardTimer": { 
    "count": 2,
    "meanRate": 0.36649792432150535,
    "oneMinRate": 0.4,
    "fiveMinRate": 0.4,
    "fifteenMinRate": 0.4,
    "min": 12944,
    "max": 2078856,
    "mean": 1045900.0,
    "stddev": 1032956.0,
    "p50": 2078856.0,
    "p75": 2078856.0,
    "p95": 2078856.0,
    "p98": 2078856.0,
    "p99": 2078856.0,
    "p999": 2078856.0
  }
}
```
Starting with `min` and until the end of the `cardTimer` JSON object, the output seems to display quite big numbers for milliseconds, rather, the units seem to be nanoseconds instead. I timed a project of mine locally and I encountered the same behaviour: the units seem to be nanoseconds instead of the ones specified, regardless of the particular units. 

Is this the correct behaviour, or is it a bug where the units specified are being ignored? What am I missing?

Thanks in advance for all your help.

**Comment by tjquinno** [comment]
This is definitely a Helidon bug. The JSON output should use the units set on the timer for formatting the histogram information.

I have a fix ready for review.

**Comment by javierdiegof** [comment]
Thanks a lot guys, appreciate it :)
