### ISSUE TITLE
Should automatically provide GraalVM settings when endpoint accepts or returns a POJO

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#3090]
## Environment Details
* Helidon Version: 2.3.0
* Helidon SE or Helidon MP MP
* JDK version: n/a
* OS: n/a
* Docker version (if applicable): n/a

----------

## Problem Description
A JAX-RS endpoint method which returns a POJO works fine when launched using `java -jar` but returns empty responses when run as a native image.

## Steps to reproduce
1. Use `helidon init` to create an MP project based on the quick-start example.
2. Add a POJO `Message` class with the `String` attribute `message`:
    ```
    public class Message {
        private String message;
    
        public Message(String msg) {
            message = msg;
        }
    
        public String getMessage() {
            return message;
        }

        public void setMessage(String message) {
            this.message = message;
        }
    }
    ```
3. Modify one of the generated endpoints, or add a new one at a new path, which instantiates and returns a `Message` object instead of `JsonObject`:
    ```
        @GET
        @Path("/pojo")
        @Produces(MediaType.APPLICATION_JSON)
        public Message getDefaultMessagePojo() {
            return new Message(String.format("%s %s!", greetingProvider.getMessage(), "World"));
        } 
    ```
4. Build for GraalVM but run _without_ GraalVM:
    ```
    mvn package -Pnative-image
    java -jar target/quickstart-mp.jar
    ```
    Access the endpoint: `curl http://localhost:8080/greet/pojo` The response is as expected.
5. Run _with_ GraalVM (`-Pnative-image`). Access the endpoint. The response is empty.

## To work around this:
1. Add 
    ```
    [
      {
        "name": "me.tjquinn.mp.quickstart.Message",
        "allPublicConstructors" : true,
        "allPublicMethods" : true
      }
    ]
    ```
    to the empty generated `META-INF/native-image/reflect-config.json` file.
2. Rebuild (with `-Pnative-image`) and rerun. The response is now correct.

## Change:
Ideally, Helidon would automatically generate the `reflect-config` data for any POJO that the developer uses as a JAX-RS endpoint parameter or return value.

**Comment by tomas-langer** [comment]
We do not need to generate `reflect-config.json` in this case - the native image extension can analyze the resource classes during native image build and add them for reflection programmatically (as we do it for a lot of classes already).

Also this is only needed for classes that are not annotated by any annotation (for example for `@Entity` we already do this).

The cases I see here:

1. Any public method on a resource class that returns a pojo (other then Response)
2. Any public method on a resource class with entity parameter (non-annotated parameter of method)
3. What about other entry points? Such as GraphQL, grpc, messaging? Is there a similar case where an unnanotated POJO can be used for serialization through JSON-B or similar, that requires reflection at runtime?

**Comment by tjquinno** [comment]
True enough, It doesn't make much difference _how_ Helidon would provide the GraalVM settings for such POJO classes, whether by generating `reflect-config.json` content or treating the class as if it were annotated with `@Reflected` or in some other way. 

The goal is to take this burden off the developer in some way for POJOs used in declaring endpoints. If there are other similar uses in other contexts which the extension could discover and act on, all the better.
