### ISSUE TITLE
generated pom.xml is incorrect

### ISSUE THREAD

**Issue by delabassee** [oracle/helidon#31]
- Generate a Quickstart project using the Mvn archetype.

- `xsi:schemaLocation` is incorrect

`--><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mav         en.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">`

**Comment by biezhi** [comment]
I have a problem with the `mvn` generated structure, but I can run it.

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mav         en.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
```

**Comment by delabassee** [comment]
it works but it's quite ugly

**Comment by barchetta** [comment]
We generate the archetypes on the fly from the quickstart examples as part of the build. Looks like we have a bug in `examples/archetypes/create-archetypes.sh` when it modifies the quickstart pom.
