### ISSUE TITLE
helidon-tests-integration-mp-graphql fails with JDK 17

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#3100]
## Environment Details
*  Helidon Version: 2.3.1-SNAPSHOT
* MP
* JDK version: java 17-ea 2021-09-14 LTS
* OS: Oracle Linux Server release 7.7

----------

## Problem Description
The test `tests/integration/mp-graphql` fails when built with JDK 17.

## Steps to reproduce

1. Set JAVA_HOME to JDK 11 and do priming build of helidon repo: `mvn clean install -DskipTests`
2. Set JAVA_HOME to JDK 17 and build test:
```
cd tests/integration/mp-graphql
mvn clean install

```
Fails with:
```
[ERROR] io.helidon.microprofile.graphql.server.DateTimeIT.testDatesAndMutations  Time elapsed: 0.055 s  <<< FAILURE!
java.lang.AssertionError:

Expected: is "17 Feb. 1968"
     but: was "17 Feb 1968"
	at io.helidon.microprofile.graphql.server.DateTimeIT.testDatesAndMutations(DateTimeIT.java:253)
```

**Comment by tmiddlet2666** [comment]
Looks like this - https://bugs.openjdk.java.net/browse/JDK-8208487
I will remove the en-AU local tests as they are unpredictable.
