### ISSUE TITLE
`host` vs `bind-address` configuration issues

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#3103]
## Environment Details
* Helidon Version: 2.3.0
* Helidon SE and Helidon MP

----------

## Problem Description

While investigating a questions from a user I've uncovered issues with configuring the bind-address for the default socket.

1. In Helidon SE the `host` configuration property for the default socket appears to be ignored. We use this property in many of our examples including the quickstarts. It looks like these should be changed to `bind-address`.  For named sockets it looks like we do always use `bind-address` (but see related issue #3104).
2. The above is also true for Helidon MP examples where `server.host` is usually ignored but `server.bind-address` works. I think this is because the MP configuration is converted to SE config and passed to WebServer and it hits 1 above.
3. But beware in MP Server because there is code that assumes `server.host` when the Server builder is explicitly used : https://github.com/oracle/helidon/blob/69812d43c53e4f777cf872c176a4a0221ee83366/microprofile/server/src/main/java/io/helidon/microprofile/server/Server.java#L259

## Steps to reproduce
1. Generate the Helidon SE quickstart application. Build and run it. It works!
2. Change the `host` attribute to your local IP address like:
    ```
    server:
      port: 8080
      host: 192.1.2.3
    ```
    Build and run the app and you see it still binds to the default address (0.0.0.0).
3. Change `host:` to `bind-address:` and build and run again and voila! It binds to the IP address as it should.
4. You can do something similar with the Helidon MP quickstart.

**Comment by tomas-langer** [comment]
As there is a bit of a confusion here and we use `host` extensively in our examples, we should support both `host` and `bind-address`.
We can decide which one of these to deprecate.

**Comment by tomas-langer** [comment]
I have changed the behavior to work as expected in examples:
- `host` is only supported on `server` configuration; `bind-address` can also be used
- `bind-address` must be defined on named sockets (`host` is ignored for named sockets)

**Comment by barchetta** [comment]
I've also reproduced this in 1.4.8.
