### ISSUE TITLE
Named sockets ignore `bind-address`

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#3104]
## Environment Details
* Helidon Version: 2.3.0
* Helidon SE and Helidon MP

----------

## Problem Description
If you configure your Helidon application with named sockets on different IP address, it appears as though the `bind-address` property on the name socket is ignored and the `bind-address` property on the default socket is used instead.

## Steps to reproduce
1. Build `examples/webserver/mutliport` and run it. This defines multiple sockets on different ports, but all bound to `localhost`. It works.
2. In `application.yaml` change the `bind-address` for socket `private` from localhost to your local IP. Build and run and when the server starts you'll see the private channel still binds to 0.0.0.0. 
3. In `application.yaml` change the `private` bind-address back to localhost. 
3. In `application.yaml` change the default server `host: "localhost"` to `bind-address: <your local IP>` (yes you need to change `host` to `bind-address` see issue #3103 ).
4. Now when you build and run you'll see *all* sockets bind to the IP

So the `bind-address` configuration on the named sockets is ignored and the one on the default server is always used.

Looks like the problem is here:
https://github.com/oracle/helidon/blob/69812d43c53e4f777cf872c176a4a0221ee83366/webserver/webserver/src/main/java/io/helidon/webserver/NettyWebServer.java#L245

This code is executed for each named socket. The `port` is correctly pulled from the named socket configuration, but the bindAddress is always pulled from the server configuration.

**Comment by barchetta** [comment]
I've also reproduced this in 1.4.8

**Comment by tomas-langer** [comment]
Reopened to be fixed in our 1.x branch

**Comment by tomas-langer** [comment]
This issue is now fixed in both 1.x and 2.x branches
