### ISSUE TITLE
Customizable path for vault k8s auth

### ISSUE THREAD

**Issue by belcherbrandon** [oracle/helidon#3106]
## Environment Details
* Helidon Version: 2.3.0
* Helidon SE
* JDK version: 11

----------

## Problem Description
We need to be able to authenticate against a different vault login path than the default "kubernetes" path that is currently being used.

What is being used currently: https://vault:8200/v1/auth/kubernetes/login
What we need: https://vault:8200/v1/auth/my-custom-path/login

**Comment by tomas-langer** [comment]
This would probably be useful for all vault authentications (token, app role & k8s)
