### ISSUE TITLE
Enable DataFetchingEnvironment as part of @GraphQLApi @Query methods

### ISSUE THREAD

**Issue by dvirguttman** [oracle/helidon#3110]
Helidon Version: 2.3
Helidon SE or Helidon MP: MP
JDK version: 11
OS: MacOS 11.4

----------

## Problem Description
Lets assume we have class `AllResources`that contains Resource A,B,C..:
```
AllResources {
 ResourceA
 ResourceB
 ResourceC
...
}
```
Each resource is in different DB table, and it takes time to process each one of them.
We would like to expose single endpoint and process ResourceX query only if the user request it.
If it was possible to add to `@Query` method something like `ExecutionInput` it was great..

**Comment by tmiddlet2666** [comment]
Similar to https://github.com/oracle/helidon/issues/2990

**Comment by dvirguttman** [comment]
The same is for `@Context SecurityContext` (io.helidon.security.SecurityContext) - we need to authorize some of our graphql endpoints and security context is needed..

**Comment by tmiddlet2666** [comment]
@dvirguttman 
Are you able to provide a bit more info on this requirement?

> Each resource is in different DB table, and it takes time to process each one of them.
> We would like to expose single endpoint and process ResourceX query only if the user request it.
> If it was possible to add to @Query method something like ExecutionInput it was great..

Regards the above, if you have 3 queries defined, ResourceA, ResourceB and ResourceC, only the query that is targeted by an individual GraphQL request, say `query { ResourceA }` will be executed. Graphql does expose the single endpoint and only the query requested is executed.

Is this what you mean otherwise, please provide some more context, code example you are after.
Thanks

**Comment by dvirguttman** [comment]
@tmiddlet2666 
Hope that is make more sense :
```
class ResourceA {
  //...
}

class ResourceB {
  //...
}

class AllResources {
  ResourceA a;
  ResourceB b;
}

@GraphQLApi
@ApplicationScoped
public class Sample {
    
  
  @Query
  @Description("Get Resource A")
  public ResourceA getResourceA() {
    return repository.getResourceA();
  }
  
  @Query
  @Description("Get Resource B")
  public ResourceB getResourceB() {
    return repository.getResourceB();
  }

  // This is current situation:
  // 1. User ask for all resources, but query only resourceA
  // 2. Our application code query both resourceA & resourceB
  // 3. GraphQL framework filter out resourceB from result
  @Query
  @Description("Get All Resources")
  public AllResources getAllResources() {
    return AllResourcesBuilder.create()
        .resourceA(repository.getResourceA())
        .resourceB(repository.getResourceB())
        .build();
  }

  // We would like to save expensive call "repository.getResourceB()"
  // For that, annotation like ExecutionInput or so, might give us this ability and save significant time.
  @Query
  @Description("Get All Resources")
  public AllResources getAllResources(@ExecutionInput input) {
    return AllResourcesBuilder.create()
        .resourceA(input.contains(resourceA) ? repository.getResourceA() : null)
        .resourceB(input.contains(resourceB) ? repository.getResourceB() : null)
        .build();
  }
  
}
```
Please let me know
Thanks

**Comment by tmiddlet2666** [comment]
@dvirguttman Thanks for that clarification.
I assume you are referring to https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/ExecutionInput.java ?
If this is the case, then i think that is doable.

**Comment by tmiddlet2666** [comment]
Regarding SecurityContext, this would require full security integration with Helidon. I will add another issue for this.

**Comment by dvirguttman** [comment]
Yes, that was my meaning. Thanks!
Regarding the Security Context, it is possible to inject it to the bean so there is workaround for that..

**Comment by tmiddlet2666** [comment]
@dvirguttman 
Please see my fork IT:

https://github.com/tmiddlet2666/helidon/blob/issue-3110/tests/integration/mp-graphql/src/test/java/io/helidon/microprofile/graphql/server/ExecutionInputIT.java

Which uses:
https://github.com/tmiddlet2666/helidon/blob/issue-3110/microprofile/graphql/server/src/test/java/io/helidon/microprofile/graphql/server/test/queries/ExecutionInputQueriesAndMutations.java#L32

```
    @Query
    public String testExecutionInputNoArgs(ExecutionInput input) {
        return input.getQuery();
    }

    @Query
    public String testExecutionInputWithArgs(@Name("name") String name, ExecutionInput input) {
        return name + input.getQuery();
    }

    @Query
    public String testExecutionInputWithArgs2(@Name("name1") String name1, ExecutionInput input, @Name("name2") String name2) {
        return name1 + name2 + input.getQuery();
    }
```

**Comment by dvirguttman** [comment]
Thanks @tmiddlet2666 
Just to clarify, so `ExecutionInput input` is optional for `@Query` method, correct?

I see that `input.getQuery()` returns the query string.
If we already processed that string into Map (or some data structure) is it possible to expose also that? (and avoid string processing again)
Thanks

**Comment by tmiddlet2666** [comment]
@dvirguttman Yes the ExecutionInput is optional.

I guess you could store the value in a Context? https://helidon.io/docs/v2/apidocs/io.helidon.common.context/io/helidon/common/context/Context.html
The class with the queries is a CDI Bean so you could do anytying you wanted in there.
would need to be thread safe of course.

**Comment by dvirguttman** [comment]
Thanks

Actually, I meant for something little bit different (but it is probably out of your control)
On helidon graphql library execution you are callint to the GaphQl library:
https://github.com/oracle/helidon/blob/master/graphql/server/src/main/java/io/helidon/graphql/server/InvocationHandlerImpl.java#L95
Inside, within `Execution` we are building the `OperationDefinition`(it is also part of the `ExecutionContext`) that contains the selection set: `operationDefinition.getSelectionSet()`.
This selection set contains the user query data in convenient way.

**Comment by tmiddlet2666** [comment]
@dvirguttman 
Ah ok, so this is available on the DataFetchingEnvironment which is available when a method is being executed.
https://github.com/oracle/helidon/blob/master/microprofile/graphql/server/src/main/java/io/helidon/microprofile/graphql/server/DataFetcherUtils.java#L110

I'm thinking then instead of the ExecutionInput being the method being recognised as a param, we could allow DataFetchingEnvironment, which actually has more information available that Execution Input has.

I think that would be more useful. What do you think?

**Comment by dvirguttman** [comment]
Yeah, that will be great.
`environment.getExecutionStepInfo().getField().getSingleField().getSelectionSet().getSelections()` is exactly what I need..

**Comment by tmiddlet2666** [comment]
Closed via https://github.com/oracle/helidon/pull/3204

**Comment by tmiddlet2666** [comment]
@dvirguttman That is committed now. It will be available when the next helidon release is done.
Thanks for your input.

**Comment by dvirguttman** [comment]
Great!
Thanks @tmiddlet2666

**Comment by dvirguttman** [comment]
@tmiddlet2666 thanks!
