### ISSUE TITLE
JEP 290 - deserialization filters

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#3158]
Although Helidon does not use any Java serialization, we should provide a robust approach to JEP 290

This may include:

- [ ] #3200
- [x] Allow custom filters overriding this default
- [x] (maybe) only do whitelisting with blacklist being everything else
- [x] Blog article

**Comment by tomas-langer** [comment]
Minimal code to resolve this:
```
        if (ObjectInputFilter.Config.getSerialFilter() == null) {
            ObjectInputFilter filter = ObjectInputFilter.Config.createFilter("!*");
            ObjectInputFilter.Config.setSerialFilter(filter);
        }
```

**Comment by delabassee** [comment]
FYI https://openjdk.java.net/jeps/415 (Java 17)
