### ISSUE TITLE
Doc: dead link

### ISSUE THREAD

**Issue by delabassee** [oracle/helidon#3165]
## Environment Details
NA

----------

## Problem Description

The [SE  —  Fault Tolerance in Helidon SE](https://helidon.io/docs/v2/#/se/faulttolerance/01_faulttolerance) page  links to the 
[Fault Toleance SE API Javadocs](https://helidon.io/docs/v2/apidocs/io.helidon.faultolerance/io/helidon/faultolerance/package-summary.html) wich is a 404!

**Comment by romain-grecourt** [comment]
Blame the javadoc tool ;)
https://helidon.io/docs/v2/apidocs/io.helidon.faulttolerance/io/helidon/faulttolerance/package-summary.html

**Comment by spericas** [comment]
PR #3167
