### ISSUE TITLE
Need to fix Helidon MP/SE doc - Metrics Support for Exemplars (typo)

### ISSUE THREAD

**Issue by shukawam** [oracle/helidon#3174]
## Environment Details
* Helidon Version: 2.3.1
* Helidon MP and SE

----------

ref: 
- [https://github.com/oracle/helidon/blob/master/docs/shared/metrics/prometheus-exemplar-support.adoc](https://github.com/oracle/helidon/blob/master/docs/shared/metrics/prometheus-exemplar-support.adoc)

now: If a metric necessarily corresponds to a specific sample—​for example a minimum or maximum—​Helidon associates a sample that has that exact value as the exemmplar for the metric.

shoud be: If a metric necessarily corresponds to a specific sample—​for example a minimum or maximum—​Helidon associates a sample that has that exact value as the exemplar for the metric.

**Comment by ljamen** [comment]
Fixed in PR #3225
