### ISSUE TITLE
Need to fix Helidon MP/SE doc - OCI Vault (image src is invalid)

### ISSUE THREAD

**Issue by shukawam** [oracle/helidon#3175]
## Environment Details
* Helidon Version: 2.3.1
* Helidon MP and SE

----------

ref: [https://helidon.io/docs/v2/#/mp/oci/03_vault](https://helidon.io/docs/v2/#/mp/oci/03_vault)

The image src does not seem to be set up properly.

![image](https://user-images.githubusercontent.com/62193282/124349478-260c2780-dc2a-11eb-969a-27bbb2ea41d5.png)

Currently, the documentation says `image::oci/ocivault.png[OCI Vault, align="center"]`, but I think it should be `image::oci/vaultkey.png[OCI Vault, align="center"]`. Isn't it?

**Comment by ljamen** [comment]
See PR #3224
