### ISSUE TITLE
Memory leak with Request Scope and Fault Tolerance

### ISSUE THREAD

**Issue by gmpatter** [oracle/helidon#3199]
## Environment Details
* Helidon Version: 2.3.0
* Helidon MP
* JDK version: 11.0.9
* OS: MacOS 11.4

----------

## Problem Description
With Helidon MP 2.3.0 I’m seeing a potential memory leak in our application. In a heap dump from one load test I could see 595,000 instances of org.jboss.weld.contexts.SerializableContextualInstanceImpl with reference to an instance of Hk2RequestScope being hung on to by HelidonCdi instanceCache.

It seems to happen when injecting ServerRequest into a resource to use in an endpoint, while also using a Fault Tolerance annotation on the endpoint. Without the FT annotation I’m not seeing any instance of org.jboss.weld.contexts.SerializableContextualInstanceImpl created with reference to Hk2RequestScope.

## Steps to reproduce
Create a new helidon-quickstart-mp app.

Inject ServerRequest and update the GET endpoint to use ServerRequest. Also add @Timeout annotation to the GET endpoint:
```
@Context
ServerRequest mServerRequest;

@Path("/{name}")
@GET
@Produces(MediaType.APPLICATION_JSON)
@Timeout
public JsonObject getMessage(@PathParam("name") String name) {
  return createResponse(name + " tenant " + mServerRequest.headers().first("X-CCTenantId").get());
}
```
Make n number of requests to the endpoint:
```
for ((i=1;i<=1000;i++)); do   curl -v --header "X-CCTenantID: tenant1" "localhost:8080/greet/gareth"; done
```
Take a heap dump, you can see n number of SerializableContextualInstanceImpl with instance=org.glassfish.jersey.inject.hk2.Hk2RequestScope. Eclipse MAT OQL query:
```
SELECT instance AS instance FROM org.jboss.weld.contexts.SerializableContextualInstanceImpl s WHERE instance.toString().contains("org.glassfish.jersey.inject.hk2.Hk2RequestScope")
```
Force GC, take another heap dump and still see n number of SerializableContextualInstanceImpl.

**Comment by gmpatter** [comment]
Although in the simple reproducer I see one instance per request, in our app, with multiple CDI beans using FT annotations and injecting ServerRequest, we see 9 instances created per request. Just adding in case it adds any extra layer of complication.

**Comment by spericas** [comment]
@gmpatter Do you have a sense as to whether this issue was present in earlier versions of Helidon? Or was 2.3.0 the first version you tried this with?

**Comment by gmpatter** [comment]
@spericas unfortunately I don't. 2.3.0 is the first version I've noticed it in, but our load tests hadn't been run in quite a while so  can't really say when it might have started.

**Comment by spericas** [comment]
I'm able to confirm the problem. Information collected is as follows, with O(N) or O(1) based on number of requests:

- Number of `SerializableContextualInstanceImpl` instances grows monotonically and O(N).
- Number of instances from package `io.helidon.microprofile.faulttolerance` (MP) is O(1).
- Number of instances from package `io.helidon.faulttolerace` (SE) is O(1).

Currently investigating other places in Helidon and Jersey.

**Comment by spericas** [comment]
Multiple entries in CDI cache related to Hk2RequestScope:

<img width="914" alt="Screen Shot 2021-07-21 at 3 40 24 PM" src="https://user-images.githubusercontent.com/5586231/126550339-ddf90f18-9294-42f8-8e58-8b6dd5765bf9.png">

**Comment by spericas** [comment]
PR #3214

**Comment by spericas** [comment]
@gmpatter A couple of issues you reported recently have been fixed in SNAPSHOT. Do you have some time to build from sources and try the fixes? Should be useful before the next release.

**Comment by gmpatter** [comment]
@spericas I've tested #3199 and #3194 with latest snapshot locally and both are resolved. Thanks!
