### ISSUE TITLE
The whenShutdown logic is not executed

### ISSUE THREAD

**Issue by biezhi** [oracle/helidon#32]
I tried to start `quickstart-se` from the command line, and I started it from the IDE. I press `Ctrl+C` or use the IDE to close the program (actually sending the kill -2 signal), and the logic in `server.whenshutdown()` is not executed.

**shutdown logic**

```java
server.whenShutdown().thenRun(()
                -> System.out.println("WEB server is DOWN. Good bye!"));
```

**terminal**

```bash
» java -jar target/quickstart-se.jar
WEB server is up! http://localhost:8080
^C%
```

**IDE**

```java
WEB server is up! http://localhost:8080
Disconnected from the target VM, address: '127.0.0.1:49495', transport: 'socket'

Process finished with exit code 130 (interrupted by signal 2: SIGINT)
```

**Comment by spericas** [comment]
The `whenShutdown()` returns the `CompletableFuture` for the server in question, it is **not** a JVM shutdown hook. If you have multiple servers running on different ports, each one could have a different handler registered for that event. To trigger such a handler, a server must be stopped using `shutdown()` or implicitly after an unrecoverable error. 

If you have a need for a JVM shutdown hook, please file a request for such a feature.
