### ISSUE TITLE
Micrometer test in examples fails

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#3212]
Follow up of #3210 

The test in io.helidon.examples.micrometer.se.MainTest does not have `.await()` in the last section that validates Micrometer.
The #3210 will separate the tests into methods and disable it.

The original test would just hang, as the failures are not correctly propagated. The test actually fails with:
```
org.opentest4j.AssertionFailedError: Unable to find expected all-gets timer count 2.0 ==> 
Expected :true
Actual   :false
```

**Comment by tomas-langer** [comment]
The method to fix is `testMicrometer` in the refactored code

**Comment by tjquinno** [comment]
Fix is ready; waiting for @tomas-langer to merge #3213
