### ISSUE TITLE
Is it possible to auto generate swagger for helidon SE?

### ISSUE THREAD

**Issue by nieliecious** [oracle/helidon#3227]
## Environment Details
* Helidon Version: 2.3.2
* Helidon SE 
* JDK version: 11
* OS: MAC

----------

Is there a way to auto generate swagger for Helidon SE?

**Comment by romain-grecourt** [comment]
Currently generation of a Swagger/OpenAPI spec is only supported with Helidon MP.

**Comment by romain-grecourt** [comment]
See https://github.com/oracle/helidon/issues/3231
