### ISSUE TITLE
exemplar use causes unexpected "MNAME" error from prometheus

### ISSUE THREAD

**Issue by paulparkinson** [oracle/helidon#3230]
When using exemplar feature, prometheus scrape receives the following error:
"expected timestamp or new record, got "MNAME" "

## Environment Details
* Helidon Version: 2.3.1
* Helidon MP
* JDK version: GraalVM CE 20.1.0
* OS: Linux 
* Docker version (if applicable):

----------

## Problem Description
See above

## Steps to reproduce
1. Add metrics and tracing to application such as 
     https://github.com/oracle/microservices-datadriven/tree/main/grabdish/order-helidon
     https://github.com/oracle/microservices-datadriven/blob/main/grabdish/order-helidon/src/main/java/io/helidon/data/examples/OrderResource.java
2. Add required dependency such as...
        <dependency>
            <groupId>io.helidon.tracing</groupId>
            <artifactId>helidon-tracing-jaeger</artifactId>
        </dependency>
3. Notice prometheus scrape is successful
4. Add additional exemplar dependency...
        <dependency>
            <groupId>io.helidon.metrics</groupId>
            <artifactId>helidon-metrics-trace-exemplar</artifactId>
            <scope>runtime</scope>
        </dependency>
5. Notice prometheus scrape gives error "expected timestamp or new record, got "MNAME" "

**Comment by tjquinno** [comment]
I tried following Paul's steps with the simple Helidon MP quick-start app, and things seemed to work just fine.

I'm now starting to work with the project he pointed to, seeing if I can sidestep the DB connectivity to test more easily (and hope in the process I don't perturb the experiment so much that the error won't occur).

**Comment by tjquinno** [comment]
See also #3194  Might be the underlying cause of the blanks labels, but the exemplar code should tolerate blank labels anyway.
