### ISSUE TITLE
Make sure JAX-RS client responses are closed in examples

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#3249]
Validate that all examples (and other usages) of JAX-RS clients correctly close responses (and clients if relevant)

**Comment by jansupol** [comment]
The archetypes ([for instance quickstart](https://github.com/oracle/helidon/blob/master/archetypes/quickstart-mp/src/main/resources/src/test/java/__pkg__/MainTest.java.mustache)) would be good to be closed as well. Autoclosable can be used:
```
try (Response r=...) {
}
```

**Comment by spericas** [comment]
Clearly we should do this in server environments and for long-lived VM's. But do we really want to update the code in all relevant tests even though those are short-lived VM's? Clearly correct but also a bit academic in a testing environment.

**Comment by spericas** [comment]
PR #3259
