### ISSUE TITLE
WebClient API hangs when trying to connect using http to an https EP

### ISSUE THREAD

**Issue by delabassee** [oracle/helidon#3254]
## Environment Details
* Helidon Version: 2.3.2
* Helidon SE (haven't tested on Helidon MP)
* JDK version: 17-EA
* OS: OSX
* Docker version (if applicable): NA

----------

## Problem Description

My tests are using the WebClient API. The App is configured with the deployment cert (so locally, the cert is invalid) and is listening using https on 8080.

- webclient trying to connect to https://localhost:8080 will properly fail with a SSLHandshakeException 
- webclient trying to connect to http://localhost:8080 will hang forever

**Comment by Verdent** [comment]
Fixed by #3305
