### ISSUE TITLE
Messaging creates new config where it should not

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#3287]
`Messaging` interface (line 351) uses `Config.create()`
This method should never be used from inside Helidon components, as it may produce invalid config (or even throw an exception - such as with invalid meta configuration).

Please use `Config.empty()` instead, or find another way of obtaining a valid configuration.

**Comment by danielkec** [comment]
@tomas-langer The change is backward incompatible, this fix should be targeted for 3.0.0
