### ISSUE TITLE
Native-image for Alpine OS (musl) not working 

### ISSUE THREAD

**Issue by Franos13** [oracle/helidon#3367]
Helidon Version: 2.3.2
Helidon MP
JDK version: 11
OS: Alpine OS

----------

## Problem Description
Try to generate an Alpine OS native executable  using mvn -Pnative-image -DskipTests=true clean package

## Steps to reproduce
Ubuntu 20.04 
Install GraalVM java11-21.2.0
Install musl 2.2.2: configure/make/make install
Install build-essential 
Copy /usr/lib/x86_64-linux-gnu/libz.a <GRAALVH_HOME>/lib/static/linux-amd64/musl
Extract from an Alpine docker image with apk add g++, libstdc++.a
Copy this one under <GRAALVH_HOME>/lib/static/linux-amd64/musl
Rename the libstdc++.a under /usr/lib/gcc/x86_64-linux-gnu/9/ (for exemple mv libstdc++.a libstdc++.aa) in order to not have any conflict 
Using Helidon CLI create a MP project
mkdir <myhelidon project>/src/main/META-INF/native-image/group-id/artifact-id
Create under this folder native-image.properties file with content: Args=--static --libc=musl
Then run mvn -Pnative-image -DskipTests=true clean package

Run file <myhelidon project>/target/<executable generated> => LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=4b99011c879e2f45b2d8246594ab241a08347963, for GNU/Linux 3.2.0, with debug_info, not stripped
instead of: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped

**Comment by romain-grecourt** [comment]
Can you try with `-Dnative.image.buildStatic=true`.

Or in your pom.xml:
```
<plugin>
    <groupId>io.helidon.build-tools</groupId>
    <artifactId>helidon-cli-maven-plugin</artifactId>
    <configuration>
        <buildStatic>true</buildStatic>
    </configuration>
</plugin>
```

See the helidon-maven-plugin [usage](https://github.com/oracle/helidon-build-tools/tree/master/maven-plugins/helidon-maven-plugin#goal-native-image)

**Comment by Franos13** [comment]
Hello Romain,
Having this in the pom:
<plugin>
                <groupId>io.helidon.build-tools</groupId>
                <artifactId>helidon-maven-plugin</artifactId>
                **<configuration>
                        <buildStatic>true</buildStatic>
                        <additionalArgs>
                                <additionalArg>--static</additionalArg>
                                <additionalArg>--libc=musl</additionalArg>
                        </additionalArgs>
                </configuration>**
                <executions>
                    <execution>
                        <id>third-party-license-report</id>
                    </execution>
                </executions>
</plugin>

It works perfectly :-) I was able to generate an executable that works fine on Alpine OS: it's great. 

Thanks a lot Romain !

Best Regards.

**Comment by tomas-langer** [comment]
The properties file must be under resources directory, so it is added by maven to the jar file:

mkdir /src/main/META-INF/native-image/group-id/artifact-id is wrong, please use

`mkdir ./src/main/resources/META-INF/native-image/group-id/artifact-id` and then put `native-image.properties` file there
The `group-id` and `artifact-id` are placeholders for your module. Example for Helidon common module would be:
`src/main/resources/META-INF/native-image/io.helidon.common/helidon-common/native-image.properties`

**Comment by Franos13** [comment]
Hello Tomas,

Check that on my side.
With the good location (ie /src/main/**resources**/META-INF/native-image/group-id/artifact-id) for native-image.properties with Args=--static --libc=musl content it works :-)

Best Regards.

**Comment by tomas-langer** [comment]
Closing this issue as we have resolved both issues.
Please reopen (or create a new issue) if this is not sufficient.
Thanks
