### ISSUE TITLE
Helidon memory consumption

### ISSUE THREAD

**Issue by Tibor17** [oracle/helidon#3401]
I am using the version `2.3.2` on Windows.
I guess high memory consumption is caused by Jersey.
Quarkus consumes only 70 MiB in pure java mode and Quarkus uses Netty and Resteasy which is maybe the reason.
My application has default REST server JAX-RS, so both Helidon and Quarkus are comparable in terms on API.

Helidon should be used by projects for which the memory footprint is mandatory value.

Not sure if my singletons become optimized in Helidon. The beans may also consume great part of the heap. Basically, there are only two ecosystems and reactive frameworks with SE features, Vertx and Helidon, and I see that sometimes beans/proxy (having services like _Transactions_) are useless however the JavaEE/Jakarta EE annotations (like _Inject_ insted of Event Bus in Vertx) are very juicy. This all makes sense but we need to get smaller memory footprint than Quarkus based on Java EE API. A combination of plain object + Java EE annotations may be interesting (with some limitations to the EE spec).

So I guess the memory footprint comes from two:
1. Jersey v.s. Netty/Resteasy
2. beans and their optimizations

**Comment by tomas-langer** [comment]
Hello @Tibor17, could you please share with us the method of measurement and the project you used to measure it?

**Comment by Tibor17** [comment]
I will give your a feedback but you have to wait.

Dňa ut 21. 9. 2021, 16:40 Tomas Langer ***@***.***>
napísal(a):
