### ISSUE TITLE
Use explicit host in tests

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#3475]
When running tests on random ports, we should bind to a specific host (`localhost`) to use the loopback interface.

This is needed because of MacOS, where, when binding to a wildcard, we may end up with an open socket that is not accessible (see https://github.com/oracle/helidon/issues/249), or we may bind side by side with another process that may be hit by our test code instead of Helidon.

To fix this problem, we need to:
1. Bind to `localhost`
2. Use `localhost` when using WebClient
3. Use `InetAddress.getLoopbackAddress()` or `InetAddress.getByName("localhost")` when using Socket directly

`InetAddress.getLocalHost` DOES NOT WORK and may hit a non-Helidon endpoint

This is a source of intermittent issue on MacOS, where we get "connection reset by peer", "timeout" or "connection reset by host" errors that seem to come from Helidon, but in reality these come from another process listening on the same port in a way that does not conflict with our binding.

**Comment by dalexandrov** [comment]
Fixed with PR #3575
