### ISSUE TITLE
Compatibility of io.helidon.microprofile.cdi.Main with Gradle 

### ISSUE THREAD

**Issue by happylynx** [oracle/helidon#3570]
When simple hello world JAX-RS project is stated from Idea or using Gradle application plugin (`gradlew run`), it fails to find `@Path` annotated classes.

It is caused by Gradle application plugin and Idea providing application classpath in two entries 
* `build\resources\main` that contains `META-INF` directory
* and `build\classes\java\main` that contains compiled classes

`org.jboss.weld.environment.deployment.discovery.FileSystemBeanArchiveHandler#handle` and `org.jboss.weld.environment.deployment.discovery.FileSystemBeanArchiveHandler#handleDirectory` however expect that directory structure that contains `META-INF/beans.xml` also contains annotated classes.

As result the initialization console output sequence contains
```
WARNING: There are no JAX-RS applications or resources. Maybe you forgot META-INF/beans.xml file?
```
and the handler is not found.

When application is started from final jar file (that contains both `META-INF/beans.xml` and annotated classes), it runs fine.

Related issue [Simple weld-se bootstrap example fails to find class when using gradle](https://issues.redhat.com/browse/WELD-2040)

## Environment Details
* Helidon Version: 2.3.4
* Helidon MP
* JDK version: java version "17" 2021-09-14 LTS
* OS: Win 10
* Gradle Version: 7.2

----------

## Steps to reproduce
1. Extract attached delidon-demo.zip project
2. Run `gradlew run`
3. Access `http://localhost:7001/hello` in a browser

### Expected result
`hello world` response

### Actual result
`No handler found for path: /hello` response

[helidon-demo.zip](https://github.com/oracle/helidon/files/7381195/helidon-demo.zip)

**Comment by barchetta** [comment]
Updated example build.gradle files to make this work. See PR #3612
