### ISSUE TITLE
MetricsSupport must be created before a service accesses the registry

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#360]
## Environment Details
* Helidon Version: 0.11.0
* Helidon SE
* JDK version: 9.0.4
* OS: Mac OS High Sierra
* Docker version (if applicable): n/a

----------

## Problem Description
The developer must invoke `MetricsSupport.create` before a metrics-enabled service tries to access the metrics registry or an NPE results.

## Steps to reproduce
In the SE restful web service guide code (helidon/examples/guides/se-restful-webservice) find the `Main.createRouting` method. As written, it first creates the `MetricsSupport` object and then instantiates `GreetService`. Reverse the order. Then try to `mvn package` the project. The test will fail with an NPE. Restore the original order and the test passes.

Ideally, this ordering would not be important. This issue is for investigating whether there is a way to remove the ordering requirement.

**Comment by spericas** [comment]
I have noticed this behavior before. Ordering is important and I'm not sure there's an easy way around it. OTOH, I'd be really nice to produce a different type of exception, such as `IllegalStateException` with some additional information for the developer.

**Comment by tomas-langer** [comment]
I am trying a no-exception approach. There is still a certain level of ordering necessary, though only in access to actual repository
 - factory is a singleton created as soon as anybody accesses it
 - base registry (which is the only one using config) is lazily created on access
 - other registries are created immediately, as they are not impacted by configuration changes

The other approach would be to simply throw an `IllegalStateException` - I do not like this approach much, as it enforces a certain coding style.
