### ISSUE TITLE
Shutdown using HelidonContainer not successful

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#3610]
`HelidonContainer.instance().shutdown();` may not shutdown the container as expected (reported through Slack).
Customer is using streams - this should shutdown Helidon when the channel terminates

```java
msgRuntime.onChannelTerminated(c -> {
    HelidonContainer.instance().shutdown();
});
```

**Comment by dalexandrov** [comment]
Unable to reproduce. No response from customer as well.
