### ISSUE TITLE
OIDC loading meta data fails due to path being stripped from identity-uri

### ISSUE THREAD

**Issue by jmntn2000** [oracle/helidon#3627]
## Environment Details
* Helidon Version: 2.4.0
* Helidon SE
* JDK version: JDK-17
* OS: any
* Docker version (if applicable):

----------

## Problem Description
An error is thrown due to failed lookup from .well-known/openid-configuration not existing.  The issue is this path should be appended to the full identity-uri from the config but currently its being appended to just the scheme and host portion.

## Steps to reproduce
oidc:
 ...
 identity-uri:  https://my-oidc.someplace.com/opidc/realm

Throws an exception with the following:
https://my-oidc.someplace.com/.well-known/openid-configuration can't be loaded. 

The correct path should be:
https://my-oidc.someplace.com/opidc/realm/.well-known/openid-configuration

I believe this started with 2.4.0

**Comment by ottuzzi** [comment]
Hi,

   this is a blocker in my organization as we cannot upgrade helidon to version 2.4: is there any ETA?

*Ciao
Piero

**Comment by tomas-langer** [comment]
Resolved for 2.x, only pending PR with forward port to 3.x
