### ISSUE TITLE
MP server CDI extension might discard non-ApplicationScoped root resource classes

### ISSUE THREAD

**Issue by ljnelson** [oracle/helidon#363]
See:

https://github.com/oracle/helidon/blob/5edc48edb60a3eb3f6402984533d4633029c82bc/microprofile/server/src/main/java/io/helidon/microprofile/server/ServerCdiExtension.java#L47

I believe that will rule out otherwise valid `Application`-less root resource classes, right?

Consider a root resource class annotated with `@RequestScoped`, not `@ApplicationScoped`.  It should be picked up, right?  But because it doesn't have `@ApplicationScoped` on it, this extension will ignore it.

**Comment by spericas** [comment]
As we already discussed, this needs clarification from the MP and JAX-RS specs. Personally, I feel that existing JAX-RS users would dislike the idea of a _synthetic_ application class being created for them. In summary, the current behavior seems OK to me for now (perhaps a CDI-only JAX-RS should drop the notion of application classes altogether, and use CDI discovery instead).

**Comment by ljnelson** [comment]
Note that our current behavior already creates a synthetic application in some cases but using only @ApplicationScoped resources:

https://github.com/oracle/helidon/blob/5edc48edb60a3eb3f6402984533d4633029c82bc/microprofile/server/src/main/java/io/helidon/microprofile/server/ServerCdiExtension.java#L56-L59

I'm trying to understand why our current behavior doesn't also allow `@RequestScoped` resources.

**Comment by spericas** [comment]
@ljnelson Good point

**Comment by tomas-langer** [comment]
We can create the "synthetic" application also for RequestScoped resource classes if no application is found. But only in that case.

I have gone through the same mental exercise as you (and there is already a bug opened for it: #154 )
The problem is that I have no way of knowing which classes/instances are returned by an Application.
I cannot instantiate an Application just to inspect it, as it may have injected fields that would fail, or side effects of the method calls that I cannot run. 
So I could end up with an explicit Application that returns an instance of `Foo` and synthetic Application that also returns `Foo`, which is bad behavior and could cause errors.
So I have done a simple decision:

- If an Application exists with bean defining annotation - use it
- If no Application is found, use resources annotated with `ApplicationScoped`

We could modify the condition to also include `RequestScoped` resources.

As we discussed in #154 this is a very complicated problem with no clear definition. Also I do not want to do classpath scanning to find classes that are applications - I want to use CDI as the only source of truth.

**Comment by spericas** [comment]
@tomas-langer I agree that creating a synthetic application class when one already exists can be problematic. OTOH, if an application subclass does not exist, gathering only resource classes that are `ApplicationScoped` seems odd. 
To be more consistent with JAX-RS class scanning, we should scan for all resource classes (regardless of scope) and all providers annotated with `@Provider`. Note that a JAX-RS application comprises resources and providers.

**Comment by ljnelson** [comment]
(Hi, @tomas-langer; #154 is more about what scope resource classes should have and what to do when they aren't annotated with a CDI scope at all.  This bug is: given that we create a synthetic application already, why do we look for only `@ApplicationScoped` root resource classes?)

Incidentally, you actually _can_ instantiate an `Application` here without injection blowing up.  You can't simply call its constructor, of course, and you can't ask the `BeanManager` to do it for you via `getReference` (if you're in an `AfterBeanDiscovery` observer method), but you _can_ ask the related `Context` to create an instance for you.  Something like:

    beanManager.getContext(applicationBean.getScope()).get(applicationBean, beanManager.createCreationalContext(applicationBean));

This will result in an `Application`-typed contextual instance with injection having been performed, and is not prohibited by the CDI specification.  Now you can find the classes and providers that `Application` already "knows about" and automatically pick up only those it doesn't know about.

**Comment by tomas-langer** [comment]
That will use CDI to inject the application, not Jersey. And I cannot use Jersey, as it is not yet initialized.
I propose to change the behavior to include resource classes with bean defining annotation. We probably should also register all `@Provider` annotated beans with bean defining annotation as @spericas  mentioned.

This is all we should do in my opinion, as anything else exposes us to risks. Also as this is a microservice framework, we expect either an Application class, or a few resources to create the resulting microservice - we are not an application server and can have restrictions on how we search for resources.

**Comment by ljnelson** [comment]
OK; whatever seems best.

So that I can learn something: given that the Jersey CDI extension is on the classpath, what is the material difference between Jersey injecting the application and CDI injecting the application?  Won't CDI end up providing the objects to "fill" the injection slots anyway?

**Comment by tomas-langer** [comment]
No, the injection is a combination of CDI and Jersey - you can inject '@Context' with Jersey and '@Inject' with CDI.
The implementation actually asks CDI to inject and if it doesn't, HK2 does the injection in Jersey.

**Comment by ljnelson** [comment]
Aha!  I see.  Can an `Application` use `@Context` when it is instantiated, given that the provider class that fills the `@Context`-annotated slot might be in the return value of its `getClasses()` method?  Surely not.  And if not, won't all injection be satisfied by CDI?

**Comment by tomas-langer** [comment]
You can do (and injectionManager is correctly injected):
```
@ApplicationScoped
@ApplicationPath("/")
public class GreetApplication extends Application {

    @Context
    private InjectionManager injectionManager;

    @Override
    public Set<Class<?>> getClasses() {
        return CollectionsHelper.setOf(GreetResource.class);
    }
}
```

**Comment by ljnelson** [comment]
Wow!  I see.  Jersey sure does some weird things—I'm glad that `InjectionManager` is not part of the JAX-RS specification!

So we can't instantiate the `Application` ourselves from within CDI to find out what its authoritative class and singleton sets are, because the `Application` we're looking at might be coupled to Jersey (as opposed to "pure" JAX-RS) and might inject some Jersey-specific objects using `@Context`.  (Obviously if it were a "pure" JAX-RS `Application` none of the twelve or so explicitly listed items injectable via `@Context` are available anyway, so that would be moot.)  I think I understand.

**Comment by ljnelson** [comment]
> That will use CDI to inject the application, not Jersey.

I had a sudden thought this morning: the JAX-RS 2.1 specification _requires_ that it be possible for CDI to create and inject `Application` subclasses.  Section 11.2.3, page 68:

> In a product that supports CDI, implementations MUST support the use of CDI-style Beans as…`Application` subclasses.

This means that it _must_ be possible for CDI to instantiate and inject `Application`s in "a product that supports CDI" (such as MicroProfile).  There are ramifications here that I'm not yet seeing but I wanted to record this.

**Comment by spericas** [comment]
Real use cases where developers inject into application subclasses are extremely rare. For the sake of the argument, let's assume that we can instantiate an application subclass as Laird says, then what would be the proposed semantics?

**Comment by ljnelson** [comment]
See https://gist.github.com/ljnelson/8f7007417c3916e36ba70ea2f363cae3 for a way to interrogate an `Application` for its list of classes and singletons.  It should be relatively easy to thus distinguish "owned" classes from "unowned" classes.

**Comment by spericas** [comment]
@ljnelson Right, so my question was more other resources or providers that exist but are not returned by the application subclass methods. Looking at your code, seems like those would just be ignored, right?

**Comment by ljnelson** [comment]
Right, or whatever you would want to do (deploy two applications?).  They cannot, of course, be part of the `Application` in question itself, because as you know the return values of its `getClasses()` and `getSingletons()` methods are gospel.

**Comment by tomas-langer** [comment]
The behavior of Helidon MP now mimics that of application servers when it comes to how we identify resources to be part of an application.
