### ISSUE TITLE
Provide config override of servicename for OCI ATP Service Integration with Wallet Management

### ISSUE THREAD

**Issue by paulparkinson** [oracle/helidon#3648]
Currently, the OCI ATP Service Integration with Wallet Management feature automatically uses the [servicename]"_high" service and overriding this serviceAlias must be done programmatically. Would be convenient to be able to provide that in config instead.

## Environment Details
* Helidon Version: 2.4.0
* Helidon MP
* JDK version: GraalVM 20.2.0
* OS:
* Docker version (if applicable): ghcr.io/graalvm/graalvm-ce:21.3.0

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

## Steps to reproduce
Use https://github.com/oracle/helidon/tree/master/examples/integrations/oci/atp-cdi and attempt to connect to  [servicename]"_tp" or any service that is not "_high" . Services provided by ADB are high, low, medium, tp, and tpurgent.

**Comment by ljnelson** [comment]
Hi, @paulparkinson; you may be [in luck](https://github.com/oracle/helidon/blob/c51cf34df1c7aa4cebe165c13525bcd492912288/integrations/cdi/datasource-ucp/src/main/java/io/helidon/integrations/datasource/ucp/cdi/UCPBackedDataSourceExtension.java#L182-L192).  If I'm reading you right, that's [in 2.4.0 today](https://github.com/oracle/helidon/blob/c51cf34df1c7aa4cebe165c13525bcd492912288/integrations/cdi/datasource-ucp/src/main/java/io/helidon/integrations/datasource/ucp/cdi/UCPBackedDataSourceExtension.java#L232-L247).

**Comment by arjav-desai** [comment]
We have removed adding "_high" by default to provided service name. Now, User provides the full service name instead.
