### ISSUE TITLE
Upgrade Hystrix to 1.5.18

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#365]
1.5.18 has been released (it is actually a re-release of 1.5.11) and looks to be the final active release from Netflix and reflects what Netflix is using internally. Netflix will no longer be actively maintaining Hystrix. See https://github.com/Netflix/Hystrix/blob/master/README.md

We should move to 1.5.18 as we explore other options (see issue #357).

**Comment by spericas** [comment]
Initial testing with 1.5.18 shows a couple of regressions related to how the HALF_OPEN state of a circuit breaker is implemented. Working on a solution for this.

**Comment by barchetta** [comment]
Fixed by PR #391 and #395
