### ISSUE TITLE
Cache-Control Header getting override in the response (Helidon MP 2.3.2)

### ISSUE THREAD

**Issue by AppyArora** [oracle/helidon#3668]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 2.3.2
* Helidon SE or Helidon MP : Helidon MP
* JDK version: 11
* OS: Windows
* Docker version (if applicable):

----------

## Problem Description

- on Adding cache-Control header with max-age directive to 24 hours(86400) in the response Object...it is getting overwrite internally and value changes to no-store

- on every request the behaviour is same

-there is no exception but attaching the screenshot also i can see some other headers are added like content-Diposition
![image](https://user-images.githubusercontent.com/22344481/143041836-6ba298f8-e01a-41fc-8544-4cfffcd1dff0.png)

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
Step-1 written one controller using Helidon Mp 2.3.2 which is calling other service method and this method is reading the data from the json file(json data in file).
step-2 using the Data read from the json file then  prepare the Response object using below code snip:
**"CacheControl cache = new CacheControl();
        cache.setMaxAge(86400);
       /* return Response.status(Response.Status.OK).header().entity(response)
                .build();*/

        return Response.status(Response.Status.OK).entity(response).cacheControl(cache)
                    .build();"**

Testing:
1) via post : Execute the controller end point and verify the headers it shows cache-control overwritten with value as no-store(pls refer the above screenshot).
2) via browser(chrome): Executed the endpoint on the browser and verify the response header in the console of the browser the cache is overwritten to value no-store

sample code for the above issue:

Interface sample:

**@Path("/cx/abc/abcManagement/v4/abcCustomer")
@Authenticated

public interface TMFCustomerDescribeResource {
    @GET
    @Path("/describe")
    @Produces(MediaType.APPLICATION_JSON)
    // @RolesAllowed({Constants.ROLE_DX4C_ADMIN, Constants.ROLE_DX4C_USER})
    Response describeCustomerResource(@Context SecurityContext securityContext, @Context HttpHeaders headers) throws ApplicationException, IOException;
}**

Resource sample

**@ApplicationScoped
@Flogger
public class TMFCustomerDescribeResourceImpl implements TMFCustomerDescribeResource {
   @Override
    public Response describeCustomerResource(SecurityContext securityContext, HttpHeaders headers) throws ApplicationException {
        log.atInfo().log("Entering describeCustomerResource");
            return customerDescribeService.readJsonFile();
    }
}**

service layer
  **@Override
    public Response readJsonFile()  {
        log.atInfo().log("Entering readJsonFile ");
        String  response = data();
        CacheControl cache = new CacheControl();
        cache.setMaxAge(86400);
       /* return Response.status(Response.Status.OK).header().entity(response)
                .build();*/

        return Response.status(Response.Status.OK).entity(response).cacheControl(cache)
                    .build();

    }

   private  String data(){
        JsonNode jsonNode = null;
        try (InputStream inputStream = getClass().getResourceAsStream(fileNamePath)) {
            if (inputStream != null) {
                jsonNode = mapper.readValue(inputStream, JsonNode.class);
            } else {
                log.atSevere().log("No describe json file found or invalid resource found");
                throw new ConfigurationNotFoundException("Invalid requested resource");
            }
        } catch (IOException | ConfigurationNotFoundException ex) {
            ex.printStackTrace();
        }
        return jsonNode.toString();
    }**

**Comment by spericas** [comment]
@AppyArora The use case you provide is a bit convoluted, we need something simpler to test the problem. I created a sample project based using the Helidon CLI and modified it a bit. I _do not see any problems_ with `CacheControl`. The header is returned as expected:

```
(~/Projects/quickstart-mp) >> curl -v http://localhost:8080/greet
*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#0)
> GET /greet HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.70.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Cache-Control: no-transform, max-age=86400
< Content-Type: application/json
< Date: Tue, 30 Nov 2021 15:46:35 -0500
< connection: keep-alive
< content-length: 26
```

If you still think there's a problem, please provide some runnable code that shows it. I'm attaching my application as a zip file that you can use as a starting point for that.

[quickstart-mp.zip](https://github.com/oracle/helidon/files/7628769/quickstart-mp.zip)

**Comment by spericas** [comment]
Closing after a week without any comments. If still a problem, please re-open with a modified `quickstart` application that shows the issue.
