### ISSUE TITLE
SignedJwt's parseToken expects JWT's payload characters from base64 encoding instead of base64url encoding

### ISSUE THREAD

**Issue by dikshabhatti** [oracle/helidon#3675]
## Environment Details
* Helidon Version: 2.2.1
* Helidon SE or Helidon MP : Helidon MP
* JDK version: 
* OS:
* Docker version (if applicable):

----------

## Problem Description
SignedJwt's parseToken expects JWT's payload characters from base64 encoding instead of base64url encoding. 
Hence parsing of valid JWT payloads fails if they have characters from the base64url encoding character set.

Occurrence : 
Every time the token payload has characters from base64URL encoding characters set 

LOGS : 
"Provider io.helidon.security.CompositeAuthenticationProvider. Message: Invalid token"

## Steps to reproduce
run parseToken on a valid JWT token of the following format : 
<header>.ewogICJpc3MiOiAidGVzdCIsCiAgImF1ZCI6IFsKICAgICJPQUFDbGllbnR0ZXN0IiwKICAgICJ0ZXN0IgogIF0sCiAgImV4cCI6IDE2NDA0NDU5ODQsCiAgImp0aSI6ICJnamlVOU51UFV5WTZDelVlLUdZS3ZRIiwKICAiaWF0IjogMTYzNzgxNzk4NCwKICAic3ViIjogIk9BQUFkbWludGVzdCIsCiAgImNsaWVudCI6ICJPQUFDbGllbnR0ZXN0IiwKICAic2NvcGUiOiBbCiAgICAib3BlbmlkIgogIF0sCiAgImRvbWFpbiI6ICJPQUFEb21haW50ZXN0IiwKICAiZ3JhbnQiOiAiQVVUSE9SSVpBVElPTl9DT0RFIiwKICAiZ3JvdXBzIjogWwogICAgIk9BQS1BZG1pbi1Sb2xldGVzdCIKICBdLAogICJhcHBJZCI6ICJ0ZXN0IiwKICAic3RhdGljQXR0ciI6ICJDdXN0b21WYWx1ZSIsCiAgInNlc3Npb25JZCI6ICJ0ZXN0LXRlc3QtNDk3Mi10ZXN0LTFkOTJkMDlmZGIxZnxsZUlnVjZwSWwxZEo0M3h4d010NHY2YldVcTVBRm1obDhabVNoM3RiT2lzPSIsCiAgImFwcGxpY2F0aW9uSWQiOiAidGVzdCIsCiAgIm5vbmNlIjogInRlc3QtYjU3MC00MzUwLXRlc3QtZDAwNWJmNDIyYTNhIiwKICAibWRjX3Nzb19saW5rIjogIjI2NWM3LXRlc3QwMDUyLn5-VXNlcklkZW50aXR5U3RvcmUxIiwKICAicmVzU3J2QXR0ciI6ICJSRVNPVVJDRUNPTlNUIgp9.<signature>

# "Provide sample code/application if relevant"
The parsing of above token will fail 
As the payload pattern expected is 
private static final Pattern JWT_PATTERN = Pattern
      .compile(“([a-zA-Z0-9/=+]+)\\.([a-zA-Z0-9/=+]+)\\.([a-zA-Z0-9_\\-/=+]*)“);

payload character's patter : ([a-zA-Z0-9/=+]+)
This character set belongs to base64encoding https://datatracker.ietf.org/doc/html/rfc4648#section-4 (Table1)

It should be ([a-zA-Z0-9-_=]+) instead , the character set for baseURLencoding  https://datatracker.ietf.org/doc/html/rfc4648#section-5 (Table2)

**Comment by klustria** [comment]
@dikshabhatti,  does the provided sample token come with `.` at the beginning and end of the string?

**Comment by dikshabhatti** [comment]
> @klustria I just gave an example of JWT payload and omitted header and signature in above-quoted sample

So to be precise the incoming JWT token comes in the following format, so yes the payload has the character '.' in the beginning and end
<header>.<payload>.<signature>

The issue is with characters expected as part of the payload

**Comment by klustria** [comment]
Ok, I see the header and signature  before and after the payload after clicking edit on it which is invisible from the normal view.

**Comment by klustria** [comment]
If you can, would you be able to share a snippet of the code that calls parseToken?

**Comment by dikshabhatti** [comment]
> If you can, would you be able to share a snippet of the code that calls parseToken?

I don't have this detail. 
Following is my exact use case is 
Identity provider : Oracle's OAM
Client used for JWT token validation : Helidon MP

JWT Token returned by the Identity provider ( Oracle's OAM) : eyJraWQiOiJPQUFEb21haW4iLCJ4NXQiOiJlaVpMUUF3alViMVBoblBuWFQySUJiQy16c0kiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwOi8vb2FtaG9zdDEudm0ub3JhY2xlLmNvbTo3Nzc3L29hdXRoMiIsImF1ZCI6Ik9BQUNsaWVudCIsImV4cCI6MTYzMjczODM4NSwianRpIjoiZmItYjhpSWRDdlUweWVaSktJeGxFdyIsImlhdCI6MTYzMjczNDc4NSwic3ViIjoiYWRtaW4xIiwiYXBwSWQiOiJteW9hYXByb3RlY3RlZGFwcDEiLCJncm91cHMiOiJPQUEtQWRtaW4tUm9sZSIsImFwcGxpY2F0aW9uSWQiOiJteW9hYXByb3RlY3RlZGFwcDEiLCJub25jZSI6IjIzZjlmOGYwLWRiMTQtNDk5ZS05NDEyLTE3Nzk5NzkwZGZhMCIsImNsaWVudCI6Ik9BQUNsaWVudCIsInNjb3BlIjpbIm9wZW5pZCJdLCJkb21haW4iOiJPQUFEb21haW4ifQ.PIuSzgwGnI1qKaBl6F8s74JCFYIi0lca49UV2U07jxUvMoA6rTOMZ8bW9RAiGvw_8P-fbwasOUea_lTskxJJ4WgFBLmmoqjyGuRFYbs8H-1tptmrHDyKP0e-ei10_lSm8Y1czLpAZFpV5ovnJr7Jh3Q6PaVdrwOMsIKJVb8Y1zA1BHT6kOgCtaTl0c_fNzSQHO7l6WMnaeb4dfMIPpoGGIQ83cCapiKENU7nOA6JuEb8LrUb1spxTAdqO3idEaNMwthCM74Q6ydRc2k7BVaJXT6PoNxCuI4xxd8RlRxcItCalVsA2FL535_e77KunMh53L6gTYyoUklt-4y9dmJm4w

Now this is a valid JWT as I am able to parse it using any client library like jose4j or https://jwt.io/

But helidon errors out saying invalid token when presented with this token. ( reason elaborated in detailed bug description)

**Comment by klustria** [comment]
The above example should have succeeded because there is no - or _ in the payload. Nevertheless, the description above of using the wrong regex pattern to match the token is causing the issue. `+` and `/` from the base64 encoding should be replaced with `-` and `_` to become base64URL. So the suggestion of using this `([a-zA-Z0-9-_=]+)` is the right thing to do.

**Comment by klustria** [comment]
This is fixed in Master via https://github.com/oracle/helidon/pull/3722 so will appear in v3.0.0. Plan is to have this back ported to upcoming v2.4.1.

**Comment by klustria** [comment]
This is backported to 2.4.x line via https://github.com/oracle/helidon/pull/3740 and hence will be available in the upcoming 2.4.1 release.
