### ISSUE TITLE
Tracing: JAX-RS Client request span not visible if client times out

### ISSUE THREAD

**Issue by Sobuno** [oracle/helidon#3691]
## Environment Details
* Helidon Version: 2.4.0
* Helidon SE or Helidon MP: Helidon MP
* JDK version: 11
* OS: Windows
* Docker version (if applicable): N/A

----------

## Problem Description
When firing a request using a Jersey Client, a span is generated and visible in e.g. Jaeger if the server manages to reply. However, if the server does not reply (e.g. in the case of a client timeout being reached), no span is visible.

The problem is easily reproducible using the attached example: I have created two endpoints that each call example.org One is located at /test/works and has a generous timeout value. The other is located at /test/broken and is set to timeout the connection after 1 millisecond.

By calling each of these endpoints, we will see the following for /test/works and /test/broken respectively:
![image](https://user-images.githubusercontent.com/3593183/144491652-3a6a0979-d6cb-401b-b82d-4faf6e368b5e.png)

![image](https://user-images.githubusercontent.com/3593183/144491726-fd4631fe-f1ff-49f9-b0fb-9344887b1efc.png)

Note the missing spans on the second picture (that are actually the reason for the entire trace being marked as having an error - yet the root cause of the error disappears).

## Steps to reproduce
1. Build and run the attached sample code while having an active Jaeger All-in-One instance running locally.
2. Access http://localhost:8080/test/broken in a browser
3. Observe that there is no span in Jaeger indicating that an outbound request was attempted
4. Access http://localhost:8080/test/works in a browser
5. Observe that there is a span in Jaeger indicating that an outbound request was attempted (and was successful)

[timeout-no-span-sample.zip](https://github.com/oracle/helidon/files/7644719/timeout-no-span-sample.zip)

**Comment by spericas** [comment]
Fix checked into master only PR #3725
