### ISSUE TITLE
Compression setting not effective if HTTP2 enabled

### ISSUE THREAD

**Issue by lambdaupb** [oracle/helidon#3694]
Compression 

## Environment Details
* Helidon Version: 2.4.0
* Helidon SE
* JDK version: 17
* OS: linux

----------
 #2334 Enabled http compression, this works for HTTP1 but once http2 is enabled, the setting is not applied.

see: https://github.com/oracle/helidon/blob/c4958dd87a0ecd484c6cd0a6c6b06dae10515b7b/webserver/webserver/src/main/java/io/helidon/webserver/HttpInitializer.java#L180-L210

**Comment by spericas** [comment]
PR #3705 PR #3700
