### ISSUE TITLE
Document need to configure CDI when using custom config with HelidonTest

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#3747]
`mp.initializer.allow=true` must be configured when using `@Configuration(useExisting=true)` in combination with `@HelidonTest`, as otherwise CDI will not start.
This should be clearly documented either in javadoc of `@Configuration` or in testing documentation (or in both).

**Comment by barchetta** [comment]
This has been fixed in 2.x. Still need to fix in 3.x.

**Comment by tejo93** [comment]
Please confirm that this flag mp.initializer.allow=true can be used only in Helidon MP Testing framework and not in Helidon MP

**Comment by dalexandrov** [comment]
*No*, this flag is used when you want to start Helidon cdi container yourself with `SeContainerInitializer`. So, it is *not bound* to Helidon MP Testing Framework *only*.

**Comment by dalexandrov** [comment]
This is an additional functionality to customise the CDI container start up.
Starting cdi container manually can be practical for same very hacky workarounds, but you can break a lot, native image for example.
This is just an additional option for customisation, and is not a common practice, thus, should not be used in production.
