### ISSUE TITLE
Injection manager problems with multiple apps and dynamic features

### ISSUE THREAD

**Issue by spericas** [oracle/helidon#3752]
## Environment Details
* Helidon Version: 2.4.0
* Helidon MP
* JDK version: 11
* OS: Mac OS

----------

## Problem Description
When defining multiple `Application` subclasses and a `DynamicFeature`, an exception is reported in `HelidonHK2InjectionManagerFactory` because the parent injection manager's type is not recognized.

```
IllegalState Invalid parent injection manager
```

Thanks to Milan Kuchtiak for the test showing the problem.

**Comment by barchetta** [comment]
Fixed in 2.4.1.

**Comment by spericas** [comment]
PR #3754
PR #3755
