### ISSUE TITLE
An error occurred when compiling the /examples/grpc/metrics project with native-image

### ISSUE THREAD

**Issue by duss023** [oracle/helidon#3759]
## Environment Details
* Helidon Version:2.4.0
* Helidon SE
* JDK version:11
* OS:win10
* Docker version (if applicable):

----------

## Problem Description
An error occurred when compiling the helidon-2.4.0/examples/grpc/metrics project with native-image
Can you help me find a solution to the problem
message:
**C:\Users\user\Downloads\helidon-2.4.0\examples\grpc\metrics>mvn package -Pnative-image**
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: windows
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 10.0
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 0
[INFO] os.detected.classifier: windows-x86_64
[INFO]
[INFO] -------< io.helidon.examples.grpc:helidon-examples-grpc-metrics >-------
[INFO] Building Helidon gRPC Server Examples Metrics 2.4.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ helidon-examples-grpc-metrics ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ helidon-examples-grpc-metrics ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ helidon-examples-grpc-metrics ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\user\Downloads\helidon-2.4.0\examples\grpc\metrics\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ helidon-examples-grpc-metrics ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ helidon-examples-grpc-metrics ---
[INFO]
[INFO] --- helidon-maven-plugin:2.3.0:report (third-party-license-report) @ helidon-examples-grpc-metrics ---
[INFO] Scanning Helidon gRPC Server Examples Metrics
[INFO] Reading input from HELIDON_THIRD_PARTY_LICENSES.xml on classpath
[INFO] Writing output to C:\Users\user\Downloads\helidon-2.4.0\examples\grpc\metrics\target\HELIDON_THIRD_PARTY_LICENSES.txt
[INFO]
[INFO] --- maven-dependency-plugin:3.1.2:copy-dependencies (copy-libs) @ helidon-examples-grpc-metrics ---
[INFO] io.helidon.examples.grpc:helidon-examples-grpc-common:jar:2.4.0 already exists in destination.
[INFO] io.grpc:grpc-netty:jar:1.35.0 already exists in destination.
[INFO] io.grpc:grpc-core:jar:1.35.0 already exists in destination.
[INFO] com.google.code.gson:gson:jar:2.8.6 already exists in destination.
[INFO] com.google.android:annotations:jar:4.1.1.4 already exists in destination.
[INFO] io.netty:netty-codec-http2:jar:4.1.63.Final already exists in destination.
[INFO] io.netty:netty-common:jar:4.1.63.Final already exists in destination.
[INFO] io.netty:netty-buffer:jar:4.1.63.Final already exists in destination.
[INFO] io.netty:netty-transport:jar:4.1.63.Final already exists in destination.
[INFO] io.netty:netty-codec:jar:4.1.63.Final already exists in destination.
[INFO] io.netty:netty-handler-proxy:jar:4.1.63.Final already exists in destination.
[INFO] io.netty:netty-codec-socks:jar:4.1.63.Final already exists in destination.
[INFO] com.google.guava:guava:jar:30.0-jre already exists in destination.
[INFO] com.google.guava:failureaccess:jar:1.0.1 already exists in destination.
[INFO] com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava already exists in destination.
[INFO] org.checkerframework:checker-qual:jar:3.5.0 already exists in destination.
[INFO] com.google.j2objc:j2objc-annotations:jar:1.3 already exists in destination.
[INFO] com.google.errorprone:error_prone_annotations:jar:2.3.3 already exists in destination.
[INFO] io.perfmark:perfmark-api:jar:0.23.0 already exists in destination.
[INFO] org.codehaus.mojo:animal-sniffer-annotations:jar:1.19 already exists in destination.
[INFO] com.google.code.findbugs:jsr305:jar:3.0.2 already exists in destination.
[INFO] io.grpc:grpc-services:jar:1.35.0 already exists in destination.
[INFO] io.grpc:grpc-stub:jar:1.35.0 already exists in destination.
[INFO] com.google.protobuf:protobuf-java-util:jar:3.12.0 already exists in destination.
[INFO] io.grpc:grpc-protobuf:jar:1.35.0 already exists in destination.
[INFO] io.grpc:grpc-api:jar:1.35.0 already exists in destination.
[INFO] io.grpc:grpc-context:jar:1.35.0 already exists in destination.
[INFO] com.google.protobuf:protobuf-java:jar:3.12.0 already exists in destination.
[INFO] com.google.api.grpc:proto-google-common-protos:jar:2.0.1 already exists in destination.
[INFO] io.grpc:grpc-protobuf-lite:jar:1.35.0 already exists in destination.
[INFO] io.helidon.common:helidon-common:jar:2.4.0 already exists in destination.
[INFO] io.helidon.grpc:helidon-grpc-server:jar:2.4.0 already exists in destination.
[INFO] io.helidon.grpc:helidon-grpc-core:jar:2.4.0 already exists in destination.
[INFO] io.helidon.common:helidon-common-configurable:jar:2.4.0 already exists in destination.
[INFO] io.helidon.common:helidon-common-context:jar:2.4.0 already exists in destination.
[INFO] io.helidon.grpc:io.grpc:jar:2.4.0 already exists in destination.
[INFO] io.helidon.common:helidon-common-http:jar:2.4.0 already exists in destination.
[INFO] jakarta.inject:jakarta.inject-api:jar:1.0 already exists in destination.
[INFO] io.helidon.health:helidon-health:jar:2.4.0 already exists in destination.
[INFO] io.helidon.fault-tolerance:helidon-fault-tolerance:jar:2.4.0 already exists in destination.
[INFO] org.eclipse.microprofile.health:microprofile-health-api:jar:2.2 already exists in destination.
[INFO] io.helidon.config:helidon-config:jar:2.4.0 already exists in destination.
[INFO] io.helidon.common:helidon-common-reactive:jar:2.4.0 already exists in destination.
[INFO] io.helidon.common:helidon-common-mapper:jar:2.4.0 already exists in destination.
[INFO] io.helidon.common:helidon-common-media-type:jar:2.4.0 already exists in destination.
[INFO] io.helidon.tracing:helidon-tracing:jar:2.4.0 already exists in destination.
[INFO] io.opentracing:opentracing-util:jar:0.33.0 already exists in destination.
[INFO] io.opentracing.contrib:opentracing-grpc:jar:0.2.1 already exists in destination.
[INFO] io.opentracing:opentracing-api:jar:0.33.0 already exists in destination.
[INFO] io.helidon.grpc:helidon-grpc-metrics:jar:2.4.0 already exists in destination.
[INFO] io.helidon.bundles:helidon-bundles-config:jar:2.4.0 already exists in destination.
[INFO] io.helidon.config:helidon-config-object-mapping:jar:2.4.0 already exists in destination.
[INFO] io.helidon.config:helidon-config-hocon:jar:2.4.0 already exists in destination.
[INFO] com.typesafe:config:jar:1.4.1 already exists in destination.
[INFO] io.helidon.config:helidon-config-yaml:jar:2.4.0 already exists in destination.
[INFO] org.yaml:snakeyaml:jar:1.27 already exists in destination.
[INFO] jakarta.annotation:jakarta.annotation-api:jar:1.3.5 already exists in destination.
[INFO] io.helidon.metrics:helidon-metrics:jar:2.4.0 already exists in destination.
[INFO] io.helidon.config:helidon-config-mp:jar:2.4.0 already exists in destination.
[INFO] org.eclipse.microprofile.config:microprofile-config-api:jar:1.4 already exists in destination.
[INFO] io.helidon.config:helidon-config-yaml-mp:jar:2.4.0 already exists in destination.
[INFO] io.helidon.common:helidon-common-service-loader:jar:2.4.0 already exists in destination.
[INFO] io.helidon.metrics:helidon-metrics-api:jar:2.4.0 already exists in destination.
[INFO] io.helidon.config:helidon-config-metadata:jar:2.4.0 already exists in destination.
[INFO] io.helidon.metrics:helidon-metrics-service-api:jar:2.4.0 already exists in destination.
[INFO] org.eclipse.microprofile.metrics:microprofile-metrics-api:jar:2.3.2 already exists in destination.
[INFO] io.helidon.webserver:helidon-webserver:jar:2.4.0 already exists in destination.
[INFO] io.helidon.media:helidon-media-common:jar:2.4.0 already exists in destination.
[INFO] io.helidon.common:helidon-common-key-util:jar:2.4.0 already exists in destination.
[INFO] io.helidon.logging:helidon-logging-common:jar:2.4.0 already exists in destination.
[INFO] io.opentracing:opentracing-noop:jar:0.33.0 already exists in destination.
[INFO] io.helidon.tracing:helidon-tracing-config:jar:2.4.0 already exists in destination.
[INFO] io.netty:netty-codec-http:jar:4.1.63.Final already exists in destination.
[INFO] io.netty:netty-handler:jar:4.1.63.Final already exists in destination.
[INFO] io.netty:netty-resolver:jar:4.1.63.Final already exists in destination.
[INFO] io.helidon.webserver:helidon-webserver-cors:jar:2.4.0 already exists in destination.
[INFO] io.helidon.media:helidon-media-jsonp:jar:2.4.0 already exists in destination.
[INFO] io.helidon.service-common:helidon-service-common-rest:jar:2.4.0 already exists in destination.
[INFO] io.helidon.grpc:helidon-grpc-client:jar:2.4.0 already exists in destination.
[INFO] io.helidon.integrations.graal:helidon-graal-native-image-extension:jar:2.4.0 already exists in destination.
[INFO] org.glassfish:jakarta.json:jar:1.1.6 already exists in destination.
[INFO] io.github.classgraph:classgraph:jar:4.8.87 already exists in destination.
[INFO]
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ helidon-examples-grpc-metrics ---
[INFO]
[INFO] --- helidon-maven-plugin:2.3.0:native-image (native-image) @ helidon-examples-grpc-metrics ---
[INFO] Building native image :C:\Users\user\Downloads\helidon-2.4.0\examples\grpc\metrics\target\helidon-examples-grpc-metrics
[WARNING] Warning: Ignoring server-mode native-image argument --no-server.
[INFO] [helidon-examples-grpc-metrics:6812]    classlist:   6,966.50 ms,  0.96 GB
[INFO] [helidon-examples-grpc-metrics:6812]        (cap):   2,857.55 ms,  0.96 GB
[INFO] [helidon-examples-grpc-metrics:6812]        setup:   7,178.96 ms,  0.96 GB
[INFO] To see how the classes got initialized, use --trace-class-initialization=io.helidon.common.serviceloader.HelidonServiceLoader,io.helidon.common.serviceloader.HelidonServiceLoader$Builder$ServiceWithPriority,io.helidon.common.http.MediaType
[INFO] [helidon-examples-grpc-metrics:6812]     analysis:  29,082.33 ms,  1.87 GB
[WARNING] Error: Classes that should be initialized at run time got initialized during image building:
[WARNING]  io.helidon.common.serviceloader.HelidonServiceLoader was unintentionally initialized at build time. To see why io.helidon.common.serviceloader.HelidonServiceLoader got initialized use --trace-class-initialization=io.helidon.common.serviceloader.HelidonServiceLoader
[WARNING] io.helidon.common.serviceloader.HelidonServiceLoader$Builder$ServiceWithPriority was unintentionally initialized at build time. To see why io.helidon.common.serviceloader.HelidonServiceLoader$Builder$ServiceWithPriority got initialized use --trace-class-initialization=io.helidon.common.serviceloader.HelidonServiceLoader$Builder$ServiceWithPriority
[INFO] [helidon-examples-grpc-metrics:6812]      [total]:  43,757.92 ms,  1.87 GB
[WARNING] io.helidon.common.http.MediaType was unintentionally initialized at build time. To see why io.helidon.common.http.MediaType got initialized use --trace-class-initialization=io.helidon.common.http.MediaType
[WARNING]
[WARNING] com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
[INFO] # Printing build artifacts to: C:\Users\user\Downloads\helidon-2.4.0\examples\grpc\metrics\target\helidon-examples-grpc-metrics.build_artifacts.txt
[WARNING]  io.helidon.common.serviceloader.HelidonServiceLoader was unintentionally initialized at build time. To see why io.helidon.common.serviceloader.HelidonServiceLoader got initialized use --trace-class-initialization=io.helidon.common.serviceloader.HelidonServiceLoader
[WARNING] io.helidon.common.serviceloader.HelidonServiceLoader$Builder$ServiceWithPriority was unintentionally initialized at build time. To see why io.helidon.common.serviceloader.HelidonServiceLoader$Builder$ServiceWithPriority got initialized use --trace-class-initialization=io.helidon.common.serviceloader.HelidonServiceLoader$Builder$ServiceWithPriority
[WARNING] io.helidon.common.http.MediaType was unintentionally initialized at build time. To see why io.helidon.common.http.MediaType got initialized use --trace-class-initialization=io.helidon.common.http.MediaType
[WARNING]
[WARNING]       at com.oracle.svm.core.util.UserError.abort(UserError.java:73)
[WARNING]       at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:555)
[WARNING]       at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:168)
[WARNING]       at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$12(NativeImageGenerator.java:727)
[WARNING]       at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:73)
[WARNING]       at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:727)
[WARNING]       at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:529)
[WARNING]       at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
[WARNING]       at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
[WARNING]       at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
[WARNING]       at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
[WARNING]       at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
[WARNING] Error: Image build request failed with exit status 1

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

**Comment by dalexandrov** [comment]
I confirm the same issue for 2.4.2-SNAPSHOT on MacOS and GraalVM based on JDK 17.0.1 
with the following message:

```
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  To see how this object got instantiated use --trace-object-instantiation=java.util.Random. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.

```

**Comment by barchetta** [comment]
For the `Random` error I think the grpc code needs to do lazy initialization of Random as is done in WebServer: https://github.com/oracle/helidon/blob/50239a037d2d1eae463f43a4cfa7446e954ae295/webserver/webserver/src/main/java/io/helidon/webserver/WebServerTls.java#L57

**Comment by dalexandrov** [comment]
It is actually fixed with native image, it works. Should we do it lazy in examples?
