### ISSUE TITLE
question about restart webserver

### ISSUE THREAD

**Issue by wojtask9** [oracle/helidon#377]
Currently it look's like WebServer cannot perform "restart" ( sequence `startup()->shoutdown()->startup()` ).
It is intended behaviour or something else?

In case that this behaviour is intended "Helidon" should throw exception when second time `startup()` method is called or maybe `hide`  shoutdown() method from API because`WebServer.whenShoutdown()` is enough?

**Comment by tomas-langer** [comment]
`WebServer.whenShutdown` is called when the server is shut down. Method `shutdown` actually invokes the shutdown sequence.
There may be multiple parties interested in `whenShutdown`.

We intentionally do not support restart - we expect to be in a container (Docker) and that should be restarted, rather than the WebServer

**Comment by wojtask9** [comment]
@tomas-langer 
I fully understand your concerns. My thinking was wrong.
That's why I'm only asking that restarting server shouldn't be reported as `InvalidStateException` ?

**Comment by tomas-langer** [comment]
Yes, you are right. The server behaves as if it started again, yet the port is -1 and it actually isn't started. The server should fail second startup.
The code below prints to stdout:  "Started again on port: -1"
```
ws.shutdown()
                .thenAccept(stoppedServer -> {
                    stoppedServer.start()
                            .thenAccept(startedAgain -> {
                                System.out.println("Started again on port: " + startedAgain.port());
                            })
                            .exceptionally(throwable -> {
                                System.out.println("Failed to start again: " + throwable.getClass().getName() + ": " + throwable
                                        .getMessage());
                                return null;
                            });
                });
```

**Comment by tomas-langer** [comment]
The behavior is changed to throw an `IllegalStateException` if an attempt is made to restart a server.
