### ISSUE TITLE
bare-mp archetype should not use full microprofile bundle

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#3785]
## Problem Description

If you generate the `bare-mp` example project we use the full `helidon-microprofile` bundle. We should not since this pulls in lots of stuff. It should start with `helidon-microprofile-core` and add just what it needs.

Open to debate if bare should  continue to add metrics and health, or only add `helidon-media-jsonp` 

Also, we might want to consider fixing some of the threadpool sizes on bare via configuration to reduce footprint.

**Comment by spericas** [comment]
I think `bare` should be as minimal as possible so we can point people to it when making the sort of comparisons we are seen now. We can leave `quickstart` as is.

**Comment by barchetta** [comment]
This has been fixed in 2.x and 3.x. I have included the Metrics and Health dependencies for now. 

We are continuing to investigate tuning options. I think we should create a separate issue once we determine the right thing to do.  So I'm closing this as fixed.
