### ISSUE TITLE
Support configuration of `io.netty.allocator.maxOrder` and set reasonable default

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#3801]
During testing we have discovered the need to tune Netty's `io.netty.allocator.maxOrder`. This can be done through system properties, but we should support it directly.

Also, Netty appears to default this to 11 which can result in significant memory consumption. We should pick a more reasonable default such as 3 or 4.

Some background info: https://programmer.group/pool-area-of-netty-memory-pool.html

**Comment by spericas** [comment]
The order refers to the number of times to shift bits (x2). Initial size is 8K. We could even go to 6 or 512K x thread. The default of 11 translates to 16 Mb per thread, which seems way too much.

**Comment by spericas** [comment]
PR #3809

**Comment by spericas** [comment]
This needs to fixed in master as well. Reopening.

**Comment by spericas** [comment]
PR #3826

**Comment by spericas** [comment]
PR #3834
PR #3831
