### ISSUE TITLE
WebClientException: Connection reset by the host

### ISSUE THREAD

**Issue by vbezhenar** [oracle/helidon#3836]
## Environment Details
* Helidon Version: 2.4.1
* Helidon SE
* JDK version: 17.0.1
* OS: Linux

----------

## Problem Description
I have a relatively simple http server which basically issues http request to another server and handles the response. It worked for Helidon 2.3.4. After I updated to Helidon 2.4.1, it does not work. I verified with 2.4.0 and it does not work either. When I'm receiving http response from another server using WebClient, I'm getting `io.helidon.webclient.WebClientException: Connection reset by the host` exception. I believe that it's related to https://github.com/oracle/helidon/pull/3427 change.

Here's relevant code:
```
        byte[] bipRequestBytes = domToBytes(bipRequestSoapDocument);
        WebClient webClient = webClientBuilder.build();
        WebClientRequestBuilder webClientRequestBuilder = webClient.post();
        webClientRequestBuilder.contentType(APPLICATION_SOAP_XML_UTF_8_MEDIA_TYPE);
        return webClientRequestBuilder.submit(bipRequestBytes)
                .flatMapSingle(webClientResponse ->
                        processBipResponse(webClientResponse));

    private Single<Element> processBipResponse(WebClientResponse webClientResponse) {
        return webClientResponse.content().as(byte[].class)
                .map(bipResponseBody ->
                        processBipResponse(webClientResponse, bipResponseBody));
    }
```

Basically I'm submitting byte array and processing byte array from response.

I investigated http traffic and found out that server does not set `content-length` for response (or transfer-encoding). But it sends all the data and, I think, it closes connection afterwards. According to this SO answer: https://stackoverflow.com/a/11376887/315129 this is a valid behaviour and should not cause web client errors.

Here is http response:

```
HTTP/1.1 200 OK
Server: nginx/1.21.1
Date: Wed, 26 Jan 2022 06:43:18 GMT
Content-Type: text/xml;charset=UTF-8
Connection: close
Accept: text/xml, text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Accept-Encoding: gzip
BipDestinationUrl: http://10.49.44.182:8095/mz-shep/serviceWsdl.wsdl
BipFlowDirection: out
BipSessionId: 84d5373c-f2e1-4d3e-9889-d29215560543
BipSignedMessage: false
breadcrumbId: ID-testshep-egov-kz-43422-1642765727283-15-24313196
destinationTrottling: 0
Host: 192.168.145.133
User-Agent: Helidon/2.3.4 (java 17.0.1+12-LTS-39)
X-Forwarded-For: 192.168.39.30
X-Real-IP: 192.168.39.30

<soap:Envelope...
```

**Comment by Verdent** [comment]
Hi @vbezhenar , I have managed to reproduce your issue with version 2.4.1, but not with 2.4.2. May I ask you to verify, whether this issue is still happening to you with 2.4.2 release? If it does, please reopen this issue.

**Comment by vbezhenar** [comment]
I checked with 2.5.0 and it works, thanks a lot.
