### ISSUE TITLE
Release Build: `autoReleaseAfterClose` should be false 

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#3837]
`parent/pom.xml` has this configured for `nexus-staging-maven-plugin`:

```
<autoReleaseAfterClose>true</autoReleaseAfterClose>
```
This should be changed to `false`.

This parameter is currently ignored because we explicitly manage the lifecycle of the staging repository during a release build. But it is a snake waiting in the grass that could bite us down the road if we ever change certain aspects of the release build. 

What does this parameter do? It tells the staging plugin to release the staging repository immediately after the staging repository is closed. We never want to do that. We always want to manually release the staging repository. Fortunately the staging plugin does not manage the staging repository lifecycle in our release build so this parameter has no effect. But having this set is a hazard.

**Comment by ljnelson** [comment]
For posterity:

https://github.com/sonatype/nexus-maven-plugins/blob/nexus-maven-plugins-1.6.8/staging/maven-plugin/src/main/java/org/sonatype/nexus/maven/staging/deploy/strategy/StagingDeployStrategy.java#L160-L162
