### ISSUE TITLE
Consider upgrading to Jackson 2.13.0 or later

### ISSUE THREAD

**Issue by spericas** [oracle/helidon#3879]
Due security analysis reported on users' channel

**Comment by barchetta** [comment]
For Helidon 2, we can consider [2.12.6 (Dec 2021)](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.12.6) if 2.13.X has compatibility risks.

For Helidon 3, Jackson [2.13.X](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.13) has some new Jakarta variants -- need to determine if/how those impact us.

**Comment by barchetta** [comment]
In 2.x we have upgrade to 2.12.6. In 3.x we have upgraded to 2.13.1.
