### ISSUE TITLE
Support for multiple headers to be passed on for service to service authentication calls using Helidon RestClient

### ISSUE THREAD

**Issue by bvkrish83** [oracle/helidon#3886]
We have multiple helidon based micro-services implemented. We are now trying to enable REST API calls using Helidon RestClient to pass on authentication information from one service to another service when required..

We make use of OIDC IDCS Provider, and have additional checks based on another custom header value in our micro-services.
When we add an outbound section under security.proivders.oidc, there seems to be provision to allow only one header to be passed on either Authorization (by default) or custom header mentioned under outbound.*.outbound-token.header.

Is there a provision to pass on multiple headers (mentioned in config) to allow both OIDC authentication and our additional header based validations to be perfomed in our case? If not, does it make sense to add support for this?

## Environment Details
* Helidon Version: 2.4.1
* Helidon MP
* JDK version: 17.0.2
* OS: Windows 10

----------

Example: Our services require presence of 2 headers to complete the authentication process. One being Authorization header, validated using OIDC Provider. Another X-Internal-Auth that does additional validations on top of IDCS validation. Tried by having 2 outbound configuration sections as below, but looks like only one out of this is being honoured.

              outbound:
                - name: "authorize-header"
                  hosts: [ "*" ]
                - name: "custom-header"
                  hosts: [ "*" ]
                  outbound-token:
                    header: "X-Internal-Auth"

Expected: Both Authorization and X-Internal-Auth header values should be passed on for service to service authentication calls.

**Comment by bvkrish83** [comment]
I have identified a work-around using Eclipse MicroProfile libraries, using RegisterClientHeaders annotation - and adding list of headers as comma separated entry under configuration key org.eclipse.microprofile.rest.client.propagateHeaders.

I am not sure whether there is any equivalent API available in Helidon MicroProfile world or not.

**Comment by tomas-langer** [comment]
If you want to propagate multiple security headers, you can use multiple security providers. You cannot simply propagate an arbitrary header using OIDC provider.
This could be achieved through HeaderProvider.
Also using MP Rest Client is ok to propagate specific headers from request.

**Comment by tomas-langer** [comment]
I will close this issue, as you have found a suitable workaround.
