### ISSUE TITLE
Docs: first pass at updating outdated 2.0 content

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#3890]
We should make a pass over the docs to update obvious Helidon 2  content. For example:

- Ensure pre-reqs state Java 17
- Organize migration guides to separate 1.x to 2.x migration from 2.x to 3.x migration. Mention Java 17 and Jakarta packages in 2 to 3 migration.
- Check occurrences of "Helidon 2" and cleanup as appropriate

**Comment by ljamen** [comment]
LJ Notes: To address the Java versions (and other version differences between 2 and 3) I suggest we create versioned prerequisite variables and include those vs. 'hard coding' version numbers into the doc. We started doing this in 2.x.
