### ISSUE TITLE
External doc referred in Helidon's rest client doc needs update

### ISSUE THREAD

**Issue by klustria** [oracle/helidon#3899]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 2.3.2
* Helidon MP

----------

## Problem Description
Customer is asking how to disable hostname verification for a rest client in Helidon MP. The repo doc: https://github.com/oracle/helidon/blob/master/docs/mp/restclient/09_rest-client.adoc suggests reading the microprofile rest client configuration doc in https://download.eclipse.org/microprofile/microprofile-rest-client-1.2.1/microprofile-rest-client-1.2.1.html, but doesn't provide tips on how to disable hostname verification. However, the new version of the microprofile rest client doc does provide this tip in: https://download.eclipse.org/microprofile/microprofile-rest-client-2.0/microprofile-rest-client-spec-2.0.html#_hostname_verification. This issue was created to find out if doc can be changed with this new link.

**Comment by klustria** [comment]
Hi Lisa @ljamen, Thanks for assigning this to yourself so I'll let you work on this and remove myself as an assignee. Basically the goal of this change is just to replace 
the link  https://download.eclipse.org/microprofile/microprofile-rest-client-1.2.1/microprofile-rest-client-1.2.1.html with https://download.eclipse.org/microprofile/microprofile-rest-client-2.0/microprofile-rest-client-spec-2.0.html
in https://github.com/oracle/helidon/blob/master/docs/mp/restclient/09_rest-client.adoc#rest-client-configuration. Let me know if you have further questions.

**Comment by ljamen** [comment]
https://github.com/oracle/helidon/pull/3909
