### ISSUE TITLE
404 Response without body

### ISSUE THREAD

**Issue by AllanHoejgaardJensen** [oracle/helidon#390]
# 404 without response body/entity information

## Environment Details
* Helidon Version: 1.28
* Helidon MP
* JDK version: 11
* OS: MacOs
* Docker version: 18.09.1

----------

## Problem Description
Responses resulting in 404 does not seem to be able to have a body in the response.
Providing a response having an entity message for the requester e.g a json including HATEOAS links or just plain json" seems [not possible](https://github.com/oracle/helidon/blob/master/webserver/jersey/src/main/java/io/helidon/webserver/jersey/ResponseWriter.java#L110)

I implemented a very rudimentary  ["solution"](https://github.com/AllanHoejgaardJensen/helidon-breakfastcode-2019/blob/master/src/main/java/io/helidon/webserver/jersey/ResponseWriter.java#L110) in an attempt to get it working for the small example I have been using for exemplifying use of HTTP and other principles in microservices. I just do not know whether this is generally applicable or not. I have forked this project and run all tests ok with the rudimentary version.

If you think it is useful, I can create a PR for that.

Thanks.

**Comment by delabassee** [comment]
Not weighing on this issue and for the records, @AllanHoejgaardJensen has signed the OCA.

**Comment by romain-grecourt** [comment]
@spericas Is this something you can take a look at ?

**Comment by Holubow** [comment]
I experience the following unit test failures with this change: JerseySupportTest.nonJerseyGetNotFound:249->doAssert:329 » Processing Error cl...
  JerseySupportTest.nonJerseyPOSTNotFound:256->doAssert:329 » Processing Error c...

**Comment by spericas** [comment]
@romain-grecourt Sure
