### ISSUE TITLE
deleteById() in employee-app EmployeeRepositoryImpl.java broken

### ISSUE THREAD

**Issue by mshannongit** [oracle/helidon#3905]
The current impl of deleteById(String id) appears broken in 
https://github.com/oracle/helidon/blob/master/examples/employee-app/src/main/java/io/helidon/service/employee/EmployeeRepositoryImpl.java

## Environment Details
* Helidon Version: 2.4.2
* JDK version: 11
* OS: Mac

----------

## Problem Description
Ensure  drivertype: Array is being used in application.yaml (rather than Database)

Connect to web ui - e.g. http://localhost:8080/public/index.html

Click on an Employee, then click delete().  Record is not removed.

Alternative, try an update an Employee.  The update is essentially a delete followed by an add.  Due to the delete() part failing, the update ends up resulting in a secondary record being added with same id.

Current code
```
  @Override
    public CompletionStage<Long> deleteById(String id) {
        return CompletableFuture.completedFuture(eList.stream()
                                                         .filter(e -> e.getId().equals(id))
                                                         .findFirst()
                                                         .map(eList::indexOf)
                                                         .map(eList::remove)
                                                         .map(it -> 1L)
                                                         .orElse(0L));
    }
```

Potential replacement 1)
```
		Integer index = eList.stream().filter(e -> e.getId().equals(id)).findFirst().map(e -> eList.indexOf(e)).get();
		if (index != null)
		{
			eList.remove(index.intValue());
			return CompletableFuture.completedFuture(1L);
		}
		return CompletableFuture.completedFuture(0L);
```
or

Potential replacement 2)
```
		final AtomicLong deleteCount = new AtomicLong(0);
		eList.forEach(
			e -> {
				if (e.getId().equals(id))
				{
					if (eList.remove(e))
					{
						deleteCount.incrementAndGet();
					}
				}
			});

		return CompletableFuture.completedFuture(deleteCount.get());
```

**Comment by spericas** [comment]
PR #3910
