### ISSUE TITLE
Unable to provide custom response body with an implementation of AuthenticationProvider

### ISSUE THREAD

**Issue by anand-osvc** [oracle/helidon#3906]
Unable to provide custom response body with an implementation of AuthenticationProvider.

## Environment Details
* Helidon Version: 2.4.1
* Helidon MP
* JDK version: 11
* OS: Linux
* Docker version (if applicable): NA

----------

## Problem Description
I have an extended class for performing authentication and is defined like below.
public class HttpBasicAuthProvider extends SynchronousProvider implements AuthenticationProvider
I have a case where I need to return Http status as 404, when I do so I get a default message as the response body, not the one I set as description in AuthenticationResponse object. Only HttpsStatus and the Response Headers propagated and not the response message. On debugging I found like from one of the framework filters (SecurityFilterCommon), only http status and headers extracted from the AuthenticationResponse object and not the description.
How can I pass custom message body for a 404 case?

## Steps to reproduce
1. Create a rest end point
2. Secure it with an implementation of AuthenticationProvider class and give @Authenticated annotation for the rest endpoint.
3. Return a status code of 404 with a custom message.
eg: AuthenticationResponse.builder().statusCode(404)
                    .responseHeader(Http.Header.EXPECT, MessageFormat.format("{0} : {1}", statusCode, message))
                    .status(AuthenticationResponse.SecurityStatus.FAILURE).description(message).build();

Expected: I need the custom message as response body with status code available in api response.
Actual: Only status code and any header passed comes. Response body is not coming.

**Comment by spericas** [comment]
@anand-osvc Could you share `HttpBasicAuthProvider.java`?

**Comment by spericas** [comment]
@anand-osvc You mentioned some code that isn't propagating the description? There's some code in `SecurityFilterCommon` that seems guarded by the property `security.jersey.defaults.debug` that you can try setting to `true`.

**Comment by anand-osvc** [comment]
@spericas : If I set security.jersey.defaults.debug=true, I am getting the response as expected.

**Comment by spericas** [comment]
I'm closing this issue since using the debug property seems acceptable at this time. We do not want to return entities by default under these conditions for security reasons.
