### ISSUE TITLE
Verify CORS origin/host matching algorithm

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#3917]
## Environment Details
* Helidon Version: 2.x
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
In researching a separate issue, Santiago discovered what might be a bug in the Helidon CORS host/origin matching code.

We need to check:
1. How ports in the `Origin` and `Host` headers factor into the CORS protocol itself.
2. If the Helidon CORS code does the right thing with ports.

**Comment by spericas** [comment]
PR #3925
