### ISSUE TITLE
Allow developers to exclude specific REST API endpoints from access log

### ISSUE THREAD

**Issue by mhorejsi** [oracle/helidon#3924]
As of today, AccessLogSupport doesn't allow us to exclude any HTTP endpoints. External system in our application calls microservice `/metrics` endpoint every few minutes. The access log is after a while full of irrelevant log messages.

We'd like to exclude `/metrics` endpoint from our access log. The support can be written in a generic way to allow us to exclude paths matching one of the exclude regular expressions.

It's also interesting that our access log file is full of `/metrics` endpoints, but there is no `/health` endpoint. The `/health` endpoint is called every few minutes as well. Helidon should log either all _internal_ API calls (with _internal_ I mean metrics / health / etc.) or none of them.

## Environment Details
* Helidon Version: 2.3.3
* Helidon MP
* JDK version: JDK 17
* OS: N/A

**Comment by spericas** [comment]
@mhorejsi I'm taking a look at your RFE which seems very reasonable. As for the difference between the access log for health and metrics, I don't see that. Perhaps something in your app or the version of Helidon that you are using. Try the latest Helidon or provide more details about your app for further analysis.

**Comment by spericas** [comment]
@mhorejsi Please see if the additional config property would work for you in PR #3951

**Comment by mhorejsi** [comment]
Looks good, this should satisfy our requirement. Thanks for implementing it!

> As for the difference between the access log for health and metrics, I don't see that. Perhaps something in your app or the version of Helidon that you are using. Try the latest Helidon or provide more details about your app for further analysis.

We don't do anything specific with health / metrics. If upgrade to latest Helidon won't help, I'll open another issue and attach reproducible sample application.

**Comment by spericas** [comment]
@mhorejsi Roger on issue and sample app

**Comment by spericas** [comment]
Solved by PR #3951
