### ISSUE TITLE
Hocon configs does not support include

### ISSUE THREAD

**Issue by aljawado700** [oracle/helidon#3926]
## Environment Details
* Helidon Version:  2.4.1
* Helidon SE or Helidon MP: SE
* JDK version: 17
* OS: mac os Montery
* Docker version (if applicable): N/A

----------

## Problem Description
hocon cofigs directive "include" does not work.

repro: create two config files 1.conf and 2.conf. Add include 1 in 2.

**Comment by trentjeff** [comment]
See https://github.com/lightbend/config/blob/main/HOCON.md#includes

**Comment by ljnelson** [comment]
@tomas-langer looks to me (I don't know this area at all) like Helidon's HOCON support is not allowing customization of the `ConfigFactory` options that would permit this use case:

https://github.com/oracle/helidon/blob/b3fd9c0d19b1d8a2fc090a8c212cb7b2179d1407/config/hocon/src/main/java/io/helidon/config/hocon/HoconConfigParser.java#L129

We're using this:

https://github.com/lightbend/config/blob/v1.4.1/config/src/main/java/com/typesafe/config/ConfigFactory.java#L739-L741

…and the default options do not include a `ConfigIncluder`:

https://github.com/lightbend/config/blob/v1.4.1/config/src/main/java/com/typesafe/config/ConfigParseOptions.java#L47-L49

Do you concur?

**Comment by trentjeff** [comment]
@ljnelson , place take a look at what i have put together so far here - https://github.com/oracle/helidon/compare/master...trentjeff:issue-3926?expand=1

**Comment by trentjeff** [comment]
@barchetta fyi

**Comment by trentjeff** [comment]
fixed and merged in 2.x and master - https://github.com/oracle/helidon/pull/3998
