### ISSUE TITLE
Grant.builder() should extend Grant.Builder<Builder>

### ISSUE THREAD

**Issue by martin-sladecek** [oracle/helidon#3929]
## Environment Details
* Helidon Version: 3
* Helidon MP
* JDK version: 11
* OS: Linux
* Docker version (if applicable):

----------

## Problem Description
Grant.builder() should return some class that extends Grant.Builder<Builder> instead of the wildcarded Builder (i.e. there will need to be a special subclass for pure Grant).

Currently, it is not possible to use the Grant.Builder and Role.Builder as a parameter of the same methods (without ugly code).

## Sample method that should be able to accept all Grant builders, including a builder for Grant itself:
```
private static <B extends Grant.Builder<B>> B populateCommonFields(B builder)
```

**Comment by martin-sladecek** [comment]
Ideally, the testAccept should be able to work with the builder normally, like this:
```
    private static <B extends Grant.Builder<B>> B deserializeCommonFields(B builder) {
        return builder.origin("my-origin");
    }
```

**Comment by spericas** [comment]
I'm not sure the type system can handle that without the wildcard.

**Comment by martin-sladecek** [comment]
The way I had to workaround it was to create a special class `GrantBuilder extends Grant.Builder<GrantBuilder>`, would it be possible to do the same?

**Comment by spericas** [comment]
And have `Role.Builder extend GrantBuilder`? The problem with that is that it will fail to create a `Role` (not backward compatible) since `Role.builder().name("xxx").build()` will be of type `Grant` and not `Role` --- the return value of `name` will be `GrantBuilder`.

**Comment by martin-sladecek** [comment]
No, I thought Role.Builder would also have to extend Grant.Builder.

**Comment by martin-sladecek** [comment]
You are right, this doesn't have any nice solution. I guess your solution is the best possible.

**Comment by spericas** [comment]
@martin-sladecek I believe the solution that I proposed does not really improve the status quo (it should compile without any warnings as is). Closing the issue for now, we can revisit later.
