### ISSUE TITLE
Config profiles fail to function as expected with JSON/HOCON

### ISSUE THREAD

**Issue by darkevilmac** [oracle/helidon#3937]
## Environment Details
* Helidon Version: 2.4.2
* Helidon SE or Helidon MP: SE
* JDK version: JDK 17
* OS: macOS 12.1
* Docker version (if applicable): N/A

----------

## Problem Description
Config profiles fail to function as expected when using the hocon/json parsers, if you create a project with `application.json`, `application-dev.json`, and `config-profile-dev.json` files that are otherwise identical to equivalent yaml files then Helidon will refuse to load the configuration and will fallback to environment variables.

I'd expect that the function should be the same across formats considering they're both supported officially.

## Steps to reproduce
Create a new Helidon SE project and the relevant configuration files, attempt to load a variable listed in one of those configuration files, you'll get an exception stating that the key isn't present in the configuration.

I did some debugging on my end and found that the issue seems to be related to the [HoconConfigParser](https://github.com/oracle/helidon/blob/master/config/hocon/src/main/java/io/helidon/config/hocon/HoconConfigParser.java) class. When compared to the [YamlConfigParser](https://github.com/oracle/helidon/blob/master/config/yaml/src/main/java/io/helidon/config/yaml/YamlConfigParser.java#L92-L95) I noticed that the `supportedSuffixes` method was not overridden. If I create a breakpoint just before this method is called and force the resulting variable to include `json` then the issue resolves itself, until I launch the application again of course.

For reference here are the config files I was using during my tests: https://gist.github.com/darkevilmac/99eff127cf669e22ceea6e945e710e62

**Comment by spericas** [comment]
@darkevilmac Had a quick look at the issue. Indeed it seems the problem is in that method in `HoconConfigParser`. Will work on a PR to fix this.

**Comment by spericas** [comment]
PR #3945
