### ISSUE TITLE
OciRestApi - Get methods for configType and configProvider fields would help developers switch between OciObjectStorage vs ObjectStorageClient

### ISSUE THREAD

**Issue by bvkrish83** [oracle/helidon#3944]
We are using Helidon to interact with OCI ObjectStorage components. To achieve this, we are providing all OCI configuration options as part of configuration "oci.default.config and oci.config" - using both Instance Principal and OCI Profile based configuration.

But, as of now, Helidon doesn't have full support for all operations that can be performed using Object Storage SDK - like ListObjects operation on a bucket. In these cases, we want to switch to ObjectStorageClient to make the corresponding request.

We are forced to either duplicate the OCI Profile configuration, or read OCI Profile configuration data ourselves to decide on whether to use InstancePrincipal vs OCI Profile connectivity.

It might be helpful, if Helidon provides get methods for configType and configProvider fields in OciRestApi - as that would ease the process of creating ObjectStorageClient instance, and also avoid redundant reading of configuration data.

Once configType and configProvider get methods are public, we could write method similar to below one to instantiate the ObjectStorageClient properly.

>     ObjectStorageClient createObjectStorageClient(Config config) {
>         OciRestApi ociRestApi = OciRestApi.create(config);
>         if (ociRestApi.configType() == OciRestApi.ConfigType.INSTANCE_PRINCIPAL) {
>             return new ObjectStorageClient(InstancePrincipalsAuthenticationDetailsProvider.builder()....build());
>         } else if (ociRestApi.configType() == OciRestApi.ConfigType.OCI_PROFILE) {
>             return new ObjectStorageClient(SimpleAuthenticationDetailsProvider.builder()....build());
>         }
>     }
## Environment Details
* Helidon Version: 2.4.1
* Helidon MP
* JDK version: 17.0.2
* OS: Windows 10

**Comment by tomas-langer** [comment]
Hello and thanks for your issue.
As part of our ongoing improvements to OCI integration, we have decided to update our approach and provide a CDI integration for OCI SDK.
Once this change is done, you will be able to use the full set of APIs available through the SDK and get the authentication through injection.
Our own implementation will become deprecated and will be eventually removed from Helidon.

@ljnelson kindly go through the issue to see if we cover this use case in our new implementation.

**Comment by ljnelson** [comment]
This is covered in the new implementation; see #3961, particularly the class javadoc in the `OciExtension.java` class.

**Comment by bvkrish83** [comment]
@tomas-langer @ljnelson Thanks for the information.

I noticed these changes are still in progress. When can we expect to get a first build (even intermediate) with these changes available? Also, by which version do you guys plan to get rid of about to be deprecated code in Helidon?

Answers to these questions would help us schedule our releases accordingly and ensure we migrate to new suggested approach.

**Comment by tomas-langer** [comment]
Expectations (these may change):
- we want to have the OCI SDK CDI integration in the very next release (2.4.3 or 2.5.0 whichever we chose)
- existing custom OCI integration will be deprecated in the same version
- existing custom OCI integration would be most likely removed in version 3.0.0 (as it was an experimental feature)

**Comment by bvkrish83** [comment]
@tomas-langer @ljnelson Awesome. Tried the new OCI Extension with Helidon MR release 2.5.0, did a basic verification. Everything worked smoothly.

Will try to check out and verify more scenarios in the next couple of weeks. Hoping that more documentation and examples will be added to help the developers - For now, I had to dig into the source to get understanding how it works, and what keys need to be provided / added.

**Comment by ljnelson** [comment]
Glad to hear it. Did you see the [extensive javadoc](https://helidon.io/docs/v2/apidocs/io.helidon.integrations.oci.sdk.cdi/io/helidon/integrations/oci/sdk/cdi/OciExtension.html)?

**Comment by bvkrish83** [comment]
Yes, Javadoc documentation was pretty detailed.
In order to understand the difference in the config keys used between config and config-file approaches, had to look into the source code. Most of the other details were understandable from Javadocs itself.
