### ISSUE TITLE
Provide more details on how to make Jackson on Jersey work for MP

### ISSUE THREAD

**Issue by klustria** [oracle/helidon#3953]
## Environment Details
* Helidon Version: All
* Helidon MP

----------

## Problem Description
The FAQ section https://github.com/oracle/helidon/wiki/FAQ#how-do-i-use-jackson-in-helidon-mp does not provide a complete answer on how to make Jackson work when using  helidon-microprofile bundles artifact as a dependency. This issue: https://github.com/oracle/helidon/issues/3198 actually provides answer on what dependency within the bundle needs to be excluded. In my testing adding `jersey-media-json-binding`  and excluding `jersey-media-json-binding` from  `helidon-microprofile` bundles dependency made it work, even though the issue also suggests excluding `jakarta.json.bind-api` and `yasson`. Maybe we can add in the FAQ that if helidon-microprofile bundles artifact is used, then we need to add exclusion like this: 
```yaml
<dependency>
    <groupId>io.helidon.microprofile.bundles</groupId>
    <artifactId>helidon-microprofile</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-json-binding</artifactId>
        </exclusion>
        <exclusion>
            <groupId>jakarta.json.bind</groupId>
            <artifactId>jakarta.json.bind-api</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.eclipse</groupId>
            <artifactId>yasson</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by ljnelson** [comment]
I've updated the FAQ with the contents: https://github.com/oracle/helidon/wiki/FAQ#how-do-i-use-jackson-in-jersey

**Comment by klustria** [comment]
This is a sufficient update to this issue. I'll close this now.
