### ISSUE TITLE
MediaType.parse doesn't handle parameter without value

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon#3956]
```java
MediaType.parse("text/html; charset=");
```

throws the following Exception:
```java
java.lang.IllegalStateException: No more elements!
	at io.helidon.common.http.Tokenizer.checkState(Tokenizer.java:172)
	at io.helidon.common.http.Tokenizer.checkState(Tokenizer.java:157)
	at io.helidon.common.http.Tokenizer.previewChar(Tokenizer.java:119)
	at io.helidon.common.http.MediaType.parse(MediaType.java:328)
	... 1 more
```

**Comment by tomas-langer** [comment]
Can you please post a link to a spec that allows this? According to https://www.rfc-editor.org/rfc/rfc7231#section-3.1.1.2 `charset` must be a token - which means it cannot be empty. Also the token should be one of the registered ones.

**Comment by romain-grecourt** [comment]
I looked at the spec and found the same thing you did.
This is a customer issue with the webClient not able to return a response where other clients work fine (JDK's httpclient and curl) 

The server is not compliant though given that it works with other clients I believe that we should support that as well. If we don't want to we should at least handle the error properly.

**Comment by Tomas-Kraus** [comment]
I may try to handle this in #6774
