### ISSUE TITLE
AuthenticationProvider not returning Response body for failure

### ISSUE THREAD

**Issue by georgyrajan** [oracle/helidon#3995]
## Environment Details
Helidon Version: 2.4.1
Helidon MP
JDK version: 11
OS: Linux
Docker version (if applicable): NA

----------

## Problem Description

I have an extended class for performing authentication and is defined like below.

public class HttpBasicAuthProvider extends SynchronousProvider implements AuthenticationProvider

I have a case where I need to return Http status as 401, when I do so I do not get a response body.

I would like the application to return an oracle standard response body for 401 as :
{
    "detail": "Please try again or contact oracle support to get access.",
    "o:errorDetails": [
        {
            "title": "Unauthorized"
        }
    ],
    "title": "Unauthorized",
    "type": "https://datatracker.ietf.org/doc/html/rfc7235#section-3.1"
}

The http standards ask to send and entity if challenge is made atleast once  

https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

[10.4.2]() 401 Unauthorized
The request requires user authentication. The response MUST include a WWW-Authenticate header field (section 14.47) containing a challenge applicable to the requested resource. The client MAY repeat the request with a suitable Authorization header field (section [14.8](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.8)). If the request already included Authorization credentials, then the 401 response indicates that authorization has been refused for those credentials. If the 401 response contains the same challenge as the prior response, and the user agent has already attempted authentication at least once, then the user SHOULD be presented the entity that was given in the response, since that entity might include relevant diagnostic information. HTTP access authentication is explained in "HTTP Authentication: Basic and Digest Access Authentication"

## Steps to reproduce

implement AuthenticationProvider and extend SynchronousProvider in application 

check for 401 failure response from postman

**Comment by spericas** [comment]
PR #4090

**Comment by spericas** [comment]
@georgyrajan Take a look at the test/sample here:

https://github.com/oracle/helidon/tree/helidon-2.x/tests/integration/security/security-response-mapper

for how to use a `SecurityResponseMapper` to customize your response when an error is encountered. In particular, how communication (if necessary) between provider and mapper is done through the use of the Helidon context API. This new feature shall be included in the upcoming 2.5.0 version.
