### ISSUE TITLE
Add support for MicroProfile JWT auth

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon#40]
As part of MicroProfile 1.2 implementation JWT Auth support must be added to Helidon. Consider implementing the latest versio of JWT Auth.

http://microprofile.io/project/eclipse/microprofile-jwt-auth

**Comment by tomas-langer** [comment]
TCK now requires Servlet, so we cannot pass it. See: https://github.com/eclipse/microprofile/issues/59 for reference.

**Comment by tomas-langer** [comment]
Passed most TCK - opened issues with MP JWt-Auth for those we could not.
Merged into master

**Comment by OndroMih** [comment]
Hi @tomas-langer, were you able to run the JWT TCK in the end, even if it requires the servlet API? Or did you work around it somehow? I'd like to raise an issue for MP JWT to remove the servlet dependency from the TCK and use JAX-RS instead. Other specs have done a similar thing already.

**Comment by OndroMih** [comment]
I've raised an issue to make the MP JWT Servlet test optional if Servlets are not supported by the implementation: https://github.com/eclipse/microprofile-jwt-auth/issues/133
