### ISSUE TITLE
Enhance OpenAPITools generator to support MP REST client API 1.4.1, 2.0, and 3.0

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#4012]
## Environment Details
* Helidon Version: 2.x, 3.x
* Helidon SE or Helidon MP MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
Tracking bug for https://github.com/OpenAPITools/openapi-generator/issues/11953

**Comment by aserkes** [comment]
I found  an issue working with this task. The point is when I tried to use Java Client Generator to generate MicroProfile REST client v3.0 artifact using OpenAPI Spec v3 that contains such fragment :
```
paths:
  '/pet/{petId}':
    post:
      tags:
        - pet
      summary: Updates a pet in the store with form data
      description: ''
      operationId: updatePetWithForm
      parameters:
        - name: petId
          in: path
          description: ID of pet that needs to be updated
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '405':
          description: Invalid input
      security:
        - petstore_auth:
            - 'write:pets'
            - 'read:pets'
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  description: Updated name of the pet
                  type: string
                status:
                  description: Updated status of the pet
                  type: string
  '/pet/{petId}/uploadImage':
    post:
      tags:
        - pet
      summary: uploads an image
      description: ''
      operationId: uploadFile
      parameters:
        - name: petId
          in: path
          description: ID of pet to update
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - petstore_auth:
            - 'write:pets'
            - 'read:pets'
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                additionalMetadata:
                  description: Additional data to pass to server
                  type: string
                file:
                  description: file to upload
                  type: string
                  format: binary
```
As a result I receive an artifact.
If I try to build it I get an exception :
`org.eclipse.microprofile.rest.client.RestClientDefinitionException: You cant have more than 1 entity method parameter!`

The problem is that the resulting artifact contains the code that does not compliant JAX-RS 2.1 specification:
```
@RegisterRestClient
@RegisterProvider(ApiExceptionMapper.class)
@Path("/pet")
public interface PetApi  {

    @POST
    @Path("/{petId}")
    @Consumes({ "application/x-www-form-urlencoded" })
    public void updatePetWithForm(@PathParam("petId") Long petId, @Multipart(value = "name", required = false)  String name, @Multipart(value = "status", required = false)  String status) throws ApiException, ProcessingException;

    @POST
    @Path("/{petId}/uploadImage")
    @Consumes({ "multipart/form-data" })
    @Produces({ "application/json" })
    public ModelApiResponse uploadFile(@PathParam("petId") Long petId, @Multipart(value = "additionalMetadata", required = false)  String additionalMetadata,  @Multipart(value = "file" , required = false) Attachment _fileDetail) throws ApiException, ProcessingException;
}
```

Related points from JAX-RS 2.1 specification :
```
3.3.2.1 Entity Parameters
The value of a parameter not annotated with @FormParam or any of the annotations listed in in Section 3.2,
called the entity parameter, is mapped from the request entity body. Conversion between an entity body and
a Java type is the responsibility of an entity provider, see Section 4.2. Resource methods MUST have at
most one entity parameter.

3.2 Fields and Bean Properties
When a resource class is instantiated, the values of fields and bean properties annotated with one the following annotations are set according to the semantics of the annotation:
@MatrixParam Extracts the value of a URI matrix parameter.
@QueryParam Extracts the value of a URI query parameter.
@PathParam Extracts the value of a URI template parameter.
@CookieParam Extracts the value of a cookie.
@HeaderParam Extracts the value of a header.
@Context Injects an instance of a supported resource, see chapters 10 and 11 for more details.
...
```

To solve this problem the Java Client Generator has to be changed, but the problem is that no specification that related to the processing of the forms exists and the generator in this part will be provider specific and this has to be discussed.

**Comment by tjquinno** [comment]
Some questions and thoughts.

1. The error message you posted does not tell which method is wrong. I assume both are, because both have multiple parameters, but maybe you could confirm that by commenting out first one method, rebuilding and restarting, then uncommenting that one and commenting out the other one, rebuilding, and restarting, and seeing if the same error occurs both ways.
2. Which  earlier versions of MP REST client, 1.0 and 2.0, accept the same code without error, if any?
3. Does this error result from a change in the MP REST client code itself, or does the newer MP REST client have a dependency on a newer JAX-RS version and it is actually JAX-RS that detects this problem and MP REST client is simply wrapping the exception?
4. Clearly the generator can know if there are multiple parameters for an endpoint method because it has access to the OpenAPI document and the internal model derived from the document. Maybe this is too simplistic, but perhaps the generator will have to be changed to:
   1.  Detect this situation.
   2. Generate a uniquely-named POJO class or record with one field for each multipart parameter.
   3. Generate the multipart `PUT` method signature with _one_ entity parameter with the type of the generated class or  record mentioned above.
   4. Generate the `PUT` method in the interface as a `default` method with an implementation which takes the single parameter and invokes an interface method with the signature that is currently generated, passing the separate parts of the multipart data as separate parameters.

I'm not sure what other logic would have to be generated so step 4 above would work. But this approach would implement an endpoint with a single entity parameter as required while still exposing an interface method with the separate parts. The developer implements _that_ method instead of the actual endpoint method.

I am not very familiar with the MP REST client itself and multipart. Maybe this approach is not feasible, but it seems to me as if this or something like this should be workable.

**Comment by aserkes** [comment]
@tjquinno 
1. Error message the same for the both methods. I tried to comment/uncomment methods and the results  are the same.
2. MP REST client  (versions 1.4.1 or 2.0) does not have this problem, but  for these versions of MP Rest client another provider was used. It was `smallrye`. This issue exists only for MP REST client  of version 3.0 and `jersey` as a provider. I did not find any other provider that fully support MP REST client 3.0.
3. This case is fully dependent on the provider. This error is not related to the MP REST client code  and in my case `jersey` detects the problem and it is correct behaviour.
4. I thought about the same solution as you proposed and I agree with you, but as I wrote before this case is provider`s specific. Current implementation is depended form `apache.cxf` and its `@Multipart`. If we decide to change the code of the OpenApi generator maybe it is better to use `@FormParam` from Jakarta EE and `@FormDataParam` from Jersey and this is the topic for discussion.

**Comment by tjquinno** [comment]
I agree we need to discuss this issue to find a good path forward. Unfortunately, I have to be out of the office for a while and I do not want us to stop making progress on this waiting for me to return. So exchanging ideas will have to happen here, asynchronously. I apologize for that.

I do not think the generator can assume that all multipart requests will use form data. What if the OpenAPI document specified other subtypes of `multipart` different from `form-data`? For example, `mixed`. 

I can think of two approaches. Maybe one of these would work. Maybe there are other options as well.

## Change the generator so it creates provider-independent code
This is what I was thinking about in my previous note and what you said you had also thought about. Even if this is possible, it might not be the best solution. It probably would require the generator to contain or to generate code that the various providers/implementations already implement in their own way (such as the form data support you mentioned).

## Allow users to select the JAX-RS provider at generation-time
It would probably be best if the generator lets the user select which JAX-RS implementation to use: jersey, resteasy/smallrye, etc. 

The normal way to do this with the OpenAPITools generator is to create one or more _libraries_ under a _generator_. In this case, that could mean (for example) the resteasy/smallrye implementation would be used by the templates in the existing MP REST client generator and we could create a `jersey` library under that generator. 

The jersey library would override as few templates as possible (but as many as needed) from the parent MP REST client generator to create code that works with Jersey.

Users who want the generator to create code using the existing resteasy/smallrye support would not specify a library. Users who wanted the Jersey support would specify the jersey library.

This approach isolates the changes we would make from the existing generator. Doing this greatly reduces the risk that our work would cause problems for existing users of the generator and therefore greatly reduces the need for us to test the existing generator after we add the library.

The OpenAPITools site describes the general approach of creating libraries. Also look at the internal gist I earlier linked to privately for some more information on how the generator is organized.
