### ISSUE TITLE
Create short Helidon guide describing how to use OpenAPITools generator for Helidon

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#4018]
## Environment Details
* Helidon Version: 2.x, 3.x
* Helidon SE or Helidon MP MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
Today, users can use the OpenAPITools generator to create Helidon MP server code and MicroProfile REST client code.
We have no documentation on the Helidon site explaining how to do this.

This issue represents creating a short guide which summarizes the support in the tool for Helidon and gives detailed instructions and examples (command line, the tool's maven plug-in, etc.) for using the tool to generated or update Helidon-friendly code.

**Comment by barchetta** [comment]
This should include an example.

**Comment by tjquinno** [comment]
See  #4024. Thibault is already working on the example.

**Comment by barchetta** [comment]
That sounds good. I was thinking it could follow the pattern that Keith uses in one of his projects. He has a project with spec, client and server modules. Maven plugin is used to generate client and server code (use base interface for generated code with business logic in implementing class).  You can run the client code to communicate with the server.

**Comment by barchetta** [comment]
Covered by new Epic for Helidon Specific generator. Closing.
