### ISSUE TITLE
Update Helidon OpenAPITools guide to describe Helidon SE support

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#4020]
[## Environment Details
* Helidon Version: 2.x, 3.x
* Helidon SE or Helidon MP SE
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
See #4019 (adding SE server support to the tool) and #4018 (creating short Helidon guide for using the tool)

Presumably, by the time we have completed #4019 we will have the guide mentioned in #4018. This issue is for the work to update the guide with new information about Helidon SE generation using the tool.

**Comment by barchetta** [comment]
Covered by new Epic for Helidon Specific generator. Closing.
