### ISSUE TITLE
Create/update brief Helidon guide on using OpenAPITools generator for MP REST client gen.

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#4021]
## Environment Details
* Helidon Version: 2.x, 3.x
* Helidon SE or Helidon MP MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
See also #4018 (creating brief Helidon guide for using OpenAPITools generator) and #4012 (enhancing the tool to handle MP REST client API 2.0 and 3.0 as well as 1.4.1 as it does currently)

This issue is for the work to update the guide once the MP REST client changes are done in the OpenAPITools generator.

**Comment by barchetta** [comment]
Covered by new Epic for Helidon Specific generator. Closing.
