### ISSUE TITLE
Productize current work toward OpenAPITools enhancement for Helidon SE WebClient generation

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#4022]
## Environment Details
* Helidon Version: 2.x, 3.x
* Helidon SE or Helidon MP SE
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
Tim has already done some work for adding Helidon SE web client generation to the OpenAPITools generator.

This issue is for the work to finish that effort and merge it into the tool.

**Comment by barchetta** [comment]
This will be covered by our Helidon specific generator.
