### ISSUE TITLE
Update Helidon guide for OpenAPITools gen with Helidon SE client generation information

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#4023]
## Environment Details
* Helidon Version: 2.x, 3.x
* Helidon SE or Helidon MP SE
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
See also #4022 (adding Helidon SE client gen to the tool) and #4018 (creating Helidon guide about using OpenAPITools generator)

This issue covers the work for updating the Helidon guide to using OpenAPITools with new info about Helidon SE client generation.

**Comment by barchetta** [comment]
Covered by new Epic for Helidon Specific generator. Closing.
