### ISSUE TITLE
Add doc, examples for using the MicroProfile OpenAPI-U/I extension with Helidon

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#4024]
## Environment Details
* Helidon Version: 2.x, 3.x
* Helidon SE or Helidon MP MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
The MicroProfile OpenAPI-U/I extension https://github.com/microprofile-extensions/openapi-ext/tree/main/openapi-ui easily adds a GUI to an application with OpenAPI support that lets users drive the REST API of the service from a browser.

This works easily today with simple Helidon MP apps, with some tricks required for more complicated cases. See our FAQ section on this for some of the information: https://github.com/oracle/helidon/wiki/FAQ#the-microprofile-openapi-ui-extension

We should add a few simple examples.

**Comment by tvallin** [comment]
Hello @tjquinno, 
Is there something specific you would like to see as an example ?

**Comment by tjquinno** [comment]
I think we want two examples: one showing the simplest and most common use case, and a separate one showing many if not all of the complications a developer might have. 

These are the complications:
* Specify an application path prefix for the business endpoints (`/myapp`)
* Specify a non-default path for the OpenAPI U/I endpoint
* Specify a non-default path for the endpoint that returns the OpenAPI document

I think in my description below I've remembered all the details for how to make the complicated scenario work, but I might have missed a point or two. Check the doc for the OpenAPI U/I for the config settings available to control its behavior.

Example 1. Start with the example app here https://github.com/oracle/helidon/tree/master/examples/microprofile/openapi-basic. Then add the dependency shown in the FAQ link to add the U/I support. (This is a very simple example but is the one closest to what _most_ users will do.)


Example 2. Start with the result from the above step. Modify it as follows:

1.  Add an `Application` class with `@AppPath` set to something like `/myapp` and implement its `getClasses` method to return a `Set` containing the greeting resource class.
2.  Add an `Application` class with `@AppPath` set to something like `/myopenapi` and implement its `getClasses` method to return the two U/I resource classes (mentioned in the FAQ).
3.  Modify the `microprofile-config.properties`:
    1.  Have Helidon expose the OpenAPI document at a custom endpoint. IIRC `openapi.web-context=/myopenapi`
    2.  Have the OpenAPI U/I code expose its GUI at a custom endpoint. I don't recall the property name. The U/I documentation gives the property name.
    3.  Have the OpenAPI U/I get the OpenAPI document from the customized Helidon endpoint. There is another OpenAPI U/I property setting to control that.

The customized path for the OpenAPI U/I cannot be more than one segment. That is, `/myopenapi` will work  IIRC but `/my/openapi` will not. This is due to the way the OpenAPI U/I code is written; there is nothing Helidon can do about that.

**Comment by phillip-kruger** [comment]
If you are usingSmallRye OpenAPI (i think you do but could not confirm) also look at the ui module in https://github.com/smallrye/smallrye-open-api, when most of the microprofile-ext work moved. It's better maintained there

**Comment by phillip-kruger** [comment]
There you can use the IndexHTMLCreator to generate a custom HTML, making things like changing the path and other config easier. See https://github.com/smallrye/smallrye-open-api/blob/main/ui/open-api-ui/src/main/java/io/smallrye/openapi/ui/IndexHtmlCreator.java

**Comment by tvallin** [comment]
Thanks a lot @phillip-kruger, I will have a look and update the examples.
