### ISSUE TITLE
Remove opentracing from core of webserver

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#4085]
As OpenTelemetry has gained momentum, we should remove opentracing support from webserver core, and add new module(s) for tracing support that are not built into webserver.

This will have the following impact:
- configuration will be separated into the tracing module only (e.g. tracer would not be available on webserver or its builder)
- performance impact will be visible only when tracing module would be used and registered
- tracing integration would be less optimal, as it would no longer be part of the core code

**Comment by danielkec** [comment]
Fixed by #4458
