### ISSUE TITLE
Enhence OpenAPI Generator (MicroProfile REST client generation) - allow users to select the JAX-RS provider at generation-time

### ISSUE THREAD

**Issue by aserkes** [oracle/helidon#4116]
## Environment Details
* Helidon Version:
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description

It would probably be best if the generator lets the user select which JAX-RS implementation to use: jersey, resteasy/smallrye, etc. when the user wants to generate MicroProfile REST client artifact.

The normal way to do this with the OpenAPITools generator is to create one or more libraries under a generator or use some configuration option for the existing library. In this case, that could mean (for example) the resteasy/smallrye implementation would be used by the templates in the existing MP REST client generator and we could create a jersey library under that generator or use configOption (fro example `provider`) with value `jersey` for an existing library and generator.

The jersey library(configOption `provider`) would override as few templates as possible (but as many as needed) from the parent MP REST client generator to create code that works with Jersey.

Users who want the generator to create code using the existing resteasy/smallrye support would not specify a library/configOption. Users who wanted the Jersey support would specify the jersey library/configOption.

This approach isolates the changes we would make from the existing generator. Doing this greatly reduces the risk that our work would cause problems for existing users of the generator and therefore greatly reduces the need for us to test the existing generator after we add the library.

**Comment by barchetta** [comment]
Given our new direction with Helidon specific generators I am closing this issue as no longer applicable.
