### ISSUE TITLE
MicroProfile OpenAPI 1.1

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon#412]
See also:

- [ ] #550 (SE support)

**Comment by tjquinno** [comment]
Joe pointed to https://github.com/smallrye/smallrye-open-api which is an MP-compliant implementation. I am in the process of looking at this to see if/how/to what extent we might be able to take advantage of it.

**Comment by m0mus** [comment]
Closing this task. Tracking will continue in #550 and #619 tasks.
