### ISSUE TITLE
Additional OpenAPITools server problems and enhancements

### ISSUE THREAD

**Issue by spericas** [oracle/helidon#4125]
Other problems not covered in #4110.

- [ ] Generator creates an empty Application subclass with a path specified in @ApplicationPath. This class is currently ignored by Helidon because it does not have a BDA such as @ApplicationScoped. We should either add a BDA or drop it altogether. Since it is empty, we should be gathering all resources/providers using CDI bean discovery anyway.
- [ ] The sources are generated under src/gen/java which is not a compiler source root for Maven by default. One possibility would be to update the generated pom. Alternatively, we could change that location for Helidon (likely better).
- [ ] Generation of @Valid should be turned off by default
- [ ] Indentation, especially in model classes, is ugly and inconsistent
- [ ] There should be unit tests in the generated code
- [ ] There should be an option to generate source only and not a full project with pom

**Comment by tjquinno** [comment]
See a few relevant comments here: https://github.com/oracle/helidon/issues/4110#issuecomment-1098334149

**Comment by barchetta** [comment]
This will be covered by our Helidon specific generators.
