### ISSUE TITLE
Update existing Helidon lab on OCI

### ISSUE THREAD

**Issue by ljamen** [oracle/helidon#4129]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 2.x
* Helidon SE 
* JDK version: 11
* OS: na
* Docker version (if applicable):

----------

## Problem Description
Lab on OCI is from Helidon 1.x and needs to be updated. 

## Steps to reproduce
Existing Lab (in prod): https://docs.oracle.com/en/solutions/develop-microservice-java-app/develop-application1.html#GUID-618F068E-3BF2-48B2-ABD2-78BE2A65F00A
Updated Lab to review (in UAT): https://docs-uat.us.oracle.com/en/solutions/develop-microservice-java-app/develop-application1.html#GUID-5B75A27F-D0B1-4CB3-BBCE-D67AABFAFACC

**Comment by ljamen** [comment]
This will not have a PR since the files are outside of Git. I've asked @dalexandrov to review the content with me using the UAT link above.

**Comment by ljamen** [comment]
Create an Oracle Review site to discuss updates https://review.us.oracle.com/review2/Review.html#reviewId=449987;scope=document;status=open,fixed

**Comment by dalexandrov** [comment]
Just one minor fix, looks good now! Thank you!!!

**Comment by ljamen** [comment]
Here is the build in UAT with all requested changes. https://docs-uat.us.oracle.com/en/solutions/develop-microservice-java-app/develop-application1.html#GUID-618F068E-3BF2-48B2-ABD2-78BE2A65F00A

**Comment by edbratt** [comment]
So long as the Lab steps work as intended, I'm happy. Go ahead and publish if you haven't already.
