### ISSUE TITLE
Support HOCON include without extension

### ISSUE THREAD

**Issue by janotav** [oracle/helidon#4152]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 2.5.0
* Helidon SE 
* JDK version: 14
* OS: Linux
* Docker version (if applicable):

----------

## Problem Description

According to [spec](https://github.com/lightbend/config/blob/master/HOCON.md#include-semantics-file-formats-and-extensions), extension should not be mandatory when processing includes. Following should work:

* base.conf
* cloud.conf: include "base"

Currently only this works:

* base.conf
* cloud.conf: include "base.conf"

**Comment by spericas** [comment]
PR #4152
