### ISSUE TITLE
No handler found for path: /greeting For Gradle Project

### ISSUE THREAD

**Issue by gyanicit** [oracle/helidon#4182]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 2.5.0
* Helidon MP
* JDK version: 11
* OS: Windows 10
* Docker version (if applicable): None

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
### I have cloned the project from https://github.com/oracle/helidon/tree/2.5.0/examples/quickstarts/helidon-quickstart-mp. Without any change trying to run the application but having issue
"No handler found for path: /greet"

Even not sure why server is running on port no: ___7001___ . And Same project is running fine with Maven.

May 06, 2022 8:37:52 AM io.helidon.common.LogConfig doConfigureLogging
INFO: Logging at initialization configured using defaults
May 06, 2022 8:37:52 AM org.jboss.weld.bootstrap.WeldStartup <clinit>
INFO: WELD-000900: 3.1.6 (Final)
May 06, 2022 8:37:52 AM org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory create
INFO: WELD-ENV-000020: Using jandex for bean discovery
May 06, 2022 8:37:52 AM org.jboss.weld.bootstrap.WeldStartup startContainer
INFO: WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
May 06, 2022 8:37:52 AM org.jboss.weld.event.ExtensionObserverMethodImpl checkRequiredTypeAnnotations
INFO: WELD-000411: Observer method [BackedAnnotatedMethod] private io.helidon.microprofile.openapi.OpenApiCdiExtension.processAnnotatedType(@Observes ProcessAnnotatedType<X>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
May 06, 2022 8:37:52 AM org.jboss.weld.event.ExtensionObserverMethodImpl checkRequiredTypeAnnotations
INFO: WELD-000411: Observer method [BackedAnnotatedMethod] public org.glassfish.jersey.ext.cdi1x.internal.ProcessAllAnnotatedTypes.processAnnotatedType(@Observes ProcessAnnotatedType<?>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
May 06, 2022 8:37:53 AM io.helidon.tracing.tracerresolver.TracerResolverBuilder build
INFO: TracerResolver not configured, tracing is disabled
May 06, 2022 8:37:53 AM io.helidon.microprofile.tracing.TracingCdiExtension prepareTracer
WARNING: helidon-microprofile-tracing is on the classpath, yet there is no tracer implementation library. Tracing uses a no-op tracer. As a result, no tracing will be configured for WebServer and JAX-RS
May 06, 2022 8:37:53 AM io.helidon.microprofile.security.SecurityCdiExtension registerSecurity
INFO: Authentication provider is missing from security configuration, but security extension for microprofile is enabled (requires providers configuration at key security.providers). Security will not have any valid authentication provider
May 06, 2022 8:37:53 AM io.helidon.microprofile.security.SecurityCdiExtension registerSecurity
INFO: Authorization provider is missing from security configuration, but security extension for microprofile is enabled (requires providers configuration at key security.providers). ABAC provider is configured for authorization.
May 06, 2022 8:37:53 AM io.helidon.microprofile.server.ServerCdiExtension registerJaxRsApplications
WARNING: There are no JAX-RS applications or resources. Maybe you forgot META-INF/beans.xml file?
May 06, 2022 8:37:53 AM io.helidon.webserver.NettyWebServer lambda$start$8
INFO: Channel '@default' started: [id: 0xaf2e4c3e, L:/0:0:0:0:0:0:0:0:7001]
May 06, 2022 8:37:53 AM io.helidon.microprofile.server.ServerCdiExtension startServer
INFO: Server started on http://localhost:7001 (and all other host addresses) in 1806 milliseconds (since JVM startup).
May 06, 2022 8:37:53 AM io.helidon.common.HelidonFeatures features
INFO: Helidon MP 2.5.0 features: [CDI, Config, Fault Tolerance, Health, JAX-RS, Metrics, Open API, Security, Server, Tracing]

## Steps to reproduce
```

package io.helidon.examples.quickstart.mp;

import java.util.Collections;

import javax.inject.Inject;
import javax.json.Json;
import javax.json.JsonBuilderFactory;
import javax.json.JsonObject;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

import org.eclipse.microprofile.openapi.annotations.enums.SchemaType;
import org.eclipse.microprofile.openapi.annotations.media.Content;
import org.eclipse.microprofile.openapi.annotations.media.Schema;
import org.eclipse.microprofile.openapi.annotations.parameters.RequestBody;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponse;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponses;

/**
 * A simple JAX-RS resource to greet you. Examples:
 *
 * Get default greeting message:
 * curl -X GET http://localhost:8080/greet
 *
 * Get greeting message for Joe:
 * curl -X GET http://localhost:8080/greet/Joe
 *
 * Change greeting
 * curl -X PUT -H "Content-Type: application/json" -d '{"greeting" : "Howdy"}' http://localhost:8080/greet/greeting
 *
 * The message is returned as a JSON object.
 */
@Path("/greet")
public class GreetResource {

    private static final JsonBuilderFactory JSON = Json.createBuilderFactory(Collections.emptyMap());

    /**
     * The greeting message provider.
     */
    private final GreetingProvider greetingProvider;

    /**
     * Using constructor injection to get a configuration property.
     * By default this gets the value from META-INF/microprofile-config
     *
     * @param greetingConfig the configured greeting message
     */
    @Inject
    public GreetResource(GreetingProvider greetingConfig) {
        this.greetingProvider = greetingConfig;
    }

    /**
     * Return a worldly greeting message.
     *
     * @return {@link JsonObject}
     */
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public JsonObject getDefaultMessage() {
        return createResponse("World");
    }

    /**
     * Return a greeting message using the name that was provided.
     *
     * @param name the name to greet
     * @return {@link JsonObject}
     */
    @Path("/{name}")
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public JsonObject getMessage(@PathParam("name") String name) {
        return createResponse(name);
    }

    /**
     * Set the greeting to use in future messages.
     *
     * @param jsonObject JSON containing the new greeting
     * @return {@link Response}
     */
    @Path("/greeting")
    @PUT
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @RequestBody(name = "greeting",
            required = true,
            content = @Content(mediaType = "application/json",
                    schema = @Schema(type = SchemaType.STRING, example = "{\"greeting\" : \"Hola\"}")))
    @APIResponses({
            @APIResponse(name = "normal", responseCode = "204", description = "Greeting updated"),
            @APIResponse(name = "missing 'greeting'", responseCode = "400",
                    description = "JSON did not contain setting for 'greeting'")})
    public Response updateGreeting(JsonObject jsonObject) {

        if (!jsonObject.containsKey("greeting")) {
            JsonObject entity = JSON.createObjectBuilder()
                    .add("error", "No greeting provided")
                    .build();
            return Response.status(Response.Status.BAD_REQUEST).entity(entity).build();
        }

        String newGreeting = jsonObject.getString("greeting");

        greetingProvider.setMessage(newGreeting);
        return Response.status(Response.Status.NO_CONTENT).build();
    }

    private JsonObject createResponse(String who) {
        String msg = String.format("%s %s!", greetingProvider.getMessage(), who);

        return JSON.createObjectBuilder()
                .add("message", msg)
                .build();
    }
}


```

```
Clone the project
c:\helidon-quickstart-mp> gradle clean
c:\helidon-quickstart-mp> gradle build
c:\helidon-quickstart-mp\build\libs> java -jar helidon-quickstart-mp.jar
```

**Comment by barchetta** [comment]
I tried this with Java 11 with both Gradle 7.2 and 7.4.2 on MacOS (still need to try on Windows -- which I suspect is the issue). Here is what I found:

The tests are broken. The following needs to be added to the `build.gradle` file:

```
    testImplementation 'io.helidon.microprofile.tests:helidon-microprofile-tests-junit5'
```

After fixing that I had to add the following to eliminate some warnings about ambiguous dependencies on the `jandex` task:
```
compileTestJava.dependsOn jandex
jar.dependsOn test
```

That gave me a clean build and the following worked fine:
```
java -jar build/libs/helidon-quickstart-mp.jar
```
```

**Comment by barchetta** [comment]
After the changes above I was able to build and run on Windows 10.

**Comment by barchetta** [comment]
With the above fixes this is working for me.
