### ISSUE TITLE
Bump version of hibernate to 6.0.1.Final - so we can leverage various (performance) improvements

### ISSUE THREAD

**Issue by jvissers** [oracle/helidon#4188]
## Environment Details
* Helidon Version: 2.5.0
* Helidon MP
* JDK version: 17.0.2
* OS: Ubuntu 22.04 LTS
* Docker version (if applicable): n/a

----------

## Problem Description
Version 6.0.1.Final of Hibernate provides a number of performance improvements.
https://github.com/hibernate/hibernate-orm/blob/main/changelog.txt

In order to benefit from these improvements, Helidon MP should consider bumping the version to 6.0.1.Final

**Comment by ljnelson** [comment]
We can't do this on the 2.x line; Hibernate 6 [relies on Jakarta Persistence 3.0](https://hibernate.org/orm/releases/6.0/), which [involves `jakarta.persistence` packages](https://jakarta.ee/specifications/persistence/3.0/apidocs/jakarta.persistence/module-summary.html), not `javax.persistence` packages.

**Comment by jvissers** [comment]
Ah - I see, that's unfortunate.

I actually checked the [FAQ](https://github.com/oracle/helidon/wiki/FAQ) earlier and it points to the 3.0 specification: https://jakarta.ee/specifications/persistence/3.0/jakarta-persistence-spec-3.0.html

From there I took it that this potentially would be doable.

**Comment by ljnelson** [comment]
Perhaps we're talking past each other: Jakarta Persistence 3.0 features `jakarta.persistence` package names.  Helidon 2.5.0 relies on Jakarta Persistence 2.2, which features `javax.persistence` package names.

**Comment by jvissers** [comment]
> Perhaps we're talking past each other: Jakarta Persistence 3.0 features `jakarta.persistence` package names. Helidon 2.5.0 relies on Jakarta Persistence 2.2, which features `javax.persistence` package names. I'll change the FAQ information, which was written to be against our `master` branch, which will eventually become the Helidon 3.x line.

I guess we are the FAQ that I was referring to is from MP 2.5.0 and it points to 3.0.0 JPA. So that is confusing, the link in the FAQ should probably be update.

**Comment by ljnelson** [comment]
This is addressed in `master` with #4484.
