### ISSUE TITLE
Gradle test doesn't get executed from the sample grade build script

### ISSUE THREAD

**Issue by jsong8** [oracle/helidon#4196]
[//]: # "I am using the sample gradle file here
https://github.com/oracle/helidon/blob/2.4.2/examples/quickstarts/helidon-quickstart-mp/build.gradle
I am getting errors in :test when running a build
Execution optimizations have been disabled for task ':test' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '<my service path>/build/resources/main'. Reason: Task ':test' uses this output of task ':jandex' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem."

## Environment Details
* Helidon Version: 2.4.2 and 2.5.0
* Helidon SE or Helidon MP: MP
* JDK version: 11
* OS: MacOS
* Docker version (if applicable):

----------

## Problem Description
[//]: # "I am using the sample gradle file here
https://github.com/oracle/helidon/blob/2.4.2/examples/quickstarts/helidon-quickstart-mp/build.gradle
I am getting errors in :test when running a build
Execution optimizations have been disabled for task ':test' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '<my service path>/build/resources/main'. Reason: Task ':test' uses this output of task ':jandex' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem."
[//]: # "reproducible"
[//]: # "grade build or grade test"

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

**Comment by arjav-desai** [comment]
The issue coming due to changes in Gradle as discussed here https://github.com/kordamp/jandex-gradle-plugin/issues/9 and https://github.com/kordamp/jandex-gradle-plugin/issues/11. 

We can work around by changing/adding following to build.gradle in example

tasks.named('compileTestJava') {
    dependsOn(jandex)
}

test {
    useJUnitPlatform()
    dependsOn(jandex)
}

**Comment by jsong8** [comment]
Now gradle build doesn't execute tests anymore. Task:jar depends on "jandex".
> Task :jar
Execution optimizations have been disabled for task ':jar' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/jiansong/projects/ci/al/searchservice/subscriberIcijService/build/resources/main'. Reason: Task ':jar' uses this output of task ':jandex' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.
