### ISSUE TITLE
[Doc:] Helidon MP Metrics

### ISSUE THREAD

**Issue by dalexandrov** [oracle/helidon#4198]
Helidon MP Metrics documentation (according to the new documentation structure).

Path: `/HelidonMP/Observability`

- [x] Overview (may be reused from current doc)
- [x] Maven Dependency (may be reused from current doc)
- [x] Usage (may be reused from Metrics Spec doc)
- [x] API (may be reused from Metrics Spec doc/website)
- [x] Configuration (should be created)
- [x] Reference (generated)
- [x] Examples (may be reused from Helidon repo)
- [x] Additional Information (should include `Metric-Capable Modules`, `Metrics for Exemplars` and `Micrometer`)

**Comment by ljamen** [comment]
Comments left on #4536
