### ISSUE TITLE
[Doc:] Helidon MP Validation 

### ISSUE THREAD

**Issue by dalexandrov** [oracle/helidon#4202]
Helidon MP Validation documentation (according to the new documentation structure).

Path: `/HelidonMP/Enterprise`

Should cover General Bean Validation and Jersey validation 

- [x] Overview (should be created)
- [x] Maven Dependency (may be reused from current doc)
- [x] Usage (should be created)
- [x] API (should be created using Bean Validation documentation)
- [x] Configuration (should be created)
- [x] Reference (should be created)
- [x] Examples (may be reused from Helidon repo)
- [x] Additional Information (if applicable)

**Comment by ljamen** [comment]
I completed my review in the PR.
