### ISSUE TITLE
[Doc:] Helidon MP LRA 

### ISSUE THREAD

**Issue by dalexandrov** [oracle/helidon#4205]
Helidon MP LRA documentation (according to the new documentation structure).

Path: `/HelidonMP/Enterprise`

All sub-chapters should be united

- [x] Overview (should be created)
- [x] Maven Dependency (may be reused from current doc)
- [x] Usage (should be created)
- [x] API (can be reused from current doc)
- [x] Configuration (can be reused from current doc)
- [x] Reference (should be created)
- [x] Examples (reuse existing)
- [x] Additional Information (`Coordinator` may be described here)

**Comment by ljamen** [comment]
Comments on #4513
