### ISSUE TITLE
[Doc:] Helidon MP JAX-RS/Jersey Client

### ISSUE THREAD

**Issue by dalexandrov** [oracle/helidon#4208]
Helidon MP JAX-RS/Jersey Client documentation (according to the new documentation structure).

Path: `/HelidonMP/Enterprise/Calling Other Services`

Sub-chapters should be united. 

- [ ] Overview (general description should be created)
- [ ] Maven Dependency (may be reused from current doc)
- [ ] Usage (may be reused from current doc)
- [ ] API (can be reused from current doc)
- [ ] Configuration (may be extended from the current docs)
- [ ] Reference (generated)
- [ ] Examples (reuse existing)
- [ ] Additional Information (`Reactive routing` may be included here)

**Comment by spericas** [comment]
PR #4451
