### ISSUE TITLE
[Doc:] Helidon MP gRPC

### ISSUE THREAD

**Issue by dalexandrov** [oracle/helidon#4211]
Helidon MP gRPC documentation (according to the new documentation structure).

Path: `/HelidonMP/Protocols`

Open question if the chapter should be separated to client and server

- [ ] Overview (May be reused from the current doc)
- [ ] Maven Dependency (may be reused from current doc)
- [ ] Usage (may be reused from the current docs)
- [ ] API (should be created)
- [ ] Configuration (may be extended from the current docs)
- [ ] Reference (generated)
- [ ] Examples (one for server and one for client)
- [ ] Additional Information (if applicable)

**Comment by klustria** [comment]
Initial merge completed in https://github.com/oracle/helidon/pull/4569

**Comment by klustria** [comment]
This [issue](https://github.com/oracle/helidon/issues/4211) and https://github.com/oracle/helidon/issues/4316 are resolved in both PRs:  https://github.com/oracle/helidon/pull/4569 and https://github.com/oracle/helidon/pull/4606

**Comment by ljamen** [comment]
Doc reviews were conducted on #4569 and #4606. Edits were completed. This issue and 4316 can now be closed.
