### ISSUE TITLE
[Doc:] Helidon MP GraphQL

### ISSUE THREAD

**Issue by dalexandrov** [oracle/helidon#4212]
Helidon MP GraphQL documentation (according to the new documentation structure).

Path: `/HelidonMP/Protocols`

- [x] Overview (Should be extended from the current doc)
- [x] Maven Dependency (may be reused from current doc)
- [ ] Usage (may be reused from the current docs)
- [x] API (should be created)
- [x] Configuration (may be extended from the current docs)
- [ ] Reference (generated)
- [x] Examples (may be reused from the current docs)
- [x] Additional Information (if applicable)

**Comment by edbratt** [comment]
Please be sure to remove the Experimental warning block in the docs.

**Comment by spericas** [comment]
PR #4514
