### ISSUE TITLE
ThreadPool doesn't count task failures

### ISSUE THREAD

**Issue by Chewbizz** [oracle/helidon#4228]
The failedTasks counter is never written (never incremented) in ThreadPool
https://github.com/oracle/helidon/blob/59d226b8c26d04f707a74f4044118bd0d5042bfe/common/configurable/src/main/java/io/helidon/common/configurable/ThreadPool.java#L70

Assuming:
https://github.com/oracle/helidon/blob/59d226b8c26d04f707a74f4044118bd0d5042bfe/common/configurable/src/main/java/io/helidon/common/configurable/ThreadPool.java#L272-L274

One would expect failedTasks it to be incremented instead of the completedTasks counter when the Throwable parameter is not null in:
https://github.com/oracle/helidon/blob/59d226b8c26d04f707a74f4044118bd0d5042bfe/common/configurable/src/main/java/io/helidon/common/configurable/ThreadPool.java#L378-L381

As mentioned in [javadoc of afterExecute](https://devdocs.io/openjdk~18/java.base/java/util/concurrent/threadpoolexecutor#afterExecute(java.lang.Runnable,java.lang.Throwable)) it's not trivial to get failedTasks.
But I would expect either a support for reporting failures, or no support at all, hence no getter or associated metric for failures.
In the current state, the API seem to support failures, but doesn't support them, which is misleading.

**Comment by spericas** [comment]
PR #4244
