### ISSUE TITLE
helidon.io: support some vanity URLs

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#428]
Enhance helidon.io to support some vanity URLs that we can reference. 

For example: "/guides", "/getting-started", "/javadocs", "/docs"

Do this in a way that we can continue to serve web site from GitHub pages. AOK if these are redirects.

(Filing this issue here and not helidon-site so that we can track via team board).

**Comment by romain-grecourt** [comment]
See https://github.com/oracle/helidon-build-tools/issues/34

**Comment by romain-grecourt** [comment]
E.g. https://helidon.io/guides

**Comment by romain-grecourt** [comment]
https://helidon.io/guides
https://helidon.io/docs
https://helidon.io/javadocs
