### ISSUE TITLE
[Doc:] Helidon SE Health Checks documentation 

### ISSUE THREAD

**Issue by dalexandrov** [oracle/helidon#4305]
Helidon SE Health Checks documentation (according to the new documentation structure).

Path: `/HelidonSE/Observability/Health`

- [x] Overview (may be reused from current doc)
- [x] Maven Dependency (may be reused from current doc)
- [ ] Usage (may be reused from current doc and guide)
- [x] API (may be reused from current doc)
- [x] Configuration (may be reused from current doc)
- [ ] Reference (generated)
- [x] Examples (may be reused from guide)
- [x] Additional Information

**Comment by spericas** [comment]
PR #4495
