### ISSUE TITLE
[Doc:] Helidon SE Tracing documentation 

### ISSUE THREAD

**Issue by dalexandrov** [oracle/helidon#4307]
Helidon SE Tracing documentation (according to the new documentation structure).

Path: `/HelidonSE/Observability/Tracing`

- [ ] Overview (should be created)
- [ ] Maven Dependency (may be reused from current doc)
- [ ] Usage (may be reused from Tracing Spec doc)
- [ ] API (may be reused from Tracing Spec doc/website)
- [ ] Configuration (may be reused from current doc)
- [ ] Reference (generated)
- [ ] Examples (may be reused from Helidon repo and current doc)
- [ ] Additional Information (should include `Zipkin`, `Jaeger` and `Metric for Jaeger`)

**Comment by tomas-langer** [comment]
Depends on https://github.com/oracle/helidon/pull/4458

**Comment by ljamen** [comment]
Comments left on #4458
