### ISSUE TITLE
[Doc:] Helidon SE Security Providers documentation

### ISSUE THREAD

**Issue by dalexandrov** [oracle/helidon#4308]
Helidon SE Security Providers documentation (according to the new documentation structure).

Path: `/HelidonSE/Security/Providers`

- [ ] Overview (may be reused from current doc)
- [ ] Maven Dependency (may be reused from current doc)
- [ ] Usage (may be reused from current doc)
- [ ] API  (may be reused from current doc)
- [ ] Configuration (should be created)
- [ ] Reference (generated)
- [ ] Examples (may be reused from Helidon repo)
- [ ] Additional Information (may be suspended)

**Comment by ljamen** [comment]
Comments in #4557
