### ISSUE TITLE
[Doc:] Helidon SE Security Integrations 

### ISSUE THREAD

**Issue by dalexandrov** [oracle/helidon#4309]
Helidon SE Security Integrations documentation (according to the new documentation structure).

Path: `/HelidonSE/Security/Integrations`

- [ ] Overview (may be reused from current doc)
- [ ] Maven Dependency (may be reused from current doc)
- [ ] Usage  (may be reused from current doc)
- [ ] API  (may be reused from current doc)
- [ ] Configuration  (may be reused from current doc)
- [ ] Reference (generated)
- [ ] Examples (may be reused from Helidon repo)
- [ ] Additional Information (may be suspended)

**Comment by ljamen** [comment]
Reviews completed for this issue in PR #4687
