### ISSUE TITLE
[Doc:] Helidon SE Validation documentation

### ISSUE THREAD

**Issue by dalexandrov** [oracle/helidon#4311]
Helidon SE Validation documentation (according to the new documentation structure).

Path: `/HelidonSE/Enterprise/Validation`

Should cover General Bean Validation and Jersey validation 

- [ ] Overview (should be created)
- [ ] Maven Dependency (may be reused from current doc)
- [ ] Usage (should be created)
- [ ] API (should be created using Bean Validation documentation)
- [ ] Configuration (should be created)
- [ ] Reference (should be created)
- [ ] Examples (may be reused from Helidon repo)
- [ ] Additional Information (if applicable)

**Comment by m0mus** [comment]
Beam Validation is not supported in Helidon SE
