### ISSUE TITLE
[Doc:] Helidon SE OpenAPI documentation

### ISSUE THREAD

**Issue by dalexandrov** [oracle/helidon#4314]
Helidon SE OpenAPI documentation (according to the new documentation structure).

Path: `/HelidonSE/Calling Other Services`

- [x] Overview (general description should be created)
- [x] Maven Dependency (may be reused from current doc)
- [x] Usage (may be reused from current doc)
- [x] API (should be created)
- [x] Configuration (may be extended from the current docs)
- [x] Reference (generated)
- [x] Examples (reference to `Greeting` application can be used)
- [x] Additional Information (`OpenAPI-Generator` reference and usage may be included here)

**Comment by ljamen** [comment]
Comments on 4558
