### ISSUE TITLE
[Doc:] Helidon SE gRPC documentation

### ISSUE THREAD

**Issue by dalexandrov** [oracle/helidon#4316]
Helidon SE gRPC documentation (according to the new documentation structure).

Path: `/HelidonSE/Protocols`

Open question if the chapter should be separated to client and server

- [ ] Overview (May be reused from the current doc)
- [ ] Maven Dependency (may be reused from current doc)
- [ ] Usage (may be reused from the current docs)
- [ ] API (should be created)
- [ ] Configuration (may be extended from the current docs)
- [ ] Reference (generated)
- [ ] Examples (one for server and one for client)
- [ ] Additional Information (if applicable)

**Comment by edbratt** [comment]
Please be sure to remove the "Experimental" warning block in the Docs. before v3 ships.

**Comment by klustria** [comment]
Initial merge completed in: https://github.com/oracle/helidon/pull/4569

**Comment by klustria** [comment]
This issue is resolved in both PRs:  https://github.com/oracle/helidon/pull/4569 and https://github.com/oracle/helidon/pull/4606

**Comment by ljamen** [comment]
Doc reviews conducted on 4569 and 4606. Edits have been made and this issue can now be closed.
