### ISSUE TITLE
[Doc:] Helidon SE GraphQL documentation

### ISSUE THREAD

**Issue by dalexandrov** [oracle/helidon#4317]
Helidon SE GraphQL documentation (according to the new documentation structure).

Path: `/HelidonSE/Protocols`

- [x] Overview (Should be extended from the current doc)
- [x] Maven Dependency (may be reused from current doc)
- [ ] Usage (may be reused from the current docs)
- [x] API (should be created)
- [x] Configuration (may be extended from the current docs)
- [x] Reference (generated)
- [x] Examples (may be reused from the current docs)
- [x] Additional Information (if applicable)

**Comment by spericas** [comment]
PR #4478
