### ISSUE TITLE
[Doc:] Helidon MP Server documentation

### ISSUE THREAD

**Issue by dalexandrov** [oracle/helidon#4320]
Helidon MP Server documentation (according to the new documentation structure).

Path: `/HelidonMP/Server`

- [ ] Overview (may be reused from current doc)
- [ ] Maven Dependency (may be reused from current doc)
- [ ] Usage (may be reused from current doc and guide)
- [ ] API (may be reused from current doc)
- [ ] Configuration (may be reused from current doc)
- [ ] Reference (generated)
- [ ] Examples (may be reused from guide)
- [ ] Additional Information

**Comment by ljamen** [comment]
Comments on #4545
