### ISSUE TITLE
[Doc:] Helidon MP CDI documentation

### ISSUE THREAD

**Issue by dalexandrov** [oracle/helidon#4322]
Helidon MP CDI documentation (according to the new documentation structure).

Path: `/HelidonMP/CDI`

May include `Extensions` subchaper.

- [x] Overview (may be reused from current doc)
- [x] Maven Dependency (may be reused from current doc)
- [x] Usage (may be reused from current doc and guide)
- [x] API (may be reused from current doc)
- [x] Configuration (may be reused from current doc)
- [x] Reference (generated)
- [x] Examples (may be reused from guide)
- [x] Additional Information

**Comment by m0mus** [comment]
Reopening for language review
