### ISSUE TITLE
Use the metadata in documentation

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon#4326]
Once we have done #4325 , we want to use that info to generate documentation for various configuration option supported by Helidon and add that as part of our public docs.

**Comment by arjav-desai** [comment]
Rather than doing this as one big task/Pr, we have decided to tackle this as we are updating documentation for Helidon (see issues here https://github.com/oracle/helidon/projects/22).

The process for this is outlined at https://github.com/oracle/helidon/wiki/Generated-config-documentation.
