### ISSUE TITLE
Deprecations: Common

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#4363]
Classes:
- Resource - old configuration approach (since 2.0)
- ThreadPoolSupplier - Named thread pools (since 2.4.2)

Tasks:
- [x] remove the deprecated code
- [x] make sure the deprecation is correctly documented in 2.x (since, forRemoval on @Deprecated annotation, use @deprecated javadoc tag to link to the correct new implementation, or describe what to do if a simple replacement does not exist)
- [x] validate documentation and examples are correct with regard to the deprecated element

**Comment by spericas** [comment]
PR #4405
