### ISSUE TITLE
Deprecations: Common Context

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#4366]
- DataPropagationProvider - clearData should use new method (no info)

Tasks:
- [x] remove the deprecated code
- [x] make sure the deprecation is correctly documented in 2.x (since, forRemoval on @Deprecated annotation, use @deprecated javadoc tag to link to the correct new implementation, or describe what to do if a simple replacement does not exist)
- [x] validate documentation and examples are correct with regard to the deprecated element

**Comment by spericas** [comment]
PR #4388
PR #4389
