### ISSUE TITLE
Deprecations: GRPC core

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#4367]
JavaMarshaller

Uses java serialization
Used in examples (requires code changes)
Since 2.3.0

Tasks:
- [x] remove the deprecated code
- [x] make sure the deprecation is correctly documented in 2.x (since, forRemoval on @Deprecated annotation, use @deprecated javadoc tag to link to the correct new implementation, or describe what to do if a simple replacement does not exist)
- [x] validate documentation and examples are correct with regard to the deprecated element

**Comment by klustria** [comment]
Updated doc to remove any mention of java marshaller in GRPC via https://github.com/oracle/helidon/pull/4441

**Comment by klustria** [comment]
Closing issue since are tasks required for this issue are fulfilled
