### ISSUE TITLE
Static content 301 error for index.html

### ISSUE THREAD

**Issue by harrison-nc** [oracle/helidon#4402]
Hi everyone, helidon server returns `301` error when a request is sent to the context root.

## Environment Details
* Helidon Version: 2.5.1
* Helidon MP
* JDK version: 18
* OS: WSL

----------

## Problem Description
If a static classpath context is configured: `server.static.classpath.content=/static`
A request to the context root (on a local machine): `http://localhost:8080/static` returns `301` (this should server `index.html` if present in the root)

While, the following: `http://localhost:8080/static/` (👈 _note the trailing `/`_) correctly serves any `index.html` file in the context root.

Explicit request for the index file also succeeds: `http://localhost:8080/static/index.html`

## Steps to reproduce
To reproduce, create a helidon MP project using the cli choosing:

- flavor: bare
- version: current

create `index.html` file in `src/main/resources/META-INF/web`
set `server.static.classpath.location=/META-INF/web`, and
set `server.static.classpath.context=/static`

using `curl` execute `curl -v http://localhost:8080/static`

_actual behavior_ returns `301`
_expected behavior_ server `index.html`
```

**Comment by romain-grecourt** [comment]
This is by design. You can make curl follow the redirect by using `-L`:

```
curl -vv -L http://localhost:8080/static
```
