### ISSUE TITLE
Bug: ConfigProperty annotation on Map<String, String> field doesn't filter the configuration values, but populates all configuration entries in Map

### ISSUE THREAD

**Issue by bvkrish83** [oracle/helidon#4414]
For a map configuration field like below, i expect the map to be populated with all configuration entries under configKey section, but the map is populated with all possible configuration entries - without any filtering.

```java
    @Inject
    @ConfigProperty(name = "configKey")
    Map<String, String> configKeyMap;
```

Is this behaviour expected??? Is there a provision to filter out the configuration entries that just match to the name mentioned in the annotation?

If i understand correctly, filtration happens properly for List and Set field types (at-least as per the code for those branches). Why the behaviour is different for Map alone???

## Environment Details
* Helidon Version: 2.5.1
* Helidon MP
* JDK version: JDK 17
* OS: Windows 11
* Docker version (if applicable): NA

**Comment by tomas-langer** [comment]
MIcroProfile Config does not specify injection of `java.util.Map`. We do injection into a map, but you will always get the full Map of known key/value pairs.

**Comment by tomas-langer** [comment]
As Helidon, we have these options:
1. keep the current behavior and mark this "works as designed" - this creates an unusual behavior, where config property key is fully ignored (not according to spec, future spec changes may create backward incompatible behavior)
2. modify the injection to honor the specified key and filter values (not according to spec, future spec changes may create backward incompatible behavior)
3. remove support for injection of `java.util.Map` and wait for what the specification does

Both 1. and 2. suffer from possible performance impact and also from the case that not all sources can provide full set of their properties (so the map may not be complete).

**Comment by tomas-langer** [comment]
As this is not tested, we did not catch the difference in behavior. This was quite a big change (we had to switch away from using Helidon SE Config to using a full implementation of MP Config due to differences in handling environment variables), I have missed it when implementing it.
We will get back to this and restore the original behavior

**Comment by tomas-langer** [comment]
In the PR:
- injection of map with a name defined in `@ConfigProperty` will inject only properties prefixed by that key, with the key removed from keys of the map
- injection of map with default name will inject all properties available in config
- I have added a test to verify this behavior
