### ISSUE TITLE
MP should read logging.properties by default

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#443]
## Environment Details
* Helidon Version: 1.0.0
* Helidon MP
* JDK version: 9.0.4
* OS: n/a
* Docker version (if applicable): n/a

----------

## Problem Description
MP reads default configuration from predefined places, by spec.

It would be convenient for our MP implementation to read logging settings from `logging.properties` by default. 

The user can specify `-Djava.util.logging.config.file` on the `java` command line and that would remain an option, but having Helidon MP follow the convention of looking on the class path for `logging.properties` would be helpful.

**Comment by tomas-langer** [comment]
I have looked into this problem and it is not that easy to solve.
We can make this work easily when MP Server is start the "implicit" way - e.g. the MP Main class is invoked as the entry point. In this case, we can easily read the default logging properties and use them.
In case we are started "explicitly" - e.g. some custom Main class is started that configures MP Server, we have a problem - when I use logging before the MP library is used, I can change the logging levels from the `mp-logging.properties`, but it would not change appenders and log formatting.
As log formatting is probably the most important part after levels, the result is not very useful.
This will require further investigation.

**Comment by tjquinno** [comment]
At least from my point of view, the "implicit" case is the most valuable to automatically use `logging.properties` (if the file is there).

A developer who writes an app-specific main class would likely expect to set up logging explicitly also. One who uses our built-in Main would get the most benefit from this enhancement.

**Comment by tomas-langer** [comment]
The PR modified the code of our Main class as follows:

- If the system property for Java logging is defined, let it be used
- If there is a file `logging.properties` in the current directory, configure logging using it
- If there is a file `logging.properites` on the classpath, configure logging using it
