### ISSUE TITLE
3.0 dependency upgrades

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#4481]
Dependency upgrades for 3.0:

- [x] JSONP-API 2.0.1 #4412
- [x] Jersey 3.0.5 #4412
- [x] Parsson 1.0.2 #4412
- [x] Micronaut 3.4.3 #4476
- [x] Tyrus 2.0.3 #4496 
- [x] Hibernate 6.1.1.Final #4484
- [x] Jandex to 2.4.3.Final #4487
- [x] OpenTelemetry artifacts for #4518
- [x] HikariCP 5.0.1 #4519

**Comment by ljnelson** [comment]
(I ticked the checkbox for the Hibernate upgrade since the PR went in. Feel free to untick it if you're using the checkboxes to track your own work.)
