### ISSUE TITLE
helidon-examples-grpc-common doesn't build on an Apple silicon Mac

### ISSUE THREAD

**Issue by ljnelson** [oracle/helidon#4482]
The `protoc.exe` artifact that is requested by the `org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.1:compile` goal does not exist, because the introspected architecture results in a non-existent Maven artifact:
```
[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.1:compile (default) on project helidon-examples-grpc-common: Missing:
[ERROR] ----------
[ERROR] 1) com.google.protobuf:protoc:exe:osx-aarch_64:3.5.1-1
```

As you can see it does not exist: https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.5.1-1/

**Comment by tomas-langer** [comment]
Fixed by #4662
