### ISSUE TITLE
About Menu Docs

### ISSUE THREAD

**Issue by edbratt** [oracle/helidon#4485]
Repurposing for v3 About Menu tasks:

- [ ] Upgrade from 1.4 -- Revise text of sub-menu "Upgrade". Recommend, "Upgrade to version 3" or "Upgrading your Helidon Application"
- [ ] About Helidon -- Reminder, we need 'what's new' for Helidon 3. Also, I'd recommend the text be reorganized. Put Understanding Helidon Frameworks ahead of Cloud Native Tools.
- [ ] Add a ToC
- [ ] Add an introduction block.

**Comment by m0mus** [comment]
Related to https://github.com/oracle/helidon/issues/4526

**Comment by m0mus** [comment]
About menu has been refactored as part of #4526. Closing this issue as not relevant.
