### ISSUE TITLE
Why not add a library for JSON transformation?  Like Jackson ,fastjson ,Gson

### ISSUE THREAD

**Issue by ResidualSuspense** [oracle/helidon#45]
If I want to send json，I need to use  "javax.json.JsonObject"  !!!,We usually don't take this approach。As for me,I often use some librarys like Jackson,fastjson,Because we usually take a java bean convert to a json string !!!

**Comment by romain-grecourt** [comment]
We currently only support JSONP (aka JSON Parsing API) in Helidon SE.
Support for a JSON Binding framework is a new feature.

If you want to implement this yourself, you can start with this file: https://github.com/oracle/helidon/blob/master/webserver/json/src/main/java/io/helidon/webserver/json/JsonSupport.java

I did a few experiments, see this gist: https://gist.github.com/romain-grecourt/d2b04178140f7eab3b69f8ea2481fc10

**Comment by ResidualSuspense** [comment]
> We currently only support JSONP (aka JSON Parsing API) in Helidon SE.
> Support for a JSON Binding framework is a new feature.
> 
> If you want to implement this yourself, you can start with this file: https://github.com/oracle/helidon/blob/master/webserver/json/src/main/java/io/helidon/webserver/json/JsonSupport.java
> 
> I did a few experiments, see this gist: https://gist.github.com/romain-grecourt/d2b04178140f7eab3b69f8ea2481fc10

Thanks,I ‘m very much looking forward to it !!!

**Comment by mwiede** [comment]
Maybe I misunderstand the question. But if you take the quickstart-mp example, you can add something like this:

```java
@Path("/dogs")
@ApplicationScoped
public class DogResource {

  @GET
  @Produces(MediaType.APPLICATION_JSON)
  public Set<Dog> dogs() {
    final Dog dog1 = new Dog();
    dog1.name = "Falco";
    dog1.age = 4;
    dog1.bitable = false;
    final Dog dog2 = new Dog();
    dog2.name = "Wastl";
    dog2.age = 2;
    dog2.bitable = true;
    return Stream.of(dog1, dog2).collect(Collectors.toSet());
  }

  @POST
  @Consumes(MediaType.APPLICATION_JSON)
  public Response bite(final Dog dog) {
    return Response.ok().build();
  }

}
```

```
$ curl 'http://localhost:8080/dogs' -H 'Content-Type: application/json' -H 'Accept: *'  -d '{"age": 4,"bitable": false,"name": "Falco"}'
$ curl 'http://localhost:8080/dogs' 
[{"age":4,"bitable":false,"name":"Falco"},{"age":2,"bitable":true,"name":"Wastl"}]
```

So from my point of view, there is no need to add more binding libraries.

**Comment by romain-grecourt** [comment]
This is about support in the webserver directly. I.e this is for helidon-se, not helidon-mp.
In the case of helidon-mp, jsonb is can be used as-is inside a jaxrs resource.

**Comment by forseti** [comment]
Hi there,

I have read thru the document.
Is there any elegant way we can do the object transformation using helidon-se? Perhaps using helper or sth?

Thanks!!

**Comment by gcameo** [comment]
I have a use case where the json I receive has a uses a complex key as a key in a map. We need the ability to register a deserialiser for it

**Comment by romain-grecourt** [comment]
@gcameo This is something you can do today by registering your own `Reader` in the request.
See how the JsonSupport is implemented:  https://github.com/oracle/helidon/blob/6ddb6c479bf61d8d857e2304b31a5ce79666fe57/webserver/json/src/main/java/io/helidon/webserver/json/JsonSupport.java#L148

**Comment by ljnelson** [comment]
With #351 and #387 now implemented, this issue is resolved.
