### ISSUE TITLE
Update microprofile docs

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon#450]
Update the Microprofile docs.

- Describe Helidon MP and Microprofile in an overview page
- Use cards to display the sub pages nicely
- Describe the currently supported version of the Microprofile specs with description for each spec and links to the spec documents and perhaps official Javadocs.
- Add Helidon specific docs for each specification for relevant code snippet and basic usage / example
- Dissociate the portable / microprofile compliant from the Helidon specifics
- Clarify the config usages and config sources (e.g. microprofile-config.props VS application.yaml)

Some notes:
- Document CDI with basic usages and example
- Document JAXRS with basic usages and example (document that we use Jersey as the implementation and explain / show how to use the jersey specific stuff)

**Comment by romain-grecourt** [comment]
Exact APIs for Microprofile 1.2:

 - JAXRS 2.0
 - CDI 1.2
 - JSONP 1.0
 - Common annotation 1.2
 - Microprofile config 1.1
 - Microprofile fault tolerance 1.0
 - Microprofile health check 1.0
 - Microprofile metrics 1.0
 - Microprofile JWT authentication 1.0

**Comment by delabassee** [comment]
In addition, it would be useful to have this info in a matrix somewhere
- Specific Helidon release
- Which MP API (+version) does that Helidon MP version support?
- Which ones (ex. JAX-RS) are also supported on SE? (with some potential caveats)

**Comment by romain-grecourt** [comment]
@barchetta created this page, see https://github.com/oracle/helidon/wiki/Supported-APIs

**Comment by emecas** [comment]
Regarding to the subject

> Microprofile JWT authentication 1.0

[this]( https://github.com/akofoed/helidon-auth-test) is from @akofoed about demonstrating the use of two different auth mechanisms,  he is using SE, but could be a good star point for setting something for MP:
