### ISSUE TITLE
Doc - add links in Intro page

### ISSUE THREAD

**Issue by delabassee** [oracle/helidon#451]
I find the https://helidon.io/docs/latest/#/about/01_introduction page a bit unintuitive as the 1st link that one could click on this page is a MP link at the bottom of the page (modulo the dropdown menu links that you don't notice at 5am ;-) ).

IMHO, it would makes sense to have the 3 core components blocks (WebServer, Config, Security) linked to their respective docs.

**Comment by romain-grecourt** [comment]
This will be fixed in the latest version, there is an overview page and the introduction page has been re-written. See an example here: https://romain-grecourt.github.io/junkyard/health/

**Comment by romain-grecourt** [comment]
Re-open if you think we should do more updates.
