### ISSUE TITLE
Config property names inconsistencies

### ISSUE THREAD

**Issue by spericas** [oracle/helidon#453]
Config issue. The docs point to,

https://helidon.io/docs/latest/apidocs/index.html?io/helidon/webserver/ServerConfiguration.html

In order to override `workersCount`, the property `workers` is expected as shown here from the Helidon code:

           config.get("workers").asInt().ifPresent(this::workersCount);

There may be a few others like this one.

**Comment by barchetta** [comment]
I've taken a look at `ServerConfiguration`, and here are the inconsistencies I see:

|  Property                  | Method                |
| ------------------- |:-----------------|
| workers                    |workersCount      |
| receive-buffer         |receiveBufferSize|
| timeout                    |timeoutMillis         |  

I think the first two we should address by changing the property to match the method (`workers-count` and `receive-buffer-size`). I'm thinking we can leave the third (`timeout`) but don't feel strongly about that.

For backwards compatibility we should support both old and new property, with the new form taking precedence if there happens to be both. For example:
```
            config.get("workers").asInt().ifPresent(this::workersCount);
            config.get("workers-count").asInt().ifPresent(this::workersCount);
```

**Comment by spericas** [comment]
I'd prefer renaming properties over adding new redundant methods. Perhaps we should do that in all cases for consistency. We should also make sure we don't refer to the old properties in our docs.

**Comment by tomas-langer** [comment]
I will add a deprecated config function to be able to process both the new & deprecated key in the same call, also printing an info message.

Example:
```java
DeprecatedConfig.get(config, "worker-count", "workers")
                    .asInt()
                    .ifPresent(this::workersCount);
```
