### ISSUE TITLE
server.timeout property is not working in helidon 2.5.0

### ISSUE THREAD

**Issue by dv333** [oracle/helidon#4549]
##
server.timeout property is not working in helidon 2.5.0

## Environment Details
* Helidon Version: 2.5.0
* Helidon SE or Helidon MP : Helidon MP 
* JDK version: 17
* OS: Mac Arm
* Docker version (if applicable): NA

----------

## Problem Description
As per the documentation https://helidon.io/docs/v2/#/mp/jaxrs/02_server-configuration , I set the server timeout property but it is not having any impact on the timeout

## Steps to reproduce
[//]: # Create a helidon MP quickstart application, set the server.timeout=300 and add the below code to the private JsonObject createResponse(String who)  method 
 
private JsonObject createResponse(String who) {
        String msg = String.format("%s %s!", greetingProvider.getMessage(), who);

        try{
            Thread.sleep(10*1000);

        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        return JSON.createObjectBuilder()
                .add("message", msg)
                .build();
    }

Invoke the greet endpoint and can see that the timeout is not happening. 
[//]: # "Provide sample code/application if relevant"

**Comment by spericas** [comment]
This issue is invalid, `server.timeout` is not supposed to work this way. Please see documentation for `SO_TIMEOUT` in Netty.

**Comment by barchetta** [comment]
Looks like the submitter was expecting `server.timeout` to provide similar functionality to Apache's Core Timeout:  https://httpd.apache.org/docs/2.2/mod/core.html#timeout
