### ISSUE TITLE
Clarify MP security spec and update Helidon impl

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#455]
## Environment Details
* Helidon Version: 1.0.0
* Helidon MP
* JDK version: 9.0.4
* OS: n/a
* Docker version (if applicable): n/a

----------
There are ambiguities in the MP JWT-Auth spec. Tim discovered that the code generated by the MP starter works with other impls but Helidon MP rejects attempts to access the endpoints.

Specifically, with the application annotated with `@LoginConfig(authMethod = "MP-JWT")` Helidon MP reject access to endpoints that are _not_ annotated with `@RolesAllowed` and no suitable JWT in the request header, essentially acting as if each endpoint is annotated with `@DenyAll`.

In contrast, other MP impls permit such access, acting as if each endpoint is annotated with `@PermitAll`.

The spec does not state clearly what the behavior should be in this case.

@tomas-langer is going to pursue this on the MP mailing list.

**Comment by tomas-langer** [comment]
See https://github.com/eclipse/microprofile-jwt-auth/issues/124
