### ISSUE TITLE
security.provider-policy COMPOSITE will not authenticate against below first Authentication provider

### ISSUE THREAD

**Issue by s92025592025** [oracle/helidon#4559]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 2.5.0
* Helidon MP 
* JDK version: 17.0.1
* OS: MacOS Monterey 12.1
* Docker version (if applicable):

----------

## Problem Description
When using composite security.provider-policy, only the first authentication provide will be used

## Steps to reproduce
Please use the following zip
[helidon-quickstart-mp.zip](https://github.com/oracle/helidon/files/9124502/helidon-quickstart-mp.zip)

1. Set environment variable `SERVER_EXTERNAL_MP_CONFIG` to point to  the `mp-config.yaml` in the zip file(absolute path recommended)
2. run the `helidon-quickstart-mp.jar` in the `target` folder in the zip file
3. Go to `http://localhost:8000/greet`on a browser, it should prompt you to enter a username and password
4. Enter the user name password for `authenticator-2` in the `mp-config.yaml`
5. See Authentication failed and ask you for the username password again
6. Enter the user name password for `authenticator-1` in the `mp-config.yaml`
7. See `{"message":"Hello World!"}` on your browser

I am using 2 `http-basic-auth` provider to reproduce this issue in a simpler way, but in reality, mixing for example `http-basic-auth` and `oidc` provider can see the same behavior as well.

**Comment by tomas-langer** [comment]
The flags work as follows:
`SUFFICIENT`
    - if an authentication provider returns success, finish authentication
    - if an authentication provider returns abstain, continue to next
    - if an authentication provider returns failure, finish authentication and fail

Because the first provider cannot authenticate `daniel1`, it returns failure and hence the chain fails.
This can be simply fixed by making the provider optional - optional provider returns abstain instead of failure in case of failure.

The following configuration will work as expected (keep everything else as is):
```yaml
  providers:
    - name: "authenticator-1"
      http-basic-auth:
        optional: true
```

**Comment by tomas-langer** [comment]
Closing as this works as deisgned and I have provided a response that resolves the question and the application works as expected after the fix (tried on reproducer)
