### ISSUE TITLE
Query parameter in tyrus websocket.

### ISSUE THREAD

**Issue by vicky281999** [oracle/helidon#4575]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version:
* Helidon SE
* JDK version: 11
* OS: macOS Bigsur

----------

## Problem Description
In helidon Tyrus WebSocket connection I can send the data as path param but not as query param is there a way to send the data as query param?
Is there any API to get the query param? 
Inside modify Handshake request.getQueryString() is returning null, request.getParameterMap() this api contains only path param

## Steps to reproduce
Register the wss connection in the helidon webserver server router 
```
.register("/websocket",
    TyrusSupport.builder().register(
          ServerEndpointConfig.Builder.create(WssEndpoint.class, "/{token}")
                  .configurator(new WssEndpoint.WSSEndpointConfigurator())
                  .build())
           .build())
```
WSSEndpointConfigurator class extends ServerEndpointConfig.Configurator inside this class override modifyHandshake method, inside that method we have the access to the server "request" from there I have to access the query parameter

**Comment by spericas** [comment]
This looks like a bug in the integration code with Tyrus, where query params are being dropped by accident.

**Comment by AshwinPrabhuB** [comment]
Is it correct to assume that post the fix, TyrusSession.getRequestParameterMap API would also be carrying the same query params for reference within Endpoint.onOpen post successful handshake response?

**Comment by spericas** [comment]
> Is it correct to assume that post the fix, TyrusSession.getRequestParameterMap API would also be carrying the same query params for reference within Endpoint.onOpen post successful handshake response?

 Yes, I think so. Should have a PR for this later today.

**Comment by spericas** [comment]
PR #4624
