### ISSUE TITLE
RestClient not deserializing JSON Collections

### ISSUE THREAD

**Issue by Ordiel** [oracle/helidon#4613]
## Environment Details
* Helidon Version: 2.5.1
* Helidon MP
* JDK version: 11
* OS: Linux

## Description
When using a RestClient to retrieve objects containing a list, with something similar as the following API:

```java
	@GET
	@Path("/User")
	@Produces(MediaType.APPLICATION_JSON)
	UsersPage getUsers();
```

 the objects within the list are not getting deserialized. Lets say the REST endpoint call returns the following JSON data:

```json
{
   "pageSize" : 2,
   "currentPage" : 1,
   "totalPages" : 1
   "users": [
      {
         "name": "user 1",
         "id": 1
      },
      {
         "name": "user 2",
         "id": 2
      }
   ]
}
```
When being mapped to the following class:
```java
class UsersPage {
    public int pageSize, currentPage, totalPages;
    public List<User> users;
}
```
for which `User` is the following class: 

```java
class User {
    public String name;
    public int id;
}
```

the inistance of `UserPage` is correctly deserialized except for the contents of `users`, which returns null  instead of the expected 2 `User`s within it. 

What am I missing to correctly deserialize the generics contents of collections in this case a `List<User>`

Greetings and thanks in advance

**Comment by romain-grecourt** [comment]
Which jersey media provider are you using ?

E.g.

```xml
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-binding</artifactId>
    <scope>runtime</scope>
</dependency>
```

If you are not declaring one explicitly and you are using this means you are using json-b:
```xml
<dependency>
    <groupId>io.helidon.microprofile.bundles</groupId>
    <artifactId>helidon-microprofile</artifactId>
</dependency>
```

**Comment by Ordiel** [comment]
The one I have is:

```xml
<dependency>
	<groupId>io.helidon.media</groupId>
	<artifactId>helidon-media-jackson</artifactId>
	<version>2.5.1</version>
</dependency>
```
After changing it to the suggested (version added):

```xml
<dependency>
			<groupId>org.glassfish.jersey.media</groupId>
			<artifactId>jersey-media-json-binding</artifactId>
			<version>2.36</version>
			<scope>runtime</scope>
		</dependency>
```

I am still getting the collection within the response as null

**Comment by romain-grecourt** [comment]
`helidon-media-jackson` is only for Helidon SE ; you can remove it.

I'm unable to reproduce, see the changes I tried on top of `quickstart-mp` below.
Can you provide a simpler reproducer ?

```java
public class User {
    public String name;
    public int id;
}

public class UsersPage {
    public int pageSize, currentPage, totalPages;
    public List<User> users;
}

public interface UsersPageClient {

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    UsersPage getUsers();

    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    void setUsers(UsersPage usersPage);
}

@ApplicationScoped
public class UsersPageRef {
    private final AtomicReference<UsersPage> ref = new AtomicReference<>();

    UsersPage getUsersPage() {
        return ref.get();
    }

    void setUsersPage(UsersPage usersPage) {
        this.ref.set(usersPage);
    }
}

@Path("/users-page")
public class UsersPageResource {

    @Inject
    private UsersPageRef repo;

    @Inject
    private UsersPageClient client;

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public UsersPage getUsers() {
        return repo.getUsersPage();
    }

    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    public void setUsers(UsersPage usersPage) {
        repo.setUsersPage(usersPage);
    }

    @POST
    @Path("go")
    public UsersPage test(UsersPage usersPage) {
        client.setUsers(usersPage);
        return client.getUsers();
    }
}
```


```bash
curl -vvv  -X POST -H "Content-Type: application/json" -d '{ "pageSize" : 2, "currentPage" : 1, "totalPages" : 1, "users": [ { "name": "user 1", "id": 1 }, { "name": "user 2", "id": 2 } ] }' http://localhost:8080/users-page/go
```

**Comment by Ordiel** [comment]
I've been trying to reproduce it yet I am seeing the expected behavior work as a charm on a simplified version, which is weird since the project I a working on started just a few weeks back so I don't have too many changes from the quickstart archetype, I've copied all the contents of my pom to the new project I created to reproduce it and it still works. I will continue highlighting the differences to see if I can find the culprit and post it here for posterity

**Comment by Ordiel** [comment]
Issue was my response not being mapped as is given the key in the JSON data not following the expected naming ([Naming Strategy](https://javaee.github.io/jsonb-spec/docs/user-guide.html#naming-strategies)'s) as the rest of the JSON, requiring me to add a `@JsonbProperty` to that particular attribute so that it get mapped correctly
