### ISSUE TITLE
Pipeline updates - java 11 and other

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#462]
- [x] change build to run on JDK11 instead of JDK9
- [ ] add support for a module using a different java version (unless very simple) -e.g. to use Java 11 HTTP client
- [ ] add support to run a set of tests using JDK8 (to make sure we do not use Java9+ specific APIs)
- [ ] add support to run a set of tests using JDK11, utilizing module system (to make sure our services are correctly defined and that we have all dependencies correctly done in module-info.java)

**Comment by tomas-langer** [comment]
Build fails when using java11 on:

- spotbugs
- javadocs

**Comment by barchetta** [comment]
Pipeline is now running using Java 11. See PR #810
