### ISSUE TITLE
Are MessageBodyReaders supposed to cascade?

### ISSUE THREAD

**Issue by Ordiel** [oracle/helidon#4633]
## Environment Details
* Helidon Version: 2.5.1
* Helidon MP
* JDK version: 11
* OS: Ubuntu

----------

## Problem Description

I have a situation where I am using a `RestClient` to read data from another system, I need to parse a value on their JSON response to an enum, yet the names they use do not match the casing of my enum definitions causing the Enum.valueOf (which is the method being used for deserialization on JSONB as defined on the [section 3.9 of the spec](https://download.oracle.com/otn-pub/jcp/json_b-1-final-eval-spec/jsonb_spec_1.0.pdf?AuthParam=1659026740_57cd57e5fdeab378aaa3ffd5cd6878fb)) not finding them. In order to address this I would like to implement/register a [MessageBodyReader](https://download.eclipse.org/microprofile/microprofile-rest-client-1.2.1/microprofile-rest-client-1.2.1.html#_messagebodyreader) on my `RestClient` to take care of the deserialization of such enum, yet the defined MessageBodyReader is not getting invoked if such enum instance is wrapped on another class.

**Expected behavior:** 
I would expect that by registering a `MessageBodyReader` on my `RestClient` it would deserialize any instance for which that `MessageBodyReader` is defined wherever it is found when deserializing a response (note: I haven't been able to find on any specification if this is the actual behavior they should have) 

**Current behavior:**
`MessageBodyReader`s are not getting invoked unless the entire body is of the type for which they are defined 

I created a small project to reproduce this:

[MessageBodyReaderNotCascading.zip](https://github.com/oracle/helidon/files/9212749/MessageBodyReaderNotCascading.zip)

When starting the project (using `io.helidon.microprofile.cdi.Main`) if we visit http://localhost:8080/enum/AnEnum we can see the "source" from which I a getting my desired payload to transform into an enum, which is being served by `src/main/java/io/helidon/examples/quickstart/mp/provider/AnEnumResource.java`. The payload is:

```json
{
	"anEnum": "a"
}
``` 
Where `a` is supposed to match my definition of `AnEnum` (located at `src/main/java/io/helidon/examples/quickstart/mp/receiver/AnEnum.java`) which has 3 possible values A, B and, C, I'm expecting such JSON to deserialize to an instance of AnEnum#A, yet notice the payload is lower case and the enum definitions are upper case (following java's naming conventions).

By visiting http://localhost:8080/remote/enum/ we can invoke the logic on which I a using a `RestClient` to consume such payload, where I a expecting to be able to read such wrapped enum payload, such being served by `src/main/java/io/helidon/examples/quickstart/mp/receiver/RemoteResource.java`; as you can see on that class LOC#24 (`.register(new AnEnum.Reader())`) I am registering the reader (found as an inner class withing the enum definition) when building my `RestClient`, yet this is throwing the following [stackTrace](https://github.com/oracle/helidon/files/9212843/stackTrace.txt), stating `No enum constant io.helidon.examples.quickstart.mp.receiver.AnEnum.a`

I have added break points when debugging such application (at AnEnum#34) and I can confirm my `MessageBodyReader` is not getting called when deserializing.

When I continue experimenting I noticed that if I change the `RestClient` API  (defined at `src/main/java/io/helidon/examples/quickstart/mp/receiver/AnEnumAPI.java`) from returning `EnumResponse` (defined at `src/main/java/io/helidon/examples/quickstart/mp/receiver/EnumResponse.java`, which is the class containing the enum) to return `AnEnum` directly (which introduces the need to change RemoteResource#29 from `return client.getEnum().getAnEnum();` to `return client.getEnum();`) I can see the error changing to: `No enum constant io.helidon.examples.quickstart.mp.receiver.AnEnum.{"ANENUM":"A"}` and I also can reach the previously mentioned break point on my MessageBodyReader, AnEnum#34, which is applying the desired to upper case transformation on the payload (hence `{"ANENUM":"A"}` on the error) 

Is there anything I am doing wrong? Or is is simply that my expectation of how the MessageBodyReader's are supposed to work (by cascading at any level of the received payload) wrong? If so, is there a recommended way on which I could achieved the desired behavior without having to implement a whole `MessageBodyReader` for the entire payload?

**Comment by spericas** [comment]
@Ordiel MessageBodyReader's cannot be nested like that. You're trying to use a sledgehammer to crack a nut. You need to tweak your JSON serialization logic instead; in this case, you should consider using a `JsonbAdapter<A,B>` --there's a lot of documentation about how to do this online.

**Comment by spericas** [comment]
Closing as this is a not an issue.
