### ISSUE TITLE
Redundant _pkg_ folder with mustache files generated in CLI and Starter

### ISSUE THREAD

**Issue by dalexandrov** [oracle/helidon#4645]
In starter or in CLI generate random `Custom` project.
A redundant `__pkg__` folder is generated with some moustache files.

![image](https://user-images.githubusercontent.com/2016949/181747453-329afeba-ee77-4126-91df-122334b21e95.png)
.

**Comment by romain-grecourt** [comment]
Can you describe the steps to reproduce ? Or maybe paste a link to the starter that produces this project ?

**Comment by aserkes** [comment]
If you run this command with or without any additional parameters you will receive `__pkg__` folder in the generated project : 
`helidon init --batch -Dsecurity=true -Dapp-type=custom -Dflavor=mp`

**Comment by romain-grecourt** [comment]
Thanks.
