### ISSUE TITLE
Serving Static Content - Default value not set for config server.static.path.welcome

### ISSUE THREAD

**Issue by binu-r** [oracle/helidon#4654]
## Environment Details
* Helidon Version: 2.5.0
* Helidon MP
* JDK version: 11
* OS: Mac
* Docker version (if applicable):

----------

## Problem Description
As per [Documentation](https://helidon.io/docs/v2/#/mp/jaxrs/04_static-content) for serving static content, default value for config `server.static.path.welcome` is `index.html`

But the default value(`index.html`) is not set and if we are accessing the resource, a not found is thrown `No handler found for path:`

**Note**:  This issue is there only for  File system static content. The default value is set for classpath static content. 

- [Code for file system static content](https://github.com/oracle/helidon/blob/master/microprofile/server/src/main/java/io/helidon/microprofile/server/ServerCdiExtension.java#L291)

- [Code for classpath static content ](https://github.com/oracle/helidon/blob/master/microprofile/server/src/main/java/io/helidon/microprofile/server/ServerCdiExtension.java#L310)

## Steps to reproduce

1. Serve a static content that has index.html as the entry file from the file system without setting the property `server.static.path.welcome`.
2. Access the static content from the browser. (Without index.html) **`No handler found for path:` error will be shown**
4. Set `server.static.path.welcome=index.html`.
5. Restart the server and access the same path (Without index.html) and now we will be able to see the contents.

**Comment by tomas-langer** [comment]
Fixed for both 3.x and 2.x, 4.x change waiting for build, closing issue as the two main branches are fixed and merged
