### ISSUE TITLE
jakarta.enterprise:jakarta.enterprise.cdi-api:4.0.1 seems to break helidon at startup (just a heads-up) :)

### ISSUE THREAD

**Issue by bogedal** [oracle/helidon#4670]
## Environment Details
* Helidon Version: 3.0.0
Helidon MP
* JDK version: 17
* OS: windows
----------

## Problem Description
I created a small example-project and added the example build.gradle to it.
I then added the implementation 'jakarta.enterprise:jakarta.enterprise.cdi-api:4.0.1' dependency.

Build and start the service using java -jar build/libs/example-project.jar

It now fails with 
Exception in thread "main" java.lang.NoClassDefFoundError: jakarta/enterprise/inject/New
at org.jboss.weld.resolution.ResolvableBuilder.addQualifier(ResolvableBuilder.java:156)
...

UPDATE:
This only happens if you don't use enforcedPlatform here:
implementation platform("io.helidon:helidon-dependencies:${project.helidonversion}")

Still I thought you'd like to know :)

Attached the small project example.
[example-project.zip](https://github.com/oracle/helidon/files/9254429/example-project.zip)

**Comment by ljnelson** [comment]
Thanks for the heads up. CDI 4.0 is part of Jakarta EE 10 and we don't support it yet.  Somewhere in the future we will and we'll look at this then.  Thanks for using Helidon.
