### ISSUE TITLE
Jersey client: propagate SecurityContext automatically (in synchronous jersey calls)

### ISSUE THREAD

**Issue by martin-sladecek** [oracle/helidon#471]
When the jersey client is used inside a request scope (i.e. in synchronous REST call to jersey server), the SecurityContext should be automatically propagated to Jersey clients, instead of using ClientSecurityFeature.PROPERTY_CONTEXT property.

**Comment by tomas-langer** [comment]
We should use similar approach as with propagation of Tracing - `AutoDiscoverable` client filter that uses ThreadLocal to propagate the information.

**Comment by tomas-langer** [comment]
depends on #596

**Comment by tomas-langer** [comment]
As we have now the common `Context`, we can manage this even outside of synchronous calls (as long as the calls are executed in executor services wrapped with `Contexts.wrap`).
Also as part of this implementation, we should support the case when `SecurityContext` can be configured application wide - both WebServer and MP Server now have methods to configure the "top-leve" `Context`. If `SecurityContext` is registered in such a `Context`, it would be automatically available for outgoing requests as long as they happen within a scope of the context.
It should also be possible to achieve this using `Contexts.runInContext()`.
The current features (providing `SecurityContext` through JAX-RS property will be kept intact and will override values in `Context`
