### ISSUE TITLE
Docs: 3.0.0 SE and MP Config - invisible TOC

### ISSUE THREAD

**Issue by danielkec** [oracle/helidon#4720]
![image](https://user-images.githubusercontent.com/1773630/184128020-eee9ea18-71db-424e-99f8-d2f86dbefd37.png)

**Comment by danielkec** [comment]
https://helidon.io/docs/v3/#/mp/config/introduction

**Comment by ljamen** [comment]
@danielkec This is being address as part of issue #4673. I think we can close this issue and use the other.
