### ISSUE TITLE
Allow custom DNS resolver in Webclient

### ISSUE THREAD

**Issue by janotav** [oracle/helidon#4744]
## Environment Details
* Helidon Version: 2.5.x
* Helidon SE
* JDK version: Java 11
* OS:
* Docker version (if applicable):

----------

When using Helidon Webclient, there is no way how to override (Netty) default DNS resolver. It should be possible to provide custom resolver implementation.

Our specific scenario:

We are implementing reverse proxy in Helidon for a service whose DNS resolves to multiple IPs (for load-balancing purposes). Without ability to override the DNS resolver, we cannot spread the load among the target IPs.

**Comment by janotav** [comment]
It turns out that Netty supports all that is necessary for our usecase. What is needed in Helidon is to be able to somehow pass the implementation into the client:

```
            // implementation provided by the caller somehow passed using WebClient configuration interface
            DnsAddressResolverGroup resolverGroup = new RoundRobinDnsAddressResolverGroup(NioDatagramChannel.class, DnsServerAddressStreamProviders.platformDefault());

            // Helidon WebClientRequestBuilderImpl implementation:
            Bootstrap bootstrap = new Bootstrap();
            bootstrap.group(eventGroup)
                    .resolver(resolverGroup)
                    .channel(NioSocketChannel.class)
```

as outlined in https://netty.io/news/2016/05/26/4-1-0-Final.html

**Comment by tomas-langer** [comment]
Not for for future versions based on Java Socket API: this can be achieved through a custom provider implementation of `java.net.spi.InetAddressResolverProvider` service loader provider type.

**Comment by janotav** [comment]
That requires Java 18 though. For us that practically means waiting until Java 21 (planned for September 2023), because non-LTS are likely not to be supported in our eco-system.

Not the kind of answer I hoped for :-(

**Comment by tomas-langer** [comment]
Sorry, the comment was for future lookups of this issue. We will look into this immediately.

**Comment by tomas-langer** [comment]
Ideal solution for Helidon:
- define SPI that is compatible both with Netty and the Java 18 SPI, so a user can implement it single time and it would work both with Netty and with our future non-Netty client.

**Comment by janotav** [comment]
Great to see this implemented!

Is this going to be part of (the upcoming) 2.5.x release?

**Comment by Verdent** [comment]
Hi @janotav , it will. There is a backport created for it into 2.x branch :-)
