### ISSUE TITLE
Dockerfiles are not generated for custom projects

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon#4783]
ProjectStarter doesn't generate Dockerfiles if 'Custom' option is selected.

I used this configuration:
https://helidon.io/starter/3.0.1?flavor=mp&step=4&app-type=custom&media.json-lib=jsonb&tracing=true

and also tried this:
https://helidon.io/starter/3.0.1?flavor=mp&step=6&app-type=custom&media.json-lib=jsonb&tracing=true&security=true&security.atn=oidc&extra=fault-tolerance&extra=cors

**Comment by barchetta** [comment]
You need to add `docker=true`

https://helidon.io/starter/3.0.1?flavor=mp&step=4&app-type=custom&media.json-lib=jsonb&tracing=true&docker=true
