### ISSUE TITLE
Compilation error with datasource example

### ISSUE THREAD

**Issue by rajesh-g-gupta** [oracle/helidon#491]
## Environment Details
* Helidon Version: 1.0.1 (#480)
* Helidon SE or Helidon MP
* JDK version:1.8.0_191-b12
* OS:Oracle Linux Server release 7.5
* Docker version (if applicable):18.09.1-ol
* Apache Maven 3.3.9
----------

## Problem Description

Helidon/examples/integrations/cdi/datasource-hikaricp pom file references itself as dependency
I had to comment out the following dependency to compile the sample

```
<dependency>
             <groupId>io.helidon.integrations.cdi</groupId>
             <artifactId>helidon-integrations-cdi-datasource-hikaricp</artifactId>
             <version>${project.version}</version>
             <scope>runtime</scope>
</dependency>
```

```
[ERROR] Failed to execute goal on project helidon-examples-integrations-datasource-hikaricp: Could not resolve dependencies for project io.helidon.examples.integrations.cdi:helidon-examples-integrations-datasource-hikaricp:jar:1.0.1-SNAPSHOT: Could not find artifact io.helidon.integrations.cdi:helidon-integrations-cdi-datasource-hikaricp:jar:1.0.1-SNAPSHOT -> 
```

## Steps to reproduce

```
cd helidon/examples/integrations/cdi/datasource-hikaricp/
mvn clean package
```

**Comment by romain-grecourt** [comment]
You are running off master without the workspace built. Use a tag.

**Comment by rajesh-g-gupta** [comment]
I was able to build with this command. 
mvn -P examples,integrations -pl examples/integrations/cdi/datasource-hikaricp -am clean install
