### ISSUE TITLE
MicroProfile metrics project has CDI beans in it but is not a bean archive

### ISSUE THREAD

**Issue by ljnelson** [oracle/helidon#492]
This may or may not be a problem depending on original intent.

The https://github.com/oracle/helidon/tree/master/microprofile/metrics subproject has several classes in it that are annotated with CDI annotations.  Here is one arbitrary example:

https://github.com/oracle/helidon/blob/ca1ffd3b04c38b08993e1b34bdbfbfdfc3a9f633/microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/RegistryProducer.java#L31-L32

The jar file produced by this project does not have a `META-INF/beans.xml` resource in it, so this jar file will not be recognized as a [bean archive](http://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#bean_archive) (see also [section 15.1 of the CDI specification](http://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#bean_archive_se)).  That is, it is an implicit bean archive, but in the absence of the `javax.enterprise.inject.scan.implicit` System property it will not be picked up.  This may or may not be by design and is, itself, not intrinsically a problem, but it is an easy thing to miss, so original intent is important here.

The `MetricsCdiExtension` programmatically registers the beans found in this jar file:

https://github.com/oracle/helidon/blob/ca1ffd3b04c38b08993e1b34bdbfbfdfc3a9f633/microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/MetricsCdiExtension.java#L164-L169

However, if the contents of this jar file are combined in a fat jar or some other mechanism such that they are in a classpath root that contains a `META-INF/beans.xml` with an effective bean discovery mode of `annotated` (or some other mode that results in their discovery), they will be registered twice, and ambiguous dependency errors will result.

We need to either:

- mark this subproject as a bean archive (my naïve preference) and eliminate the programmatic adding of the annotated types by `MetricsCdiExtension`, or
- remove the bean-defining annotations that cause these metrics-related bean classes to be automatically discovered and then, during programmatic registration, create programmatic beans for them in the proper scopes, but reading all other metadata from the classes in question

**Comment by tomas-langer** [comment]
I am for removing the bean defining annotations. I prefer the manual registration in an extension, as it removes jar scanning requirement for this jar file.

**Comment by ljnelson** [comment]
Duly noted.  For the record there's no scanning going on because we use Jandex.  In fact, we might be able to lose a reflective method call if we keep the annotations.
