### ISSUE TITLE
JPA/JTA support in Helidon MP

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon#496]

**Comment by gcameo** [comment]
Will be really good if this implementation does not force a requirement on all of us to now have to use JPA. I am using ArangoDB and it works very nicely at the moment.. :)

**Comment by spericas** [comment]
We should probably update one of our apps (like TODOs) to use JPA. It would be nice to have a real example of JPA in Helidon.

**Comment by ljnelson** [comment]
Initial support provided via #501.
