### ISSUE TITLE
Investigate build options

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon#497]
Investigate build systems other than Werker which we can use.

**Comment by romain-grecourt** [comment]
- [tektoncd](https://github.com/tektoncd)
- [jenkins pipelines](https://jenkins.io/doc/book/pipeline/syntax/#declarative-pipeline)
- [concourse](https://concourse-ci.org/)

All of the above require setting up our own compute.

**Comment by romain-grecourt** [comment]
settled on Jenkins, see https://github.com/oracle/helidon/issues/1210
