### ISSUE TITLE
SE config should prioritize system properties and env vars as does MP

### ISSUE THREAD

**Issue by batsatt** [oracle/helidon#507]
## Environment Details
* Helidon Version: 1.0.0-SNAPSHOT
* Helidon SE

----------

## Problem Description

MP prioritizes system properties (ordinal 400) over environment variables (ordinal 300), while SE does the reverse, so produces _different_ merged results when a given key is present in both.

**Comment by tomas-langer** [comment]
This should now be fixed, as Helidon SE Config implements MP Config as well.
Fixed for 2.0 only, as this is a backward incompatible chane.
