### ISSUE TITLE
Webserver log formatter does not replace !thread!

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#521]
Web server should replace `!thread!`  in formatter configuration with current thread name.
This is not happening. We often have this in our examples:
```
# Helidon Web Server has a custom log formatter that extends SimpleFormatter.
# It replaces "!thread!" with the current thread name
java.util.logging.ConsoleHandler.level=INFO
java.util.logging.ConsoleHandler.formatter=io.helidon.webserver.netty.WebServerLogFormatter
java.util.logging.SimpleFormatter.format=%1$tY.%1$tm.%1$td %1$tH:%1$tM:%1$tS %4$s %3$s !thread!: %5$s%6$s%n
```
Unfortunately the log statements contain `!thread!` in the output:
`2019.03.20 21:11:30 INFO io.helidon.webserver.NettyWebServer !thread!: Channel '@default' started: [id: 0x64d5b673, L:/0:0:0:0:0:0:0:0:8080]`

We should either fix the formatter, or update our examples.
## Environment Details
* Helidon Version: 1.0.1
* Helidon SE
* JDK version: 1.8

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

**Comment by wojtask9** [comment]
same as first part https://github.com/oracle/helidon/issues/333

currently there are only two occurrences with wrong `formatter` in `/test/apps/bookstore` .
`bookstore` was added after https://github.com/oracle/helidon/pull/337

**Comment by tomas-langer** [comment]
How to fix:
Replace 
`java.util.logging.ConsoleHandler.formatter=io.helidon.webserver.netty.WebServerLogFormatter`
with:
`java.util.logging.ConsoleHandler.formatter=io.helidon.webserver.WebServerLogFormatter`
