### ISSUE TITLE
@ConfigProperty can't be used on same type more than once

### ISSUE THREAD

**Issue by stasha** [oracle/helidon#535]
@ConfigProperty can't be used on same type more than once

## Environment Details
* Helidon Version: 1.0.1
* Helidon  MP
* JDK version: jdk1.8.0_172
* OS: Linux Mint
* Docker version (if applicable):

----------

## Problem Description
@ConfigProperty can't be used on same type more than once. If used WELD throws:
```org.jboss.weld.exceptions.IllegalArgumentException: WELD-001409: Ambiguous dependencies for type String with qualifiers @ConfigProperty
  at injection point [BackedAnnotatedField] @Inject @ConfigProperty private info.stasha.testosterone.jersey.junit4.helidon.HelidonTest.currency2
  at info.stasha.testosterone.jersey.junit4.helidon.HelidonTest.currency2(HelidonTest.java:0)
  Possible dependencies: 
  - ConfigPropertyProducer{qualifier=ConfigQLiteral{fullPath='info.stasha.testosterone.jersey.junit4.helidon.HelidonTest.currency', key='currency', defaultValue='eur', rawType=class java.lang.String}},
  - ConfigPropertyProducer{qualifier=ConfigQLiteral{fullPath='info.stasha.testosterone.jersey.junit4.helidon.HelidonTest.currency2', key='currency2', defaultValue='eur', rawType=class java.lang.String}}
```

## Steps to reproduce
    @Inject
    @ConfigProperty(name = "currency", defaultValue = "eur")
    private String currency;
    
    @Inject
    @ConfigProperty(name = "currency2", defaultValue = "eur")
    private String currency2;

**Comment by ljnelson** [comment]
I have put together a test case locally trying to reproduce this, but cannot.

Assuming a `META-INF/microprofile-config.properties` consisting solely of `currency = usd` (or some other equivalent MicroProfile Config-compliant configuration source), this excerpt works fine:

    @Test
    public void testIssue535() {
        // assume a CDI container is in effect here
        WeldIssue535 weldIssue535 = CDI.current().select(WeldIssue535.class).get();
        assertThat(weldIssue535, is(notNullValue()));
        assertThat(weldIssue535.toString(), is(notNullValue()));
    }

    @Dependent
    private static class WeldIssue535 {

        @Inject
        @ConfigProperty(name = "currency", defaultValue = "eur")
        private String currency;

        @Inject
        @ConfigProperty(name = "currency2", defaultValue = "eur")
        private String currency2;

        private void onStartup(@Observes @Initialized(ApplicationScoped.class) final Object event) {
            assertThat(currency, is("usd"));
            assertThat(currency2, is("eur"));
        }
        
    }

**Comment by stasha** [comment]
I just tried it in context of hello world app and it works as expected.
