### ISSUE TITLE
ConfigProperty injection does not work on resource methods

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#548]
When a resource method is annotated with ConfigProperty, the injected value is an empty String instead of the configuration value.

## Environment Details
* Helidon Version: 1.0.2
* Helidon MP

**Comment by m0mus** [comment]
Validate that it's not required by the MP Config spec. If not it should be closed.

**Comment by batsatt** [comment]
@tomas-langer Do you mean something like this?
```
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Inject
    public Response list(@ConfigProperty(name="max.results") int maxResults) {}
```
If so, Jersey does not understand this as you intend, seeing the parameter as an entity instead.

**Comment by m0mus** [comment]
Closing as not a bug. This behavior is correct.
