### ISSUE TITLE
Sub resource locator authorization does not work

### ISSUE THREAD

**Issue by martin-sladecek** [oracle/helidon#552]
Pre-matching authorization currently seems to leave all the resources open. No authorization is being processed (tested with ABAC), because the endpoint config contains no annotations in this case and so the validations are skipped.
## Environment Details
* Helidon Version: 1.0.2
* Helidon MP
* JDK version: 11.0.2
* OS: Linux
* Docker version (if applicable):

----------

## Problem Description + Sample code
Let's define a sample resource
```java
@ApplicationScoped
@Path("/test")
public class RootResource {

@Inject private SubResource sub;

@GET 
@Path("/")
@RolesAllowed("ROLE_A") 
@Authorized
public String test() {
   return "TEST PASSED";
}

@Path("/sub")
// This is ignored with prematching-authorization: false
// I would expect that "prematching" means that even this annotation is going to be validated.
@RolesAllowed("ROLE_A", "ROLE_B")
@Authorized
public SubResource sub() {
    // Here goes some custom logic that relies on the authorization policies being valid
    return sub;
}
}
```

```java
@ApplicationScoped
public class SubResource {

@GET 
@Path("/")
@RolesAllowed("ROLE_A") 
@Authorized
public String test() {
   return "SUB-TEST PASSED";
}
}
```

**Without** pre-matching authorization, anybody can request sub-resource from sub(), but then the particular resource in SubResource that was matched will going to be validated.

**With** pre-matching authorization, any of these resources can be called, no matter what the roles of the user are.
I would expect that prematching authorization will be validating all annotations above including the annotations along the path.

**Comment by spericas** [comment]
I'll let @tomas-langer confirm, but I believe this is working as designed. 

@martin-sladecek What exactly is your use case? Why is the no pre-matching option not working for you?

**Comment by martin-sladecek** [comment]
Not sure if it's clear from my previous comment.
Current behavior: user that does NOT have ROLE_A role can call any of those endpoints
Expected behavior: user must have ROLE_A to call all of those endpoints and authorization will be evaluated also for sub()

**Comment by spericas** [comment]
@martin-sladecek I see, I get it now.

**Comment by tomas-langer** [comment]
This is related to sub resource locators only. In such a case we do not have information about the "parent" resource method annotations, so we only process annotations on the sub-resource method.
Investigating with Jersey team to be able to retrieve all annotations.

**Comment by tomas-langer** [comment]
Workaround:
Place security annotations on the sub-resource method and class, as these are processed.

**Comment by tomas-langer** [comment]
Behavior is to be as follows (the closest behavior as described in `RolesAllowed` javadoc expanded to sub resources):
1) If only resource class annotated, use resource class annotation
2) If resource class and method annotated, use resource method annotation
3) If sub-resource class annotated, use sub-resource class annotation (regardless of annotations on resource)
4) If sub-resource method annotated, use sub-resource method annotation

By `use` we mean _ignore all annotations on any other class/method "above"_
