### ISSUE TITLE
Fallback annotation breaks automated Tracing propagation

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#560]
In case a method that uses Jersey client to call external service is annotated with `@Fallback`, the tracing is disconnected (client request is a root span).
This is caused by running in a different thread (an FT thread) rather than on the original JAX-RS thread.

This should be resolved in a way that we correctly transfer request context between threads.
Connect to work done for Helidon database for context support in executor services and for "in-context" execution.

## Environment Details
* Helidon Version: 1.0.2
* Helidon MP

**Comment by spericas** [comment]
This makes sense, we need to fix it in the FT 2.0 code that is currently under review. You can assign it to me if you want.

**Comment by tomas-langer** [comment]
depends on #596
