### ISSUE TITLE
Span write-content should not outlive parent span

### ISSUE THREAD

**Issue by spericas** [oracle/helidon#561]
The parent span for `write-content` is the complete HTTP request/response span. Looking at traces in Zipkin always shows `write-content` ending _after_ its parent, which is very odd.

**Comment by spericas** [comment]
<img width="1109" alt="Screen Shot 2019-04-10 at 3 56 54 PM" src="https://user-images.githubusercontent.com/5586231/55964777-4adbe500-5c43-11e9-82c9-db0acc0cf7b9.png">

**Comment by m0mus** [comment]
Merged
