### ISSUE TITLE
Jenkins-X with Helidon

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon#568]
Create a guide describing how to use Jenkins-x as a CI/CD for a Helidon service.

**Comment by spericas** [comment]
Would this be different to using Jenkins-x with a non-Helidon service?

**Comment by gcameo** [comment]
I don't think there is anything special to be done on Helidon for this. I already use Jenkins-X with my Helidon projects. The changes you do are all bespoke depending on your pipeline

**Comment by tomas-langer** [comment]
Closing this issue as there is nothing specific we need to do for Jenkins X.
Feel free to re-open with a detailed use case + expected support from Helidon, if the above statement is not true for you.
