### ISSUE TITLE
Refactor ServerConfiguration to follow development guidelines

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon#575]
Refactor ServerConfiguration to follow Helidon development guidelines for Build/Config.

The config mapping for SocketConfiguration is done by ServerConfiguration, this should be done in SocketConfiguration instead.

The fix for #519 introduces a new configuration attribute called "enabled-protocols" to SocketConfiguration.

Instead this attribute should be added to SSLContextBuilder, so that all SSL configuration is nested under the same config object. 

Note that SSLContextBuilder builds `javax.net.ssl.SSLContextBuilder`, we will need to create a sub-class to store custom attributes. SocketConfiguration.Builder also accepts `javax.net.ssl.SSLContext` ; it will need to be changed to the new SSLContext class, and SSLContextBuilder will need to have a way to build instances of the new SSLContext class using instances of `javax.net.ssl.Context`.

The new SSLContext class should be something like `io.helidon.webserver.SSLContext`, with a inner statis class Builder. SSLContextBuilder should inherit `io.helidon.webserver.SSLContext.Builder` and be marked deprecated.

**Comment by romain-grecourt** [comment]
@tomas-langer FYI, feel free to update as needed.

**Comment by tomas-langer** [comment]
I have chosen the following approach:
1. `ServerConfiguration` is now deprecated for building `WebServer`, all methods are now available on `WebServer.Builder`
2. Added `TlsConfig` to manage SSL related configuration
3. Kept existing setup and deprecated it
4. Deprecated configuration keys (using `DeprecatedConfig`)
