### ISSUE TITLE
helidon 0.10.0 archetype is not available in Maven central repository

### ISSUE THREAD

**Issue by hantsy** [oracle/helidon#63]
## Environment Details
* Helidon Version: 0.10.0
* Helidon SE or Helidon MP
* JDK version: java version "1.8.0_181"
* OS: Windows 10 64bit
* Docker version (if applicable):

----------

## Problem Description

 helidon 0.10.0 archetype is not available in Maven central repository

## Steps to reproduce

Follow the Getting started guide, and ran the following command.

     mvn archetype:generate -DinteractiveMode=false \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-quickstart-se \
    -DarchetypeVersion=0.10.0 \
    -DgroupId=io.helidon.examples \
    -DartifactId=quickstart-se \
    -Dpackage=io.helidon.examples.quickstart.se

It failed.

**Comment by barchetta** [comment]
The archetype is in Maven Central:

https://search.maven.org/artifact/io.helidon.archetypes/helidon-quickstart-se/0.10.0/maven-archetype

And it appears to work:

```
$ rm -rf ~/.m2/repository/io/helidon/
$ mvn archetype:generate -DinteractiveMode=false \
-DarchetypeGroupId=io.helidon.archetypes \
-DarchetypeArtifactId=helidon-quickstart-se \
-DarchetypeVersion=0.10.0 \
-DgroupId=io.helidon.examples \
-DartifactId=quickstart-se \
-Dpackage=io.helidon.examples.quickstart.se
[INFO] Scanning for projects...
. . .
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.259 s
[INFO] Finished at: 2018-09-18T11:08:29-07:00
[INFO] ------------------------------------------------------------------------
```

What error do you see when it fails?

**Comment by hantsy** [comment]
@barchetta Worked today. Thanks.

I had searched the mvnrepository.org, it is not available when I tried this command.
