### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by longtran84** [oracle/helidon#630]
longtran@longtran:~/Downloads/helidon-master/examples/quickstarts/helidon-quickstart-se$ mvn clean
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact io.helidon:helidon-bom:pom:1.0.4-SNAPSHOT @ line 126, column 25
[ERROR] 'dependencies.dependency.version' for io.helidon.bundles:helidon-bundles-webserver:jar is missing. @ line 147, column 21
[ERROR] 'dependencies.dependency.version' for io.helidon.config:helidon-config-yaml:jar is missing. @ line 151, column 21
[ERROR] 'dependencies.dependency.version' for io.helidon.health:helidon-health:jar is missing. @ line 155, column 21
[ERROR] 'dependencies.dependency.version' for io.helidon.health:helidon-health-checks:jar is missing. @ line 159, column 21
[ERROR] 'dependencies.dependency.version' for io.helidon.metrics:helidon-metrics:jar is missing. @ line 163, column 21
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.helidon.examples:helidon-quickstart-se:1.0.4-SNAPSHOT (/home/longtran/Downloads/helidon-master/examples/quickstarts/helidon-quickstart-se/pom.xml) has 6 errors
[ERROR]     Non-resolvable import POM: Could not find artifact io.helidon:helidon-bom:pom:1.0.4-SNAPSHOT @ line 126, column 25 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for io.helidon.bundles:helidon-bundles-webserver:jar is missing. @ line 147, column 21
[ERROR]     'dependencies.dependency.version' for io.helidon.config:helidon-config-yaml:jar is missing. @ line 151, column 21
[ERROR]     'dependencies.dependency.version' for io.helidon.health:helidon-health:jar is missing. @ line 155, column 21
[ERROR]     'dependencies.dependency.version' for io.helidon.health:helidon-health-checks:jar is missing. @ line 159, column 21
[ERROR]     'dependencies.dependency.version' for io.helidon.metrics:helidon-metrics:jar is missing. @ line 163, column 21
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by spericas** [comment]
If you clone the latest repo, you need to build it from the top to ensure all the SNAPSHOT artifacts are available. Otherwise, please check out a released version such as:

https://github.com/oracle/helidon/releases/tag/1.0.3
