### ISSUE TITLE
OIDC Provider has inconsistency problems with scope and audiences naming 

### ISSUE THREAD

**Issue by asantaga** [oracle/helidon#647]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 1.0.3
* Helidon SE 
* JDK version: 
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

* OS: Windows 10 & Ubuntu 18.04
* Docker version (if applicable): N/A
* OIDCS Version : 18.4.2-1903181528

## Problem Description
Using the oidc-login example and executing the  /jersey Endpoint 

Within the JerseyResource.java file the rest method specifies two scopes called "first_scope" and "second_scope"

one would think that set the primary audience to something like "http://localhost:7987" in the ```application.yaml``` and the scopes in resources to ```first_scope``` and ```second_scope```.  

If you set this then the example will fail with the following error before doing the redirect to oidcs for authentication

```
{"error": "invalid_scope", "error_description": "Invalid scope."}
```
If you set the audience to have two trailing forward slashes e.g. ```http://localhsot:7987//``` then the solution will work and redirect to OIDCS for authentication.

However once authentication has succeeded the redirect back to the original URL fails and goes into infinite loops. I believe this is covered by issue https://github.com/oracle/helidon/issues/644

Problem is reproducible every time

[//]: # "Provide sample code/application if relevant"
use idcs-login example

**Comment by asantaga** [comment]
Doing some additional debugging
Using the idcs_login example

Within IDCS i have 
- the primary audience as ```http://localhost:7987``` 
- Scopes as "/first_scope" and "/second_scope"
IDCS Shows the full scope name as http://localhost:7987/first_scope and http://localhost:7987/second_scope

Debugging the code , specifically line266 of OidcProvider.java, I introspected the queryString being generated for OIDCS and I see

(URLDecoded and obvuscated) gives me 
```
client_id=xxxx&response_type=code&redirect_uri=http://localhost:7987/oidc/redirect&scope=openid http://localhost:7987//second_scope http://localhost:7987//first_scope&nonce=xxxx&state=/jersey
```

Here we can see a double // between the audience and the scope.  
This is the issue

**Comment by asantaga** [comment]
workaround : do not have scopes starting with / and ensure audiences end with a /

**Comment by tomas-langer** [comment]
The fix works as follows:
- if scope audience is not configured, the scope is requested without leading slash
- if scope audience is defined, the scope is requested as scope audience + `/` + scope name, ensuring there is exactly one `/` between audience and name
