### ISSUE TITLE
Source code inconsistencies

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#648]
This is an issue to gather all inconsistencies in the source code we are aware of, so we can eventually decide 
 - on a single approach and refactor the code
 - or agree to disagree and leave such inconsistencies in

Currently known:
- `if (null == field)` vs `if (field == null)`
- `if ((result == null) && (parent != null))` vs `if (result == null && parent != null)`
- order of stuff in `pom.xml` 
    - `dependencies` before `build` vs `dependencies` after `build`
    - pom version location
    - `groupId` and `artifactId` order
- methods should never return null - always Optional (unless prescribed by implemented interface from somebody elses API) - this is a rule that we need to add to development guidelines
- use static imports vs. not using static imports (e.g. `Objects.requireNonNull`)
- how to format fluent API
```
stream.map()
            .map()
            .filter()
            .collect()
```
vs 
```
stream
   .map()
   .map()
   .filter()
   .collect()
```

**Comment by tomas-langer** [comment]
Order of stuff in a class (this vs. anything else).
```
public static final FIELD;
static final FIELD;
private static final FIELD;
private static field;
field;
private field;
public constructor;
protected constructor;
constructor;
private constructor;
public static method;
static method;
@Override
public method;
public method;
method;
private static method;
private method;
public class Class;
class Class;
private class Class;
```

**Comment by tomas-langer** [comment]
Usage of `final` keyword
`final` in fields - agreed, we should use
`final` in parameters vs. not using it
`final` in local variables vs. not using it

**Comment by spericas** [comment]
My $.02:

- Use of `final`: I agree with @tomas-langer, fields only
- I'm fine with any order of modifiers such as `public`, `static`, ...
- Highly dislike (null == foo), seems backwards to me
- Parentheses in expressions that aren't need should be eliminated (nested ones are rarely needed)
- Methods should be allowed to return `null`, returning `Optional` gets into more object creation and impacts performance if used everywhere 
- Avoid capturing lambdas if possible (object creation)
- Don't mind static imports
- Prefer fluent API with `.` on first line (not after `\n`)
- Use conditional expressions over if-then-else if possible
- Don't care about ordering in pom files

**Comment by tomas-langer** [comment]
@spericas 
- Highly dislike (null == foo), seems backwards to me - I will try to unlearn this, as I seem to be the only one using it
- Parentheses in expressions that aren't need should be eliminated - I tend to disagree here, as the parentheses make readability better, as they clearly separate conditions. Open for discussion ;)
- Methods should be allowed to return null, returning Optional gets into more object creation and impacts performance if used everywhere - I do not like the ambiguity of APIs when `null` is allowed - and very strongly. The rule to forbid `null` as an argument and `null` as a response from a method should stand - open to discussion only if performance difference is bigger than 1% (considering everything else is the same). Also if we ever decide to go this way, we would need to introduce one of the annotation APIs to clearly mark return types as nullable or not-nullable
- Prefer fluent API with . on first line (not after \n) - not sure I get your meaning, can you show examples?
- Use conditional expressions over if-then-else if possible - if you mean `condition ? whenTrue : whenFalse` - I would agree only for statements that are short - if you need to format into a multi-line statement, please do not use it, as the readability is way worse. Also from performance point of view this does not matter at all, as both should be compiled into the same bytecode

**Comment by barchetta** [comment]
For reference:

* [Original JDK Coding Conventions](https://www.oracle.com/java/technologies/javase/codeconventions-contents.html) from 1999
* [Proposed revised version from community](https://cr.openjdk.java.net/~alundblad/styleguide/index-v6.html) from 2015
* [PR](https://github.com/openjdk/guide/pull/14) from May 2020 to try and get above merged into OpenJDK Developer Guide. It resulted in much discussion and little action.
* [An attempt](https://mail.openjdk.java.net/pipermail/guide-dev/2020-August/000231.html) to get an editorial board assembled to work on updating the Coding Conventions
* [Googles Java Style Guide](https://google.github.io/styleguide/javaguide.html)

**Comment by tomas-langer** [comment]
I am closing this issue, as we will not do a "one-off" PR to fix all of these. The code style is slowly aligning as we modify existing code.
