### ISSUE TITLE
Example in section Quickstart Examples doesn't work

### ISSUE THREAD

**Issue by TimurJD** [oracle/helidon#66]
## Environment Details
* Helidon Version: 0.10.0
* Helidon SE
* JDK version: 1.8.0_181
* OS: macos 10.13.6
* Docker version (if applicable):

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
Following by [Quickstart Examples](https://helidon.io/docs/latest/#/getting-started/02_base-example) I have such output:
`2018.09.18 13:44:28 INFO io.netty.util.internal.PlatformDependent Thread[main,5,main]: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
`

`2018.09.18 13:44:28 INFO io.helidon.webserver.netty.NettyWebServer Thread[nioEventLoopGroup-2-1,10,main]: Channel '@default' startup failed. Startup failure routine initiated.`
`WEB server is DOWN. Good bye!`

It happens whenever I run **mvn package** or directly run the generated example via intellij idea.

## Steps to reproduce

1. Generate project **quickstart.se** with command:
`mvn archetype:generate -DinteractiveMode=false \`
    `-DarchetypeGroupId=io.helidon.archetypes \`
    `-DarchetypeArtifactId=helidon-quickstart-se \`
    `-DarchetypeVersion=0.10.0 \`
    `-DgroupId=io.helidon.examples \`
    `-DartifactId=quickstart-se \`
    `-Dpackage=io.helidon.examples.quickstart.se`

2. cd quickstart-*
3. mvn package

**Comment by spericas** [comment]
Maybe something else running on port 8080? You can change the port in src/main/resources/application.yaml.

**Comment by TimurJD** [comment]
@spericas yes, you are right, port 8080 was already in use. Maybe it would be better to adjust the INFO message to something like this: "Port 8080 is already in use"?

**Comment by spericas** [comment]
I'm closing this issue and opening one for the enhancement.
