### ISSUE TITLE
Work created faster than completed

### ISSUE THREAD

**Issue by olotenko** [oracle/helidon#685]
## Environment Details
* Helidon Version: Version: 1.0.4-SNAPSHOT
* Helidon SE
* JDK version: $ java -version
java version "12" 2019-03-19
Java(TM) SE Runtime Environment (build 12+33)
Java HotSpot(TM) 64-Bit Server VM (build 12+33, mixed mode, sharing)
Java HotSpot(TM) 64-Bit Server VM 12+33 (Mac OS X 10.14.4): 4 cpus, 4.0 GB max mem
* OS:Mac OS X 10.14.4
* Docker version (if applicable):

----------

## Problem Description

* Start:
```
$ java -Dbookstore.size=10 -Dapp.json-library=JSONP -Dserver.workers=1 -Dserver.executor-service.max-pool-size=16 -jar ~/demo/helidon/load-testing/helidon-se/target/helidon-se.jar
```
(load-testing is the test scenario provided by dev)

* Use 8 keep-alive connections
* Send GET /books repeatedly, 3ms think time (if no think time, then 2 connections suffice)
* Within a couple of minutes you can observe heap pressure (response times go up)
* Within 5 minutes OOME on the helidon-se kicks in

Similar problem of smaller magnitude exists in Helidon-MP, too. (the above configuration appears to be stable, but smaller think time also drives heap pressure to the levels where the JVM is in GC almost all the time)

## Steps to reproduce

Example node js script to drive load:
```
'use strict';

const http = require('http');

const CONCURRENCY=8;
const THINK_TIME=3;
const agent = new http.Agent({
  keepAlive: true,
  keepAliveMsecs: 600000,
  timeout: 600000,
  maxSockets: CONCURRENCY,
});

let dt = 0;
let c = 0;
const responses = {};
const doit = (cb) => {
  const t0 = process.uptime();
  const req = http.get('http://localhost:8080/books', {
                agent: agent,
                timeout: 600000,
                headers: {connection: 'keep-alive'}
              });
  req.on('error', err => {
    console.log('ERROR', err);
    cb();
  });

  req.on('response', res => {
    const code = res.statusCode.toString();
    responses[code] = (responses[code] || 0)+1;
    let sz = 0;
    res.on('data', ch => sz += ch.length);
    res.on('end', () => {
      dt += process.uptime() - t0;
      c++;
      cb();
    });
  });
};

let started = 0;
let finished = 0;

const t0 = process.uptime();
const processone = () => {
  const now = process.uptime();
  if (now - t0 < 300) {
    return setTimeout(doit, THINK_TIME, processone);
  }

  finished++;
  if (finished === started) {
    console.log('DONE', c, 'in', now - t0, 'seconds which is', c / (now - t0), '/s avg rt', dt / c, ' seconds');
    console.log('RESPONSES', responses);
    process.exit(0);
  }
};

while(started < CONCURRENCY) {
  started++;
  processone();
}
```

**Comment by batsatt** [comment]
Can you please try to reproduce this on a current version of JDK 8 (e.g. VM 1.8.0_201-b09)?

**Comment by olotenko** [comment]
The details in the internal thread.

**Comment by spericas** [comment]
Moved to wiki.
