### ISSUE TITLE
Jersey thread pool should be sized by # of cores by default

### ISSUE THREAD

**Issue by batsatt** [oracle/helidon#689]
The thread pool in both MP and in SE with Jersey is statically sized by default, but should be sized according to the # of cores.

When max size > core size and a reasonably sized queue is used, the `ThreadPoolExecutor` will not add new threads until the queue is full which will only occur under exceptional load and/or when application code consumes threads for long periods. The net is that the core size is also effectively the max size, and this algorithm cannot easily be changed.

Issue #690 has been filed to investigate a smarter algorithm, but, for now, the core and max values can just be set to the same value.

**Comment by spericas** [comment]
@batsatt What if we provide a small queue instead? The default implementation seems to create a queue with _max_ capacity. The downside of this approach is that you may get some rejections, but otoh that would be an indication that the app needs tuning.

**Comment by batsatt** [comment]
I considered this, but don't know how to determine a reasonable default size to use for the queue. Given that we need a better long term solution, I don't think we want a short term one that will likely result in rejections, requiring support, documentation etc.

The long term solution needs to be started on a.s.a.p.
