### ISSUE TITLE
RouteListRoutingRules post method has copy/paste errors

### ISSUE THREAD

**Issue by ljnelson** [oracle/helidon#70]
See, for example:

https://github.com/oracle/helidon/blob/c3ddab97fec4af26b8e4584e3d73649c8123d2c4/webserver/webserver/src/main/java/io/helidon/webserver/RouteListRoutingRules.java#L219

PR coming shortly.

**Comment by barchetta** [comment]
And

https://github.com/oracle/helidon/blob/c3ddab97fec4af26b8e4584e3d73649c8123d2c4/webserver/webserver/src/main/java/io/helidon/webserver/RouteListRoutingRules.java#L214

**Comment by ljnelson** [comment]
For posterity: the workaround in Helidon 0.10.0 and earlier is to use chaining:

    final Routing.Rules rules = // ...
    rules.get(/* some recipe */).post(/* some recipe */);

**Comment by romain-grecourt** [comment]
Not sure there is anything specific related to "chaining" since this is a fluent interface.
I've tested the workaround mentioned by @ljnelson, did not work for me.

What worked for me was to force a path of "/".

```java
public class MyService implements Service {

    @Override
    public void update(Routing.Rules rules) {
        rules
            .get(this::test)
            .post("/", this::test);
    }

    private void test(ServerRequest req, ServerResponse res){
        res.send("ok");
    }
}
```
