### ISSUE TITLE
Memory leak io.netty.handler.codec.DefaultHeaderImpl

### ISSUE THREAD

**Issue by umishu** [oracle/helidon#703]
I am created simple status check web application with helidon.
This program receive 1-3 request per second, 
crashed by OutOfMemoryError at several hours.

## Environment Details
* Helidon Version: 1.1.0
* Helidon SE 
* JDK version: Oracle 8_212
* OS: Windows
* Docker version (if applicable):

----------

## Problem Description
Checked some test with jvisualvm.
In operation, -Xmx option 128m, crashed at several hours,
Test1, -Xms option 16ms and 1 request per second, crashed at 15min.
Test2, -Xms option 16ms and 3 request per second, crashed at 5min.
* request from chrome browser.

DefaultHeaderImpl increase each request, and was not GC.

## Steps to reproduce
Sample Code
`public class HelidonStatusServer {
	
	public static void main(String[] args) {
		new WatcherRunner().start();
		
		WebServer.create(
                ServerConfiguration.builder().port(8088).timeout(60_000).build(),
                Routing.builder()
                .get("/status", new StatusHandler())
                .register("/", StaticContentSupport.builder(Paths.get("www")) 
                        .welcomeFileName("index.html").build())
                .build()
        ).start();
	}
	
    public static class StatusHandler implements Handler {

        @Override
        public void accept(ServerRequest req, ServerResponse res) {
        	res.headers().contentType(MediaType.APPLICATION_JSON);
        	res.headers().add("Access-Control-Allow-Origin", "*");
            res.send(StatusStore.toJson());
        }
    }
}`

### visualvm screenshot filtered netty packages
![heap](https://user-images.githubusercontent.com/14878573/57886346-f215f280-7867-11e9-8cfd-14a0c21f7ce7.png)

**Comment by batsatt** [comment]
@umishu I have confirmed that this issue has already been fixed by PR #695 (and #702), which will be available in the next release.
