### ISSUE TITLE
Upgrade open tracing

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#706]
Upgrade open tracing. Latest version (at the time of this writing) is 0.33.0.

Note that this will require code changes. Methods that were deprecated in 0.32.0 have been removed. For more info see:

https://github.com/opentracing/opentracing-java/blob/master/CHANGELOG.md
https://medium.com/opentracing/opentracing-java-0-32-released-a3c9b6af08e4

**Comment by barchetta** [comment]
Looks like Brave hasn't implemented 0.32.0 yet. This PR is WIP:
https://github.com/openzipkin-contrib/brave-opentracing/pull/93

**Comment by tomas-langer** [comment]
Brave opentracing 0.34 now supports the new version (0.33)

**Comment by tomas-langer** [comment]
Resolved via #1230
