### ISSUE TITLE
Improve method names in the SecurityContext interface

### ISSUE THREAD

**Issue by ashishksingh** [oracle/helidon#709]
## Environment Details
* Helidon Version: 1.1.0

## Problem Description

The naming convention in the SecurityContext interface at io.helidon.security.SecurityContext is sometimes confusing. Like the env method should have been two methods getEnv and setEnv to make the distinction very clear. In the code otherwise it gets difficult to understand what I'm doing otherwise. 
Similarly the service() method, and a bunch of others.

**Comment by romain-grecourt** [comment]
FWIW this is coding style of the Helidon APIs.
I will let @tomas-langer comment for more details.

**Comment by ashishksingh** [comment]
Thanks @romain-grecourt , I wasn't aware of these guidelines and that README page. I will go through it in detail and close the ticket if the code was adhering to the prescribed standards anyway.

**Comment by tomas-langer** [comment]
Closing as the naming conventions adhere to the ones defined in development guidelines.
