### ISSUE TITLE
AnnotationAnalyzers load in indeterminate order

### ISSUE THREAD

**Issue by dansiviter** [oracle/helidon#710]
## Environment Details
* Helidon Version: 1.1.0
* Helidon MP
* JDK version: adoptopenjdk/openjdk11:jdk-11.0.3_7-alpine (on Docker) and JDK 11.0.2 (on Mac)
* OS: Alpine and Mac Mojave
* Docker version (if applicable): Docker for Mac 2.0.0.3

----------

## Problem Description
Two potential issues:

When the `AnnotationAnalyzer` load within `SecurityFilter` they do so via the `ServiceLoader` mechanism into a `List`. The `ServiceLoader` has no guarantee of order which means that list could be in any order and is indeterminate. When the analysers are processed, depending on the order in which they were loaded they can overwrite the answer of the previous one. Between running locally on the Mac and within docker, I've observed that on the mac the analysers were:

```
[
  io.helidon.microprofile.jwt.auth.JwtAuthAnnotationAnalyzer@68dbe225,
  io.helidon.security.abac.role.RoleAnnotationAnalyzer@145ef9e8
]
```

...and in Docker:

```
[
  io.helidon.security.abac.role.RoleAnnotationAnalyzer@7e1953f7,
  io.helidon.microprofile.jwt.auth.JwtAuthAnnotationAnalyzer@26f07261
]
```

In the latter case, the JWT analyser was overriding the Role analyser which gives different authentication responses. This makes it impossible to reliably run using authorisation using the same codebase across various operating systems and java versions.

Second issue is that `JwtAuthAnnotationAnalyzer` does not process `@PermitAll` annotation but does process `@RolesAllowed`. This means if the JWT analyser follows the Role analyser, it will override its decision. However, due to the previous issue it's not possible to guarantee the order in which this happens. In searching through the Microprofile JWT spec, it's somewhat light on how `@PermitAll` should work, however I did find [this](https://github.com/eclipse/microprofile-jwt-auth/blob/1.1/spec/src/main/asciidoc/interoperability.asciidoc).

## Steps to reproduce
Create an application that has two or more analysers, run it in various operating systems and java builds and observer, via debug, that the analysers are in a different order.

**Comment by dansiviter** [comment]
Apologies for being late to the party, but isn't [this](https://github.com/oracle/helidon/blob/ca19b6e614d254f232863ae926a178328ebadfbd/security/integration/jersey/src/main/java/io/helidon/security/integration/jersey/SecurityFilter.java#L129) going to result in duplicates in the `analyzers` list?

**Comment by dansiviter** [comment]
@tomas-langer / @m0mus Just highlighting that the PR appears to make the situation worse. Should this have a unit test?

**Comment by tomas-langer** [comment]
There is a new PR with a unit test.
Sorry for the inconvenience.
