### ISSUE TITLE
Expand media types our OpenAPI support should accept

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#752]
The landscape for a YAML media type is unsettled. There is no IANA-registered "pure" one (such as `application/yaml`).

I did some reading during the implementation of our initial implementation of OpenAPI support (SE and MP), and as released in 1.1.2 we deal with these media types:

`application/vnd.oas.openapi+json`
`application/json`
`application/vnd.oas.openapi` (default in the absence of `Accept:` in the request)
`application/x-yaml`

Santiago has raised the very valid point of whether we should expand this list due to what people are actually using "in the wild" for YAML. 

I want to get the group's input so we can decide whether to expand the list and, if so, what we should expand it to. It's relatively simple to accommodate more media types in our OpenAPI implementation. I would just prefer to go in once to update the list rather than make numerous changes.

Some possibilities (not meant to be exhaustive):

- `text/yaml`
- `application/yaml`

I have read some debates on-line about the merits of `text` (it is human-readable) vs. `application` (it is intended for software to consume), and `vnd` vs. `x-` etc. etc. etc. Let's try to avoid rehashing those discussions here! 

The point is there is no registered "standard" media type for YAML so we need to decide what we want our OpenAPI implementation to support.

**Comment by spericas** [comment]
I don't see any harm in supporting a few more commonly used media types, despite not being officially registered. I am especially fond of those that are not `vnd`.

**Comment by tjquinno** [comment]
I agree, and it's quite simple to add additional media type support to our code that supports OpenAPI. I just would prefer to make one set of changes, one push, one review cycle, and one merge to handle all the additional ones we decide to handle.

Please, everyone, list what specific ones you think we should support.

**Comment by tjquinno** [comment]
For example:

- OpenLiberty uses media type `text/plain` for YAML format.
- Thorntail layers on SmallRye's implementation and uses the same media type it does: `application/yaml` which is not registered.

There is a lengthy and years-long-running discussion here https://github.com/OAI/OpenAPI-Specification/issues/110 which discusses the `application/vnd.oas.openapi` and `application/vnd.oas.openapi+json` media types that are proposed. Our implementation currently supports those (along with `application/json` and `application/x-yaml`).
