### ISSUE TITLE
Helidon does not send json Stream

### ISSUE THREAD

**Issue by auryn31** [oracle/helidon#756]
I am currently trying to send a json stream with Helidon. I use the exact same code with quarkus and it works, but not with Helidon. Is there something special to pay attention? 

my code to write the response is:

    class StreamResponseOutput : StreamingOutput {

      override fun write(os: OutputStream?) {
        val writer = BufferedWriter(OutputStreamWriter(os))
        val countDownLatch = CountDownLatch(1)
        DataService.getDataStream(0).subscribe({
            writer.write(Klaxon().toJsonString(it))
            writer.write("\n")
            writer.flush()
        }, ::println, {
            os?.close()
            countDownLatch.countDown()
        })
        countDownLatch.await()
        writer.flush()
      }
    }

my response in quarkus is a json object every time, I get one from the datastreamservice. Helidon waits till everything is there and writes the json after the last one is received. 

what did I missed?

**Comment by spericas** [comment]
@auryn31 Could you provide more details about your resource method? Looks like there may be an issue with flushing partial data all the way to the network. We'd need to create a test for this use case.

**Comment by auryn31** [comment]
@spericas i am currently working on a framework comparison 
https://github.com/auryn31/spring-async-rest-example/tree/master/reactive-backend/reactive-helidon
here are more details about the code

**Comment by spericas** [comment]
> @spericas i am currently working on a framework comparison
> https://github.com/auryn31/spring-async-rest-example/tree/master/reactive-backend/reactive-helidon
> here are more details about the code

Ok, I see the method `loadCarsAsOctetStream()`.

**Comment by auryn31** [comment]
These two are basically doing the same:

`@GET
    @Produces(MediaType.APPLICATION_OCTET_STREAM)
    fun loadCarsAsOctetStream(): StreamingOutput {
        return CarStreamResponseOutput()
    }

    @GET
    @Produces("application/stream+json")
    fun loadCarsAsJsonStream(): Response {
        val responseStream = CarStreamResponseOutput()
        return Response.ok().header("Access-Control-Allow-Origin", "*").entity(responseStream).build()
    }`

**Comment by spericas** [comment]
@auryn31 I can confirm that the flush is ignored. I have a fix for the issue that needs a new test to be provided. Should be available in the next release.

**Comment by auryn31** [comment]
thanks (Y)

**Comment by spericas** [comment]
Issue has been fixed and should be available in next release.
