### ISSUE TITLE
HTTP_2 in combination with SSL (TSL 1.2)

### ISSUE THREAD

**Issue by stgloor** [oracle/helidon#762]
I did configure the server side with the experimental configuration (in MP):

> 
> experimental:
>    http2:
>      enable: true
>      max-content-length: 16384

With curl when using option `http-prior-knowledge` it works because it doesn't negotiate, thus not upgrade from http 1.1 to http2 instead it initially starts with http2.

With curl when using option http2 it doesn't.

## Environment Details
* Helidon Version: 1.0.4
* Helidon SE and Helidon MP
* JDK version: 11
* OS: Windows / Linux
* Docker version (if applicable): not applicable

----------

## Problem Description

Excerpt from protocol log when using curl with option http2 and protocol negotiation:
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-SHA
* ALPN, server did not agree to a protocol
...
Both sides are configured to use http2. 

Expected behaveiour would be, that the upgrade request from the client during initiation would be acknowledged by helidon and further communication bases on http2 (with streaming).

The problem is easily reproduceable by configure the service as http2 service (TLS 1.2. or 1.3.) and yielding a request with 

> $ curl --http2 <url>

using curl: 

> $ curl --http2  -v --cacert /C/temp/hgbuemeadevcontainerregistry/HGBURootCA.cer                                                                                               https://hgbuemeaservicecluster.de.oracle.com:30020/greet

 Trying 10.165.72.72...
* TCP_NODELAY set
* Connected to hgbuemeaservicecluster.de.oracle.com (10.165.72.72) port 30020 (#                                                                                              0)
* ALPN, offering h2
* ALPN, offering http/1.1

,...
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-SHA
* ALPN, server did not agree to a protocol
* 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Thu, 6 Jun 2019 15:19:05 GMT
< transfer-encoding: chunked
< connection: keep-alive

**Comment by spericas** [comment]
Resolved and will be available in the 1.1.3 release.
