### ISSUE TITLE
WebServer system services

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#780]
We need to be able to extend WebServer to achieve:

1. Add objects to application wide `Context`
2. Intercept every request to the `WebServer`

Currently we have a problem achieving the second point, as every handle may finish the processing (e.g. calls `response.send()` and not `req.next()`).

Proposed solution:

- Create a `SystemService` interface that can be registered with server configuration
- Add support for loading these through Java service loader (default is not to load the services)
- Invoke the `SystemServices` before processing routing on server

This is marked as P1, as other features depend on such an approach (AccessLog support, Tracing refactoring)

**Comment by spericas** [comment]
Are these services only relevant to requests and always processed before routing? Should there be something equivalent for response pipelines?

**Comment by tomas-langer** [comment]
After extended analysis, we have decided to postpone this for release 2.0, as it is quite a heavy change in the way webserver is configured.

The main issues:

 - we have to consider multiple listeners being configured (e.g. localhost:8080 and 192.168.1.1:7777) with different routes defined (and different security etc.).
 - there are multiple components that need to work as "system services":
  - Tracing
  - Context support (`io.helidon.common.Context`)
  - Metrics registry (should be a single registry per app, endpoint set up in web server)
  - health checks (should be a single "registry" per app, endpoint set up in web server)
  - Security
  - Tracer and tracing configuration
  - Vendor metrics (for WebServer, gRPC server and in the future database client, messaging)
  
We need to decide on which "level" to configure these components, with possibilities:

- Helidon microservice (e.g. static for this virtual machine)
- Helidon Web Server
    - Web Server Configuration
    - Web Server Listener
    - Web Server Routing
- Helidon gRPC Server
- other Helidon top-level components (messaging, database client)

**Comment by tomas-langer** [comment]
We did not find a reason to change behavior of web server and we most likely will not. We may re-open this if this requirement resurfaces.
