### ISSUE TITLE
Multiple SLF4J bindings

### ISSUE THREAD

**Issue by rbkrabbe** [oracle/helidon#786]
## Environment Details
* Helidon Version: 1.1.1
* Helidon MP
* JDK version: 11 (sourceCompatibility = 1,8)
* OS: Windows/Linux
* Docker version (if applicable): N/A

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"
It seems that helidon-microprofile-fault-tolerance includes an SLF4J binding that conflicts with the one configured by application developers.

When running a Helidon MP application with SLF4J binding in dependencies (log4j-slf4j-impl), the following warning from SLF4J is logged at startup:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/.../libs/log4j-slf4j-impl-2.11.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/.../libs/slf4j-jdk14-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
```

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"
Build and run an application with the following dependencies:
```
    implementation platform("io.helidon:helidon-bom:1.1.1")
    implementation 'io.helidon.microprofile.bundles:helidon-microprofile-1.2'
    implementation 'org.glassfish.jersey.media:jersey-media-json-binding:2.26'
    implementation group: 'org.apache.logging.log4j', name: 'log4j-slf4j-impl', version: '2.11.2'
```
The warning is logged at startup.

**Comment by spericas** [comment]
Yes, I can't recall how this dependency made it in. I'll take a look and try to remove it.

**Comment by spericas** [comment]
Dependency removed.
