### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon#799]
Evaluate adding GraphQL support to Helidon.

Justification:

The concept of Back End Services For Front end(BFF pattern) has compelled us think beyond REST and GraphQL offers excellent consolidation reducing network traffic as the number of HTTP calls are consolidated in a single POST operation.
 
Please let me know should you have subsequent questions, I have highlighted the areas relevant for our requirement below
 
Detailed explanation:
 
In the traditional frontend and backend design, usually the Mobile App or Website directly accesses the backend service, the backend microservices call each other, and then return the final result to the frontend client.
 
For clients (especially mobile), too many HTTP requests are expensive.
 
Therefore, in order to minimize the number of requests, the frontend generally tends to obtain associated data through a single API.
 
It means that sometimes the backend will do some UI-related logic processing to meet the needs of the client .
 
The biggest difference in BFF’s frontend and backend architectures is that the frontend (Mobile, Web) no longer directly accesses the backend microservices, but rather accesses it through the BFF layer. And each client will have a BFF service.
 
With BFF, there are fewer mutual calls between microservices. This is because some UI logic is processed at the BFF level.
 
Advantages of GraphQL API:

1. On demand data model definition
2. Get many resources in a single request

GraphQL vs REST:

For the comparison between GraphQL and REST, there are mainly the following differences:

1. Data Acquisition: REST lacks scalability and GraphQL can be accessed on demand. The payload can be extended when the GraphQL API is called.

2. API calls: REST’s operation for each resource is an endpoint, and GraphQL only needs a single endpoint, but the post body is not the same.

3. Complex data requests: REST requires multiple calls for nested complex data, GraphQL calls once, reducing network overhead.

4. Error code processing: REST can accurately return HTTP error code, GraphQL returns 200 uniformly, and wraps error information.

5. Version number: REST is implemented via v1/v2, and GraphQL is implemented through the Schema extension.

**Comment by spericas** [comment]
https://github.com/eclipse/microprofile-graphql

**Comment by tmiddlet2666** [comment]
FYI the plan is for initial version to work with the soon to be release microprofile-graphql 1.0.3 spec.
