### ISSUE TITLE
Wrong "constant" SamplerType name for Jaeger

### ISSUE THREAD

**Issue by martin-sladecek** [oracle/helidon#827]
## Environment Details
* Helidon Version: latest
* Helidon SE
* JDK version: 
* OS:
* Docker version (if applicable):

----------

## Problem Description
JaegerTraceBuilder.SamperType.CONSTANT should pass "const" type instead of "constant" to Jaeger.

**Comment by tomas-langer** [comment]
Thanks for the fix. I did not require backward compatibility, as the current value would not work at all with Jaeger.
