### ISSUE TITLE
Make sure Helidon support in MP starter is upgraded as we support new MP versions

### ISSUE THREAD

**Issue by tjquinno** [oracle/helidon#832]
The MP starter already supports Helidon, but for our support for MP 1.2.

As we support additional versions of MP we should make sure that the starter's support for Helidon keeps pace.

**Comment by barchetta** [comment]
Close since this was addressed by PR #843 (at least for MP 2.2).

**Comment by barchetta** [comment]
Ooops! I was thinking quickstarts. Sorry!

**Comment by tjquinno** [comment]
I've created https://github.com/eclipse/microprofile-starter/issues/192 to request and track the enhancement to the starter.

**Comment by tjquinno** [comment]
Rudy has a PR to add Helidon 1.2 MP 2.2 support to the starter: https://github.com/eclipse/microprofile-starter/pull/193

**Comment by tjquinno** [comment]
Posted  a question on the starter issue asking for an ETA. Waiting for a response.

**Comment by tjquinno** [comment]
The PR was approved today. All checks passed. Waiting for merge.

**Comment by tjquinno** [comment]
The PR has been merged. The on-line app at `starter.microprofile.io` does not yet show it though. I'll leave this issue open until it's there and I've had a chance to verify that it works.

**Comment by tjquinno** [comment]
Update from the PR approver:

> You may watch https://gitter.im/eclipse/microprofile-starter for messages from bot about when the build is ready on https://test-start.microprofile.io/
>
>It will appear on https://start.microprofile.io/ when we release 0.9.4

And the entry appears on the test URL but I have not had a chance to run it yet. Soon.

**Comment by tjquinno** [comment]
I will close this issue because the main site https://start.microprofile.io/ now shows Helidon as a choice for MP 2.2.

I will open another issue to do a similar update to the MP starter for Helidon and MP 3.0.
