### ISSUE TITLE
MP Metrics 2.0

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#833]
Upgrade metrics to 2.0.
This is a breaking change.

**Comment by spericas** [comment]
List of changes required for 2.0 (some not backward compatible):

- [ ] Refactor counters denoted by `@Counted` and add support for `@ConcurrentGauge` for older counters
- [ ] Deprecate `MetricRegistry.register(String, Metric, Metadata)`
- [ ] Support for `MetadataBuilder` and immutability
- [ ] Support for new `MetricID` and changes to metric filters
- [ ] New regex for labels
- [ ] Updates to JSON format
- [ ] Updates to new OpenMetric format (formerly Prometheus)
- [ ] Default value of `reusable`
- [ ] Changes to some base metric names: using `total`, counter to gauges and use of tags

**Comment by m0mus** [comment]
ETA 3 weeks

**Comment by tjquinno** [comment]
Santiago and I now have the TCK passing all tests. Working on SpotBugs violations, etc.
