### ISSUE TITLE
Add exception writer to Helidon WebServer

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#878]
It would be nice to have a feature that would allow the following:

```
try {
  doSomething(response);
} catch (Exception e) {
  response.send(e);
}
```
or
```
future.thenApply(response::send)
  .exceptionally(response::send);
```

The signature would be:
```
public Void send(Throwable e);
```

This method should have two modes:

1. Default mode - send a 500, log exception to a log and (maybe) send an entity with a (configurable) message
2. Development mode - send a 500, send an entity with formatted exception stacktrace

The switch to development mode would be done via configuration (and of course possible through a builder).

**Comment by romain-grecourt** [comment]
This would replace `ServerRequest.next(Throwable)`, right ?

I like the idea of using writers, this would allow for media supports to handle their own exceptions.

The signature should probably not be coupled to `Void`, so that it can be used with other types, e.g.  `CompletionStage<U>`

```java
public <T> T send(Throwable e)
```

**Comment by ljnelson** [comment]
Any ideas for configuration item name and location?  I'm all ears.
