### ISSUE TITLE
Minor documentation bugs

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#887]
Some minor documentation bugs I've noticed on the web site

In the Navbar "OpenAPI" appears in between "Guides" and "javadocs". It really should appear before "Guides".

https://helidon.io/docs/latest/#/guides/04_dockerfile
`quickstarts` link is broken

**Comment by romain-grecourt** [comment]
This is because the entry for OpenAPI is after the one for guides inside sitegen.yaml
