### ISSUE TITLE
This is just a reference for anyone who wants to use Jackson in Helidon MP instead of Yasson 

### ISSUE THREAD

**Issue by gcameo** [oracle/helidon#900]
## Environment Details
* Helidon Version: 1.2.0
* Helidon MP
* JDK version: 1.8

----------

## Problem Description
Using Jackson for Helidon MP

I struggled a lot to get rid of Yasson because I haven't used Micro-profile extensively. In the end what I did is very similar to what is documented here - See below for copy paste version

https://cassiomolin.com/2016/08/10/using-jackson-as-json-provider-in-jersey-2x/

It may be good to provide a simple example that includes Jackson as the Json Provider in Helidon MP.

the performance of Yasson is horrible. See here

https://github.com/fabienrenaud/java-json-benchmark

You can also customise the Jackson Mapper to create Custom Serialisers to meet your needs

```
@Provider
  public class CustomJacksonObjectMapperProvider  implements     ContextResolver<ObjectMapper> {
      ObjectMapper mapper = CustomObjectMapperFactory.createObjectMapper();

      @Override
      public ObjectMapper getContext(Class<?> type) {
          return mapper;
      }
   }
```

then Register it in Application class like this

```
    @Override
    public Set<Class<?>> getClasses() {
        
        return CollectionsHelper.setOf(
                JacksonFeature.class,
                CustomObjectMapperProvider.class,
                HelloWorldResource.class
        );
      }
  }
```

pom.xml changes

```
        <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-json-binding</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.eclipse</groupId>
                    <artifactId>yasson</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.jaxrs</groupId>
            <artifactId>jackson-jaxrs-base</artifactId>
        </dependency>
        <dependency>
            <groupId>io.helidon.media.jackson</groupId>
            <artifactId>helidon-media-jackson-server</artifactId>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.media</groupId>
            <artifactId>jersey-media-json-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.jaxrs</groupId>
            <artifactId>jackson-jaxrs-json-provider</artifactId>
        </dependency>
```

**Comment by romain-grecourt** [comment]
All you need to switch to Jackson is replace `jersey-media-json-binding` with `jersey-media-json-jackson`. You shouldn't have both dependencies, and `helidon-media-jackson-server` shouldn't be needed.

Providing a custom ObjectMapper should only require a compile time dependency on `com.fasterxml.jackson.core:jackson-databind` and the JAXRS API (`javax.ws.rs:javax.ws.rs-api`).

I'm not sure why you have to use `jackson-jaxrs-base` and `jackson-jaxrs-json-provider`

CC @ljnelson @spericas @tomas-langer

**Comment by gcameo** [comment]
Sorry I didn't know how to do it so thought someone may find it useful and I can't write on wiki... 

Thanks for adding to it but this is only for reference so ticket needs to be closed.

**Comment by romain-grecourt** [comment]
Roger that, I'm closing the issue.
