### ISSUE TITLE
Use dependency convergence plugin

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#911]
https://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html

Dependency convergence plugin ensures we depend on a single version of a third party library.
This is to catch cases where version is left in a pom.xml by accident that is managed in dependency management.

- [ ] Add convergence plugin to Helidon parent
- [ ] Add it to MP and SE example to validate intended use is working as well

**Comment by tjquinno** [comment]
See also this new, related issue: #1559
