### ISSUE TITLE
How to enable CORS headers in helidon

### ISSUE THREAD

**Issue by vatikam-orcl** [oracle/helidon#923]
Hi,
I have exposed a REST services based on ADF BC objects and REST services are working fine in helidon. But I have a requirement to enable to CORS headers. How can we do it in Helidon. Please advice.

Apologies if this is not a right forum to ask these questions. Please point me to appropriate channel.

Thanks,

**Comment by romain-grecourt** [comment]
You have to set the headers manually.

We have an issue to track some enhancement in SE to make it easy to do CORS with the WebServer, see #931 

MP uses Jersey and IIRC it doesn't have a special support for CORS so you may have some implement a custom response filter.
