### ISSUE TITLE
CORS Support

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon#931]
- Create a CORS extension for WebServer to simplify CORS configuration and handling for users.
- Document CORS with SE.
- See https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by spericas** [comment]
https://en.wikipedia.org/wiki/Cross-site_request_forgery

**Comment by spericas** [comment]
CORS support for MP in progress here: https://github.com/spericas/helidon/tree/cors/microprofile/cors

**Comment by spericas** [comment]
CORS wiki page is now here:
https://github.com/oracle/helidon/wiki/CORS-in-Helidon-MP

**Comment by rafabene** [comment]
Hi @spericas .  Any updates on microprofile-cors? I've created a custom filter for my applications but it seems that /openapi doesn't get intercepted by the filter.

**Comment by spericas** [comment]
@rafabene Hoping to get that in the next milestone, at least for MP. Not sure that would help OpenAPI as those resources are a bit different. What do you think @tjquinno?

**Comment by rafabene** [comment]
@spericas Thanks for having this as part of next milestone.
