### ISSUE TITLE
website : add "OpenJDK" to technologies section

### ISSUE THREAD

**Issue by delabassee** [oracle/helidon#940]
The home page "technologies" section (https://helidon.io/#/) lists a bunch of used projects but forgot to include "OpenJDK".

**Comment by c16a** [comment]
I guess including GraalVM was also sort of uh-oh, as it's just the underlying platform.

Statement 1: Helidon has first-class support for Prometheus and Microprofile
Statement 2: Helidon runs on GraalVM, and OpenJDK

Statement 1 is what the list of frameworks that are listed there mean. If we added OpenJDK to the list, we wouldn't be fair to the other JDK implementations which are TCK certified, to be honest.

**Comment by delabassee** [comment]
not really as the large majority of other JDK implementations are based on OpenJDK and yes, some pass the TCK while some don't.

**Comment by c16a** [comment]
Sounds fair. Raised this on helidon-website. https://github.com/oracle/helidon-site/pull/51

**Comment by barchetta** [comment]
Fixed (https://github.com/oracle/helidon-site/pull/79)
