### ISSUE TITLE
Helidon application poms

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon#944]
Prototype parent pom files to use for Helidon application.

Such pom will **not** include anything harmful such as plugin executions or dependencies since these cannot be removed or overridden down the road.

It will include:
 - properties (e.g. helidon.version, source encoding)
 - dependency management
 - plugin versions in plugin management
 - configured plugin executions in plugin management
 - non default profiles

This provides the following advantages:
 - Greatly reduces the pom.xml boilerplate
 - All Helidon examples can be standalone without the difficulties of managing standalone pom.xml

**Comment by spericas** [comment]
How does this relate to the `helidon-bom`? Is this for SE and MP? If the latter, which version?

**Comment by romain-grecourt** [comment]
fixed in #1022
