### ISSUE TITLE
Inspect project Reactor usages

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon#95]
Remove it from projects where it's not needed.

**Comment by romain-grecourt** [comment]
Reactor is used because of Config.
We need to remove the use of Flow/SubmissionPublisher from config.

This require a minor re-design of the Config API to replace Flow with something other listener mechanism.

**Comment by romain-grecourt** [comment]
This is also used in webserver.

Example from `ContentWriters` of a Publisher<DataChunk> created from a byte array:

```java
byte[] bs;
if (copy) {
    bs = new byte[bytes.length];
    System.arraycopy(bytes, 0, bs, 0, bytes.length);
} else {
    bs = bytes;
}
DataChunk chunk = DataChunk.create(false, ByteBuffer.wrap(bs));
return ReactiveStreamsAdapter.publisherToFlow(Mono.just(chunk));
```
