### ISSUE TITLE
The MP absolute=true annotation field is not removing package prefix for Gauge metric

### ISSUE THREAD

**Issue by pfmackin** [oracle/helidon#952]
Helidon Version: 1.2.0
Helidon MP
JDK version: 1.8.0_211
OS: MacOS 10.13.6
Problem Description
The MP Gauge Metric absolute field is set to true, but the metric name still has the path prefix.   This problem does not happen if I change the metric to Counter.

Here is the Microprofile spec file:///Users/pmackin/Downloads/metrics_spec-1.1%20(1).html#_fields

Steps to reproduce
Create  the sample class below. Add this class to the Quickstart MP to test this.

Build and run the application then issue the following:

curl http://localhost:8080/metrics/application

The output is 
{
  "io.helidon.examples.quickstart.mp.GreetingCardsAppMetrics.appUpTimeSeconds": 6
}

package io.helidon.examples.quickstart.mp;

import java.time.Duration;
import java.util.concurrent.atomic.AtomicLong;
import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.context.Initialized;
import javax.enterprise.event.Observes;
import org.eclipse.microprofile.metrics.annotation.Gauge;

@ApplicationScoped
public class GreetingCardsAppMetrics {

  private AtomicLong startTime = new AtomicLong(0);

  public void onStartUp(@Observes @Initialized(ApplicationScoped.class) Object init) {
    startTime = new AtomicLong(System.currentTimeMillis());
  }

  @Gauge(unit = "TimeSeconds", absolute = true)
  public long appUpTimeSeconds() {
    return Duration.ofMillis(System.currentTimeMillis() - startTime.get()).getSeconds();
  }
}

**Comment by spericas** [comment]
Registration of gauges uses a completely different codepath. This looks like an issue in `MetricsCdiExtension::recordAnnotatedGaugeSite`. We should consider using `MetricUtil`.
