### ISSUE TITLE
Check if we can generate beans.xml for MP automatically

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#956]
It may be useful to add a feature to generate `beans.xml` if not present in a project for Helidon MP applications.
This could be done using an annotation processor that would be automatically included in our dependency tree.
Must be possible to disable it (exclusion, compiler option)

**Comment by spericas** [comment]
Hmmm, have mixed feelings about this one. Developers should control what is and what is not a bean. What if classes don't satisfy the requirements of a CDI bean? That would result in a startup exception.
