### ISSUE TITLE
Provide mechanism to disable all or selected metrics

### ISSUE THREAD

**Issue by markxnelson** [oracle/helidon#958]
## Environment Details
* Helidon Version: 1.2.1
* Helidon MP
* JDK version: 11
* OS: linux
* Docker version (if applicable): 19

----------

## Problem Description

I can disable individual metrics like this:
metrics.base.classloader.currentLoadedClass.count.enabled=false

But I cannot disable all metrics, I would like to be able to do something like one of these…
metrics.base.*.enabled=false
metrics.base.all.enabled=false
metrics.base.enabled=false

**Comment by tomas-langer** [comment]
See https://github.com/oracle/helidon/pull/990 - solution for Health

**Comment by tjquinno** [comment]
See PR #1052
