### ISSUE TITLE
Weak Encryption: Inadequate RSA Padding

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [oracle/helidon#984]
https://github.com/oracle/helidon/blob/3d89e3ca0b7d1c425ae2a83b896796c4a26e6202/config/encryption/src/main/java/io/helidon/config/encryption/EncryptionUtil.java#L76
https://github.com/oracle/helidon/blob/3d89e3ca0b7d1c425ae2a83b896796c4a26e6202/config/encryption/src/main/java/io/helidon/config/encryption/EncryptionUtil.java#L104
Public key RSA encryption is performed without using OAEP padding, thereby making the encryption weak.

**Comment by tomas-langer** [comment]
See https://stackoverflow.com/questions/32033804/which-padding-is-used-by-javax-crypto-cipher-for-rsa
