### ISSUE TITLE
JSON-P Exception Handling

### ISSUE THREAD

**Issue by camerondurham** [oracle/helidon#991]
## Problem Description

JsonProcessing library from `io.helidon.media.jsonp` still throws a non-`JsonException`. When processing HTTP request content, throws `ClassCastException` when receiving JsonArray and expecting JsonObject. Should consider catching this exception and return  a `JsonException` for consistency.

[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

**Comment by spericas** [comment]
Fixed by PR #1085
