### ISSUE TITLE
Spans created for outgoing REST calls don't seem to set parent properly

### ISSUE THREAD

**Issue by MaxNanasy** [oracle/helidon#994]
## Environment Details

* Helidon Version: 1.2.2-SNAPSHOT
* Helidon SE or Helidon MP: MP
* JDK version: 11
* OS: Mac
* Docker version (if applicable): N/A

----------

## Problem Description

In code invoked from my REST resource method, if I create a span, set it as active, and then issue an outgoing REST call, I would expect the span created for the outgoing REST call to be a child of the active span.  However, the span created for the outgoing REST call is instead the child of the span with operation name "GET:io.helidon.examples.GreetResource.getRemoteMessage" (a framework-created span for my REST resource method).

## Steps to reproduce

I've done a sample application based on the autogenerated helidon-quickstart-mp (It's in [the test-tracing branch of my helidon-quickstart-mp repository](https://github.com/MaxNanasy/helidon-quickstart-mp/tree/test-tracing))

The major changes against helidon-quickstart-mp are ([diff here](https://github.com/MaxNanasy/helidon-quickstart-mp/compare/master...test-tracing)):

- Use helidon-microprofile-tracing and helidon-tracing-jaeger with constantly on sampling
- Add the endpoint `/greet/remoteGreeting?url=<remote URL>`, which performs a GET request against the remote URL and then returns `{ "message": "<message property from the GET request's JSON response>" }`
- Add invocation of `http://localhost:<port>/greet/remoteGreeting?url=http://localhost:<port>/greet` to MainTest
- Create spans within GreetingProvider's service methods surrounding the body of the methods, including the new method getRemoteMessage

I did something similar to the following to test the tracing:

1. Check out revision f9c89ce5 of helidon's master branch
2. Run `mvn install` to install helidon artifacts of version 1.2.2-SNAPSHOT
3. Start [jaeger-all-in-one](https://www.jaegertracing.io/docs/1.13/getting-started/#all-in-one)
4. Check out revision bd2cbfa of my helidon-quickstart-mp's test-tracing branch
4. Run `mvn test` 
5. Look for the trace for the /greet/remoteGreeting invocation in http://localhost:16686 (the trace with service name helidon-quickstart-mp and 21 total spans)
6. Change helidon/tracing/jersey-client as described under [Potential Solution](#user-content-potential-solution)
7. Run `mvn install` under helidon/tracing/jersey-client
8. Run `mvn test` under helidon-quickstart-mp again
9. Look for the trace for the /greet/remoteGreeting invocation again

The above steps should lead to the following two traces:

* Trace from step 5 (The innermost GET is the child of GET:io.helidon.examples.GreetResource.getRemoteMessage): ![Actual result](https://user-images.githubusercontent.com/628032/64359204-bb9de800-cfbc-11e9-8c30-b236cd5d6f20.png)
* Trace from step 10 (The innermost GET is the child of getRemoteMessage): ![Expected result](https://user-images.githubusercontent.com/628032/64359405-19cacb00-cfbd-11e9-9891-39589b745280.png)

Note the following relevant spans in the above screenshots:

- GET:io.helidon.examples.GreetResource.getRemoteMessage, the framework-created span for GreetingResource.getRemoteMessage
- getRemoteMessage, the span for GreetingProvider.getRemoteMessage
- GET (Specifically, the innermost of the two spans with operation name "GET"; the one at the top level is from MainTest), the framework-created span for the outgoing GET request
- getMessage, the span for GreetingProvider.getMessage

## <a id="potential-solution"></a> Potential Solution

Assuming that the current behavior is undesired, and the behavior in the above second screenshot is desired, one potential solution is to change ClientTracingFilter in helidon-tracing-jersey-client such that the spans it creates use the currently active span as the parent if there is one, or don't specify a parent if there's an active span (which should have the same behavior, since the default span parent is the active span), as I've done in [this commit to the active-span-parent branch of my helidon fork](https://github.com/MaxNanasy/helidon/commit/c914efd3965600a605437c64d5aa78524244429f).

### Notes on the Potential Solution

1. I don't know whether this change would break anything else in helidon
2. I don't know if there are any cases in which there is an active span but ClientTracingFilter.filter should still use the result from ClientTracingFilter.findParentSpan as the parent of the new span
3. I don't know if there's any other spans created in the helidon source code that would have similar issues

**Comment by tomas-langer** [comment]
We can look into the active span, though we cannot fully depend on it, as Jersey client may be used from Helidon SE, where we run in (possibly) more than one thread, so we cannot use `startActive`.
I will investigate possible options.

**Comment by tomas-langer** [comment]
In MP, active span is now used as a parent of other spans (outbound calls, other methods annotated as `@Traced`).
This should resolve the problem described in this issue.
